### ISSUE TITLE
Can't run VU in Windows 8.1 with CJK languages enabled

### ISSUE THREAD

**Issue by zestybaby** [VeniceUnleashed/VeniceUnleashed#1]
Because DICE ignores an old problem which would cause Windows 8.1 in CJK to break the game, it is confirmed that VU can't work in those languages too. 

Due to some new changes to Windows 8.1, some unicode characters, like "™" in this case, would cause some frostbite engine's games failed at launch, DICE was aware for this issue and took actions for BF4 and NFS Rivals, but ignored BF3 while they didn't update it for a long time.

There's a fix made by Chinese Battlefield community to fix this problem by injecting RAM to remove the ™ in title, here's the link: http://a.pomf.se/lwxkoe.exe And I think this would be easier to help building a fix for this issue.

**Comment by OrfeasZ** [comment]
Fixed in build 6684.
