### ISSUE TITLE
Bugs in vehicle and while parachuting

### ISSUE THREAD

**Issue by bigworld12** [VeniceUnleashed/VeniceUnleashed#108]
is there a problem with the vehicles atm ?
because i can't move well in Heli , parachute

**Comment by OrfeasZ** [comment]
Can you be a bit more precise?
What kind of issues are you experiencing in detail?

**Comment by JASTER1** [comment]
It seems that the sensitivity is out of wack.  I can barely turn a tank turret, cannot circle in a parachute.  Turned sensitivity all the way up and it was still slow.

**Comment by Bubucho** [comment]
Duplicate of #89 i think

**Comment by kiwidoggie** [comment]
Duplicate of #89 Vehicle Sensitivity Issues. Closing.
