### ISSUE TITLE
WebUI doesn't properly update on older GPUs or some Dual-GPU configurations

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#11]
When I start typing something in the Username/email box, I have to alt-tab and then alt-tab again to see the changes.

**Comment by OrfeasZ** [comment]
Can you see the background moving before having to Alt-Tab?

**Comment by ghost** [comment]
Yes. Note: I do not have access to the beta, but I guess I should be able to type in the input boxes.
Even login worked, but I had to alt-tab for the login error to show up.

**Comment by OrfeasZ** [comment]
Can you please generate and attach an MSINFO32 report to this issue?
Make sure to generate it while Battlefield 3 is running.

Instructions on how to do so can be found here: 
https://support.steampowered.com/kb_article.php?ref=1376-WTZN-9132

**Comment by OrfeasZ** [comment]
If you do not wish to publish your report, feel free to send it to me via email (nofate -at- nofate -dot- me).

**Comment by ghost** [comment]
Okay, I will do it now.

**Comment by ghost** [comment]
@OrfeasZ Report sent :)

**Comment by OrfeasZ** [comment]
@win32re Can you please check if you are still experiencing problems after updating to the latest build (6684)?

**Comment by ghost** [comment]
I will test this in a moment but do note I reinstalled my PC to Windows 7 SP1 x64.

**Comment by ghost** [comment]
@OrfeasZ Still same :(

**Comment by OrfeasZ** [comment]
@win32re Since you re-installed, could you possibly send me another MSINFO32 report?

**Comment by ghost** [comment]
@OrfeasZ Sent!

**Comment by OrfeasZ** [comment]
This issue appears to occur on old AMD GPU/driver configurations.
I am experiencing the same issue on my HD4XXX laptop and I've had reports that updated drivers fixed the issue.

However, since HD4XXX cards are now considered legacy, there are no new drivers being released.
I will have to look into it in more detail when I'm back from my holidays (~15 days from now).

**Comment by ghost** [comment]
Thanks for looking into this issue!

**Comment by ghost** [comment]
@OrfeasZ I still have the same GPU. However, when I launch VU, there is only a white window. Vanilla BF3 works fine.

**Comment by ghost** [comment]
White screen is gone; issue is now the same as described in the first comment.

**Comment by OrfeasZ** [comment]
This has been fixed in build 9843 (not live yet).
