### ISSUE TITLE
Spectator not receiving/showing chat messages

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#110]
**[BUILD 8389]**

You can open the chat and write into it but no message will appear (both yours or others). Not sure if others see the message.

http://youtu.be/i2KjsYsSyNQ

Don't know if it matters but during the test there was at least another spectator.

**Comment by Bubucho** [comment]
I was on this server as a spectator and I saw your messages, a bunch of players also respond.

I had no problem interacting with players and spectators

**Comment by kiwidoggie** [comment]
I personally have come across this issue as well, rarely but it does happen.

**Comment by kiwidoggie** [comment]
Try switching to a player before chatting, see if that resolves the issue?

**Comment by Bubucho** [comment]
Also, make sure your chat box is not disabled with H

@Dendari92, you also appears in this video https://youtu.be/4DQqUPHy180?t=51s

**Comment by Dendari92** [comment]
I tried to switching players but no luck. Yes, the chat isn't hidden, you can see when I'm writing a message there isn't anything in the chat feed.

**Comment by Dendari92** [comment]
Done some quick tests and I can see the chat feed only on the 30Hz server, 60Hz and 120Hz servers aren't working correctly for me.

**Comment by OrfeasZ** [comment]
This appears to occur when you join a game directly as a spectator.
If you first join as a player and then re-join as a spectator, then chat works.

**Comment by Bubucho** [comment]
Confirmed, I've joined a server directly as a spectator, say hello to everybody but nobody respond.

**Comment by OrfeasZ** [comment]
This has already been fixed in our development branch and will be pushed to production soon.

**Comment by OrfeasZ** [comment]
This has been resolved in build 8456.
