### ISSUE TITLE
Kills aren't shown when spectating a player

### ISSUE THREAD

**Issue by Bubucho** [VeniceUnleashed/VeniceUnleashed#111]
When spectating a player, there is no visual confirmation that the player you're watching.

There is no centered-bottom kill confirmation and also in the kill-feed on the top-right. The kill-feed is fine for others players

**Comment by Bubucho** [comment]
Strangely, when spectating a player in third person, the kills are shown in the kill-feed but appears as teamkills

**Comment by Dendari92** [comment]
In retail the kill log on the upper right corner doesn't show your kills/deaths (only showed in your killfeed at the bottom center), so I assume when you're spectating a player in first person it acts the same way.

**Comment by Bubucho** [comment]
Yeah I know about that, so simply adding the "normal" bottom-center message would be enough (for kill and getting killed)

**Comment by OrfeasZ** [comment]
Since build 8456 all kill messages appear in the feed and use fixed colors (blue for team1, orange for team2).
Personal kill messages (the bottom-center ones) will be added in a later build.
