### ISSUE TITLE
Suddenly spectating somebody

### ISSUE THREAD

**Issue by CaptainGrunge** [VeniceUnleashed/VeniceUnleashed#113]
Had an interisting bug I couldnt reproduce one time when I was playing Noshar TDM and camped in 
the container. A squadmember spawned at me and I couldnt move anymore - my crosshair and hud were still displayed and I could change my weapons but the camera followed the guy that spawned on me. it was like I was spectating the guy in 3rd person. 
After few seconds I got killed by somebody (so I think my player was just standing there idleing while I was "spectating" the guy). After respawning everything was "normal".

This was kind of brainfuck-moment and I couldnt find any logical explaination for this - could be possible that the guy spawned in me and the server fucked things up because of the 60Hz.

**Comment by JASTER1** [comment]
I had the exact same instance.  I can't remember if I was spawned on, but it was on Armored Kill, Deathmatch.  I was walking and all of a sudden in 3rd person watching a teammate. Had my HUD and crosshairs and wound up getting killed, spawn and back to normal.  Went back to the spot and nothing happened.

**Comment by OrfeasZ** [comment]
This is a bug that also occurs in vanilla BF3, so I'm going to close this as invalid.
If it keeps occurring at a level that makes the game unplayable we will be looking into it in more detail.
