### ISSUE TITLE
Battlebugs - Some bugs

### ISSUE THREAD

**Issue by VicVRS** [VeniceUnleashed/VeniceUnleashed#115]
Bug 001 - A SPAS-12 bug that the bullet somehow pass my head, it can happen with a sniper.

LINK: http://youtu.be/11Wva-S_jlI

Bug 002 - My VU menu and in game chat it's freezing, even when I play in windowed mode.

LINK: http://youtu.be/WiBGbmZpifM

Bug 003 - While changing vehicles on spectator mode, the vehicles HUD still on screen.

Bug 004 - Revive bug because it's driving me crazy!

---

NOTEBOOK SPECIFICATIONS

Processor: Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz
Speed: 2.1 GHz
Number of Cores: 8

Video Card 1: Intel(R) HD Graphics 4000
Chipset: Intel(R) HD Graphics 4000
Dedicated Memory: 2.1 GB
Total Memory: 4.0 GB

Video Card 2: AMD Radeon HD 7730M
Chipset: AMD Radeon HD 7730M
Dedicated Memory: 1.0 GB
Total Memory: 1.0 GB

Memory: 8.1 GB

Operating System: Microsoft Windows 7 Home Premium Edition Service Pack 1 (build 7601), 64-bit
Service Pack: 1
Size: 64 Bit

**Comment by OrfeasZ** [comment]
001 -> #139 
002 -> #11
003 ->  #116 
004 -> #94
