### ISSUE TITLE
Too long soldier names get replaced by "PlayerX"

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#119]
We should add an error message to prevent people from creating ridiculously long names.
Not sure exactly what the max length is, need to investigate.

**Comment by derrod** [comment]
The maximum length for an origin ID seems to be 16 characters. It is sensible to assume that that is the limit the engine is also enforcing.

Small Addition: The game client also crashes when using a soldier with a name with 17 characters (excluding the null terminator).

**Comment by OrfeasZ** [comment]
That seems to be correct. 
It looks like the maximum allowed characters for a name are 17 (including the null terminator).

**Comment by Xulunix** [comment]
Creating a soldier with a name longer than 16 chars (without null) causes the game to crash in the vu.dll

**Comment by OrfeasZ** [comment]
In the latest build you can only create character names with up to 16 characters.
