### ISSUE TITLE
Connecting to a dedicated server after a while gets you stuck in the loading screen

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#12]
It appears that joining a dedicated server after an unspecified amount of time will get you stuck in the black loading screen after the level has loaded.
This could be caused by invalid team allocation actions.

Investigating...

**Comment by derrod** [comment]
I want to add to this that it's still possible to join as a spectator.

**Comment by OrfeasZ** [comment]
Fixed in build 6692.
