### ISSUE TITLE
Investigate high frequency prop physics issues.

### ISSUE THREAD

**Issue by JASTER1** [VeniceUnleashed/VeniceUnleashed#120]
While sprinting, both on foot and in a vehicle, I would hit objects and they flew away at an incredible rate.  Didn't happen to everything.  First instance, in a tank, Strike at Karkand Rush.  Ran into every telephone pole and boxes and they all went flying.  Also kicking concrete rubble or boxes on foot made them shoot off.

Another movement problem was with a certain type of building.  The ones on B, Kharg Island.  Getting up the stairs caused some kind of problem which happened everytime, sprint or walk.  Didn't happen on any other stairs I tried.

**Comment by JASTER1** [comment]
Thanks for putting in the right words!

**Comment by bigworld12** [comment]
happened to me too . all props seem to have this problem

**Comment by mirh** [comment]
Just had this in Wake island DMF server. 
You only need to walk near them to see takeoff
