### ISSUE TITLE
Extra motion blur while looking up/down in spec mode

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#123]
Disabling or reducing the motion blur resolve this issue.

https://youtu.be/apTn5j2XCuI
https://youtu.be/1aj_uIRB7io

**Comment by Bubucho** [comment]
Who plays with motion blur ? :D

**Comment by kiwidoggie** [comment]
This bug was fixed awhile ago, missed this issue.
