### ISSUE TITLE
Latency issue in Chat

### ISSUE THREAD

**Issue by bigworld12** [VeniceUnleashed/VeniceUnleashed#125]
in the new chat on high frequency servers typing in chat has some latency
(try pressing J then typing fast) > it doesn't catch the first letters

**Comment by Bubucho** [comment]
I had this issue on a previous build but not anymore

**Comment by OrfeasZ** [comment]
Typing latency has been greatly reduced since build 8633.

A slight (<200ms) latency can be still experienced under some configurations, but it shouldn't be significant.
