### ISSUE TITLE
Third person camera with vehicles is too close

### ISSUE THREAD

**Issue by Bubucho** [VeniceUnleashed/VeniceUnleashed#128]
When spectating a player in a vehicle, third person camera is way too close

Screenshots:
Plane:
![bf3 12-05-2015 00-27-12-681](https://cloud.githubusercontent.com/assets/12384520/7576457/f1010eba-f83d-11e4-8074-c762029e626e.png)

LAV/BTR :
![bf3 12-05-2015 00-27-38-856](https://cloud.githubusercontent.com/assets/12384520/7576461/07775672-f83e-11e4-9749-f5eb92d12e69.png)

**Comment by OrfeasZ** [comment]
This has been resolved in build 8456.
