### ISSUE TITLE
Client crashes when a spectated player switches to an equipment slot

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#13]
This only happens when spectating a player in first-person view.

**Comment by kiwidoggie** [comment]
![tugs](https://cloud.githubusercontent.com/assets/9152262/5379401/dd0bde8c-805e-11e4-8983-ade0ede93f00.png)

**Comment by kiwidoggie** [comment]
Fixed in build 6891.
