### ISSUE TITLE
Projectiles speed on high freq server

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#130]
The overall projectiles speed seems to be increased on the high frequency servers. It's especially evident on jets, helicopters and maa.

**Comment by OrfeasZ** [comment]
Projectile speeds appear to be the same, but travel distances might appear shorter because the projectile gets spawned "faster" due to high frequency updates.

Until someone can prove that they're actually different, I'll mark this issue as invalid and close it.
