### ISSUE TITLE
Opening Chat causes slight fps drops 

### ISSUE THREAD

**Issue by MizuDG** [VeniceUnleashed/VeniceUnleashed#132]
https://www.youtube.com/watch?v=J8hUcGEhIVQ&feature=youtu.be

**Comment by bigworld12** [comment]
this also causes the first letters to not catch if you type fast check this 
#125

**Comment by OrfeasZ** [comment]
Since build 8633 WebUI should be much more performant, and should no longer cause major FPS drops. Any fluctuation in FPS should be in the scale of 1-5.
