### ISSUE TITLE
Implement the ability to disable revive spawn protection

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#136]

**Comment by bigworld12** [comment]
i thought it was a bug

**Comment by OrfeasZ** [comment]
It isn't a bug, it's also present in the retail version.

**Comment by Dendari92** [comment]
I don't think it's an intended feature even in retail, because it mainly happens when instantly accepting the revive (probably hitboxes are kinda messed up).

**Comment by kiwidoggie** [comment]
This can be done via VeniceEXT
