### ISSUE TITLE
-connect parameter & Auto connect after changing frequency

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#138]
Currently you'll have to manually reconnect after changing frequency to join a server. This process should be automatic. It can easily be solved by having a -server parameter available.

**Comment by derrod** [comment]
I think you mean something like a -connect flag? (-server starts the client in server mode).

I think it would be an improvement if you didn't need to login again too.

**Comment by Powback** [comment]
Yes, a -connect parameter would probably be more correct. An auto-login option would also be nice.

**Comment by MAGICCC** [comment]
Reminds me for a protocol for websites (vujoin://_ip_:_port_)

**Comment by ghost** [comment]
Maybe save the credentials locally to an encrypted file? And then use those when logging in?
