### ISSUE TITLE
After the last update i'm getting this infinte loop

### ISSUE THREAD

**Issue by Frankity** [VeniceUnleashed/VeniceUnleashed#141]
in WebUI_debug.log:

The key "target-densitydpi" is not supported.
    at / (line 4)

and the game keep doing this:
youtube video ->
<a href="http://www.youtube.com/watch?feature=player_embedded&v=kEsREOwkgaQ
" target="_blank"><img src="http://img.youtube.com/vi/kEsREOwkgaQ/0.jpg" /></a>

**Comment by kiwidoggie** [comment]
@Frankity Please see if this issue still happens after the latest 10293 update.

**Comment by Frankity** [comment]
@kiwidoggie i think the issue is fixed now, the game is working normally, thanks
