### ISSUE TITLE
Connection To The Gameserver has been lost.

### ISSUE THREAD

**Issue by OfficialKreek** [VeniceUnleashed/VeniceUnleashed#143]
So im Trying to play on a server, but it loads 3 minutes then it says Connection has been lost to the gameserver please check your intnerte connection and try again. Help pls

**Comment by kiwidoggie** [comment]
Try opening UDP ports 25200, 25300, 7948, and 7958 on your firewall and try again.

**Comment by OrfeasZ** [comment]
This tracker is only for issues related to Venice Unleashed.
For issues related to Project Rome please use our community forums.
