### ISSUE TITLE
WebUI stuttering at 4K resolution

### ISSUE THREAD

**Issue by TheMaxXHD** [VeniceUnleashed/VeniceUnleashed#144]
https://www.youtube.com/watch?v=iKjYEYLbx9o

Not sure if this is an issue but it think it's noteworthy to point out that the entire menu background tends to stutter quite a bit, especially at 4K. A workaround I guess you would call it would be to cap the menu at 60 fps using gametime.maxvariablefps 60 which gets rid of the stutter. And the invisible menu, which has already been identified previously in the issues tracker.

**Comment by OrfeasZ** [comment]
This has been fixed in build 9843 (not live yet).
