### ISSUE TITLE
Can't add topic or messages on Nexus forum

### ISSUE THREAD

**Issue by lawyer911** [VeniceUnleashed/VeniceUnleashed#146]
I've registered on http://forums.veniceunleashed.net/
When I log out I can owerview all topics and messages on forum, but when I sign up I can't even read topics (You are not authorised to read this forum)

**Comment by OrfeasZ** [comment]
Thanks for the report @lawyer911. This issue should now be resolved.
I've marked this as "invalid" since it's not directly related to Venice Unleashed.
Please let me know if you experience any more issues.
