### ISSUE TITLE
Spectator: Freecam movement-lag while pressing Sprint

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#15]
Pressing Sprint(Shift) while spectating in freecam-mode, the camera movement starts to hang.
Only the camera movement is affected, the game is still rendered correctly

https://nocloud.xulunix.de/public.php?service=files&t=0534ca85209c3886a70a484146ffc9f1

**Comment by OrfeasZ** [comment]
The Shift key is used for switching between spectating modes (freecam, third-person, first-person), which is the reason you're experiencing 'lag' while holding it down.
