### ISSUE TITLE
Problem with account.

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#150]
I have forgotten my nickname in battelfield Bed Company 2. I have 13 nicknames, of which, perhaps, is mine. Can you define the IP address or nickname of the account, so I can restore it?

**Comment by OrfeasZ** [comment]
This is not the place to ask for support regarding your Emulator Nexus account, or Project Rome.
For that please visit our forums at http://forums.veniceunleashed.net/viewforum.php?f=19.

**Comment by ghost** [comment]
![5435](https://cloud.githubusercontent.com/assets/16266403/11766414/41e7ba38-a197-11e5-99f4-27d776b0d329.png)

**Comment by ghost** [comment]
So what?

**Comment by Siilwyn** [comment]
The answer was already given. Create a new topic in the '[Help and Support](http://forums.veniceunleashed.net/viewforum.php?f=19)' section of 'Project Rome' and explain your problem there. This repository is only for tracking bugs in-game.

**Comment by ghost** [comment]
good joke, jude

**Comment by OrfeasZ** [comment]
Enough of this. Like I said before, if you need help ask on the forums. This is not the place for it.
