### ISSUE TITLE
VU menu randomly popping up while playing in a server

### ISSUE THREAD

**Issue by faddn** [VeniceUnleashed/VeniceUnleashed#152]
I couldnt see anything to start with, the whole black menu was blocking everything. But after some clicking this happend:

oi66.tinypic.com/2hzttee.jpg

**Comment by OrfeasZ** [comment]
This can be reproduced by opening the chat and pressing the backspace button.

**Comment by OrfeasZ** [comment]
Fixed in build 10360.
