### ISSUE TITLE
Wrong IP-Address in server browser and conncetion failing when server is bound to secondary network interface

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#153]
The server was started with the following parameters:

```
-listen X.X.X.252:25200 -RemoteAdminPort X.X.X.252:47200 -mHarmonyHost X.X.X.252:7948
```

I noticed the following issues
- The IP-Address shown in the server browser is still the primary one of the server (X.X.X.250)
- Clients are unable to connect
- RCON is still bound to 0.0.0.0

I guess the reason is that the server uses the primary network interface and thus its IP to connect to the master server. It seems that this is the reason the wrong IP appears in the server list and the clients try to connect to the wrong IP when joining.

**Comment by kiwidoggie** [comment]
As a workaround, you may need to disable all other network adapters first, then launch the servers. In my case I had to disable the VMWare Virtual Network Adapters. Otherwise this will still be looked into.

**Comment by OrfeasZ** [comment]
This has been fixed in build `14341`. The `-mHarmonyHost` parameter has been replaced with `-mHarmonyPort` which only accepts a port number and not a host. The host mHarmony will bind to will always be the same as the main Frostbite socket host (the one specified using `-listen`).
