### ISSUE TITLE
Server not loading new map after all objectives destroyed in rush OP. metro

### ISSUE THREAD

**Issue by faddn** [VeniceUnleashed/VeniceUnleashed#154]
I was running alone in a 120 hz server destroying all objectives in rush OP. metro.

After all objectives were destroyed the server would not end the round and load a new map.
I was able to keep running around and shooting for a while until the server crashed I think.

**Comment by derrod** [comment]
Maybe the server does not actually end a round if it was not live. I'll see later.

Depending on what server you were on at the time the reason for the "crash" could be windows update.

**Comment by OrfeasZ** [comment]
This happens when the game is still in warmup, since scoring is disabled.
