### ISSUE TITLE
Missing RCON commands

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#155]
This is low priority but should be included for a fully compatible rcon layer.
- `unlockList.*`
- `vars.ranked`
- `vars.unlockMode`

This list was compiled by comparing the output of the `admin.help` command from a VU and retail server.

Done or rejected (as of 23.12.2015)
- ~~`admin.effectiveMaxPlayers`~~
- ~~`admin.teamSwitchPlayer`~~
- ~~`banList.*`~~
- ~~`currentLevel`~~
- ~~`squad.*`~~
- ~~`vars.roundsPerMap`~~
- ~~`vars.autoBalance`~~
- ~~`player.isAlive`~~
- ~~`player.ping`~~
- ~~`player.idleDuration`~~
- ~~`reservedSlotsList.*`~~
- ~~`vars.bannerUrl`~~
- ~~`gameAdmin.*`~~

**Comment by kiwidoggie** [comment]
admin.effectiveMaxPlayers has been implemented.
admin.teamSwitchPlayer has been replaced by admin.MovePlayer.
banList.\* has been implemented (will need testing, but initial results work.)
squad.\* has been implemented with the exception of squad.listActive (This will be fixed very soon)
vars.autoBalance has been implemented.
vars.roundsPermap has been implemented.

All above has been implemented in build 10515 (Not Live yet)
All others are still a work in progress

**Comment by kiwidoggie** [comment]
admin.teamSwitchPlayer, currentLevel, vars.bannerURL, gameAdmin. \* , are undocumented and will not be implemented.
reservedSlotList.\* have been implemented.
player.idleDuration, isAlive, and ping have all been implemented as of 10645 (not live yet)

**Comment by kiwidoggie** [comment]
vars.bannerURL as of the documentation is ignored, so it will not be implemented.

**Comment by kiwidoggie** [comment]
reservedSlotList.* have been implemented.

**Comment by derrod** [comment]
vars.bannerUrl is documented as "Not used", same for vars.roundsPerMap. Presumably because banners are not shown on Battlelog. However I'd like to see the possibility to use banners in VU's server browser.

gameAdmin.\* is documented in earlier versions but it is unclear what it actually does.
