### ISSUE TITLE
Mouse cursors pops up when closing the ingame console.

### ISSUE THREAD

**Issue by faddn** [VeniceUnleashed/VeniceUnleashed#156]
It pops up and you have to go into the game menu to and then back to the game to get it away so you are able to move around again. I don't know how to reproduce it, it happend when I just had joined a game.

**Comment by MizuDG** [comment]
https://youtu.be/hF2XxpytpPU 
Can confirm.

**Comment by 3ti65** [comment]
Don't think this still happens. FoolHen couldn't reproduce.

**Comment by Powback** [comment]
Related to WebUI I think
