### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by 1337REKI** [VeniceUnleashed/VeniceUnleashed#157]
I cant log in it is saying "You are not authorized to access this product"

**Comment by Siilwyn** [comment]
That's because the open beta hasn't started yet. Please read the messages on the VU forum, there are already tons of people asking the same thing. Also you can read [Twitter](https://twitter.com/VeniceUnleashed) for the latest news.

**Comment by lambhassador** [comment]
Was'nt it supposed to start today?

**Comment by ExtReMLapin** [comment]
In few mins

**Comment by lambhassador** [comment]
timezone?

**Comment by ExtReMLapin** [comment]
It has nothing to do with timezone, it's in few mins.

https://twitter.com/VeniceUnleashed

See there.

**Comment by lambhassador** [comment]
thanks. Merry Christmas

**Comment by ExtReMLapin** [comment]
Np, you too ;)
