### ISSUE TITLE
An error has occurred updating Code 1x2

### ISSUE THREAD

**Issue by VRsingthegamez** [VeniceUnleashed/VeniceUnleashed#159]
Cant get into any servers at all and this message appears and It restarts my client.

**Comment by kiwidoggie** [comment]
Have you tried downloading the .zip file and extracting it and running it from there, or using the new installer?

**Comment by MAGICCC** [comment]
Happens to me when I use the .zip and startin vu.exe w/o admin

**Comment by kiwidoggie** [comment]
Ensure that the directory that VeniceUnleashed is extracted to has User's modify priv's.
