### ISSUE TITLE
Servers listed multiple times

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#16]
Pressing the "REFRESH" button in the serverbrowser multiple times before the list is loaded, causes the server to get listed multiple times.
Each click on the button (before the list is loaded) will cause the server to get listed one more time.

https://nocloud.xulunix.de/public.php?service=files&t=9aee277560787a88613864ffdbb477d1

**Comment by OrfeasZ** [comment]
Fixed in build 6806.
