### ISSUE TITLE
Black loading screen

### ISSUE THREAD

**Issue by Noobasoar** [VeniceUnleashed/VeniceUnleashed#161]
Vu doesn't open, goes to a black loading screen and never proceeds

**Comment by kiwidoggie** [comment]
Do you have Intel Integrated graphics installed?

**Comment by Lashazior** [comment]
http://i.imgur.com/3Jspf4O.png same issue myself, gets to about 61k and crashes.

I have a phenom x6, 5770 graphics with up to date drivers, sufficient ram. Does this program utilize SSE4.1 instruction set at all?

**Comment by kiwidoggie** [comment]
If you are on Windows 7, please ensure that you have the Windows 7 Platform Update installed found https://www.microsoft.com/en-US/download/details.aspx?id=36805

Also, ensure that if you do have integrated graphics that it is disabled, or vu.exe is set to use the discrete graphics.

**Comment by Lashazior** [comment]
That update is already installed, still having issues

**Comment by Noobasoar** [comment]
Does not seem like it...

**Comment by kiwidoggie** [comment]
I do not believe so, try running with -vudebug as a launch parameter, also the crash server has been up for awhile now so you not being able to contact it seems like it's a local issue. But I will try to help you out, do you have any Anti-Virus/Anti-Malware installed or any Firewalls?

**Comment by Noobasoar** [comment]
Vudebug paramater gives the following...
[1225/171819:ERROR:webgraphicscontext3D_command_buffer_impl.cc(227)]Failed
to initialize command buffer.   Also [208]... Does this make sense?

**Comment by Noobasoar** [comment]
Updated direct and resolved issue
