### ISSUE TITLE
Triple Monitor HUD stretched instead of centered on center monitor!

### ISSUE THREAD

**Issue by krazr** [VeniceUnleashed/VeniceUnleashed#166]
Hey guys I may be one of the few but I have a triple 5760x1080 (Samsung 120hz 27"x3) monitor setup and it works great with the stock BF3 interface.  The way the triple monitor interfaces should work is that all of the HUD information (chat, ammo count, life meters, etc.) should work is just like a standard single monitor setup. *In the main startup menu/interface, All three of my monitors are on and I see the background video but... The HUD interface like the game server list and all of the text is squeezed into the middle monitor...  It looks like the HUD interface is actually rendered in 5760x1080 resolution but it's squeezed into a 1920x1080 space in the center screen only.  However, if I mouse over the server browser and anything else that's showing squeezed unless it's in the center, I have to move the mouse cursor to where those words would be displayed had the HUD actually been stretched across the entire 5760x1080 space... So I have to move the mouse to a blank spot to the far left monitor and mouse over that area for the actual box to highlight that's squeezed into the center monitor... It's the same thing in game and I can't actually do much in the interface or read it because of how squeezed it is.

**Comment by kiwidoggie** [comment]
Screenshots or video please :) I believe I understand what you are saying, but we don't want to make assumptions here.

**Comment by rierei** [comment]
http://forums.veniceunleashed.net/forums/viewtopic.php?f=40&t=8402

**Comment by OrfeasZ** [comment]
Does this only happen in fullscreen mode, or does it also happen while running windowed?

**Comment by krazr** [comment]
Guys it won't let me take proper screenshots in fullscreen mode and I don't have enough bandwidth to upload a video with 5760x1080 resolution of almost any size.  My realtime upload speed is 80 kbps and it's not letting me taking proper screenshots with the print screen button.  I just get a black screen with print screen that shows the frames counter in the top right corner...  If there's a better way to do any of those things please let me know and I'll give it a try.  Nothing has changed for me at all though and it's still the same. I could change to windowed mode and then everything is screwed but it shows up non-squeezed.  It corrects the squeezed look of the information that Venice puts in but it takes screws up the hud and puts it on the far screens instead of all in the center screen.  Chat box looks correct too (non-squeezed) in windowed mode but again it's on the far left screen instead of being in the normal place in the center screen's view
![screenie 5760x1080 windowed](https://cloud.githubusercontent.com/assets/451595/12077314/57006b10-b1a3-11e5-8ab7-455a1f9a1650.jpg)

**Comment by krazr** [comment]
![2016-01-02_00001](https://cloud.githubusercontent.com/assets/451595/12077370/dc882df2-b1a5-11e5-8e95-bb28740af6bd.jpg)
![2016-01-02_00002](https://cloud.githubusercontent.com/assets/451595/12077372/dc8eb71c-b1a5-11e5-9ad2-2d6b427de23c.jpg)
![2016-01-02_00003](https://cloud.githubusercontent.com/assets/451595/12077371/dc8adf16-b1a5-11e5-9605-ceb2433d303b.jpg)
Okay so I realized this guy in the forum post you linked above showed a guy taking screenshots with Steam so I did the same.  What you can't see in the last screenshot which is your main menu is that to make "QUIT" highlight like it is right now, my mouse pointer is actually all the way to the left of the black screen to get "QUIT" to highlight.  If I mouse over any of the menu items in my center screen they don't acknowledge my pointer is over them.  So they don't match up correctly with the resolution my in-game is using.  The only way I can use any of the menu items is by putting my mouse where the buttons would show if the menu was actually stretched out to 5760x1080.  Regardless everything HUD based should display only in the center screen and the outer two 1920x1080p spaces (left and right screens) should only be peripheral vision and not menu items/HUD items.

**Comment by kiwidoggie** [comment]
Someone via reddit also posted about the same/similar issue. See: https://www.reddit.com/r/VeniceUnleashed/comments/41a37b/5760x1080_needs_optimization/

**Comment by kiwidoggie** [comment]
This seems to have been fixed and will roll out with the new update. If this issue occurs after the new update (which hasn't come out yet) please re-open this ticket.

http://i.imgur.com/TmzsbaO.jpg

**Comment by FlashHit** [comment]
Seems fixed 🤔
