### ISSUE TITLE
Venice Unleashed Startup Issues with Integrated Graphics (Intel, AMD, NV)

### ISSUE THREAD

**Issue by AlexEe77** [VeniceUnleashed/VeniceUnleashed#169]
Though there being an entry in the [Official FAQ](http://forums.veniceunleashed.net/viewtopic.php?f=40&t=8246#p48894) still a lot of people seem to have problems with it.

Example Threads:
- http://forums.veniceunleashed.net/viewtopic.php?f=40&t=8258
- http://forums.veniceunleashed.net/viewtopic.php?f=40&t=8251

**Comment by tkoschka** [comment]
Had same Problem, but could fix it by using this workaround:
- Rightclick the venice shortcut for the freq you want to play
- there is an option like "execute with gfx card"
- select the nvidia card there and everything works (atleast for me)

**Comment by tkoschka** [comment]
okay, the workaround doesnt help to much, game still crashes when server gets closed and when map changes

**Comment by kiwidoggie** [comment]
There was an update pushed a few days ago that should have resolved these issues. @tomgrassmann @AlexEe77 can you confirm?

**Comment by tkoschka** [comment]
tested it, now the error only occurs sometimes when writing in the chat

**Comment by kiwidoggie** [comment]
Which server were you using, if you don't mind me asking? Or is it a persistent issue throughout all servers?

**Comment by tkoschka** [comment]
EU #1 but now i'm getting the error on startup. I see the loading screen for  some seconds, than the animation stops and i see in the background the directx message

**Comment by kiwidoggie** [comment]
This bug should have been fixed with the new WebUI version, if anyone else has issues feel free to message to re-open.
