### ISSUE TITLE
Shift + Tab doesn't work

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#17]
You can't cycle backwards through UI elements with shit + tab in the login screen.

**Comment by OrfeasZ** [comment]
I'm not quite sure I understand what you're talking about.
Are you referring to the Steam Overlay when launching the game via Steam?

**Comment by derrod** [comment]
No, I'm talking about the login form.

Pressing Tab will jump to the next element (i.e. password field) as expected, Shift + Tab will show the same behaviour while it is expected to cycle backwards i.e. from the "Login" button back to the password field.

**Comment by OrfeasZ** [comment]
It appears that most keys combinations do not work properly (like Ctrl+A).
Will be working on fixing that.

**Comment by OrfeasZ** [comment]
Fixed in build 6876.
All key combinations should now work (including pasting text in input elements).
