### ISSUE TITLE
Venice Unleashed Updater Updating Client fail

### ISSUE THREAD

**Issue by lambhassador** [VeniceUnleashed/VeniceUnleashed#170]
Updater gets stuck at 1/6 and crashes to desktop. If restarted, updating begins again at 1/6 and never gets past.

**Comment by AlexEe77** [comment]
I guess the devs are aware of that issue. try the official [.zip](http://veniceunleashed.net/VeniceUnleashed.zip) and extract the files to your game dir just as workaround

**Comment by kiwidoggie** [comment]
See http://forums.veniceunleashed.net/viewtopic.php?f=40&t=8246 on updating issues, if you need further support post on the forums.
