### ISSUE TITLE
M1 Abrams, after firing coaxial machine gun, switch to cannon immediately, there will be a short reload action, even there is already 1 ammo.

### ISSUE THREAD

**Issue by zhm86** [VeniceUnleashed/VeniceUnleashed#173]
This short reload action makes screen jitter.
Tested in 60Hz server.

**Comment by kiwidoggie** [comment]
Please confirm with a side-by-side video of the effects in 60hz and 30hz to see if there are any differences. Just reply to this issue to re-open it.
