### ISSUE TITLE
Procon commands make server crash

### ISSUE THREAD

**Issue by NicoCelliers** [VeniceUnleashed/VeniceUnleashed#174]
When you type a message in procon as admin. The moment you send the message, the server crashes and has to be restarted.

**Comment by kiwidoggie** [comment]
Investigating currently.

**Comment by derrod** [comment]
This requires at least one player to be on the server.

**Comment by OrfeasZ** [comment]
This should be fixed in build 10822.

**Comment by MAGICCC** [comment]
Connected via B3 on my server and after loading the plugin_adv.xml the server crashes when `admin.say` got called

```
160103 02:28:00 DEBUG   "getCommand: ('admin.say', 'Be sure you visit our other servers as well! Check for the other [B3]FUNSERVER in the serverlist!', 'all')"
160103 02:28:05 ERROR   'Lost connection to Frostbite2 server'
160103 02:28:05 INFO    'Connecting to frostbite2 server ...'
160103 02:28:06 ERROR   'IOError [Errno 10061] No connection could be made because the target machine actively refused it'
```

When the server is running a while and using `!say text` the server wont crash

```
160103 03:28:59 CONSOLE "['player.onChat', 'MAGIC', '!say hi', 'all']"
160103 03:28:59 DEBUG   'AdminPlugin: OnSay handle 5:"!say hi"'
160103 03:28:59 DEBUG   'AdminPlugin: Handle command !say hi'
160103 03:28:59 DEBUG   "getCommand: ('admin.say', 'MAGIC: hi', 'all')"
160103 03:28:59 CONSOLE "['player.onChat', 'Server', 'MAGIC: hi', 'all']"
```

**Comment by OrfeasZ** [comment]
Are you sure you updated your server to build 10822?

**Comment by MAGICCC** [comment]
Yes it was at build 10822, now it got updated to 10827. I will try it again

**Comment by derrod** [comment]
No issues with 32 players on 10822 so far. Granted I don't have B3 and can't test if something it does different than the rcon tools I use that crashes the server.
