### ISSUE TITLE
Inconsistent Damage (M1911)

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#177]
The Video speaks for itself. Since it isn't damage collecting because we were on Ts and they really shot/hitted only one bullet. https://youtu.be/bpk5498t3JQ

**Comment by OrfeasZ** [comment]
Further research suggests that this is caused by a hit registering more than once while the bullet is travelling through a player's body, due to the increased update rate.

**Comment by kiwidoggie** [comment]
See: http://www.youtube.com/watch?v=3vDOC1V6GM8
Looks similar.

**Comment by OrfeasZ** [comment]
Fixed in build 12914.
