### ISSUE TITLE
Invisible Soldier Model in High Frequency with High Ping

### ISSUE THREAD

**Issue by rierei** [VeniceUnleashed/VeniceUnleashed#179]
Playing tdm in ziba tower 120 hz server, which is very frantic, I noticed that at times the player models are invisible.

When make quick encounters with enemies, as I run around the map, find invisible enemy only viewing the shots and weapon flashs.

When spawn in squad ally there are cases where:
- The ally is invisible.
- Near enemy is invisible.

In all cases the invisibility lasted up to about 3 seconds and my ping was 250.

**Comment by rierei** [comment]
Video: [VU_invisiblesoldier](https://vid.me/l87s)

**Comment by OrfeasZ** [comment]
Probably an issue with the server choking under load. Will close this for now.
