### ISSUE TITLE
Using backspace to navigate buggy

### ISSUE THREAD

**Issue by spooker0** [VeniceUnleashed/VeniceUnleashed#18]
Expected behavior: Backspace is supposed to let you go back a screen when you're in the Venice menu.

Problem:
When you quit out of a server and repeatedly press backspace, you're put into a black screen with "loading" flashing on the bottom right corner. There is no way to get out of this screen unless you quit the client.

When you login, then press backspace repeatedly, you see the login screen again, but if you try to login again, the form says "This account is already in-use from a different location". Expected behavior is that you should not be able to backspace into the login screen, or doing so should automatically log you out.

**Comment by OrfeasZ** [comment]
This is unexpected behavior and will be disabled in the next release.

**Comment by OrfeasZ** [comment]
Fixed in build 6758 (not live yet).
