### ISSUE TITLE
Downloading and installing.

### ISSUE THREAD

**Issue by DumbBoot** [VeniceUnleashed/VeniceUnleashed#182]
I dont see any intructions on how to download and install the product.

I downloaded the zip file and i dont know what to do from there. Every time i open any of the files they just come up as a error message.

**Comment by MAGICCC** [comment]
1.) Extract it somewhere
2.) Link your Originaccount to you EN one: http://sso.emulatornexus.com/link
3.) Start org. BF3 once
4.) Start VU
5.) Profit?!

**Comment by DumbBoot** [comment]
Im confused. how do i link orign with that website. i logged in and then hit link account and nothing happens. i turned my add blocker off. 

also do i log in with the website or the app origin

**Comment by DumbBoot** [comment]
Im very confused on this installation process. Maybe a video tutorial would be useful.

**Comment by ghost** [comment]
When you Click on "Link your Account" a popup will be Open. So maybe your Browser block Popups.

**Comment by OrfeasZ** [comment]
This issue tracker is not for direct support.
If you want support visit our forums.
