### ISSUE TITLE
Game Crash when Shoot on to Specator Camera

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#188]
When you Shoot on to the Spectator Camera, the Specator his Game Crash.
Sorry for Bad English.

**Comment by OrfeasZ** [comment]
Can you provide an associated crash ID for that crash?

**Comment by ghost** [comment]
No, i dont get any Crash ID. Just a Screen from Windows with "Venice Unleashed funktioniert nicht mehr" (Venice Unleashed dont Work anymore.) and get te Following Options.
- Wait for Venice Unleashed
- Close Venice Unleashed
- Debug Venice Unleashed (This is because i have Visual Studio 2015 Installed)

**Comment by ghost** [comment]
I can give you this. I translate it from German to Englisch. Got it from the Windows Event viewer.

Name of the Crashed programm: vu.exe, Version: 1.0.0.0, Timestamp: 0x511c9356
Name of the Crashed module: vu.dll, Version: 0.9.0.0, Timestamp: 0x5681a75d
Exceptioncode: 0xc0000409
Failureoffset: 0x0044c881
ID from the Crashed Process: 0x594
Starttime of the Failure Programm: 0x01d1434dc928c9d9
Path to the Crashed Programm: C:\Program Files (x86)\VeniceUnleashed\vu.exe
Path to the Crashed Module: C:\Program Files (x86)\VeniceUnleashed\vubin\vu.dll
ReportID: cc1048c9-af41-11e5-8250-d43d7e4e3213

And other Stuff from the Event Viewer:

Failbucket , Typ 0
Eventname: BEX
CAB-File-ID: 0

Problemsignature:
P1: vu.exe
P2: 1.0.0.0
P3: 511c9356
P4: vu.dll
P5: 0.9.0.0
P6: 5681a75d
P7: 0044c881
P8: c0000409
P9: 00000002
P10

I added the .WER File from the Event Viewer.
Edit// Github is a Little bit buggy for me :D I cant Upload the WER File, so i uploaded it to my Server.
https://do.mrkek.ovh/2015-12/AppCrash_vu.exe_9876b9bb921663a242cba8afcd8dc99d6e0fb9d_2d0e0324_1f69d3d5.zip

**Comment by kiwidoggie** [comment]
Currently tracking progress https://github.com/EmulatorNexus/VeniceUnleashed/issues/199 there.
