### ISSUE TITLE
Suggestion: Allow opening the menu during killcam

### ISSUE THREAD

**Issue by MizuDG** [VeniceUnleashed/VeniceUnleashed#192]
This has been present only in BF3 and to this day, it's annoying as hell that you can't do anything while you watch the killcam.

**Comment by bigworld12** [comment]
also i suggest keeping the chat stay open because it's annoying to re-type what i was typing coz i got killed

**Comment by kiwidoggie** [comment]
I think this is intentionally by DICE to fix https://www.youtube.com/watch?v=DaprSQsy81A. I will look into it.
