### ISSUE TITLE
In-Use from another location

### ISSUE THREAD

**Issue by Frankity** [VeniceUnleashed/VeniceUnleashed#193]
i just got this after pressing login button!
![Image of issue](http://i.axton.ml/01-01-16/BUm)

**Comment by kiwidoggie** [comment]
Is this still an issue? Sometimes it may take a few moments to timeout.

**Comment by OrfeasZ** [comment]
This probably means you're still running an instance of the game, or that you crashed and your previous connection hasn't timed out yet.
