### ISSUE TITLE
driver profles not loading do to unknown binary name 

### ISSUE THREAD

**Issue by senposage** [VeniceUnleashed/VeniceUnleashed#194]
vu.exe needs to be `renamed` to bf3.exe or gpu driver profiling doesn't work 
tested on two machines a amd and a nvidia one(should affect intel as well) 
you can confirm by running nvidia inspector and copypasta ing the profile name from bf3.exe to vu.exe 
this is likely a fair chunk of  the reason that people are having performance issues

**Comment by senposage** [comment]
from the looks of it you may need to create a copy of the actual bf3.exe and rename it so something like bf3vu.exe so your injection will work ...

**Comment by kiwidoggie** [comment]
We are not going to change the executable, OP has posted a workaround with the profiles. I personally just created a new one and used the same settings (SLI Enabled).

**Comment by senposage** [comment]
- the work around doesn't exist for AMD users the only way to fix the profiles is to hex edit the atiapfxx.blb which is a pain in the ass and will break every driver update also the CFX profile won't work either because thats defined in the driver .dll 's which you can't tamper with due to driver signature enforcement

**Comment by senposage** [comment]
open atiapfxx.blb (located in c:\windows\syswow64) and have a look round 0000FC00 thats what defines the aa/shader optimisation profile 
maby you can patch it via the launcher
