### ISSUE TITLE
Teams are not reinitialized after map switch

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#195]
This can lead to issues when switching between maps with different sized teams.
Rush (2x16) -> Conquest Large (2x32) => Only 32 slots (2x16) available/Server limited to 32 slots
Conquest Large (2x32) -> Rush (2x16) => 64 Slots stay available, works.

Squad Deathmatch (probably other modes that don't use a 2 Team setup too) still works correctly (4x6). Switching from Rush to SQDM to CQL will correctly initialize two teams with 32 slots for CQL.

It also seems weird that Rush only allows 32 players while on Vanilla BF3 64 player rush is actually possible.

**Comment by OrfeasZ** [comment]
This should be fixed in one of the latest builds.
Please let me know if that's not the case.
