### ISSUE TITLE
Feature Request: Disabling updating and crash reporting

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#197]
Two feature requests that might be useful for people running headless machines or server providers who do not want to have to RDP into a machine.

Disabling updating
- Allows to run multiple instances off of one installation without not being able to restart them when an update is available
  - A workaround to this issue is to have one folder with a VU installation per instance
- Allows patching in a maintenance window rather than having to update as soon as an update is available
- Allows easier central patching
- Patching starts a new process so if you're checking for the PID of the spawned process to determine if a server has crashed/shut down this will break such scripts

Disabling crash reporting (at least for servers) makes automatic server restarts easier.
Alternatively please make it possible to just disable the dialogue (which also does not work on headless linux machines) and log the output to a file instead.

**Comment by kiwidoggie** [comment]
+1 for the server disabling auto-update. I rather it be configurable or just leave it offline and display a log.

**Comment by OrfeasZ** [comment]
This has been implemented in build 10827. Servers can now disable startup updates using the **-noUpdate** switch (note, this feature is only available for server instances).
Crash reporting will **not** be toggle-able, but it has now been updated in order to properly work in headless environments.

**Comment by derrod** [comment]
What about simply sending the crash report but not waiting for user confirmation before restarting?

**Comment by OrfeasZ** [comment]
You can run your server using -headless on windows, which should alleviate this issue, while allowing you to output the log to a file of your choice.
