### ISSUE TITLE
Can't quit the game properly

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#2]
I've encountered a bug, while I want to quit the game, it would freeze when exiting, and both press close button or press Alt + F4 won't work, it makes me have to use task manager to force close the game. Please take a look at this issue and release a patch to fix this problem.
FYI I'm using Windows 7 Ultimate 64 bit, I'll provide more information about my PC if you need it.

**Comment by OrfeasZ** [comment]
@huangfengye Can you please confirm that this problem is still present?

**Comment by mirh** [comment]
I can confirm the game still doesn't close when you press the X button on the top-right of the window
Windows 7 64bit too

**Comment by OrfeasZ** [comment]
Several safeguards have been put in place to ensure the game quits.
It is perfectly normal for the game to freeze for a few seconds before completely shutting down.
