### ISSUE TITLE
Playing on low-end GPU's

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#20]
Is it possible to do some tweaks which will disable shadows and effects in order to play Venice Unleashed on low-end GPU's like ATI 5450?

**Comment by Xulunix** [comment]
No, i don't think this is planed atm.
if you can't play vanilla BF3, you can't play VU.

**Comment by OrfeasZ** [comment]
It might be possible, but not something we want to consider right now.
We might revisit this at a later date.
