### ISSUE TITLE
Chat window stays after being kicked

### ISSUE THREAD

**Issue by xerxes-at** [VeniceUnleashed/VeniceUnleashed#202]
Chat window stays if it was visible while being kicked.

![vu_2016_01_02_19_46_19_779](https://cloud.githubusercontent.com/assets/5236639/12075717/de55f7e8-b189-11e5-987b-9ae8694c54e1.jpg)

**Comment by kiwidoggie** [comment]
This is caused by VEXT not unloading plugins after being dropped or kicked from the server. Not sure what the implementation for this is supposed to be, adding NF to take a look.

**Comment by OrfeasZ** [comment]
This should be fixed in the upcoming update.
