### ISSUE TITLE
Killfeed is delayed in spectator mode

### ISSUE THREAD

**Issue by MAGICCC** [VeniceUnleashed/VeniceUnleashed#203]
Noticed it today, after doing some spectatortests. 
Recorded on a 60Hz server
https://www.youtube.com/watch?v=Jm4EFWsqjrs

**Comment by AlexEe77** [comment]
video is private

**Comment by MAGICCC** [comment]
ugh, changed it to Unlisted

**Comment by OrfeasZ** [comment]
This is an inherent problem with the way Frostbite handles the kill-feed.
I'm marking this as invalid since we'll be completely replacing that functionality for spectators soon.
