### ISSUE TITLE
[Bug] In spectator mode player legs rotate around (Jet) 

### ISSUE THREAD

**Issue by VladMcCaffrey** [VeniceUnleashed/VeniceUnleashed#205]
Spectator mode, Going on a player that is flying a jet. The legs off the players character rotate around and just do funny stuff.

Video: https://www.youtube.com/watch?v=neQ6BmKMP1U 

Here's a few screenshots

![Image1](http://i.imgur.com/4Q7nBrt.jpg)
![Image2](http://i.imgur.com/c90cy0e.jpg)
![Image3](http://i.imgur.com/6cVkJUL.jpg)

**Comment by OrfeasZ** [comment]
Duplicate of #76
