### ISSUE TITLE
Failing to update client files 

### ISSUE THREAD

**Issue by 1942FOOFIGHTER** [VeniceUnleashed/VeniceUnleashed#209]
Have you ran Battlefield 3 successfully via origin: YES
Do you have ANY integrated graphics (AMD APU, Intel Integrated, NV Optimus): NO
Operating System: Windows 10
Anti-Virus Solution: SuperAntiSpyware Pro/Windows Defender
Have you linked your account for verification: YES
Have you tried above troubleshooting steps: YES
Does VU quit without a crash: NO
Crash Record: An Error Has Occurred While Updating Code 2X2 Your Client will restart in 5 seconds
What were you doing when it crashed: Signing in and its trying to Update client files

**Comment by kiwidoggie** [comment]
Download the latest files from http://veniceunleashed.net/downloads and let me know if you still have this issue. There have been many user's with this issue recently, adding NF to take a look to ensure all services are still up.

**Comment by 1942FOOFIGHTER** [comment]
I did everything is working thanks 

```
On Thursday, January 14, 2016 6:44 AM, kiwipuppeh <notifications@github.com> wrote:
```

 Download the latest files from http://veniceunleashed.net/downloads and let me know if you still have this issue. There have been many user's with this issue recently, adding NF to take a look to ensure all services are still up.—
