### ISSUE TITLE
Show this issue

### ISSUE THREAD

**Issue by hanjianlin** [VeniceUnleashed/VeniceUnleashed#21]
![image](https://cloud.githubusercontent.com/assets/883268/5112052/ef243c68-705f-11e4-93f5-a2878c7ef3bb.png)

**Comment by OrfeasZ** [comment]
@zestybaby
I'm not sure if this is Chinese, but if so could you possibly translate what the dialog says?

**Comment by zestybaby** [comment]
That means the account was used on too much PCs.

**Comment by OrfeasZ** [comment]
@zestybaby Thank you.
@hanjianlin You should contact EA/Origin about licensing issues.
Closed.

**Comment by hanjianlin** [comment]
@zestybaby
I removed the Core directory and repaired by roigin Battlefield 3 files
Has been resolved!
You get the beta qualifications that?

**Comment by zestybaby** [comment]
@hanjianlin Yes, since I'm a member from mod team, I granted that from the beginning.

**Comment by hanjianlin** [comment]
@zestybaby 
I would like to get Niece qualifications! I do not know what way can I get one?
