### ISSUE TITLE
New Premium Purchased, and Installed. No DLC servers show up!

### ISSUE THREAD

**Issue by ThatBritishGamerChap** [VeniceUnleashed/VeniceUnleashed#210]
Hello There

So I got the Premium DLC for Battlefield 3 Via Origin. Unfortunately, I cannot seem to get any DLC mapped servers to appear in the server list. How can I rectify this?

Thanks
-TBGC

**Comment by kiwidoggie** [comment]
That means that there are no servers running the DLC maps currently. As we are still in testing and many people only have the base game, admins tend to stick with the older maps. There is nothing wrong on your end.
