### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by InvalidHandle** [VeniceUnleashed/VeniceUnleashed#211]
During startup, the following message is displayed, and the game crashes shortly after. (No possibility to login yet)
This ID has been given to provide here: 49243C0A-3E4A-48F4-8705-B45E5BD2237D (not a fixed code, changes every time)

**Comment by kiwidoggie** [comment]
This is caused by MSI's Nahimic audio software. Uninstall, restart your pc and try again. This is a non-issue due to VU but to personal configuration. If you would like further troubleshooting send me a PM on the forums.
