### ISSUE TITLE
Can't Reset My Password!!!

### ISSUE THREAD

**Issue by kemocono** [VeniceUnleashed/VeniceUnleashed#212]
i havent been playing for a while and i forgot my my password! so when i click "I forgot my password"
this message in showing [Unable to load the Are You a Human PlayThru™. Please contact the site owner to report the problem.]
so please solve it! thanks
![capture](https://cloud.githubusercontent.com/assets/17785197/13705607/3941aa70-e7aa-11e5-8ad7-9cc427f95d3b.PNG)

**Comment by OrfeasZ** [comment]
Thanks for bringing this to our attention. It should now be fixed.
