### ISSUE TITLE
Frostbite variable "end" confused with lua end

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#214]
Frostbite variables called end will cause a syntax error and prevent it from compiling.

In the Fog class, we have a variable called end. 
If we include that variable, the script won't compile since the function will end early.

This can be solved by remapping fog.end to fog.endDistance.
fog.start should also be remapped to fog.startDistance for likeness sake.

**Comment by OrfeasZ** [comment]
As a workaround you can try accessing them using the brackets operator for now (ie. `fog['end']`).

**Comment by OrfeasZ** [comment]
Starting with the next update, all game data members that are reserved lua keywords will have `Value` appended to them. For instance, `end` will become `endValue`.

Here is a full list of members this applies to:
```
and break do else elseif end false for function if
in local nil not or return then true until
```

**Comment by Powback** [comment]
Also applies to out, as seen in 
BandPassFir64NodeData
CompressorNodeData
CrossfaderNodeData
DataGetNode
etc.

Also for repeat as seen in AwardData.

**Comment by OrfeasZ** [comment]
@Powback apparently I didn't type in the whole list. Here's what it looks like right now:

```
and break do else elseif end
false for function goto if in
local nil not or repeat return
then true until while
```

**Comment by Powback** [comment]
@OrfeasZ These modified values are not reflected in TypeInfo, so iterating through fog will still return end instead of endValue.
