### ISSUE TITLE
Cant create soldier 

### ISSUE THREAD

**Issue by crystillgirl** [VeniceUnleashed/VeniceUnleashed#219]
everytime i put name it mean name taken or other error i tryed random words it sill

**Comment by MAGICCC** [comment]
The linking service is down. You mught check the VU Discord server which is linked in the forum

**Comment by crystillgirl** [comment]
im on discord see no links

**Comment by kiwidoggie** [comment]
http://forums.veniceunleashed.net/viewtopic.php?f=40&t=8876

**Comment by OrfeasZ** [comment]
Closing this as it's not really relevant. You will be able to download/use VU again once version 1.0 is released.
