### ISSUE TITLE
[REQ] Mod name in debug console

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#222]
It would be nice to have the mod name automatically added to prints. Perhaps as a bool in the mod config?

Example:
VEXT TestPlugin:
print("Test Print")

Console:
[TestPlugin] Test Print

**Comment by OrfeasZ** [comment]
After the next update prints and events related to a specific VeniceEXT module will contain its name as seen below:
![](http://i.nofate.me/S2FLz1nTS4.png)
![](http://i.nofate.me/S4YkTlcCNF.png)
