### ISSUE TITLE
[REQ] Spawn player at position X with loadout Y

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#224]
Should create a SoldierEntity at position X with loadout Y
Position should be a LinearTransform.
Loadout should be an array of CustomizeSoldierData or whatever's used for loadout. 
```
if s_Player.soldier == nil then
    SoldierManager:SpawnSoldier(LinearTransform, CustomizeSoldierData)
end
```

The goal is to completely remove the spawn UI and spawn the player with a custom UI. 
I'm not sure how this would affect the existing spawnpoints, but as long as we're able to select the weapons you deploy with, it should be fine.

**Comment by 3ti65** [comment]
kinda redundant as it's featured as one of multiple 'commands' here:

https://github.com/EmulatorNexus/VeniceUnleashed/issues/226

(Although i didnt specify the parameter types)

**Comment by Powback** [comment]
Duplicate request
