### ISSUE TITLE
[REQ] New Events and Commands

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#226]
Important
--------------------------------------------

Types of some parameters are not always defined due to lack of my knowledge on how its done in bf3.
the commands are something we discussed before, its basically an invoking of stuff that should happen.
for example:
in our custom UI we press spawn, this triggers a netevent, which then is handled in our server lua. There we then want to invoke the SpawnPlayer(playerEntity, loadout, position), to actually spawn the player.
we need the commands so we can invoke stuff that the default UI used to handle (since we're replacing that one)

COMMANDS: (Most important is the spawning stuff)
--------------------------------------------

_**Note:**
These commands are supposed to actually manually trigger stuff that should happen.
For example the SpawnPlayer(playerEntity, loadout, position) should spawn a player with a certain layout at a certain position. Stuff like Suicide or LeaveGame could be covered with !Kill or !Kick admin commands, but then there's no way to differentiate between whether the player has left himself or has been left. These commands are absolutely essential for the realitymod._ 

- [x] SpawnPlayer(playerEntity, loadout, position)
- [x] SpawnKit(loadout, position)
- [x] SpawnVehicle(vehicleEntity, position)
- [x] SpawnObject(objectEntity, position)
 
- [x] CreateSquad(player, team, squad, name)
- [ ] ChangeLockSquad(player, team, squad, isLocked)
- [x] JoinSquad(player, team, squad)
- [x] LeaveSquad(player, team, squad)
 
- [x] Suicide(player)
- [x] LeaveGame(player)

MISSING EVENTS: (Server & Client)
--------------------------------------------

**Player:**
 
- [x] Player:WeaponChanged(player, oldWeaponEntity, newWeaponEntity) // Player has changed which weapon they are holding.
- [x] Player:FiremodeChanged(player, enum fireMode) // Clientside only?
- [x] Player:Score(playerEntity, difference) // Difference is change to player's score (positive or negative)
- [x] Player:Healing(givingPlayerEntity, receivingSoldierEntity, healthPointsGiven)
- [x] Player:Repairing(givingPlayerEntity, receivingVehicleEntity, repairPointsGiven)
- [x] Player:GivingAmmo(givingPlayerEntity, receivingObjectEntity, ammoPointsGiven)
- [x] Player:GivingDamageToTeamPlayer(playerEntity, victimSoldierEntity, damagePointsGiven)
- [x] Player:GivingDamageToPlayer(givingPlayerEntity, receivingSoldierEntity, damagePointsGiven)
- [x] Player:GivingDamageToVehilce(givingPlayerEntity, receivingVehicleEntity, damagePointsGiven)
- [ ] Player:GivingDamageToObject(givingPlayerEntity, receivingObjectEntity, damagePointsGiven)
- [x] Player:EnemySuppressed(player, victim)
 
- [x] Player:Revived(revivedPlayerEntity, medicPlayerEntity) // Player has been revived from a "critically injured" condition to full health by a medic using "shock paddles". Players can only be revived in the interval between a PlayerKilled event and a subsequent PlayerDeath event.
 
- [x] Player:Suicided(playerEntity)
- [ ] Player:Death(playerEntity) // This event occurs when a player is decisively dead, and cannot be revived; they will only return to the game by respawning.
- [x] Player:Left(playerEntity)
 
- [x] Player:EnterControlPoint(player, controlPointEntity)
- [x] Player:ExitControlPoint(player, controlPointEntity)

**Missing Player Overloads:**

- [x] Player:SquadChange(player, oldSquad, newSquad)
- [x] Player:Killed(victim, inflictor, position, weapon, roadkill, headshot, victimInReviveState, assistingPlayers[])
 
**Vehicle-/ Object:**
 
- [x] Vehicle:Enter(playerEntity, vehicleEntity)
- [x] Vehicle:Exit(playerEntity, vehicleEntity)
- [x] Vehicle:Spawned(vehicleEntity, position)
- [x] Vehicle:Destroyed(vehicleEntity, inflictor, position, weapon)

- [ ] Object:Destroyed(objectEntity, inflictor, position, weapon)
 
**Kit:**
 
- [x] Kit:Pickup(playerEntity, kitEntity)
- [x] Kit:Drop(playerEntity, kitEntity)
 
**Team:**
 
- [x] Team:ChangedCommander(teamID, oldCommanderPlayerEntity, newCommanderPlayerEntity)
- [x] Team:ChangedSquadLeader(squadID, oldLeaderPlayerEntity, newLeaderPlayerEntity)
 
- [x] Team:SquadCreated(player, team, squad, name)
- [x] Team:SquadRemoved(team, squad)
 
**Game/ Round:**
 
- [ ] Server:RoundStart()
- [ ] Server:TicketsChanged(teamID, ticketsDelta, remaining) 
- [ ] Server:TimeLimitReached() // Event fires when the fixed time limit for a round expires
 
_**Note:**
Server:RoundOver roundTime, winningTeam already exists, that's why i went with this convention. The namespace 'server' for round stuff might not be the optimal choice here._

**ControlPoint:**
 
- [x] ControlPoint:OwnerChanged(controlPointEntity, attackingTeamID)
- [x] ControlPoint:Neutralized(controlPointEntity, teamID, playerEntities)
- [x] ControlPoint:Captured(controlPointEntity, teamID, playerEntities)
 
MISSING HOOKS: 
--------------------------------------------
-snip-

Managers: 
--------------------------------------------
// Todo

**Comment by OrfeasZ** [comment]
@3ti65 some of these are already supported:

`CreateSquad`, `JoinSquad` and `LeaveSquad` can be handled via `player.squadID = SquadId.SquadX`, where `X` is either `None` or `1` through `32`. If the squad doesn't already exist it will be created. If `SquadId.SquadNone` is used, the player will be removed from their current squad.

`Suicide` can be achieved using `player.soldier:Kill(killedByAdmin)`, where `killedByAdmin` is a boolean. I believe that if it's set to `false`, the death will be handled as a suicide.

`LeaveGame` can be achieved by kicking the player from the server using `player:Kick()` or `player:Kick(reason)`, where `reason` is a string representing why the player was kicked.

It should be noted that all of the above are available from the server-side VeniceEXT interface.

**Comment by OrfeasZ** [comment]
Also, `SpawnObject` can be achieved using `EntityManager:CreateClientEntity` or `EntityManager:CreateServerEntity`. Parameters are `DataContainer entityData, LinearTransform transform`. It should be noted that just because you create an entity on the server, it doesn't mean that it will also be created on the client.

**Comment by OrfeasZ** [comment]
There's also an experimental `player:Spawn(spawnPointEntity, checkSpawnArea)` function that spawns a player at a specific spawn point (`checkSpawnArea` is a bool when set to false will bypass the "safe spawning" checks, ie. spawn point is not being shot at when it's another soldier).

**Comment by 3ti65** [comment]
The player:Spawn should have an overload or a fixed parameter that lets you define a loadout for that player. (Which class, weapon, etc)

Also, it would be nice to have more knowledge on how the loadout / kit thing is handled upon spawn.

**Comment by 3ti65** [comment]
@kiwidoggie 
Added:
Player:FiremodeChanged(player, enum fireMode)

Renamed:
Player:ChangeWeapon -> Player:WeaponChanged

The FireModeChanged event could be clientside only probably. Just need that for the UI.

**Comment by 3ti65** [comment]
added Hook:

Client:UpdateInput(entryInput)

we might need this parallel to the event but as a hook, e.g. to stop certain players from pressing certain buttons. (to prevent bunnyhopping etc)

**Comment by OrfeasZ** [comment]
Build 12211 contains the following events:
- Player:SetSquad(player, squad)
- Player:SetSquadLeader(player)
- Player:KickedFromSquad(player, oldSquad)

**Comment by OrfeasZ** [comment]
Build 12214 adds:
- Server:RoundReset
- Player:KitReplaced(player, oldSoldier, newSoldier)
- CapturePoint:Captured(capturePointEntity)
- CapturePoint:Lost(capturePointEntity)
- Vehicle:Enter(vehicleEntity, player)
- Vehicle:Exit(vehicleEntity, player)
- Vehicle:Damage(vehicleEntity, damageDone)
- Vehicle:Destroyed(vehicleEntity, vehiclePoints, hotTeam)
- Vehicle:Disabled(vehicleEntity)
- Vehicle:SpawnDone(vehicleEntity)
- Vehicle:Unspawn(vehicleEntity)
- Player:ReviveAccepted(reviver, revivee)
- Player:ReviveRefused(revivee)
- Player:ManDownRevived(reviver, revivee, isAdrenalineRevive)
- Player:ChangingWeapon(player)
- Player:Reload(player, weapon, position)
- Player:EnteredCapturePoint(player, capturePointEntity)
- Player:ExitedCapturePoint(player, capturePointEntity)

**Comment by 3ti65** [comment]
removed hook 'Client:UpdateInput(entryInput)' since its already covered by 'Input:PreUpdate'.

**Comment by 3ti65** [comment]
Player:KitReplaced(player, oldSoldier, newSoldier) --doesnt work
    CapturePoint:Captured(capturePointEntity) --doesnt work
    CapturePoint:Lost(capturePointEntity) --doesnt work
    Vehicle:Enter(vehicleEntity, player) --doesnt work
    Vehicle:Exit(vehicleEntity, player) --doesnt work
    Vehicle:Damage(vehicleEntity, damageDone) --doesnt work
    Vehicle:Destroyed(vehicleEntity, vehiclePoints, hotTeam) --doesnt work
    Vehicle:Disabled(vehicleEntity) --doesnt work
    Vehicle:SpawnDone(vehicleEntity) --doesnt work
    Vehicle:Unspawn(vehicleEntity) --doesnt work
    Player:ChangingWeapon(player) --doesnt work
    Player:Reload(player, weapon, position) --doesnt work

**Comment by kiwidoggie** [comment]
Fixed in build 12460

**Comment by kiwidoggie** [comment]
Player:Left has been implemented in 12461

**Comment by 3ti65** [comment]
For the client event Player:FiremodeChanged(enum firemodeType) its possible that its done similar to swbf (code from txt):

FireLogicType GetFireMode( )
        {
            return m_FireModes.at( m_FireModeIndex );
        }
...

int32_t m_FireModeIndex; //0x01D8
...

eastl::vector<FireLogicType> m_FireModes; //0x01E8

**Comment by OrfeasZ** [comment]
Build 12946 adds `soldier:GetCurrentWeaponFireLogic()` and `soldier:GetWeaponFireLogicByIndex(idx)` (client-side).

**Comment by 3ti65** [comment]
Gonna verify which Events are still needed and then update the issue accordingly.

**Comment by 3ti65** [comment]
Added event:

Player:EnemySuppressed(player, victim)

Gonna update the list soon to see what we still need

**Comment by kiwidoggie** [comment]
Build 15479 adds `Player:EnemySuppressed` (called once per update that suppression is updating)
Build 15480 adds `Player:Suicided` when they kill themselves (menu, or otherwise)

**Comment by kiwidoggie** [comment]
Build 15481 adds `Player:Healing`, `Player:GivingDamageToTeamPlayer`, and `Player:GivingDamageToPlayer`

**Comment by kiwidoggie** [comment]
Build 15482 adds `Player:GivingAmmo(supplier, receiver , magCount)` (slightly different from what was asked for)

**Comment by kiwidoggie** [comment]
Build 15484 adds `Player:Repairing(player, vehicle, damageDone)` (slightly different)
