### ISSUE TITLE
Using other (Super-)Bundles causing Crash

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#227]
Loading/ Mounting (Super-)Bundles crashes both the VU Client and Server on Mapchange or Disconnect. Client crashes instantly and Server once the game is ready. (Powback)
High priority bug since without this fixed it's not feasible to use any game content on other maps than the ones that already have it contained.

**Comment by Powback** [comment]
Also crashes when you access the settings menu. Under video/keybinds

**Comment by 3ti65** [comment]
https://mega.nz/#!Vgx3ETDJ!LNv2gOLeEfHhSkgR7cC1PRQ5YZ_OcWp_u64PnG92WXs

DL link for the bundlecrash test mod. Same as linked by Powback in Discord before.

**Comment by Powback** [comment]
I should note that only the client crashes in the linked mod iirc.

**Comment by OrfeasZ** [comment]
Are there documented instances of the server crashing?

**Comment by Powback** [comment]
I haven't experienced server crashes related to bundlemounting after the update.

**Comment by OrfeasZ** [comment]
@3ti65 @Powback does this still happen?

**Comment by Powback** [comment]
@OrfeasZ Yes. Changing map after loading bundles causes the client to crash. The server seems fine however.

Replicated by the mod above.
Steps: 
Start server
Join server
Change map using procon. -> Client crash

**Comment by Powback** [comment]
Can also be demonstrated by entering the video settings.

Edit: Unrelated issue.

**Comment by OrfeasZ** [comment]
Build `13693` implements possibly the most terrible hack ever known to humanity in an attempt to fix this god forsaken issue, which has made me question my sanity. This is in no way guaranteed to work, especially under complex bundle loading scenarios.

Here's an example of how to """properly""" inject custom superbundles and bundles into a level:
```lua
Events:Subscribe('Level:LoadResources', function(dedicated)
    ResourceManager:MountSuperBundle('SpChunks')
    ResourceManager:MountSuperBundle('Levels/COOP_003/COOP_003')
end)

Hooks:Install('ResourceManager:LoadBundles', 100, function(hook, bundles, compartment)
    if bundles[1] == 'Levels/XP2_Skybar/XP2_Skybar' then
        bundles = {
            'Levels/COOP_003/COOP_003',
            'Levels/COOP_003/AB00_Parent',
            'Levels/XP2_Skybar/XP2_Skybar',
        }

        hook:Pass(bundles, compartment)
    end
end)
```

Any custom bundles need to be loaded before the main level bundle, as anything else seems to invoke the wrath of zh1nt0 and crashes your game.

**Comment by Powback** [comment]
For future reference: Primary bundles must be listed before secondary bundles, otherwise the client will crash.

Example:
```
'Levels/COOP_003/COOP_003',
'Levels/COOP_003/AB00_Parent'
```
not:
```
'Levels/COOP_003/AB00_Parent',
'Levels/COOP_003/COOP_003',
```
