### ISSUE TITLE
[REQ] Access server data in VEXT

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#228]
* ServerName (String)
* Playlist (String/array)
* Current map (String)
   * Levels/MP_001/MP_001 or just MP_001
* Current gamemode (String)
   * Conquest_Large
* Current Round (int)
* Round Count (int)
* PlayerCountNeededForMultiplayer (int)

**Comment by OrfeasZ** [comment]
@Powback instead of implementing all of these separately, would it be preferable to expose an interface to execute RCON commands and get their responses?

**Comment by Powback** [comment]
I would like to access those with vext in order to do custom loading screens and in game UI, even if it's read-only. Procon access would be a plus.

**Comment by OrfeasZ** [comment]
You can get most of these via game Settings, which will be exposed via `SettingsManager`.

**Comment by Powback** [comment]
The primary information I'm looking for is server name, map name, round count and current round. If the rest could be accessed from procon, it would be nice, but I'm not looking for that possibility.

**Comment by OrfeasZ** [comment]
Procon is a program.

**Comment by OrfeasZ** [comment]
Also, I don't believe the server name is available from the client.

**Comment by Powback** [comment]
I am aware. I mean rcon of course. I blame drinks.

**Comment by Powback** [comment]
Server name should be accessable from client in order to create custom loading screens and general UI information.

**Comment by OrfeasZ** [comment]
I will not be implementing this. I'll expose an interface on the server to execute rcon commands and then you can take their result and send it to the client using NetEvents. In combination with accessing Settings objects, you should be able to achieve what you're trying to do.

**Comment by Powback** [comment]
Fair enough. It seems like the better solution.
