### ISSUE TITLE
Can't move when re-connecting after spectating

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#23]
There is currently an issue where the Input Schema isn't being properly reset when exiting Spectator mode, resulting in the player being unable to move when re-joining a server normally.

**Comment by OrfeasZ** [comment]
Fixed in build 6786.

**Comment by derrod** [comment]
This bug still occurs in build 6865.

**Comment by OrfeasZ** [comment]
Looks like some later changes in the way the spectator mode works have caused this bug to re-appear.

**Comment by OrfeasZ** [comment]
Fixed again in build 6885.
