### ISSUE TITLE
[REQ] Global mods/Libraries

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#230]
Mods that can be accessed by other mods would enhance the modding experience. 

MathLib contains several 3D math functions.
If a mod wants to use MathLib, they would have to copypaste the mod and implement it in their own system.
If MathLib gets updated, everyone would have to manually copypaste the new version of MathLib, instead of just updating the MathLib mod.

You know the deal. We need global mods.

**Comment by 3ti65** [comment]
Wouldnt it make more sense to just be using those libraries via 'require' ?
Launching several mods parallel makes source control and dependencies alot harder.
But not sure.

**Comment by Powback** [comment]
Yes, basically lua libraries that can be accessed via require.

**Comment by OrfeasZ** [comment]
I've been thinking about this. First of all, the way it would work is that a global mod would get loaded individually for every other mod, meaning it will maintain its own state per mod. Now, the problem this introduces is that a global mod will be able to essentially "hijack" any other mod, by registering custom hooks or events, listening to local (net)events, etc, which could pose a small security risk.

**Comment by OrfeasZ** [comment]
After careful consideration I've decided that I won't be implementing this. If for some reason in the future this becomes highly requested I will reconsider.
