### ISSUE TITLE
Forward EffectManager to vEXT

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#231]
As discussed in discord. The Frostbite EffectManager can spawn and play effects. There should be a vEXT EffectManager which can just forward the function calls to the original one.

**Comment by Powback** [comment]
SoundManager also perhaps?

**Comment by 3ti65** [comment]
yup would be nice

**Comment by OrfeasZ** [comment]
@Powback it looks like you can spawn sound effects by passing a `SoundAsset` to the EffectManager. You'll have to try it once the initial implementation lands.

**Comment by OrfeasZ** [comment]
EffectManager has been implemented and provides the following functions (very untested):

- `number EffectManager:PlayEffect(DataContainer asset, LinearTransform transform, EffectParams params, bool firstPersonEffect)`
- `EffectManager:StopEffect(number handle)`
- `EffectManager:ResetEffect(number handle)`
- `EffectManager:SetEffectParameterBool(number handle, string name, bool value)`
- `EffectManager:SetEffectParameterInt(number handle, string name, number value)`
- `EffectManager:SetEffectParameterFloat(number handle, string name, number value)`
- `EffectManager:SetEffectTransform(number handle, LinearTransform transform)`
- `bool EffectManager:IsEffectPlaying(number handle)`
- `bool EffectManager:IsEffectDead(number handle)`
- `EffectManager:DisableEffects(number disableTimer)`
- `EffectManager:Clear()`

`EffectManager:PlayEffect(...)` returns a number which represents the effect handle. That handle can be passed to most of the other functions.

Here's a sample creation and usage of `EffectParams`:

```lua
local params = EffectParams()
params:SetFloat("EmitterParameter1", 12.3)
```

`EffectParams` has the following functions:
- `bool params:SetX(string name, T value)`
- `T params:GetX(string name)`
- `bool params:HasX(string name)`
- `number params.size`

Where `X` is one of `Bool`, `Int`, `Float`, and `Vec4`, and `T` is the corresponding value type.

This should be live on the dev branch within the next few hours.
