### ISSUE TITLE
Allow server sided DLL hosting / HTTP library 

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#232]
Having no DLLs distributed to client side makes a lot of sense, but on the server side it would be nice to have the ability to call a webservice or actual DLLs. Useful for Mumble integration, having a global ban list service, custom stats and tons of other useful stuff. Since the server admin actually hosts the files, he has full insight on what gets called.

**Comment by OrfeasZ** [comment]
Networking support will be added to both the server and the client side, exposed via vEXT. That includes raw TCP/UDP (and other protocols) and possibly helpers for HTTP. On top of that, a local storage implementation on the server side will be implemented, with bindings to SQLite.

With that being said, I still don't feel comfortable with enabling the execution of native (non sandboxed) code, even in controlled server environments. If there's a demand for it I might reconsider.

**Comment by 3ti65** [comment]
The things you mentioned should be sufficient. Otherwise we can make a new issue.
