### ISSUE TITLE
[REQ] Client console command registering. 

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#236]
Allow mods to access the client console by registering variables and functions/callbacks that will be executed on the client. The variable should only be passed if the input matches the type of the variable.

It's basically a replacement for kAdmin's chat command implementation.

Usage: 

ConsoleManager:RegisterVar(name, variable, (optional) hint)
ConsoleManager:RegisterCallback(name, callback, (optional) hint)

Example 1:

local s_Instance = SomeClass(p_Instance)

ConsoleManager:RegisterVar('TestMod.Enable', s_Instance.enable, "Enable / Disable some instance")

Example 2:

ConsoleManager:RegisterCallback('TestMod.DoThing', self.DoThing, hint)

function TestMod.DoThing((string) p_input)

**Comment by OrfeasZ** [comment]
Build `15629` introduces a new client-side `Console` library with the following methods:

- `ConsoleCommand Register(string name, string description, function callback)`
- `ConsoleCommand Register(string name, string description, object obj, function callback)`
- `bool Deregister(ConsoleCommand command)`
- `bool Deregister(string name)`
- `void DeregisterAll()`

The `callback` function has a single table argument, containing all the arguments passed to the console command by the user when executing it and can optionally return a string, which will be printed to the console output.

All commands will be automatically deregistered when the player leaves the server or when the mod in question gets unloaded.

The `ConsoleCommand` type has the following fields / methods:

- `string name`
- `string description`
- `string groupName`
- `void Deregister()`

Sample usage:
```lua
Console:Register("SomeCommand", "Incredible command description.", function(args)
    if #args == 1 and args[1] == "hello" then
        return "goodbye"
    end
end)
```

Then, the command will be executable via the in-game console as `modname.SomeCommand`, where `modname` is the name of the mod that has registered it.

Thanks @kiwidoggie
