### ISSUE TITLE
[REQ] Server roles accessable by vext server side.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#237]
Basically a json file that contains roles and users.

RoleManager:GetUsers('role') // returns an array of users under the selected role.

RoleManager:GetUser('username') // returns the user's roles as an string array. If there's no roles for the selected user, the array is empty or nil.

This is used to allow admins to perform admin stuff without using rcon.

**Comment by OrfeasZ** [comment]
An SQLite interface will be implemented, backed by local file storage. That should be enough to achieve something like this.
