### ISSUE TITLE
Uppercase letter in modlist.txt or in vu.modlist.add causes NetEvents to not work

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#238]
Example: 
```
modlist.txt
TestMod
```
NetEvents won't reach the server or client.

```
modlist.txt
testmod
```
NetEvents works properly.

**Comment by Powback** [comment]
I suggest that all mod inputs are converted to lowercase. That way you can remove mods without typing the correct case, as well as avoiding issues like this. The print messages should still contain the correct case.

**Comment by 3ti65** [comment]
@OrfeasZ  testmod can be downloaded in discord: VU /modders -> pinned message

**Comment by OrfeasZ** [comment]
This should be fixed in build 12215.
