### ISSUE TITLE
[REQ] Additional raycast features

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#240]
Raycast:Ray(Lineartransform start, Lineartransform Direction, float distance, ?RigidBodyCollisionLayer layer, ) // Returns nil or a Hit class

Hit class:
Vector3 point // the hit point transform
LinearTransform normal // the normal of the surface hit + point
Float distance // the distance between start and point, for ease of access
Entity entity // nil or hit entity
Vector3 transform // the transform of the entity hit

**Comment by OrfeasZ** [comment]
What's `RigidBodyCollisionLayer` supposed to represent?

**Comment by Powback** [comment]
Not sure if RigidbodyCollisionLayer is the correct term, but there should be certain layers that the raycast can hit.

Like invisible walls that bullets can pass through, but not players. This is not really an important parameter, but it would be nice if it was included.

    enum RigidBodyCollisionLayer {
	RigidBodyCollisionLayer_Invalid = 0,
	RigidBodyCollisionLayer_VehicleLayer = 1,
	RigidBodyCollisionLayer_VehicleAndCharacterCollisionLayer = 2,
	RigidBodyCollisionLayer_Size = 3
    }

**Comment by OrfeasZ** [comment]
Here are the different ray casting flags available (they can be combined):
```
CheckDetailMesh
DontCheckWater
DontCheckTerrain
DontCheckRagdoll
DontCheckCharacter
DontCheckGroup
DontCheckPhantoms
```

Are these enough for what you're trying to do?

**Comment by kiwidoggie** [comment]
This has been implemented in 12320

Client:
`RayCastHit RaycastManager:Racast(Vec3 from, Vec3 to, flags)`
`Entity RaycastManager:GetEntityInRaycast(float distance)`
