### ISSUE TITLE
Input:PreUpdate with readinstance on shared crashes client

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#242]
Hooking Input:PreUpdate on client and having Partition:ReadInstance event on shared crashes the client.
Seems to be just this hook. If you remove Partition:ReadInstance it works fine, as it does in bfjumper. This is using new hook system
[hookcrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1292829/hookcrash.zip)

**Comment by FoolHen** [comment]
Also, and most likely related, p_Hook:Pass() crashes the client too even without modifying its arguments. Seems like it only happens with this hook too

**Comment by OrfeasZ** [comment]
This should be fixed as of build 12229. If it's not let me know and I'll re-open the issue.
