### ISSUE TITLE
soldier:SetPosition(Vec3) resets the vertical rotation of the camera.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#243]
The horizontal rotation is kept, but the vertical rotation gets reset.

edit:
The best would be to not touch the rotation, as it causes jitter when it's called rapidly.

**Comment by Powback** [comment]
Preferably:
SetRotation(LinearTransform) // ignores trans, client and sever
SetPosition(Vec3) // only sets the pos, not touching rotation, server only
SetTransform(LinearTransform) // sets everything, server only

**Comment by kiwidoggie** [comment]
This has been added in Build 12264. `SoldierEntity:SetTransform(transform, updateAiming)`

**Comment by Powback** [comment]
SoldierEntity:SetTransform does not work in build 12466.
http://powback.com/u/08a2064135629ddccbead3856f016610.7z

ext/server/__init__.lua:63

I assume SetTransform doesn't set the transform correctly. If we change SetTransform(trans, true), the aim will be affected, but the position will not change.

Controls:
v = toggle noclip
alt = move forwards
space = move up
ctrl = move down

edit:
It seems to do *something*, but it looks like it gets corrected by the server before any noticeable change has been made.

**Comment by OrfeasZ** [comment]
Build 12941 removes `soldier:SetTransform()` (you can use `soldier.transform = x`) and changes `soldier:SetPosition(x)` to not affect view angles. `soldier:SetPosition(x)` is now also available on client-side soldier instances.
