### ISSUE TITLE
WebUI Flickering

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#245]
The issue seems to be triggered when a WebUI redraw is called. This includes CSS transitions/Animations or if something on the webpage is changed. (Adding/Removing text).

This can also be seen in the new console.

Examples:
[Example1](https://gfycat.com/hardtofindlightblesbok)
[Example2](http://powback.com/u/59e0f0db3bc18.webm)

**Comment by OrfeasZ** [comment]
Can you provide a very simple sample that reproduces this?

**Comment by FoolHen** [comment]
@OrfeasZ 
[flickertest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1389356/flickertest.zip)
Just a simple button, if you hover over it, you can see that a duplicate flickers at the middle left of the screen.
I couldn't replicate it with more stuff, but it's happening a lot in our custom UI

**Comment by Powback** [comment]
To add to this. If you create a dropdown menu, the options will not appear. I'm not sure if this worked prior to the update.

**Comment by 3ti65** [comment]
In addition to what Powback wrote, the sliders (e.g. from Pow's Cinematic Tools) are no longer usable after the most recent update.

**Comment by FoolHen** [comment]
Added a slider:
[flickertest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1414907/flickertest.zip)

**Comment by OrfeasZ** [comment]
Fixed in build 12253.
