### ISSUE TITLE
Memory corruption in VEXT

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#248]
These are some issues I found, some are new from 12229 update and some from before:

-  Some client hooks crash the client when calling hook:Pass() (both with modified arguments and original ones)
**Hooks that cause crashes:**
UI:PushScreen
Input:PreUpdate
ClientEntityFactory:Create
**Hooks that work fine:**
UI:EnableCursorMode
UI:CreateChatMessage

- Hooking UI:InputConceptEvent causes crash.

- Hooking UI:CreateChatMessage, after doing p_Hook:Pass("changed text", p_Channel, p_Player, p_RecipientMask, p_SenderIsDead), sometimes it outputs "changed text" followed by random characters:
![captura de pantalla 22](https://user-images.githubusercontent.com/7466799/31908701-0782996c-b838-11e7-9545-81de0e195f4b.png)

- hooking ServerEntityFactory:Create outputs device or resource busy on server. Client gets stuck on loading when joining the server

![](https://cdn.discordapp.com/attachments/187339455315574784/371712138055647233/Captura.PNG)

**Comment by OrfeasZ** [comment]
Fixed in build 12236

**Comment by FoolHen** [comment]
@OrfeasZ
All seem to be fixed except calling hook:Pass(p_Cache, p_DeltaTime) on Input:PreUpdate

**Comment by OrfeasZ** [comment]
@Raikem this seems to be an implementation issue with how this specific hook manages argument passing. Will be fixed soon.

**Comment by OrfeasZ** [comment]
The `Input:PreUpdate` hook issue has been fixed in build 12251. Usage example:

```lua
function OnInputPreUpdate(p_Hook, p_Cache, p_DeltaTime)
	print(p_Cache[InputConceptIdentifiers.ConceptMoveForward])
	p_Cache[InputConceptIdentifiers.ConceptMoveForward] = 0.0
	p_Hook:Pass(p_Cache, p_DeltaTime)
end
```
