### ISSUE TITLE
[Feature Request] Better Squadleader Management

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#249]
As a creator of client and server vEXT mods, i want to be able to easily distinguish between normal players and players asigned as squadleaders. As of now, theres no simple way of getting the information, whether a player is a squadleader or not. 

Therefore, as discussed on the meeting, we want an enhancement on the player object that can be retrieved through the PlayerManager. A simple readonly bool flag is sufficient.

=> player.IsSquadleader

This flag should be implemented on **both client and server** PlayerManager.

(Sidenote: You mentioned hooking the TeamSquadManager:SetSquadleader event internally and then setting the variables on the PlayerManager)

**Comment by OrfeasZ** [comment]
Build 12236 introduces the field `player.isSquadLeader`.

**Comment by FoolHen** [comment]
@OrfeasZ can you make it writable on server? I don't think there is a way to change SL right now.
