### ISSUE TITLE
[Feature Request] Ability to spawn any blueprint at linear transform

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#250]
As a creator of client and server vEXT mods, i want to be able to spawn any blueprint at a certain linear transform. 

Use cases:

- Spawning objects (buildings, objects, ...)
- Spawning vehicles

**Comment by OrfeasZ** [comment]
Build 12241 introduces the following methods:
- `EntityManager:CreateClientEntitiesFromBlueprint(blueprint, transform)`
- `EntityManager:CreateServerEntitiesFromBlueprint(blueprint, transform)`

Both these functions return an iterable list of entities.
