### ISSUE TITLE
[Urgent] Driver crash - GetDeviceRemovedReason

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#253]
After the latest update, I've been getting this crash message frequently, to the point where it's impossible to use VU.
http://powback.com/u/5a09be93c19f3.png

Happens if I open the console, launch the game or sign in, join game, spawn. Seems semi-random.

**Comment by 3ti65** [comment]
same crash here. happens after a couple of seconds ingame, everytime. only started happening after one of the recent updates. effectively cant work on VU anymore until this is fixed. :(

**Comment by 3ti65** [comment]
doesnt happen to foolhen. he's got an AMD card. nVidia related then. pls fix

**Comment by 3ti65** [comment]
fixed in 12277
