### ISSUE TITLE
Accessing video settings crashes the client

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#257]
OS: Microsoft Windows [Version 10.0.16299.125]
GPU: Nvidia GTX 1080
Processor: Intel i7 8700k @ 4.5GHz

Build: 12316
Map: Any
Mods: None
Crash dump: None

How to reproduce:
Press escape
Options
Video Settings
Crash

Not sure how long this has been happening, but I believe it was working July 16th, when I created a mod that affected some sliders inside the video settings.

Steps taken:
Reinstalled windows
Reset settings

**Comment by OrfeasZ** [comment]
@Powback have you tried deleting your save profile (`Documents/Battlefield 3/settings`)?

**Comment by Powback** [comment]
Yes, that's what I mean by reset settings,

**Comment by OrfeasZ** [comment]
@Powback does this also happen on the main branch or the vanilla game?

**Comment by Powback** [comment]
Happens on the main branch too.
Does not happen in the vanilla game.
Modifying the settings in vanilla and then accessing it in VU still replicates the crash.

**Comment by Powback** [comment]
Settings in case it should be relevant: http://powback.com/u/dfc432b6dde414ccc6f49d04fd5f7ec9.7z

**Comment by OrfeasZ** [comment]
This smells like a driver issue. Can you enable D3D10/11 debugging, attach a debugger to VU (ie. using Visual Studio) and capture the debug output? You can enable debugging from the DirectX Control Panel. You might have to download the DXSDK to get that.

![](http://i.nofate.me/eVlyfLVa.png)

![](http://i.nofate.me/XphH5KCQ.png)

**Comment by Powback** [comment]
Crashes with the exception "Exception thrown at 0x00495760 in vu.exe: 0xC0000005: Access violation reading location 0x00000014. occurred"

Not sure if I did it correctly.

**Comment by kiwidoggie** [comment]
I cannot reproduce on my end. Just to ensure we are talking about the same thing; you mean

![image](https://user-images.githubusercontent.com/9152262/34462776-f3f96210-edff-11e7-8aa8-fce2172b429e.png)
This screen?

**Comment by Powback** [comment]
That's correct. Happened before and after a complete windows wipe.

I'll check if the same happens after a reinstall when I have time.

**Comment by Powback** [comment]
Repairing BF3 through Origin solved the issue. Not sure why it persisted in VU and not vanilla.

**Comment by Powback** [comment]
The issue happened again.

I deleted all my settings and game files, then reinstalled.
The issue still persists.

**Comment by Powback** [comment]
For future reference: 

This happened because i mklink'd the BF3 install to a different directory. Installing it normally resolves the issue.

**Comment by Powback** [comment]
Seems like this issue was caused by enabling DSR
