### ISSUE TITLE
[Req] Allow fine-grained control over weapon recoil

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#258]
When you fire a weapon, the camera returns to the starting position. For PR we want to eliminate this: the camera should stay where the recoil puts you, so the weapon handling is more skill-based.
We tried setting RecoilAmplitudeDecreaseFactor to 0 in /Weapons/M16A4/M16A4_Gunsway.txt and although it works, the roll rotation isn't reset and the min and max pitch angle of the camera is changed, so eventually you can't look at your feet and you can look backwards above your head [like this](https://cdn.discordapp.com/attachments/319035622100566017/337194418396200960/Sin_titulo.png).

**Comment by 3ti65** [comment]
i'd change the title to 

"remove the silly recoil reset"

**Comment by 3ti65** [comment]
Hatti made a C++ dll that fixes this issue when injected.

We might need some additional vEXT features in order to get it running in lua exclusively.

Heres the C++ code:

https://pastebin.com/5myXqpdH

And here's the DLL that can be injected:

[BF3CustomRecoil.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1984372/BF3CustomRecoil.zip)

**Comment by OrfeasZ** [comment]
Build `14178` adds the following new classes:

**Shared**

`AimAssist`
- `AimAssist(AimAssist ref)`
- `DataContainer data`
- `Vec2 speed`
- `int lastZoomLevel`
- `float yaw`
- `float pitch`
- `float acceleration`
- `float accelerationTimer`
- `float attractZoomPostTimer`
- `float targetDistance`
- `float softZoneLambda`
- `float polynomialFactor`
- `bool useAimAssist`
- `bool useInputPolynomials`
- `bool hasChangedZoomed`
- `bool isSnapZoom`

`GunSwayDeviation`
- `GunSwayDeviation()`
- `GunSwayDeviation(GunSwayDeviation ref)`
- `float pitch`
- `float yaw`
- `float roll`
- `float transY`

`GunSway`
- `GunSway(GunSway ref)`
- `DataContainer data`
- `LinearTransform cameraRecoilTransform`
- `GunSwayDeviation currentRecoilDeviation`
- `GunSwayDeviation currentLagDeviation`
- `GunSwayDeviation currentDispersionDeviation`
- `float timeSinceLastShot`
- `float dispersionAngle`
- `float minDispersionAngle`
- `float crossHairDispersionFactor`
- `float currentGameplayDeviationScaleFactor`
- `float currentVisualDeviationScaleFactor`
- `float suppressionMinDispersionAngleFactor`
- `float randomAngle`
- `float randomRadius`
- `float jumpingTimer`
- `int seed`
- `int initialFireShot`
- `bool fireShot`
- `bool isFiring`
- `bool isJumping`
- `bool isMoving`

**Client**

`AimingSimulation`
- `AimingSimulation(AimingSimulation ref)`
- `AimAssist aimAssist`
- `DataContainer data`
- `float sway`
- `float yaw`
- `float pitch`
- `float aimYawTimer`
- `float aimPitchTimer`
- `float zoomTransitionTimer`
- `float fovMultiplier`
- `float fovTransitionTimer`
- `float fadeTimer`
- `float currentZoomTransitionTime`
- `float currentFovTransitionTime`
- `int zoomLevel`
- `int oldZoomLevel`
- `int switchToZoomLevel`

`SoldierWeapon`
- `SoldierWeapon(SoldierWeapon ref)`
- `DataContainer data`
- `GunSway correctedGunSway`
- `GunSway predictedGunSway`
- `AimingSimulation aimingSimulation`
- `string name`
- `int primaryAmmo`
- `int secondaryAmmo`
- `FireLogicType fireLogic`

The following fields and methods have been added to the client `SoldierWeaponsComponent` class:
- `int currentWeaponIndex`
- `int weaponCount`
- `SoldierWeapon GetWeapon(int index)`

The following methods have been **removed** from the client `SoldierEntity` class:
- `GetCurrentWeaponSlot()`
- `GetCurrentWeaponName`
- `GetCurrentPrimaryAmmo()`
- `GetCurrentSecondaryAmmo()`
- `GetCurrentWeaponFireLogic()`
- `GetWeaponCount()`
- `GetWeaponNameByIndex()`
- `GetWeaponPrimaryAmmoByIndex()`
- `GetWeaponSecondaryAmmoByIndex()`
- `GetWeaponFireLogicByIndex()`

It also adds the following events:
- `GunSway:Update(GunSway gunSway, float deltaTime)`
- `GunSway:UpdateRecoil(GunSway gunSway, float deltaTime)`

**Comment by Powback** [comment]
Accessing AimAssist crashes, unassumingly because it's not used in MP

**Comment by Powback** [comment]
GunSway:Update -> gunsway.isFiring will randomly turn true
https://ybin.me/p/042ae0abeedc67d5#UJBYqXBKq8PTw9DHekzWIDJpof6Y1pD8rT4Yr3Zkar0=

same goes for UpdateRecoil

gunsway.fireShot does not exist.

aimingSimulation doesn't seem to return the correct data.
```
sway: (0.000000, -0.000000)
yaw: -nan
pitch: -6.0490684220237e-21
aimYawTimer: 5.6441464222964e-23
aimPitchTimer: 0.0
zoomTransitionTimer: -2.3349032719577e+26
fovMultiplier: 0.0
fovTransitionTimer: 0.0
fadeTimer: 32.388889312744
currentZoomTransitionTime: -4.0298814749501e+23
currentFovTransitionTime: -8.0283827323878e+24
zoomLevel: 0
oldZoomLevel: 0
switchToZoomLevel: 0
```

pitch and yaw seems to be decreasing *very* rapidly

**Comment by Powback** [comment]
http://powback.com/u/1837aef5a16a28fd951269b439015e6b.7z

Seems fine otherwise.

**Comment by Powback** [comment]
weaponCount returns the same as currentWeaponIndex

**Comment by FoolHen** [comment]
Also, the removed methods are still there on server and the server ``SoldierEntity`` doesnt have the ``weaponsComponent`` field.

**Comment by OrfeasZ** [comment]
> Also, the removed methods are still there on server and the server `SoldierEntity` doesnt have the `weaponsComponent` field.

That's intended.

**Comment by OrfeasZ** [comment]
Build `14182` fixes all the issues mentioned above and also introduces the following additional fields to the `AimingSimulation` type:
- `bool zoomLevelLocked`
- `bool zoomDisabled`
- `bool trySwitchOnNextUpdate`
- `bool forceZoom`

**Comment by FoolHen** [comment]
AimAssist.pitch always returns 0, valve pls fix.

Edit: seems like most of its values are always 0 or false.
```lua
print(s_AimAssist.data)
print(s_AimAssist.speed)
print(s_AimAssist.lastZoomLevel)
print(s_AimAssist.yaw)
print(s_AimAssist.pitch)
print(s_AimAssist.acceleration)
print(s_AimAssist.accelerationTimer)
print(s_AimAssist.attractZoomPostTimer)
print(s_AimAssist.targetDistance)
print(s_AimAssist.softZoneLambda)
print(s_AimAssist.polynomialFactor)
print(s_AimAssist.useAimAssist)
print(s_AimAssist.useInputPolynomials)
print(s_AimAssist.hasChangedZoomed)
print(s_AimAssist.hasChangedZoomed)
```
outputs this:
https://i.imgur.com/XEiQIo0.png

**Comment by OrfeasZ** [comment]
Fixed in build `14184` which also removes the `polynomialFactor` field from the `AimAssist` type.
