### ISSUE TITLE
Issue with the player:SelectWeapon function

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#259]
Setting multiple weapons with the player:SelectWeapon function works fine basically, however there are some issues:

This works: (starting with WeaponSlot_0 and iterate up)

`player:SelectWeapon(WeaponSlot.WeaponSlot_0, pistol, { })
player:SelectWeapon(WeaponSlot.WeaponSlot_1, weapon, { weaponAtt0, weaponAtt1 })`

This only adds the pistol:

`player:SelectWeapon(WeaponSlot.WeaponSlot_1, weapon, { weaponAtt0, weaponAtt1 })
player:SelectWeapon(WeaponSlot.WeaponSlot_0, pistol, { })`

The order shouln't matter really imo, is that a VU bug?

Also, you cant have any 'gaps' in the weapon slot order:

`player:SelectWeapon(WeaponSlot.WeaponSlot_0, knife, { })
player:SelectWeapon(WeaponSlot.WeaponSlot_8, pistol, { })
player:SelectWeapon(WeaponSlot.WeaponSlot_9, weapon, { weaponAtt0, weaponAtt1 })`

This will only add the knife. It works if its the order 0, 1, 2 though

If possible, we want to be able to set specific slots without having to fill the slots in between, so we can have one specific item always on the same button.

**Comment by OrfeasZ** [comment]
This is expected behavior. Setting a weapon on slot 0 clears all other slots.
