### ISSUE TITLE
getting the unknown error

### ISSUE THREAD

**Issue by bigworld12** [VeniceUnleashed/VeniceUnleashed#26]
i am still getting the unknown error

**Comment by OrfeasZ** [comment]
@bigworld12 
What do you mean you're getting the 'unknown error'?
Where are you getting that error and what circumstances?

**Comment by bigworld12** [comment]
yesterday when i was logging in i was getting "unknown error"
now i am getting "you are not authorized to access this product"

**Comment by OrfeasZ** [comment]
@bigworld12 
The unknown error occurs sometimes when the backend is restarted.
As for the other error, it means you don't have a valid Closed Beta license tied to your account.
If you have gotten an invitation make sure to redeem your key at http://veniceunleashed.net/downloads
