### ISSUE TITLE
TeamSquadManager:GetSquadPlayerCount() crashes server

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#262]
Calling  TeamSquadManager:GetSquadPlayerCount( TeamID, SquadID) causes a crash. It was working fine before recent updates.

exception code: 0xC0000005
exception info: The thread tried to read from or write to a virtual address for which it does not have the appropriate access

Crash dump:
[778002a6-7136-41fe-ac8b-554135c6db9e.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1595148/778002a6-7136-41fe-ac8b-554135c6db9e.zip)

**Comment by OrfeasZ** [comment]
This should be fixed in build 12324.
