### ISSUE TITLE
[REQ] Soldier:GetCameraRotation, Soldier:GetCameraTransform

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#263]
We currently have SoldierEntity:GetCameraPosition. Getting the camera rotation and transform would be helpful as well.

**Comment by kiwidoggie** [comment]
`Player:GetCameraTransform()` has been added in build 12333

**Comment by Powback** [comment]
Crashes in build 12461

**Comment by kiwidoggie** [comment]
This has been moved to `ClientUtils:GetCameraTransform()` and world to screen has moved to `ClientUtils:WorldToScreen(Vec3)` in build 12466
