### ISSUE TITLE
[Req] Way to know if member of an instance is null

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#264]
Say we have:
```
AIEntryData 57826D97-5FE8-8F4A-8F47-0B226E73F6CF
    $::GameAIEntryData
        $::Asset
            $::DataContainer
            Name *nullString*
    EquipmentType *nullGuid*
    Armament *nullGuid*
    Mobility *nullGuid*
    StrengthType Infantry
    ReuseTime 0.0
    Forbidden True
    HasExposedSoldier False
    InterludeOnly False
    InvalidForAI False
```

As `EquipmentType`  is null, accesing it crashes the server.

```lua
if instanceGuid == Guid("57826D97-5FE8-8F4A-8F47-0B226E73F6CF", "D") then
  local s_Instance = AIEntryData(instance)
  local eq = AIVehicleBehaviourData(s_Instance.equipmentType)
end
```

AFAIK there is no way to tell if `EquipmentType` is null. A way to know if it is would be useful as automated iterations through instance members causes crashes. I'm trying to copy an instance automatically and this crash makes it impossible.

**Comment by kiwidoggie** [comment]
`if s_Instance.equipmentType == nil then end`

**Comment by FoolHen** [comment]
@kiwidoggie Its not nil tho, that's why I posted this issue. 
If you do ``print(s_Instance.equipmentType)`` the server closes. If you do ``print(tostring(s_Instance.equipmentType))
`` the output is ``sol.sol::detail::unique_usertype<VeniceEXT::Classes::Shared::AIVehicleBehaviourData>: 0E169580``.
Also if you do ``print(eq.name)`` it closes too.

**Comment by OrfeasZ** [comment]
Fixed in build 12337.
