### ISSUE TITLE
[REQ] ScreenToWorld

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#266]
SharedUtils:ScreenToWorld(Vec3( MousePos.X, MousePos.Y, Camera.NearClipplingPlane) // Returns Vec3.

Combining this with RayCast can give us some interesting usage.

**Comment by OrfeasZ** [comment]
Build `14854` adds `Vec3 ClientUtils:ScreenToWorld(Vec3 mousePos)`. If it doesn't work bug @kiwidoggie.

**Comment by FoolHen** [comment]
@kiwidoggie doesnt work https://i.imgur.com/cdFmNEq.png

**Comment by OrfeasZ** [comment]
Fixed in build `15821`.
