### ISSUE TITLE
[REQ] Implement a Rotation Property on LinearTransform

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#267]
In a lot of cases, we're gonna need the rotation of some object. To simplify things and to keep all the modders from having to implement their own rotation calculation, we'd like to have a property on the LinearTransform class, which allows one to read out the current rotation as an euler angles.

As an example you could get a soldiers rotation by using:

player.soldier.transform.rotation

Suggested type: Vec3. Suggested X,Y,Z value range either -180 - 180 or 0 - 360.

**Comment by FoolHen** [comment]
https://github.com/Raikem/RotationHelper 
I created a class to do this in the meantime, but would be better to have it natively. Reference links to the math I used are inside the file if you need them

**Comment by kiwidoggie** [comment]
Added in build 12952
