### ISSUE TITLE
[Crash] Crash with corrupted banlist.txt

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#268]
VU Server crashes on start up. Crash dump here:

[b0e1cdee-c6d5-49e8-9e7e-c1c44bd5aec7.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1623645/b0e1cdee-c6d5-49e8-9e7e-c1c44bd5aec7.zip)

Server Console Log:

https://media.discordapp.net/attachments/400284286625906698/400813421802815488/2018-01-11_01_49_49-Battlefield_3TM_Server.png

EDIT: This is caused by writing stupid stuff into the banlist.txt.

For example just writing 'Powback' in it, will cause this crash. It would be easier for the server owners (and us therefor) to get a message like 'banlist corrupted'.

**Comment by kiwidoggie** [comment]
This has been fixed in build 12332
