### ISSUE TITLE
[Crash] Different crashes when spawning buildings with vEXT

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#269]
When spawning objects with vEXT, there's a felt 30% chance that it will crash.

-snip-

**Comment by Powback** [comment]
Models disappearing is caused be garbage collection.
Adding the spawned objects into a member table solves the disappearing issue.

**Comment by 3ti65** [comment]
EDIT:

Some of the crashes were related to wrong serialization of frostbite types sent over netevents.
Some crashes were probably related to the garbage collector thing if the entity is not saved as member variable or in a table.

However there's still a crash when spawning some objects which crashes both client and server. Here's the testmod replicating the issue:

[ObjectSpawnTest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1649323/ObjectSpawnTest.zip)

Steps to reproduce:

1. Start up map:
XP3_Shield ConquestLarge0 2

2. Spawn in and type in chat:
'spawn1' -> spawns building, no crash
'spawn2' -> spawns building, no crash
'spawn3' -> spawns building, crashes client and server with crashdump
'spawn4' -> spawns building, crashes client and server with crashdump

**Comment by OrfeasZ** [comment]
All of these have been fixed in build 12354. The reason spawn3 causes a crash is because it only needs to be spawned on the server as a networked entity:

```lua
EntityManager:CreateServerEntitiesFromBlueprint(blueprint, transform, true)
```

Notice the `true` parameter.
