### ISSUE TITLE
[Bug] Frostbite primitives (Guid, Vec3, etc) passed through netevents are not being serialized properly

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#271]
Same as the Vec3 recently, Guids are not properly working for some reason.

**Comment by 3ti65** [comment]
LinearTransforms also dont get serialized properly, and Vec3 still does not work. There was a seperate bug for Vec3s, it's currently closed but should be reopened. Imma link it.

**Comment by OrfeasZ** [comment]
I won't be re-opening the other issue. I've renamed this to make it more generic.

**Comment by 3ti65** [comment]
Alright makes more sense. 

Strings seem to work perfectly though.

**Comment by OrfeasZ** [comment]
Strings are just strings, not a Frostbite type.

**Comment by 3ti65** [comment]
[NetEventsParamsTest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1649588/NetEventsParamsTest.zip)

Above is a Unit Test Mod for testing the sending of the following types over NetEvents (Both Client -> Server and Server -> Client):

- Guid
- Vec2
- Vec3
- Vec4
- LinearTransform

How to:

Type in chat 'clientserver' for Client -> Server.
Type in chat 'serverclient' for Server -> Client.

Check the receivings end output for success / failure messages.

Sending a table with those types will crash the receiving side before even getting into the Handler-function. To test those after fixing that, simply uncomment the according code blocks.

**Comment by OrfeasZ** [comment]
Fixed in build 12376.
