### ISSUE TITLE
Spawned vehicles crash the server on map change

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#276]
After a vehicle is spawned, the server crashes if a new map is loaded.
Restarting or ending the round is ok as long as the map doesn't change.

To reproduce: 
Build: 12402
1. Server configured to load Grand Bazzar (MP_001) with the mod on startup
2. Spawn and type "vehicle lav" in the chat, this spawns a `Vehicles/LAV25/LAV25` (on this map)
3. Change the map to Operation Firestorm (MP_012) using Procon
Server loads the blueprints of the new map and crashes, crashdump is attatched.

Crashdump: https://i.xulunix.de/i/fOfvj9xz.dmp
Used mod: https://i.xulunix.de/i/2opPvN5P.rar

**Comment by OrfeasZ** [comment]
Fixed in build 12442.
