### ISSUE TITLE
Reloading mods from ingame rcon causes the server to crash.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#277]
Testmod: http://powback.com/u/67c833bc4373c42a245f91954c63826f.7z
Crashdump: http://powback.com/u/7b6a0a5b2841bacb6c6e96fea20ba59a.dmp

To reproduce type "reload" into chat.

**Comment by kiwidoggie** [comment]
Does reloading the mod work from standard RCON?

**Comment by 3ti65** [comment]
@Powback ^

**Comment by Powback** [comment]
Yes, reloading from rcon works.

Maybe the crash is caused because the mod is unloaded while still performing an operation? If so, this might also be the cause of other crashes.

**Comment by OrfeasZ** [comment]
Starting with build 13225, `modList` commands have been disabled when attempting to use them from within a mod for security reasons (ie. malicious mods disabling/enabling other mods). In the future I might consider adding a flag to allow specific mods to call modList commands if the need arises.
