### ISSUE TITLE
Console uses modlist.txt name instead of the name inside mod.json

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#278]
This causes the case to be incorrect depending on what you write inside modlist.txt.

Example:
```
Modlist:
ingamercon
```
```
Console:
[VeniceEXT] [ingamercon] Initializing IngameRconServer
```

```
Mod.json:
"Name": "IngameRcon",
```

This also applies to mods that were loaded through rcon.

**Comment by Powback** [comment]
In addition to that, it seems like the rcon interface is case-sensitive to the mod names.
```
vu.modlist.add SomeMod
-- SomeMod added
vu.modlist.remove somemod
-- somemod not found
```

**Comment by OrfeasZ** [comment]
I believe this has been fixed.
