### ISSUE TITLE
 Venice Unleashed -> BF3 Folder configuration

### ISSUE THREAD

**Issue by calvin69777** [VeniceUnleashed/VeniceUnleashed#28]
hello everybody,

i have a problem, after the BF3 installation the BF3 directory is called "Battlefield 3™", but BF3 will not start because Windows can't handle the (TM).

If I remove the (TM) -> "Battlefield 3" the game will start properly.

But now I can't start BF3 by Venice Unleashed, because it will not find the BF3 installation.
Is there a way to configurige  Venice Unleashed to the "Battlefield 3"  folder ?
Thanks for help.

---

I use:
Windows 7  Ultimate 64-Bit

**Comment by OrfeasZ** [comment]
The Venice Unleashed launcher currently reads the Battlefield 3 directory from the registry, which means that you can't manually override it.
However, you should be able to fix the directory yourself in the registry.

To do so, open regedit by typing 'regedit' in your start menu and hitting enter, navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\EA Games\Battlefield 3, and change the values of 'Install Dir' and 'GDFBinary' to reflect your actual installation directory.

After doing that, the launcher should function normally.

**Comment by calvin69777** [comment]
Thank you very much for your help :)

now Venice Unleashed find my BF3 installation,
but I get an other error when Venice Unleashed try to start the louncher, "Failed to start Battlefield 3 process. Do you have the required permissions?".

These permissions are set:
![unbenannt](https://cloud.githubusercontent.com/assets/10158541/5401954/8302ce64-8180-11e4-90ef-e98701f75f8f.JPG)

I'am able to start the BF3.exe manually without confirm the admin message.

**Comment by OrfeasZ** [comment]
Try running Venice Unleashed as an administrator and make sure you're running the latest patch of the game and that your bf3.exe is not modified.

**Comment by calvin69777** [comment]
the bf3.exe is a cracked one that allows me to play without origin, but if Venice Unleashe only work with the original version of BF3 I will buy soon.

**Comment by OrfeasZ** [comment]
We do not support cracked or otherwise modified versions of the game.
Venice Unleashed only works with licensed vanilla builds of the game.
