### ISSUE TITLE
[REQ] Dependencies in [mod].json

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#284]
Some mods requires other mods to work.
Instead of having to manually enter all the mods into modlist.txt, there should be a possibility of loading the mods listed in the dependencies section of [mod].json

Example:
```
{
	"Name": "SomeMod",
	"Authors": ["SomeGuy"],
	"Description": "DoesSomething",
	"Dependencies":["Mod1","Mod2"],
	"URL": "none",
	"Version": 0,
	"HasWebUI": false,
	"HasVeniceEXT": true
}
```
In addition to that, VEXT should check if said mod exists, and if it doesn't it should print a message saying that [mod] tried to load [OtherMod] which doesn't exist.
(This also applies to mods in modlist.txt)

If the mod is listed multiple times, it should obviously only be loaded once. 

Mods that could be used as dependencies:

- VEManager
- BundleManager (Which loads bundles and adds the entries to the correct registry)
- ObjectManager (Which handles object spawning and client synchronization)
- AudioManager
- MessageManager
- _SomeModThatsNotAManager_

This will also act as a replacement for my original "Global Mods" idea, referenced at #230 , albeit with a different purpose.

**Comment by 3ti65** [comment]
Please make the dependencies an array of objects that contain both name and version of the mod thats being depended upon.

**Comment by OrfeasZ** [comment]
Build `13489` adds support for declaring mod dependencies and enforces [semver](https://semver.org/) for all mod versions. Any mods that are unable to meet their dependency requirements will fail to load. Any circular dependencies will prevent all mods from loading. 

Dependencies are declared in the `mod.json` file as follows:

```js
{
	"Name": "My Great Mod",
	"Version": "1.0.0",
	"Dependencies": {
		"mod1": "1.1.0", // Requires exactly version 1.1.0.
		"mod2": ">2.0.0", // Requires a version later than 2.0.0.
		"mod3": "~1.2.3", // Requires a version with the same major and minor components, and with an equal or greater patch component (>= 1.2.3, < 1.3.0).
		"mod4": "^1.2.3", // Requires a version with the same major component, and with an equal or greater minor or patch component (>= 1.2.3, < 2.0.0)
	},
	...
}
```

The following operands are supported: `=`, `>`, `<`, `>=`, `<=`, `^`, `~`. Specifying no operand is the equivalent of specifying `=`. The provided dependency key should match the folder where the mod is installed in.
