### ISSUE TITLE
[REQ] Client:LevelLoaded & Client:LevelLoading events

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#286]
Right now we have Server:LevelLoaded (map, gamemode, round). A client alternative would be useful to get map info without using netevents.
Edit: As 3ti said we also need Client:LevelLoading or StartedLoading with the same params

**Comment by OrfeasZ** [comment]
Build 12879 adds `Client:LevelLoaded` and `Client:LevelFinalized`. Untested.

**Comment by FoolHen** [comment]
``Client:LevelLoaded `` doesn't have map info arguments (map, gamemode, round) as the server one has, would be pretty useful to have them.

**Comment by 3ti65** [comment]
Reopen and add the arguments, else this event is useless

**Comment by 3ti65** [comment]
While youre at it, please also implement a Client:LevelLoading event with the same parameters. Cheers <3

**Comment by FoolHen** [comment]
Second parameter of Client:LevelLoaded (gamemode) is userdata instead of a string

Not only that, but the other params aren't the same as Server:LevelLoaded.

Server: 
![vu_2018-07-06_20-17-56](https://user-images.githubusercontent.com/7466799/42394280-dd86879a-8159-11e8-86d1-b8e4d82c856a.png)
Client:
![cmd_2018-07-06_20-17-33](https://user-images.githubusercontent.com/7466799/42394283-e251cf96-8159-11e8-967a-3773b5225504.png)
(Note that the second param in client is casted to a string to be able to print it)

**Comment by OrfeasZ** [comment]
Build `13312` introduces the following changes to events:
- `Client:LevelLoaded`(`levelName, gamemode`)
- `Client:LevelFinalized`(`levelName, gamemode`)
- `Level:LoadResources`(`levelName, gamemode`, `dedicatedServer`)

**Comment by OrfeasZ** [comment]
The `Level:LoadResources` event gets called right before the level starts loading.
