### ISSUE TITLE
[REQ] Squad related requests

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#288]
- We need a way to set a player as the squadleader on server (highest prio of all)
- PlayerManager:GetSquadPlayers( teamID, squadID ), as to get all players in a squad right now we have to loop through all the players and add them to a table
- A way to get( client and server) and set the locked status of a squad (low prio, we did our own system)

**Comment by OrfeasZ** [comment]
1 and 3 have been implemented in build 12879 and exposed in the following way (weird I know, but it's how frostbite works):

The server-side player class now exposes the following additional methods and properties:

* bool **isSquadPrivate** - Whether the squad the player is currently in is private or not. Might only be accurate when read from squad leaders (needs testing).
* **SetSquadLeader**(bool leader, bool squadPrivate) - Used to set/remove the leader of a squad along with the ability to mark a squad as private. For marking as private, you may have to call this on the squad leader player.

As for getting all players in a squad, if I were to expose it I would also be looping through all players to find them, so for now I've elected not to.
