### ISSUE TITLE
Console button not functioning properly in menu using Swedish kayboard layout

### ISSUE THREAD

**Issue by Timse93** [VeniceUnleashed/VeniceUnleashed#29]
The console is normally supposed to be opened using the tilde button (The one under escape and next to 1). On the Swedish keyboard layout however, tilde is in a completely different place.
The game itself handles the the Swedish keyboard layout perfectly and allows one to use the same button, even though it's a different layout.
The custom coded menu does not compensate for it and for some reason opens the menu using the Ö button. (Under the P button)
Ö however is not on the same button as tilde on the Swedish keyboard layout.

**Comment by derrod** [comment]
Can also confirm it when using a german layout.

**Comment by OrfeasZ** [comment]
This has been resolved in build 8764.
