### ISSUE TITLE
Entities don't spawn

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#290]
Entities don't spawn anymore with the new update

**Comment by OrfeasZ** [comment]
Please provide a sample mod.

**Comment by FoolHen** [comment]
[EntiyDebug.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1807978/EntiyDebug.zip)

**Comment by FoolHen** [comment]
Simplified test mod, works with MP_017 ConquestLarge0 2. F1 should spawn a wall at your position
[entitytest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1836894/entitytest.zip)

**Comment by OrfeasZ** [comment]
Fixed in build 12868.
