### ISSUE TITLE
[Req] Extended partition support

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#291]
With the new update, we're going to have to rely a whole lot more on partitions.

Therefore it would be nice to have some more possibilities when it comes to partition management.
Keep in mind that I don't fully understand the new system yet, so some of these might be useless or already exist.

Instance.partitionGuid / Instance:GetPartitionGuid// GUID
Instance.partition / Instance:GetPartition() // Instance
GetPartition(guid) // Partition
Partition.guid // GUID
? Partition:Clone(guid) // Partition
Partition.name // string
Partition.primaryInstance // Instance

**Comment by OrfeasZ** [comment]
The following exist or have been added in build 12669:

For `DatabasePartition` see [https://modders.link/wiki/doku.php?id=vext:ref:vu:cls:shr:databasepartition](https://modders.link/wiki/doku.php?id=vext:ref:vu:cls:shr:databasepartition).

`ResourceManager` now has an additional function:  

```lua
local partition = ResourceManager:FindDatabasePartition(partitionGuid)
```

Where `partitionGuid` is a `Guid` object. This function returns a `DatabasePartition` or `nil` if not found.
