### ISSUE TITLE
[Req] Event for runtime errors

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#292]
Would be good to have an event for lua runtime errors, so we can process that information outside the console. Needs to be on both the server and the client:

Client:RuntimeError(p_ErrorMessage)
Server:RuntimeError(p_ErrorMessage)

**Comment by Powback** [comment]
Isn't try/catch already implemented in standard Lua?

**Comment by 3ti65** [comment]
I dont think so

**Comment by 3ti65** [comment]
updated description

**Comment by OrfeasZ** [comment]
Errors can break VeniceEXT execution and can therefore not be reliably passed down to scripts.

**Comment by 3ti65** [comment]
Please reopen as discussed in discord.

We need something like a global error handler, which lets us know if an error occured on either client or server, without exposing too much information about the client environment.

**Comment by 3ti65** [comment]
Reopen pls

**Comment by kiwidoggie** [comment]
This is just being reopened to verify that client lua errors in release builds get logged to the debug console when debug mode is enabled. If this is the case, will be re-closing the issue.
