### ISSUE TITLE
[Req] Add return of lua type names for all vEXT types

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#293]
As discussed, add the return of lua type names for all vEXT types.

e.g.:

type(Guid('B2FF66A5-494A-B9C4-429E-2E94E03B9CA3', 'D'))

returns 'userdata'

-> should return 'Guid'

**Comment by OrfeasZ** [comment]
Currently not possible due to restrictions with how lua works.
