### ISSUE TITLE
[Req] Throw error for readonly instances that are being modified

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#294]
As the title says, please throw an error if someone tries to modify readonly datacontainers, since it will save a lot of trouble on why stuff doesnt work.

**Comment by 3ti65** [comment]
Might make sense to label this under Release 1.0 as well, since that will save us from a lot of 'why does my shit not work' posts from people that forget to clone stuff. 

Just a thought.

**Comment by OrfeasZ** [comment]
Errors have been added when trying to modify read-only arrays. Errors for read-only datacontainers will be added soon.

**Comment by OrfeasZ** [comment]
Errors for modifying fields of read-only containers have been added and will be deployed soon. Keep in mind that these errors will just be printed in the console and will not break script execution. The actual modification operation is still a no-op for read-only containers.
