### ISSUE TITLE
[Req] Make "D" the default Guid formatting

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#296]
Using the normal dashed guids was widely agreed upon to be the way to go.
So, instead of this:

Guid("57826D97-5FE8-8F4A-8F47-0B226E73F6CF", "D")

one should also be able to write:

Guid("57826D97-5FE8-8F4A-8F47-0B226E73F6CF")

**Comment by OrfeasZ** [comment]
Implemented in build 12879.
