### ISSUE TITLE
[Req] Expose unique server identifier or/and other id info to LUA 

### ISSUE THREAD

**Issue by snaiperskaya96** [VeniceUnleashed/VeniceUnleashed#298]
We need something that allows us to identify a server. This might be as simple as an UUID as NoFate suggested (iirc) or more detailed info about the server like host address + port (this will be unique per server if i'm not wrong).
In any case we need the server owner to be aware of his server's UID so there must be a way (a command perhaps) that will help him to retrieve it.

It would be *neat™* to have those info available directly on the client side without querying the server side.
Cheers

**Comment by OrfeasZ** [comment]
Every server has a UUID (you can see it in the server window when starting up). I'll be exposing that to the server-side initially. I'll have to think about client-side.

**Comment by 3ti65** [comment]
RCON:GetServerGuid() was implemented by @kiwidoggie 
but it returns a string. should be Guid according to NF on discord.

**Comment by kiwidoggie** [comment]
This has been corrected.
