### ISSUE TITLE
[REQ] EntityEvents - Automatic hashing

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#302]
EntityEvents should also accept strings, which are then hashed and passed to the engine.

Example:
FireEvent("Destroy")
FireEvent(EntityEvent("Destroy"))

Equivalent to:
FireEvent(123456789) // Destroy
FireEvent(EntityEvent(123456789)) // Destroy

**Comment by OrfeasZ** [comment]
Implemented in build 12883.
