### ISSUE TITLE
Server / Client logs are placed in the wrong directory

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#305]
Client should be placed in `Documents/Battlefield3/Logs`
Server should be placed in `Doucments/Battlefield 3/Server/Logs`

They are currently placed in the Battlefield 3 directory.

**Comment by Powback** [comment]
As previously discussed, the log files should instead be placed inside a "logs" directory in the BF3 root directory, since the profile path isn't loaded until logging has already started.

**Comment by Powback** [comment]
I'd still like logs to be placed somewhere else than the BF3 install directory.

**Comment by OrfeasZ** [comment]
Next build (`14455+`) makes the following changes to where log files are stored:

On servers, the logs will now be written in either a `logs` folder under the specified server instance path (using `-serverInstancePath`) or in `%UserProfile%\Documents\Battlefield 3\Server\logs` by default.

On clients, (when using the `-debug` startup flag) the logs will be written in either `%LocalAppData%\VeniceUnleashed\logs` or if for some reason there is no access to that to `<current-dir>\vu\logs`.

**Comment by Powback** [comment]
Logs are written to the server directory directly, prefixed with logs.
http://powback.com/u/fba3ae88b2d4eb11b282d865015e732b.png

**Comment by OrfeasZ** [comment]
Fixed in build `14483`.
