### ISSUE TITLE
.typeName returns nil on some instances

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#306]
.typeInfo.name works as it should tho.

Example:
[typenamebug.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1968844/typenamebug.zip)

**Comment by FoolHen** [comment]
Seems like ``.isReadOnly`` and ``.isLazyLoading`` are also nil, and this happens in the children of FiringFunctionData (FireLogicData, ammoconfig and shotconfigdata) with all weapons, so maybe it's because they are lazy loaded?

![captura](https://user-images.githubusercontent.com/7466799/39579973-5040a49a-4ee8-11e8-9158-076a27602c90.PNG)

**Comment by 3ti65** [comment]
this is probably related to the lazy loading stuff not being implemented properly yet

**Comment by OrfeasZ** [comment]
`FireLogicData` and `AmmoConfigData` types are structures, not DataContainers. They therefore don't carry any of the regular fields DataContainers do (like `typeName`, `isLazyLoading`, etc.). To prevent any further confusion, I will be removing the `typeName` field from DataContainers, leaving `.typeInfo` as the single source of truth.

**Comment by Powback** [comment]
Before you finalize on that decision, please note that typeInfo.name does not return the same as .typeName if the instance hasn't been casted yet.
```
Mismatch: ActionNode - DataContainer
Mismatch: AdsrNodeData - DataContainer
Mismatch: AdvancedDogTagData - DataContainer
Mismatch: AeroDynamicPhysicsData - DataContainer
Mismatch: AIAimingConstraintsData - DataContainer
Mismatch: AIDifficultyData - DataContainer
Mismatch: AIEntryData - DataContainer
Mismatch: AimingConstraintEntityCommonData - DataContainer
Mismatch: AimingConstraintEntityData - DataContainer
Mismatch: AirRadarData - DataContainer
Mismatch: AirResistanceData - DataContainer
Mismatch: AIVehicleBehaviourData - DataContainer
Mismatch: AIVehicleTypes - DataContainer
Mismatch: AIWeaponData - DataContainer
Mismatch: AlignmentData - DataContainer
Mismatch: AlternateCameraViewData - DataContainer
Mismatch: AlternateSpawnEntityData - DataContainer
Mismatch: AndEntityData - DataContainer
Mismatch: AnimatedDriverEntityData - DataContainer
Mismatch: AnimatedSkeletonDatabase - DataContainer
Mismatch: AnimationControlledStateData - DataContainer
Mismatch: AnimationSignalEntityData - DataContainer
Mismatch: AnimationTurretRotationComponentData - DataContainer
Mismatch: AntAnimatableComponentData - DataContainer
Mismatch: AntAnimationSetAsset - DataContainer
Mismatch: AntEnumeration - DataContainer
Mismatch: AntEventEntityData - DataContainer
Mismatch: AntiRollBar - DataContainer
Mismatch: AntPackageAsset - DataContainer
Mismatch: AntProjectAsset - DataContainer
Mismatch: AreaProximityEntityData - DataContainer
Mismatch: ArmamentData - DataContainer
Mismatch: ArtilleryStrikeWeaponData - DataContainer
Mismatch: AudioGraphAssetParameter - DataContainer
etc...
``` 


```
function typeinfoCheckShared:OnPartitionLoaded(p_Partition)
	if p_Partition == nil then
		return
	end
	
	local s_Instances = p_Partition.instances


	for _, l_Instance in ipairs(s_Instances) do
		if l_Instance == nil then
			print('Instance is null?')
			break
		end
		if(l_Instance.typeName ~= l_Instance.typeInfo.name) then
			if(self.m_MisMatch[l_Instance.typeName] == nil) then
				print("Mismatch: " .. l_Instance.typeName .. " - " ..  l_Instance.typeInfo.name)
				self.m_MisMatch[l_Instance.typeName] = true
			end
		end
	end
end
```

Testmod: http://powback.com/u/39da6a92a306539628776cf4f2f81a06.7z

**Comment by OrfeasZ** [comment]
I'm well aware. This will no longer be the case.

**Comment by Powback** [comment]
That's fine. I would still like the ability to know whether the instance has been casted or not though. If you can find a solution for that, it would be greatly appreciated.
