### ISSUE TITLE
[REQ] Autoconnect to localhost server / specified server guid

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#309]
I would like a launch flag that auto-connects me to a server automatically at start, assuming auto-login is enabled.

This would make crashes etc more tolerable when developing mods.

**Comment by OrfeasZ** [comment]
Added in build `16229`. You can now instruct VU to join a server by launching it via `vu://join/serverguid`. This can also be passed as a launch argument.
