### ISSUE TITLE
Server crashes when capturing a point in second round

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#31]
I noticed a bug that causes the server to crash.

How to reproduce:
1. Load a map (I tested this on XP5_003 and MP_Subway)
2. Get into the capture zone of a flag, it doesn't matter whether it is completely captured or not, it just needs to be triggered
3. Restart round or skip to next round if the map has two or more (via Rcon)
4. Enter capturing zone of a flag
5. Server will crash

**Comment by OrfeasZ** [comment]
Fixed in build 6975.
