### ISSUE TITLE
[Req] Support triggering property changes on entities

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#311]
Similar to how entities have :FireEvent(event), they should also have something like :FireField(field, value).

Example:
![image](https://user-images.githubusercontent.com/970246/39816521-d0d7f312-539b-11e8-867c-2be3567a3a8f.png)

In this case, we should be able to do something like

```
ReferenceObjectEntity:FireField('Visible', true)
```

Reference:
https://github.com/Powback/Venice-EBX/blob/master/Events/Generic/HawkLauncher/Hawk_Mis_01.txt#L80

I'll come back and update the issue with how it works exactly at a later time.

**Comment by Powback** [comment]
Looks like we're after "PropertyChanged", as demonstrated here: 

http://powback.com/u/735652a2099666ea82e1dcff4ef9bc5c.png
And in fb::LogicVisualEnvironmentEntity::propertyChanged
or fb::ServerStaticModelEntity::propertyChanged

**Comment by OrfeasZ** [comment]
You want to trigger property changes or do you want to listen for them? I've already been working on supporting the former. The latter is a bit more complicated.

**Comment by Powback** [comment]
Triggering it would be enough for my needs.

**Comment by txt231** [comment]
You need to have a proper FireEvent which supports events like fb::ServerPlayerEvent, fb::ClientPlayerEvent, and possibly more.

An example of an event that needs fb::ServerPlayerEvent is fb::ServerInputRestrictionEntity which might be useful in some vext mods.

**Comment by OrfeasZ** [comment]
@txt231 you can open a separate issue for that request.

**Comment by OrfeasZ** [comment]
Build `13443` adds a `PropertyChanged(...)` method to trigger property changes on entities. It can be called as follows:

```lua
ent:PropertyChanged(1234) -- FNV hash of the event name
ent:PropertyChanged(1234, value) -- see below for details on values
ent:PropertyChanged("SomeProperty")
ent:PropertyChanged("SomeProperty", value)
```

Currently, only some properties support setting a value of a specific type. Most property listeners that I looked at seem to only do internal changes and not read any values. See the table below for reference.

| Property Name  | Value Type |
| ------------- | ------------- |
| Transform | LinearTransform |
| ControllableTransform | LinearTransform |
| TransformIn | LinearTransform |
| Enabled | bool |
| Visible | bool |
| BoolValue | bool |
| BoolIn | bool |
| IntValue | integer |
| IntIn | integer |
| FloatValue | float |
| FloatIn | float |
| Vec3In | Vec3 |
| Vec4In | Vec4 |
| Team | TeamId |
