### ISSUE TITLE
Modifying VehicleSpawnReferenceObjectData after cloning it doesn't always work

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#312]
This mod is to block vehicles from spawning, and it was working before cloning was a thing. It seems like the viper helicopter is affected by this changes, but most of the vehicles aren't.
[testmod.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1997697/testmod.zip)

**Comment by OrfeasZ** [comment]
Cannot reproduce this with latest build.

**Comment by FoolHen** [comment]
@OrfeasZ you never were able to reproduce it, for me only the helicopters don't spawn. The bmps and the cars do spawn

![image](https://user-images.githubusercontent.com/7466799/40575123-fa2317d8-60de-11e8-818c-16c386265371.png)

Can you reopen it? Seems like i can't
