### ISSUE TITLE
Spawning some objects causes crashes

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#313]
Some close the client, examples (type these in chat):
- ``object rock``
- ``object housevilla_01_breakable``
- ``object supplycase``

[xulumod.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1998595/xulumod.zip)

**Comment by Powback** [comment]
Level is xp3_shield
Alternatively try mp_011, and 
```Debrispile_02_a_destruction
Debrispile_02_B
AdvertPillar_02
```

Ref:
Works:
https://raw.githubusercontent.com/Powback/Venice-EBX/071473993867cd2297dc662517c61edaff51e8fe/Props/Vehicles/CivilianCar_01/CivilianCar_01.txt

Doesn't work:
https://raw.githubusercontent.com/Powback/Venice-EBX/071473993867cd2297dc662517c61edaff51e8fe/Objects/DebrisPile_02/DebrisPile_02_B.txt

It is presumably because of the MeshVariationDatabase, since DebrisPile_02_B works in mp_001, where the MeshVariationDatabase contains "Variation 0" of the objects, unlike mp_011 where it contains variation 854547893.


Additionally, we're unable to modify the MeshVariationDatabase itself. 
This can be tested using:
```
if l_Instance.typeInfo.name == "MeshVariationDatabase" then
	local s_MVD = MeshVariationDatabase(l_Instance:Clone(l_Instance.instanceGuid))
	p_Partition:ReplaceInstance(l_Instance, s_MVD, true)
	s_MVD.redirectEntries:clear()
	s_MVD.entries:clear()
	print("cleared MVD: " .. tostring(l_Instance.instanceGuid))
end
```

Expected behavior:
Crash / no variation

Result:
Nothing

I would also like to add that I've tried numerous solutions to modifying the MeshVariationDatbase instance without success, and would therefore state that shit's fucked, man.

MP_011 MVDE:
```
MeshVariationDatabaseEntry 18443874-A927-8134-37B9-2C754507541E
    $::DataContainer
    Mesh objects/debrispile_02/debrispile_02_b_mesh/4749052E-D434-742A-6F81-CFF8CF289D64
    VariationAssetNameHash 854547893
    Materials::array
        member::MeshVariationDatabaseMaterial
            Material objects/debrispile_02/debrispile_02_b_mesh/9772A450-A756-8E74-90C4-FAF053191489
            MaterialVariation objects/debrispile_02/debrispile_02_b_french/4FDA29E8-DA89-40AD-8A38-79FE52E0DCC4
            TextureParameters *nullArray*
        member::MeshVariationDatabaseMaterial
            Material objects/debrispile_02/debrispile_02_b_mesh/3233CC49-EB67-4E3A-8A79-13B421A04E28
            MaterialVariation *nullGuid*
            TextureParameters *nullArray*
```

MP_001 MVDE:
```
MeshVariationDatabaseEntry 74406F1E-B431-5869-A00C-BD41702A0511
    $::DataContainer
    Mesh objects/debrispile_02/debrispile_02_b_destructable_mesh/80FE3B20-CEE5-8DCD-D758-717945E62546
    VariationAssetNameHash 0
    Materials::array
        member::MeshVariationDatabaseMaterial
            Material objects/debrispile_02/debrispile_02_b_destructable_mesh/487FA078-9A0E-8F29-D079-4BD08921306A
            MaterialVariation *nullGuid*
            TextureParameters *nullArray*
        member::MeshVariationDatabaseMaterial
            Material objects/debrispile_02/debrispile_02_b_destructable_mesh/3EA5F9D5-580E-4524-9EAD-1C812C52B140
            MaterialVariation *nullGuid*
            TextureParameters *nullArray*
```

**Comment by OrfeasZ** [comment]
Build 12942 makes some changes to the `EntityManager` interfaces. More specifically, the following methods are now available for creating entities:

```
EntityManager:CreateClientEntity(data, transform)
EntityManager:CreateClientEntity(data, params)
EntityManager:CreateServerEntity(data, transform)
EntityManager:CreateServerEntity(data, params)
EntityManager:CreateClientEntitiesFromBlueprint(blueprint, transform)
EntityManager:CreateClientEntitiesFromBlueprint(blueprint, params)
EntityManager:CreateServerEntitiesFromBlueprint(blueprint, transform)
EntityManager:CreateServerEntitiesFromBlueprint(blueprint, params)
```

Where `data` is any instance of `GameObjectData`, `transform` is a `LinearTransform`, `blueprint` is any instance of `Blueprint`, and `params` is a newly introduced type: `EntityCreationParams`.

`EntityCreationParams` currently has the following fields:

- `LinearTransform` `transform`
- `number` `variationNameHash`
- `bool` `networked`

Usage example:
```lua
local params = EntityCreationParams()
params.transform = myTransform
params.variationNameHash = 1234

EntityManager:CreateClientEntitiesFromBlueprint(blueprint, params)
```

You can avoid the crashes above by specifying a valid variation name hash when spawning the entities.

**Comment by Powback** [comment]
The addition of variation does indeed solve most issues, some objects that still cause a crash however. 

The easiest way to test this is by using the newest version of https://github.com/Powback/MapEditor, and spawn some objects until crash. 

SpatialPrefabBlueprint is the most common crash-causing blueprint.
Flags are also crashing when spawned. I suspect that it's the same crash-cause.

**Comment by Powback** [comment]
There's still an issue when spawning some objects.

mp_subway RushLarge
https://github.com/Powback/Venice-EBX/blob/master/Levels/MP_Subway/Objects/ParkEntrance/BrokenStair_01.txt

All objects in ParkEntrance seems to be affected.


MVD:
https://raw.githubusercontent.com/Powback/Venice-EBX/master/Levels/MP_Subway/Rush/MeshVariationDb_Win32.txt

```
MeshVariationDatabaseEntry F8F2505B-D9D3-0533-A6F4-2E6857311E47
    $::DataContainer
    Mesh levels/mp_subway/objects/parkentrance/brokenstair_01_mesh/30140C1C-4349-8378-7EAD-FDEF1ECC19E1
    VariationAssetNameHash 0
    Materials::array
        member::MeshVariationDatabaseMaterial
            Material levels/mp_subway/objects/parkentrance/brokenstair_01_mesh/E3E5FACF-FDFE-AA71-849D-CFD72C0E608A
            MaterialVariation *nullGuid*
            TextureParameters::array
                member::TextureShaderParameter
                    ParameterName Diffuse
                    Value objects/brickwall_01/brickwall_01_d/2CC6FE71-D2C8-8E38-D4E8-457C7D470416
                member::TextureShaderParameter
                    ParameterName Normal
                    Value objects/brickwall_01/brickwall_01_n/F2A5F726-DE13-E77E-6AAC-D7A2E8608495
                member::TextureShaderParameter
                    ParameterName Specular
                    Value objects/brickwall_01/brickwall_01_d/2CC6FE71-D2C8-8E38-D4E8-457C7D470416
        member::MeshVariationDatabaseMaterial
            Material levels/mp_subway/objects/parkentrance/brokenstair_01_mesh/60C8F94A-4ACA-46C2-9D2E-ADB1297842F3
            MaterialVariation *nullGuid*
            TextureParameters::array
                member::TextureShaderParameter
                    ParameterName Diffuse
                    Value levels/mp_subway/objects/parkentrance/concretebroken_01_d/C462981A-315E-A61C-15D5-51CFC304A5BD
                member::TextureShaderParameter
                    ParameterName Normal
                    Value levels/mp_subway/objects/parkentrance/concretebroken_01_n/8D6A714B-F50C-595F-5C05-C5862160D808
                member::TextureShaderParameter
                    ParameterName Specular
                    Value levels/mp_subway/objects/parkentrance/concretebroken_01_d/C462981A-315E-A61C-15D5-51CFC304A5BD
        member::MeshVariationDatabaseMaterial
            Material levels/mp_subway/objects/parkentrance/brokenstair_01_mesh/019498E7-B049-445D-84B7-A7D9F5C2E36F
            MaterialVariation *nullGuid*
            TextureParameters::array
                member::TextureShaderParameter
                    ParameterName Diffuse
                    Value architecture/texturesshared/stairtile_01_d/574ED7D1-9B8F-C969-2697-EC6CE66CB09D
                member::TextureShaderParameter
                    ParameterName Normal
                    Value architecture/texturesshared/stairtile_01_n/B8B74CC1-2FB6-6619-3CBD-8C88C90ADCB7
                member::TextureShaderParameter
                    ParameterName Specular
                    Value architecture/texturesshared/stairtile_01_d/574ED7D1-9B8F-C969-2697-EC6CE66CB09D
        member::MeshVariationDatabaseMaterial
            Material levels/mp_subway/objects/parkentrance/brokenstair_01_mesh/5CF426A6-7C27-449D-A1D7-622A2A232330
            MaterialVariation *nullGuid*
            TextureParameters::array
                member::TextureShaderParameter
                    ParameterName Diffuse
                    Value levels/mp_012/terrain/textures/t_rubble_01_d/3AAD4F50-095D-B675-68D0-590437009DF6
                member::TextureShaderParameter
                    ParameterName Normal
                    Value levels/mp_012/terrain/textures/t_rubble_01_n/5FBD9A78-5CFF-5EFC-61BF-D868E7B2E52D
                member::TextureShaderParameter
                    ParameterName Specular
                    Value levels/mp_012/terrain/textures/t_rubble_01_d/3AAD4F50-095D-B675-68D0-590437009DF6 
```

Spawning it with the MeshVariation 0 crashes while doing EntityManager:Create[Server/Client]EntitiesFromBlueprint

Happens regardless of server/client.

**Comment by Powback** [comment]
testmod: https://cdn.discordapp.com/attachments/187339455315574784/473551469673578507/entity-crash.7z




[dumps.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2242373/dumps.zip)

**Comment by Powback** [comment]
All objects in objects/vegetation cause a crash

**Comment by 3ti65** [comment]
NoFaTe: a crash that I was having when creating creating the soldier entity for the player was for the same reason as https://github.com/EmulatorNexus/VeniceUnleashed/issues/322 
It might affect other entities too. I fixed it locally (in my mod) by queuing the creation and doing it on the next PreSim update.

might be the same issue

**Comment by OrfeasZ** [comment]
Build `13761` fixes the server crash when spawning vegetation objects, however it seems like they don't appropriately replicate to the client as they should, and if a client joins after a vegetation object has been spawned on the server, he immediately crashes. 

Spawning vegetation on the client-side will fail by default (returning no entities), so in order to be able to actually spawn them you have to take `VegetationTreeEntityData` and switch `clientSideOnly` to `true`.
