### ISSUE TITLE
[Bug] NetEvent doesn't work for some reason

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#314]
We have multiple instances of a CapturePoint server sided class that sends a NetEvent at some point. However, for some reason, the NetEvent never reaches the client for some reason. If i do the same thing in the unit tests, it works perfectly fine. For some weird reason it must fuck up something within vEXT that leads to the NetEvent not being routed correctly. 

Steps to reproduce:

1. Load a server running the latest version of realitymod on Armored Shield ( XP3_Shield ConquestLarge0 2 )
2. Take a helicopter and fly to 'Satellite' flag (you'll see it on the map)
3. Look at server console. It will spit out some stuff continuously. Once it reaches '100 / - 100', it will say something like "sending NetEvent: CapturePoint:FullyCapped  - params: ... " ( Server/Logic/General/CapturePoint.lua - line 230 )
4. Look at client console. It should print "OnNeutralCapped ...", but it doesnt. ( Client/UI/Minimap.lua - line 68 )

**Comment by 3ti65** [comment]
It also seems that some NetEvents are invoked twice, even if they're only called once. 

Example in realitymod:

Client/Logic/ClientSLMarkerManager.lua - Line 29/30:
`print("ClientSLMarkerManager:SetMarker()")
NetEvents:SendLocal('SLMarker:SetBySL', teamId, squadId, markerType, xPos, yPos)`

Server/Logic/ServerSLMarkerManager.lua - Line 22:
`NetEvents:Subscribe('SLMarker:SetBySL', self, self.OnNewMarkerSet)`

Line 26:

```
function ServerSLMarkerManager:OnNewMarkerSet(player, teamId, squadId, markerType, xPos, yPos)
	if player.squadID == 0 or player.isSquadLeader == false then
		return
	end

	m_Logger:Write("OnNewMarkerSet()") -- this gets called twice for absolutely no fucking reason??
	self.slMarkers[teamId][squadId] = { markerType = markerType, xPos = xPos, yPos = yPos }
	self:UpdateSquad(teamId, squadId, markerType, xPos, yPos)
end
```

**> In the Client Console it prints "ClientSLMarkerManager:SetMarker()" once.
In the server Console it prints "OnNewMarkerSet()" _twice_, even though it should only be printed once.**

**Comment by Powback** [comment]
ServerSLMarkerManager:RegisterEvents() is called twice.

**Comment by 3ti65** [comment]
This seems to be resolved now. Was an issue in the rm code i suppose.
