### ISSUE TITLE
[Bug] Freeze when loading into the server

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#315]
With one of the recent updates, theres a freeze happening when loading into the server. The more one does in lua / vEXT, the longer it freezes. This can lead to a disconnect of the client while trying to load in. (Happens in case of RM)

**Comment by FoolHen** [comment]
As Powback said this seems to be because of the partitionloaded loop

**Comment by OrfeasZ** [comment]
This might be fixed in build 12927. Will verify.
