### ISSUE TITLE
LinearTransform() returns scale 0.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#317]
LinearTransform() should return
```
LinearTransform(
    Vec3(1,0,0),
    Vec3(0,1,0),
    Vec3(0,0,1),
    Vec3(0,0,0)
)
```

**Comment by OrfeasZ** [comment]
Build 12927 makes the default `LinearTransform` constructor create the identity matrix (1 across the diagonal). It also adds a new constructor `LinearTransform(123)` where `123` can be any numeric value and will be placed in the diagonal of the matrix. `LinearTransform()` is an alias for `LinearTransform(1)`.
