### ISSUE TITLE
[Crash] Calling entities from EntityFactory hook causes a crash.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#318]
```
 Hooks:Install('ClientEntityFactory:Create',999, self, OnEntityCreate)
 Hooks:Install('ServerEntityFactory:Create',999, self, OnEntityCreate)

function OnEntityCreate(p_Hook, p_Data, p_Transform)
	p_Hook:Call()
end
```

This mod causes the server to crash upon player join, and causes the client to crash upon either load or spawn.
___

There is also a typeName issue for some entities.
```
local x = p_Hook:Call()
print(x.typeName)
```
The console will sometimes output nil. 
This happens to certain types, but also for some entities that worked fine just moments before.

```
SomeEntityData // GUID1
SomeEntity
SomeEntityData // GUID1
SomeEntity
SomeEntityData // GUID1
nil
```
___
Additionally, "VisualEnvironmentEntity" will not work correctly if catched by the hook. The spawnscreen background will be transparent for example. I suspect that the issue might be related.
This also happens if we return the entity as well.

```
if(p_Data.typeInfo.typeName == "VisualEnvironmentEntityData") then
    local x = p_Hook:Call()
    p_Hook:Return(x)
end
```

**Comment by Powback** [comment]
Seems like ClientChassisComponent and ServerChassisComponent are relevant to the issue.

**Comment by OrfeasZ** [comment]
I noticed this issue too. I've done some initial digging but I couldn't figure out what's causing it (I actually think you were in teamspeak or whatever while I was looking into it the other day). If we can find more specifically what types of entities cause this crash it would probably help a lot.

**Comment by Powback** [comment]
Yeah, you're right. We didn't add the issue back then though.

I'll compile a list of problematic entities as soon as possible.

**Comment by OrfeasZ** [comment]
This issue is hurting my brain. Everything I've seen so far seems to indicate some sort of return address corruption, but I'm not sure where or why it happens. Needs some more investigation. At least the good news is that in dealing with this issue, hooks are now slightly more performant.

**Comment by OrfeasZ** [comment]
Fixed in build 13252.
