### ISSUE TITLE
[Req] Increase WebUI scroll speed

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#319]

**Comment by Powback** [comment]
There's something funky going on with the WebUI scrolling. Happens both in RM and MapEditor. Will investigate.

**Comment by FoolHen** [comment]
Indeed, click dragging a leaflet map doesnt work ingame but works in chrome.

**Comment by OrfeasZ** [comment]
Scroll speed was increased in build `14744`.
