### ISSUE TITLE
[Bug] Insert, erase, set and find fuctions don't work

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#323]
``arr:set(idx, val), arr:find(val), arr:erase(idx), arr:insert(idx, val)`` don't work. Erase and set don't display any error but they don't do anything. Find and insert print an error (the output is in a comment inside the testmod)
``arr:add(val), arr:clear(), arr:get(idx)`` work

Use ``MP_017 ConquestLarge0 2``
[arraytest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2086851/arraytest.zip)

**Comment by OrfeasZ** [comment]
`:erase(x)` should work as expected. In your example you try to remove an element at index 4, which doesn't exist (lua may be 1-based but currently vext arrays are 0-based).

**Comment by OrfeasZ** [comment]
`erase` has been fixed in the latest build. `set` and `insert` will be properly implemented shortly.

**Comment by OrfeasZ** [comment]
`find` will also be supported, but only for non-struct arrays (so only for arrays containing DataContainers or primitives such as strings, numbers, enums, etc.). This might change in the future as tooling improves.

**Comment by OrfeasZ** [comment]
`set`, `insert` and `find` should all work starting in build 13173. Keep in mind that `find` is still not available for arrays of frostbite structures (such as `Vec3`).
