### ISSUE TITLE
[Crash] Cloning an asset causes a crash when the asset is used.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#325]
Testmod: http://powback.com/u/fdcf112d8a6277d4724f3b5c11661765.7z

```
if l_Instance.instanceGuid == Guid('E628556D-6CA5-4B9D-851A-CCE10BF6A59B') then --UI/Art/Persistence/Camo/U_CAMO_DrPepper
            print("Found U_CAMO_DrPepper")
            local originalAsset = l_Instance
            local clonedAsset = UnlockAsset(l_Instance:Clone(l_Instance.instanceGuid))
            if(originalAsset ~= nil and clonedAsset ~= nil) then
                print("We have both assets, but its not the end of the partition. Replacing instance.")
                p_Partition:ReplaceInstance(originalAsset, clonedAsset, true)
            end
        end
```

To crash, enter the customization menu and select the Dr. Pepper camo.
http://powback.com/u/35e6020d23f0ad023ab27c14030d045f.png

I have also tried to add the cloned asset into the registry, but that didn't solve anything.
I've also tried to replace the instance after the partition has fully read, but the issue persists.

No crashdump.

**Comment by OrfeasZ** [comment]
I think this might be standard engine behavior, as cloning doesn't necessarily associate any additional metadata that an asset may carry post-load. I'll investigate anyway.

**Comment by Powback** [comment]
Unable to replicate in build 14089
