### ISSUE TITLE
VU license activator no longer works

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#327]
EA has changed the way license activation works, causing the embedded VU license activator (using `-activate -o_mail` etc) to no longer work.

**Comment by OrfeasZ** [comment]
Looks like EA decided to fix the legacy auth endpoint and activation works again now! Weew

**Comment by OrfeasZ** [comment]
Reopening because EA can't decide whether to keep the endpoint online or not...

**Comment by Powback** [comment]
Seems to be working again for me.

**Comment by OrfeasZ** [comment]
It's very inconsistent, which is why I've re-opened this. I'll switch to another authentication endpoint.

**Comment by OrfeasZ** [comment]
Fixed in build `14137`.
