### ISSUE TITLE
[Req] player.isManDown and player.isRevivable flags

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#329]
``soldier == nil`` and ``player.alive`` are the same, and we need a way to distinguish between a player that is revivable or dead dead

**Comment by 3ti65** [comment]
Also we absolutely need a player.isRevivable flag, that indicates whether the player is revivable or not.
The player.isManDown flag should be true when the player got revived but hasnt accepted / refused the revive yet.

**Comment by OrfeasZ** [comment]
Build `13323` adds two new events:
- `ServerSoldier:HealthAction`(`soldier`, `healthStateAction`)
- `ClientSoldier:HealthAction`(`soldier`, `healthStateAction`)

These events trigger whenever there's a transition to a new health state for a soldier. There is a new enum in VEXT (`HealthStateAction`) that represents those transitions and has the following values:
- `OnHealthy`
- `OnCriticallyDamaged`
- `OnInteractiveManDown`
- `OnManDown`
- `OnKilled`
- `OnDead`
- `OnDeathAnimationDone`
- `OnRevive`
- `OnReviveDone`
- `OnReviveAborted`

I will also add an `isManDown` field to the SoldierEntity soon™.

**Comment by 3ti65** [comment]
beautiful. will test it.

**Comment by OrfeasZ** [comment]
Build `13333` adds the following fields to `SoldierEntity` (`isManDown` already existed, lol):
- `isAlive`
- `isDead`
- `isDying`
- `isInteractiveManDown`

It also adds a `corpse` field to the `Player` object which returns a `SoldierEntity` (if a player has a corpse).

**Comment by FoolHen** [comment]
@OrfeasZ ``ServerSoldier:HealthAction(soldier, healthStateAction)`` is not really useful, as the param is a ``SoldierEntity`` and ``soldier.player`` is nil for almost all ``healthStateAction `` values (it's not nil only if the player is alive). We either need the player object as a parameter too or (probably better) a way to get the player associated to that ``SoldierEntity``, even when it's a corpse.

**Comment by 3ti65** [comment]
@Raikem make a new issue for that maybe? since its not directly related to the initial request?
