### ISSUE TITLE
Current connection sequence doesn't punch through NAT

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#33]
This prevents hybrid servers from being properly joinable in NAT environments without proper configuration.

**Comment by kiwidoggie** [comment]
You can resolve the issue by port forwarding UDP Inbound Port 7948 in the meantime.

**Comment by OrfeasZ** [comment]
However, that's not guaranteed to work with all routers.

**Comment by OrfeasZ** [comment]
Since build 7054 the server will attempt automatic port-mapping with UPnP enabled devices.
Some additional heuristics have also been applied to allow same-network connections under NAT.
