### ISSUE TITLE
[Bug] WebUI doesnt render correctly

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#331]
For example, when you resize (and it doesnt crash), some parts are not being rerendered until you hover over it with the mouse. Could be related to what we discussed in discord regarding the CEF process not getting killed when the client dies.

**Comment by 3ti65** [comment]
Possibly related to #334

**Comment by 3ti65** [comment]
Definitely related to #334 

I guess this can then be dismissed. Your call.

**Comment by Powback** [comment]
Still present in 13415
Easy way to test is by moving the windows in MapEditor.

**Comment by OrfeasZ** [comment]
Fixed in build `13446`.
