### ISSUE TITLE
[Crash] Changing Projectiles crashes server on restart

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#332]
Steps to reproduce:

1. Load newest version of realitymod
2. Go to Shared/__init.lua -> line 66
3. Comment back in that line
4. Run server. Spawn in (?)
5. Restart round via procon -> crash

**Comment by 3ti65** [comment]
This needs to be reverified. Dont think it's still legit.

**Comment by FoolHen** [comment]
They do crash if they are cloned, but they don't if you make them writable

**Comment by Powback** [comment]
This smells like the datacontainer cleanup issue. Close?

**Comment by 3ti65** [comment]
Yup, does sound like a cleanup issue. I suggest closing it.
