### ISSUE TITLE
Launching VU with too low permissions causes UI etc not to be loaded

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#333]
Mods are currently stored in the VU installation directory. If said directory requires elevated permissions, the client will be unable to download UI files.

I propose that the mods are stored in ClientInstancePath/mods

**Comment by mavanmanen** [comment]
Just ran into this issue as well. Storage directly definitely should be changed to where the user has write permissions by default.

**Comment by derrod** [comment]
VU currently writes crashdumps to `%LOCALAPPDATA%\VeniceUnleashed\dumps`, perhaps mods could be written to `%LOCALAPPDATA%\VeniceUnleashed\mods`.

**Comment by OrfeasZ** [comment]
Starting with build `13472`, downloaded mod files are placed in `%LocalAppData%\VeniceUnleashed\mods`.
