### ISSUE TITLE
VU subprocess doesn't properly close after a crash

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#334]
The VU subprocess used to close properly after a crash, but after a later build, it no longer does.

This results in 4-5 VU processes that eat away your CPU until your PC eventually bluescreens.

To replicate:
Start VU using a bat file.
Close the bat file
VU process is still running.

Only affects client.

**Comment by OrfeasZ** [comment]
Fixed in build 13334.
