### ISSUE TITLE
[Req] Add a way to get AxisAlignedBox from an entity

### ISSUE THREAD

**Issue by txt231** [VeniceUnleashed/VeniceUnleashed#336]
there needs to be a way to get fb::AxisAlignedBox from a SpatialEntity or child entity in vext. 

For help: the function should be computeBoundingBox( fb::AxisAlignedBox& )

**Comment by OrfeasZ** [comment]
Build `13445` adds the following two fields to the `SpatialEntity` type (and derived types):

- `aabb`: Returns an `AxisAlignedBox` of the Axis Aligned Bounding Box for this entity
- `aabbTransform`: Returns the `LinearTransform` of the AABB
