### ISSUE TITLE
Getting owner object from PhysicsEntityBase

### ISSUE THREAD

**Issue by txt231** [VeniceUnleashed/VeniceUnleashed#338]
There needs to be a way to get the entity parent from fb::PhysicsEntityBase classes that inherrits PhysicsEntityBase.

There should be a pointer, called m_userData which points to the entity in PhysicsEntityBase

**Comment by Powback** [comment]
Please not that MapEditor depends on this issue for easy object-selection, since most objects will return the collision entity instead of the "actual" entity at raycast hit.

**Comment by kiwidoggie** [comment]
Currently steps towards this direction in build 14122 any `PhysicsEntity` based object will have `string GetUserDataType()` in order to check the type of the user data field. This will return empty string on error.

**Comment by OrfeasZ** [comment]
Build `14258` removes `GetUserDataType()` from `PhysicsEntityBase` and instead adds a new (writable) field:
- `Entity userData`
