### ISSUE TITLE
Physics entity support

### ISSUE THREAD

**Issue by txt231** [VeniceUnleashed/VeniceUnleashed#339]
- [x] Add a way to get and set linearVelocity in fb::PhysicsEntity

Should be a virtual to get linearVelocity, but the set function is static

- [x] Add a way to get and set for angularVelocity in fb::PhysicsEntity

Should also be a virtual to get angularVelocity, but the set function is static

- [x] Add a way to get and set mass in fb::PhysicsEntity

Should also be a virtual to get mass, but the set function is static

- [x] Add a way to get part transforms and possibly part entities/nodes.

There is a list in fb::PhysicsEntity with pointer to the component/entity, tho this is not used for all types i believe.

There is a virtual to get the transforms, but to set the transform i believe you have to use the part entity.

If there is no parts it returns base transform.

- [ ] Add a way to get fb::HavokPhysicsData for fb::PhysicsEntity (return nil if doesnt exist)

**Comment by OrfeasZ** [comment]
Build `14025` adds several new types:

**SHARED**  

`PhysicsEntityBase` : `SpatialEntity`
- `PhysicsEntityBase(Entity ref)`
- `PhysicsEntityBase(SpatialEntity ref)`
- `TypeInformation typeInfo`
- `float mass`
- `float invMass`
- `Vec3 linearVelocity`: Writable
- `Vec3 angularVelocity`: Writable
- `Vec3 position`
- `bool sleeping`: Writable
- `bool addedToWorld`
- `int partCount`
- `float gravityFactor`: Writable
- `float friction`: Writable
- `float restitution`: Writable
- `float linearDamping`: Writable
- `float angularDamping`: Writable
- `void AddToWorld()`
- `void RemoveFromWorld()`
- `Entity GetPart(int index)`
- `QuatTransform GetPartTransform(int index)`
- `DataContainer GetPartMaterial(int index[, Vec3 pos])`
- `int GetPartMaterialFlags(int index)`
- `int GetProperty(int property)`
- `void SetProperty(int property, int value)`
- `int RemoveProperty(int property)`
- `void SetMass(float mass, bool updateInertia)`
- STATIC: `TypeInformation PhysicsEntityBase.typeInfo`

Please note that setting some of these values (such as velocity, friction, mass, etc.) only works for very specific entity types.

`DamageType` (enum)
- `NotSet`
- `Suicide`
- `VehicleUpsideDown`
- `DamageArea`
- `SoldierCollide`
- `Melee`
- `Count`

**SERVER**  

`ServerDamageInfo` has been renamed to `DamageInfo` and the following two fields have been added:
- `DataContainer damagedMaterial`
- `DataContainer collidingMaterial`

The `Soldier:Damage` event has also been updated to `Soldier:Damage(SoldierEntity soldier, DamageInfo info, DamageGiverInfo giverInfo)`.

`DamageGiverInfo` (all fields are writable)
- `DamageGiverInfo()`
- `DamageGiverInfo(DamageGiverInfo ref)`
- `Player giver`
- `Player assistant`
- `DataContainer weaponUnlock`
- `Entity physicsEntity`
- `Entity giverControllable`
- `Entity lockedTarget`
- `DataContainer giverCharacterCustomization`
- `DamageType damageType`

`CollisionInfo` (all fields are writable)
- `CollisionInfo()`
- `CollisionInfo(CollisionInfo ref)`
- `Entity entity`
- `DataContainer material`
- `DataContainer ownMaterial`
- `Vec3 position`
- `Vec3 normal`
- `float speed`
- `int part`
- `bool isInstantlyDestructible`

`GameEntity` : `SpatialEntity`
- `GameEntity(Entity ref)`
- `GameEntity(SpatialEntity ref)`
- `TypeInformation typeInfo`
- `void Spawn(LinearTransform transform, bool fireEnableEvent)`
- `int RegisterSpawnCallback(function cb)`: Callback handler should be `function(Entity ent)`.
- `int RegisterSpawnCallback(object obj, function cb)`
- `void UnregisterSpawnCallback(int handle)`
- `int RegisterUnspawnCallback(function cb)`: Callback handler should be `function(Entity ent)`.
- `int RegisterUnspawnCallback(object obj, function cb)`
- `void UnregisterUnspawnCallback(int handle)`
- STATIC: `TypeInformation GameEntity.typeInfo`

`PhysicsEntity` : `GameEntity`
- `PhysicsEntity(Entity ref)`
- `PhysicsEntity(SpatialEntity ref)`
- `PhysicsEntity(GameEntity ref)`
- `TypeInformation typeInfo`
- `float internalHealth`: Writable
- `Vec3 velocity`
- `DataContainer defaultMaterial`
- `bool belongsInPhysicsWorld`
- `bool isPredestructible`
- `PhysicsEntityBase physicsEntityBase`
- `DataContainer GetMaterial(Vec3 position)`
- `void SetActiveHealthState(int state)`
- `void ApplyDamage(DamageInfo info)`
- `int RegisterCollisionCallback(function cb)`: Callback handler should be `function(Entity ent, CollisionInfo info)`.
- `int RegisterCollisionCallback(object obj, function cb)`
- `void UnregisterCollisionCallback(int handle)`
- `int RegisterDamageCallback(function cb)`: Callback handler should be `function(Entity ent, DamageInfo info, DamageGiverInfo giverInfo)`.
- `int RegisterDamageCallback(object obj, function cb)`
- `void UnregisterDamageCallback(int handle)`
- `int RegisterInteractCallback(function cb)`: Callback handler should be `function(Entity ent, SoldierEntity soldier)`.
- `int RegisterInteractCallback(object obj, function cb)`
- `void UnregisterInteractCallback(int handle)`
- STATIC: `TypeInformation PhysicsEntity.typeInfo`

**CLIENT**  

`DamageInfo` (all fields are writable)
- `DamageInfo()`
- `DamageInfo(DamageInfo ref)`
- `Vec3 position`
- `Vec3 direction`
- `Vec3 origin`
- `float damage`
- `float distributeDamageOverTime`
- `int boneIndex`
- `int hitDirection`
- `bool isBulletDamage`

`DamageGiverInfo` (all fields are writable)
- `DamageGiverInfo()`
- `DamageGiverInfo(DamageGiverInfo ref)`
- `Player giver`
- `DataContainer weaponUnlock`

`CollisionInfo` (all fields are writable)
- `CollisionInfo()`
- `CollisionInfo(CollisionInfo ref)`
- `Entity entity`
- `DataContainer material`
- `DataContainer ownMaterial`
- `Vec3 position`
- `Vec3 normal`
- `float speed`
- `int part`
- `bool isInstantlyDestructible`

`GameEntity` : `SpatialEntity`
- `GameEntity(Entity ref)`
- `GameEntity(SpatialEntity ref)`
- `TypeInformation typeInfo`
- `void Spawn(LinearTransform transform, bool fireEnableEvent)`
- `int RegisterSpawnCallback(function cb)`: Callback handler should be `function(Entity ent)`.
- `int RegisterSpawnCallback(object obj, function cb)`
- `void UnregisterSpawnCallback(int handle)`
- `int RegisterUnspawnCallback(function cb)`: Callback handler should be `function(Entity ent)`.
- `int RegisterUnspawnCallback(object obj, function cb)`
- `void UnregisterUnspawnCallback(int handle)`
- STATIC: `TypeInformation GameEntity.typeInfo`

`PhysicsEntity` : `GameEntity`
- `PhysicsEntity(Entity ref)`
- `PhysicsEntity(SpatialEntity ref)`
- `PhysicsEntity(GameEntity ref)`
- `TypeInformation typeInfo`
- `float internalHealth`: Writable
- `Vec3 velocity`
- `DataContainer defaultMaterial`
- `bool belongsInPhysicsWorld`
- `bool isAnimatable`
- `PhysicsEntityBase physicsEntityBase`
- `DataContainer GetMaterial(Vec3 position)`
- `void ReenablePart(int index)`
- `int RegisterCollisionCallback(function cb)`: Callback handler should be `function(Entity ent, CollisionInfo info)`.
- `int RegisterCollisionCallback(object obj, function cb)`
- `void UnregisterCollisionCallback(int handle)`
- `int RegisterDamageCallback(function cb)`: Callback handler should be `function(Entity ent, DamageInfo info, DamageGiverInfo giverInfo)`.
- `int RegisterDamageCallback(object obj, function cb)`
- `void UnregisterDamageCallback(int handle)`
- STATIC: `TypeInformation PhysicsEntity.typeInfo`

`SoldierEntity` on both the server and client now derive from each respective `PhysicsEntity`.

**Comment by Powback** [comment]
Could we get ApplyForce as well?
```
    void applyForce(const hkReal, const hkVector4 &);
    void applyForce(const hkReal, const hkVector4 &, const hkVector4 &);
```
