### ISSUE TITLE
[REQ] SoldierEntity:GetHeadTransform

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#343]
SoldierEntity currently has GetHeadPosition, but you should be able to get the entire transform.
This is not to be confused with camera transform, which returns where you're actually looking. This function should return the head bone transform of the SoldierEntity

Alternatively a :GetBoneTransform(name/index) function could be implemented, since you'll have to hook into the whole thing anyway. 

If possible, a bone class could be implemented, which includes the local and world transform, along with information such as the collision capsule width/height. 
The bone width/length/ can already be accessed by grabbing data from ebx, but a more native implementation would be appreciated.

**Comment by Powback** [comment]
The implementation introduced in build 13344 works, but the rotation is returned as `(1.000000, 0.000000, 0.000000) (0.000000, 1.000000, 0.000000) (0.000000, 0.000000, 1.000000)`

**Comment by OrfeasZ** [comment]
Build `13402` introduces the following changes:

A new `QuatTransform` type has been introduced with the following fields and methods:
- `rotation`: quaternions represented as `Vec4`
- `transAndScale`: a `Vec4` that represents the translation coordinate in its first 3 elements and the scale factor in its last
- `ToLinearTransform()`: creates a `LinearTransform` based on the data of this `QuatTransform`
- `Clone()`: clones this `QuatTransform`

It also has the following constructors:
- `QuatTransform()`: creates a new zero `QuatTransform`
- `QuatTransform(rotation, transAndScale)`: creates a new `QuatTransform` given two `Vec4` representing the quaternions and the translation and scale

A new method has been introduced to the `LinearTransform` type:
- `ToQuatTransform(hasScale)`: creates a `QuatTransform` based on the data of this `LinearTransform`. `hasScale` is a boolean representing whether to infer a scale from the `LinearTransform` data.

A `ragdollComponent` field has been added to the client-side `SoldierEntity` type, which returns a new `RagdollComponent` type. The `RagdollComponent` type has the following fields and methods:

- `data`: returns a `DataContainer` representing the `RagdollComponentData` for this ragdoll
- `GetLocalTransform(boneIndex)`
- `SetLocalTransform(boneIndex, transform)`
- `GetWorldTransform(boneIndex)` 
- `SetWorldTransform(boneIndex, transform)`
- `GetRenderTransform(boneIndex)` 
- `SetRenderTransform(boneIndex, transform)`
- `GetInterpolatedLocalTransform(boneIndex)` 
- `SetInterpolatedLocalTransform(boneIndex, transform)`
- `GetInterpolatedWorldTransform(boneIndex)` 
- `SetInterpolatedWorldTransform(boneIndex, transform)`
- `GetActiveWorldTransform(boneIndex)` 
- `SetActiveWorldTransform(boneIndex, transform)`
- `GetActiveLocalTransform(boneIndex)` 
- `SetActiveLocalTransform(boneIndex, transform)`
- `GetLocalTransform(boneIndex)` 
- `SetLocalTransform(boneIndex, transform)`
- `GetBoneVelocity(boneIndex)` 
- `SetBoneVelocity(boneIndex, transform)`

The `GetX` methods above return a `QuatTransform` and the `SetX` methods also accept a `QuatTransform`. The `boneIndex` parameter is a numeric index representing a bone in the specific ragdoll's skeleton. You can get a list of bones and their names by looking at the `skeleton` property of `RagdollComponentData`. The default Venice skeleton is `Animations/Skeletons/VeniceAntSke01`.

All this is very untested, so feel free to give it a try and let me know how everything goes. If everything's good feel free to close this issue.

**Comment by OrfeasZ** [comment]
I should also note that this build removes `GetHeadTransform` from the `SoldierEntity` type.

**Comment by Powback** [comment]
SetLocalTransform works, but it's being constantly overwritten by the animation, making it kinda jitter back and forth between the two states.
