### ISSUE TITLE
[REQ] Math

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#345]
Some of these may already be implemented or unnecessary. 

[**Quaternion**](https://docs.unity3d.com/ScriptReference/Quaternion.html)

- [x] Euler
- [x] FromEuler
- [x] LookRotation
- [x] Normalize
- [x] RotateTowards

**Operators:**

- [x] Operator *
- [x] Operator ==

___

[**Vector3**](https://docs.unity3d.com/ScriptReference/Vector3.html)

- [x] MoveTowards
- [x] Dot
- [x] Distance
- [x] Cross
- [ ] Max
- [ ] Min

**Operators:**
- [x] operator -
- [x] operator !=
- [x] operator *
- [x] operator /
- [x] operator +
- [x] operator ==

Additionally, the shorthands would be useful.

- [x] back = Vector3(0, 0, -1).
- [x] down = Vector3(0, -1, 0).
- [x] forward = Vector3(0, 0, 1).
- [x] left = Vector3(-1, 0, 0).
- [x] negativeInfinity = Vector3(float.NegativeInfinity, float.NegativeInfinity, float.NegativeInfinity).
- [x] one = Vector3(1, 1, 1).
- [x] positiveInfinity = Vector3(float.PositiveInfinity, float.PositiveInfinity, float.PositiveInfinity).
- [x] right = Vector3(1, 0, 0).
- [x] up = Vector3(0, 1, 0).
- [x] zero = Vector3(0, 0, 0).

___
[**LinearTransform**](https://docs.unity3d.com/ScriptReference/Transform.html)

- [ ] Translate

**Operators:**

- [x] operator !=
- [x] operator ==

___
[General math:](https://docs.unity3d.com/ScriptReference/Mathf.html)
Some of these may be unnecessary or easy to implement in Lua, but it would still be nice to have them implemented.

- [x] Deg2Rad
- [x] Epsilon
- [x] Infinity
- [x] NegativeInfinity
- [x] PI
- [x] Rad2Deg
- [ ] Static
- [x] Abs
- [x] Acos
- [x] Approximately
- [x] Asin
- [x] Atan
- [x] Atan2
- [x] Ceil
- [ ] CeilToInt
- [x] Clamp
- [ ] Clamp01
- [ ] ClosestPowerOfTwo
- [ ] CorrelatedColorTemperatureToRGB
- [x] Cos
- [ ] DeltaAngle
- [x] Exp
- [x] Floor
- [ ] FloorToInt
- [ ] GammaToLinearSpace
- [ ] InverseLerp
- [ ] IsPowerOfTwo
- [x] Lerp
- [ ] LerpAngle
- [ ] LerpUnclamped
- [ ] LinearToGammaSpace
- [x] Log
- [x] Log10
- [x] Max
- [x] Min
- [ ] MoveTowards
- [ ] MoveTowardsAngle
- [ ] NextPowerOfTwo
- [ ] PerlinNoise
- [ ] PingPong
- [x] Pow
- [ ] Repeat
- [x] Round
- [ ] RoundToInt
- [ ] Sign
- [x] Sin
- [ ] SmoothDamp
- [ ] SmoothDampAngle
- [ ] SmoothStep
- [x] Sqrt
- [x] Tan

**Comment by kiwidoggie** [comment]
Multiplication is already implemented

Vec3 
- Back
- Down
- Forward
- Left
- NegativeInfinity
- One
- PositiveInfinity
- Right
- Up
- Zero
- Distance

have all been added in build 13452

**Comment by kiwidoggie** [comment]
`FromEuler` has been changed to QuatTransform(yaw, pitch, roll) in build 13453
ToEulerAngle has been implemented as well

**Comment by OrfeasZ** [comment]
Build `13456` properly exposes premade Vec3s as static variables (for example `Vec3.back`, `Vec3.negativeInfinity`, etc.). It also introduces a new `Quat` type which has the following constructors, fields, and methods:

- `Quat()`: Creates the identity Quat `(0, 0, 0, 1)`
- `Quat(x, y, z, w)`
- `Quat(vec3)`: Creates a Quat given a `Vec3` holding Euler angles
- `x`
- `y`
- `z`
- `w`
- `ToEuler()`: Returns a `Vec3` of the corresponding Euler angles for this Quat
- `Normalize()`: Normalizes this Quat
- `Clone()`: Clones this Quat

The `Quat` type also supports multiplication and comparison operators.

The euler-based `QuatTransform` constructor has been removed, along with the `ToEulerAngle` function. The `rotation` component of the `QuatTransform` type now uses the new `Quat` type instead of `Vec4`.

**Comment by ExtReMLapin** [comment]
you should add a squared version of the `Distance`, since calculating the square root is expensive, like if you want to hardcode distance checks, it's better to check the non-square-root distance

**Comment by FoolHen** [comment]
@OrfeasZ printing a Quat outputs lua_userdata. using :Normalize() on a quaternion returns nil.

**Comment by kiwidoggie** [comment]
@Raikem I'm pretty sure Normalize just normalizes the current Quat, not return a new one

**Comment by OrfeasZ** [comment]
Build `13521` adds a new `MathUtils` library which has the following functions:

- `double GetRandom(double from, double to)`: Moved from `SharedUtils`
- `Vec3 GetYPRFromULF(Vec3 up, Vec3 left, Vec3 forward)`: Moved from `LinearTransform.GetYawPitchRollFromUpLeftForward`
- `LinearTransform GetTransformFromYPR(double yaw, double pitch, double roll)`: Moved from `LinearTransform.GetTransformFromUpLeftForward`
- `bool Approximately(double a, double b)`
- `double Clamp(double value, double min, double max)`
- `double Round(double value)`
- `double Lerp(double a, double b, double t)`

It also adds the following new field to the lua math library, which represents the machine epsilon: `math.epsilon`.

**Comment by OrfeasZ** [comment]
Build `13528` adds the following:

**Quat**
- `Quat(Vec3 forward, Vec3 up)`: Constructor equivalent to `Quaternion.LookRotation`
- `float length`
- `float lengthSquared`
- `float Dot(Quat other)`
- `float Angle(Quat other)`
- `Quat RotateTowards(Quat to, float maxDegreesDelta)`
- `Quat Slerp(Quat to, float t)`
- `Quat SlerpUnclamped(Quat to, float t)`

**Vec3**
- `Vec3 MoveTowards(Vec3 to, float maxDistanceDelta)`

**LinearTransform**
- `void Translate(Vec3 trans)`

**Comment by Powback** [comment]
Vec2 implements these static members: 
```    Vec2 Vec2.down
    Vec2 Vec2.left
    Vec2 Vec2.negativeInfinity
    Vec2 Vec2.one
    Vec2 Vec2.positiveInfinity
    Vec2 Vec2.right
    Vec2 Vec2.up
    Vec2 Vec2.zero
```
Vec4 implements these: 
```
    Vec4 Vec4.negativeInfinity
    Vec4 Vec4.one
    Vec4 Vec4.positiveInfinity
    Vec4 Vec4.zero
```
Vec3 should match the same pattern, and not use methods for the shorthands.
