### ISSUE TITLE
[REQ] (Server|Client)PlayerEvent

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#346]
You need to have a proper FireEvent which supports events like fb::ServerPlayerEvent, fb::ClientPlayerEvent, and possibly more.

An example of an event that needs fb::ServerPlayerEvent is fb::ServerInputRestrictionEntity which might be useful in some vext mods.

**Comment by OrfeasZ** [comment]
Build 13472 introduces the following new types:

**CollisionEvent** (derives from `EntityEvent`)
- `ColisionEvent(int eventId, Vec3 position, Vec3 normal, float speed)`
- `ColisionEvent(string event, Vec3 position, Vec3 normal, float speed)`
- `position`
- `normal`
- `speed`

**DebrisSpawnEvent** (derives from `EntityEvent`)
- `DebrisSpawnEvent(int eventId, float min, float max, float current)`
- `DebrisSpawnEvent(string event, float min, float max, float current)`
- `min`
- `max`
- `current`

**FloatParameterEvent** (derives from `EntityEvent`)
- `FloatParameterEvent(int eventId, float parameter)`
- `FloatParameterEvent(string event, float parameter)`
- `parameter`

**IntParameterEvent** (derives from `EntityEvent`)
- `IntParameterEvent(int eventId, int parameter)`
- `IntParameterEvent(string event, int parameter)`
- `parameter`

**TransformParameterEvent** (derives from `EntityEvent`)
- `TransformParameterEvent(int eventId, LinearTransform transform)`
- `TransformParameterEvent(string event, LinearTransform transform)`
- `transform`

**ClientPlayerEvent** (derives from `EntityEvent`)
- `ClientPlayerEvent(int eventId, Player player)`
- `ClientPlayerEvent(string event, Player player)`
- `player`

**ClientDoublePlayerEvent** (derives from `ClientPlayerEvent`)
- `ClientDoublePlayerEvent(int eventId, Player player, Player extraPlayer)`
- `ClientDoublePlayerEvent(string event, Player player, Player extraPlayer)`
- `extraPlayer`

**ServerPlayerEvent** (derives from `EntityEvent`)
- `ServerPlayerEvent(int eventId, Player player, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, TeamId team)`
- `ServerPlayerEvent(string event, Player player, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, TeamId team)`
- `player`
- `sendToPlayerOnly`
- `sendToHostOnly`
- `sendToTeamOnly`
- `invertPlayerFilter`
- `invertTeamFilter`
- `team`

**ServerDoublePlayerEvent** (derives from `ServerPlayerEvent`)
- `ServerDoublePlayerEvent(int eventId, Player player, Player extraPlayer, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, TeamId team)`
- `ServerDoublePlayerEvent(string event, Player player, Player extraPlayer, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, TeamId team)`
- `extraPlayer`

The `ClientPlayerEvent`/`ClientDoublePlayerEvent` and `ServerPlayerEvent`/`ServerDoublePlayerEvent` types are only available on the client and the server respectively.

**Comment by Powback** [comment]
I've been unable to use the client/server player events.

Testmod:
```
OnChat(p_Player, p_Mask, p_Message)
	if p_Player == nil then
		return
	end

	local restriction = InputRestrictionEntityData()
    restriction.enabled = true
    restriction.overridePreviousInputRestriction = true
    restriction.applyRestrictionsToSpecificPlayer = true
  restriction.throttle = false
    restriction.strafe = false
    restriction.brake = false
    restriction.handBrake = false
    restriction.clutch = false
    restriction.yaw = false
    restriction.pitch = false
    restriction.roll = false
    restriction.fire = false
    restriction.fireCountermeasure = false
    restriction.altFire = false
    restriction.cycleRadioChannel = false
    restriction.selectMeleeWeapon = false
    restriction.zoom = false
    restriction.jump = false
    restriction.changeVehicle = false
    restriction.changeEntry = false
    restriction.changePose = false
    restriction.toggleParachute = false
    restriction.changeWeapon = false
    restriction.reload = false
    restriction.toggleCamera = false
    restriction.sprint = false
    restriction.scoreboardMenu = false
    restriction.mapZoom = false
    restriction.gearUp = false
    restriction.gearDown = false
    restriction.threeDimensionalMap = false
    restriction.giveOrder = false
    restriction.prone = false
    restriction.switchPrimaryInventory = false
    restriction.switchPrimaryWeapon = false
    restriction.grenadeLauncher = false
    restriction.staticGadget = false
    restriction.dynamicGadget1 = false
    restriction.dynamicGadget2 = false
    restriction.meleeAttack = false
    restriction.throwGrenade = false
    restriction.selectWeapon1 = false
    restriction.selectWeapon2 = false
    restriction.selectWeapon3 = false
    restriction.selectWeapon4 = false
    restriction.selectWeapon5 = false
    restriction.selectWeapon6 = false
    restriction.selectWeapon7 = false
    restriction.selectWeapon8 = false
    restriction.selectWeapon9 = false

    local objectEntity = EntityManager:CreateServerEntity(restriction, LinearTransform())
	objectEntity:Init(Realm.Realm_Server, true)

	objectEntity:FireEvent(ServerPlayerEvent("Activate", p_Player, false, true, false, false, false, TeamId.Team1))

end
```

I've also tried to change the different SendToXOnly parameters, but they all result in a server crash.

Calling FireEvent("Activate") works fine for all players.

**Comment by OrfeasZ** [comment]
Fixed in build `13769`. 

The following changes have been made to the `ServerPlayerEvent` and `ServerDoublePlayerEvent` type constructors:
- `ServerPlayerEvent(int eventId, Player player, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, bool forwardToSpectators, TeamId team)`
- `ServerPlayerEvent(string event, Player player, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, bool forwardToSpectators, TeamId team)`
- `ServerDoublePlayerEvent(int eventId, Player player, Player extraPlayer, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, bool forwardToSpectators, TeamId team)`
- `ServerDoublePlayerEvent(string event, Player player, Player extraPlayer, bool sendToPlayerOnly, sendToHostOnly, sendToTeamOnly, bool invertPlayerFilter, bool invertTeamFilter, bool forwardToSpectators, TeamId team)`

A new field has also been added to the `ServerPlayerEvent` type: `bool forwardToSpectators`.
