### ISSUE TITLE
[REQ] Events for ADS

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#348]
To enable / disable some effects for scopes, we need to have an even for when a soldier starts / stops ADS. There's no engine message for that.

**Comment by OrfeasZ** [comment]
Build `13775` adds an `isZooming` field to the client `SoldierWeaponsComponent` type, which you can use to check if a player is ADS or not. 

Example:
```lua
if player.soldier.weaponsComponent.isZooming then
    print('Player is aiming down sights.')
end
```
