### ISSUE TITLE
soldier:Kill(isSuicide) doesn't work for downed players

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#349]
``player.corpse:Kill(true)`` should make the soldier non revivable.

**Comment by kiwidoggie** [comment]
I have added `ServerPlayer:SetTimeToRespawn(float timeToRespawn)` in build 14120. Should force player back to menu if you set `player:SetTimeToRespawn(0.0)`

**Comment by FoolHen** [comment]
This crashes the server. Dumps: 
[dumps.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2626346/dumps.zip)

**Comment by kiwidoggie** [comment]
An attempt at a fix was pushed in build 14122, verify if the same issue occurs.

**Comment by FoolHen** [comment]
This doesn't seem to do anything. We need a way to kill a downed player. For example, if you get revived, stay alive for less than x minutes and get killed again we want to kill completely that player. Another example, we have a give up button that shows up when you get down and are revivable, we want to stop that corpse for being revivable if you press it.

[test mod](https://github.com/EmulatorNexus/VeniceUnleashed/files/2640637/test.zip)

**Comment by OrfeasZ** [comment]
Build `14129` removes `Player:SetTimeToRespawn(...)` and introduces `SoldierEntity:ForceDead()` for server-side `SoldierEntity` objects. Calling this while a player is in ManDown state should do what you're looking for. You can also configure ManDown behavior by modifying the `VeniceSoldierHealthModuleData` in `MpSoldier`. 

Give it a try and let me know if it works.

**Comment by FoolHen** [comment]
Works perfectly thanks.
