### ISSUE TITLE
Rcon event gibberish

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#35]
I really couldn't come up with a better title...

This is pretty self-explanatory, some rcon events have values that don't make sense:

```
[00:37:49] player.onKill Pavloo Pavloo ‹ø…Ût‹ƒ false
[00:37:49] OK
[00:37:50] player.onKill the_Uli the_Uli ‹ø…Ût‹ƒ false
[00:37:50] OK
```

`‹ø…Ût‹ƒ` should be the weapon or event (i.e. suicide). This happens when people are killed when a vehicle crashes, but now always and I haven't figured out how to reliably reproduce this bug.

There is another rcon event that has a similar issue (just the output is much longer) but I don't remember which one and have to wait for the bug to appear again as procon does not log the plaintext events and only the parsed version. I'll update this issue when I encounter it again.

**Comment by OrfeasZ** [comment]
As per Server R38 docs:

Suicide indication is unknown at this moment.
If the server kills the player (through admin.killPlayer), the result is unknown.

So I would assume this is perfectly normal behavior.
If not, I can definitely add additional checks to prevent invalid characters.

**Comment by derrod** [comment]
Suicide (using the menu):
`player.onKill Rodney Rodney Suicide false`
Suicide (using a nade):
`player.onKill Rodney Rodney M67 false`
Suicide using fall damage:
`player.onKill Rodney Rodney ‹ø…Ût‹ƒ false`

Some testing showed that this can be reliably achieved by killing oneself using falling damage.
Interestingly dying while crashing a vehicle doesn't trigger the onKill event. It seems the original occurence I observed might be caused by the players dying from the explosion outside of the vehicle, rather than its desctruction.

Killing someone via rcon doesn't trigger the player.onKill event (that might be a bug too)

Sadly I have no vanilla bf3 server to test this.

**Comment by derrod** [comment]
I was able to verify that a similar message is sent when dying through falling damage on a vanilla bf3 server.

`player.onKill Rodney Rodney ‰D$…Ût‹ƒ false`

Even though it seems weird the server behaves correctly. The only one to blame for this weirdness is therefore DICE.

**Comment by OrfeasZ** [comment]
We could of course correct this in order to display a proper cause of death (like 'World').
@kiwidoggie What do you think?

**Comment by kiwidoggie** [comment]
@OrfeasZ We should correct it.

**Comment by kiwidoggie** [comment]
If you check the damageType it is extremely out of bounds, invalid from the client. If it IS out of bounds (sometimes?) the weaponName will be correct, otherwise?

**Comment by kiwidoggie** [comment]
player.onSpawn also needs to be sanitized.

**Comment by OrfeasZ** [comment]
@kiwidoggie What's the progress on this?

**Comment by kiwidoggie** [comment]
Fixed in build 8313.
