### ISSUE TITLE
Reloading a mod with rcon causes a server crash

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#351]
Last update broke it. 
[dump.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2324337/dump.zip)

**Comment by ghost** [comment]
I think development would go much faster if you just let the git hub community help out... waited 4 years for this shit. Missed all the open beta's. Yall need to stop being protective about your code. This mod should of been dones 3 years ago.

**Comment by OrfeasZ** [comment]
@Raikem this seems to be related to your specific mod, as I can't reproduce locally.

**Comment by FoolHen** [comment]
This issue has reappeared, and it happens even with an empty mod.
[dump.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2849606/dump.zip)

**Comment by OrfeasZ** [comment]
I can't reproduce this locally but I'm hoping this is fixed in build `14509`. Give it a try and let me know.

**Comment by FoolHen** [comment]
That fixed it.
