### ISSUE TITLE
[REQ] rcon var to disable preround

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#352]
Since VU doesn't feature a progression system, there should be an option to disable preround entirely, much like game.disablepreround

**Comment by Powback** [comment]
Note:

This shouldn't be confused with setting minplayers to 0, as that *works*, but instead og disabling preround, it will instead start the round when a player joins.

This causes the level to restart when you join, causing the player to be switched to the opposite side.

There is a var called game.disablepreround available, but it seems stripped or deactivated.

**Comment by paulhobbel** [comment]
Implemented in `19963`

The [vu.DisablePreRound](https://docs.veniceunleashed.net/hosting/commands/#vudisablepreround) RCON variable can now be used for this
