### ISSUE TITLE
[Bug] Player doesnt properly disconnect from the server

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#354]
For some reason, we managed to reach a state where both kiwy and me joined the server and got disconnected again, but without the server registering the disconnect. We then couldnt reconnect anymore, and it still showed 2 people on the server:

https://i.imgur.com/GaY2Juu.png

Server was freshly started up. Does not always occur, only happend once after in 10 server restarts. (Where we always were able to connect properly)

**Comment by FoolHen** [comment]
Has happened to me a few times. Seems to be random, I couldn't find a way to reproduce.

**Comment by 3ti65** [comment]
Could be in connection with me upping the client and server timeouts?

**Comment by Powback** [comment]
This happens when the client disconnects without notifying the server. The server will eventually timeout the clients though.

**Comment by OrfeasZ** [comment]
Several additional checks have been added in build `13512` to more cleanly disconnect players when only part of the connection is lost.
