### ISSUE TITLE
[Bug] Fix Soldier:Damage Hook params

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#355]
`void Soldier:Damage(SoldierEntity soldier, ServerDamageInfo info, Player inflictor, Player assistant)`

Params inflictor and assistant are both spitting out some garbage, according to @kiwidoggie its a vanilla bug, where if you inflict damage to yourself it will have some weird stuff. However, even if someone else damages you, it will still not contain usable data.

-> For us it would be sufficient to have the hook params working if someone else damages a player, and to be able to simply detect the case when yourself or something random damage your player. (Like a cast that returns nil for example)

// Testmod will follow

**Comment by OrfeasZ** [comment]
This should be fixed in build `13507`. I'll leave this issue open while I'm also looking into other recent crashes.
