### ISSUE TITLE
[Bug] BroadcastLocal sometimes doesn't reach some clients

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#357]
[NetEventsParamsTest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2410259/NetEventsParamsTest.zip)

Type ``broadcast`` in chat multiple times, 1 out of 5 times or so it doesn't reach the client

**Comment by OrfeasZ** [comment]
Fixed in build `13721`.
