### ISSUE TITLE
[Req] Add setters to soldier ammo

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#358]
Similiar to the getters, would be cool to have setters as well, so one can set the ammo of players on the run. 

suggested functions for class SoldierEntity:

- [x] void SetCurrentPrimaryAmmo(int value) -- magazine capacity
- [x] void SetCurrentSecondaryAmmo(int value) -- overall ammo
- [x] void SetWeaponPrimaryAmmoByIndex(int index, int value) -- magazine capacity
- [x] void SetWeaponSecondaryAmmoByIndex(int index, int value) -- overall ammo

**Comment by OrfeasZ** [comment]
Added in build `13741`.

**Comment by 3ti65** [comment]
The functions dont seem to work: (in chronological order)

Client Primary / Secondary Get:
https://cdn.discordapp.com/attachments/187339455315574784/497162117603000320/unknown.png

Server Primary Get, Set, Get:
https://cdn.discordapp.com/attachments/187339455315574784/497162230622584863/unknown.png

Server Secondary Get, Set, Get:
https://cdn.discordapp.com/attachments/187339455315574784/497162329163825162/unknown.png

Client Primary / Secondary Get:
https://cdn.discordapp.com/attachments/187339455315574784/497162425033031690/unknown.png

2 observations:

1. Client doesnt get updated by server changes (probably same issue as health back then)
2. Server has a weird initial value for both primary and secondary ammo: -188788908

**Comment by 3ti65** [comment]
[AmmoSetTest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2444220/AmmoSetTest.zip)

Testmod ^^^

1. Spawn
2. Type in chat one of the following commands:

"ammoclient" -- gets primary ammo client
"ammoclient2" -- gets secondary ammo client 

"ammoserver" -- gets primary ammo server
"ammoserver2" -- gets secondary ammo server

"ammoserver 60" -- gets sets gets the primary ammo on server (to whatever number specified)
"ammoserver2 600" -- gets sets gets the secondary ammo on server (to whatever number specified)

3. See that its all fucked up
4. Don't kill yourself
5. Fix it
6. ??
7. Profit

**Comment by OrfeasZ** [comment]
Fixed in build `13829`.
