### ISSUE TITLE
[Req] Additional PlayerManager functions

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#359]
Would be nice to have the following functions added to the PlayerManager: 

Overloads for GetPlayers():

- [ ] Player[] GetPlayers(teamID) -- returns all players with the given teamID
- [ ] Player[] GetPlayers(teamID, squadID) -- returns all players with the given teamID and squadID

New function:

- [ ] Player GetSquadleader(teamID, squadID)

**Comment by 3ti65** [comment]
Might be worth thinking about merging TeamSquadManager into the PlayerManager as well, since it currently only contains 2 functions, which also kinda fit the context of the PlayerManager:

Current TeamSquadManager functions:

int GetSquadPlayerCount(TeamId team, SquadId squad)
int GetTeamPlayerCount(TeamId team)

Similar PlayerManager function:

int GetPlayerCount()

Merge into new PlayerManager overloads:

int GetPlayerCount()
int GetPlayerCount(TeamId team)
int GetPlayerCount(TeamId team, SquadId squad)

And then remove TeamSquadManager for being obsolete.

**Comment by kiwidoggie** [comment]
Build 14026 adds `PlayerManager:GetPlayersByTeam(TeamId team)` and `PlayerManager:GetPlayersBySquad(TeamId team, SquadId squad)` on both Client and Server

**Comment by kiwidoggie** [comment]
Build 14027 adds on the server `Player PlayerManager:GetSquadLeader(TeamId team, SquadId squad)`
