### ISSUE TITLE
Player statistics are not reset on map change via rcon

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#36]
Title says it all.
When changing the map via rcon command player scores are not reset.

Not sure if it only happens when changeing the map or also restarting the round.
Ending the round properly (i.e. one team wins) seems to properly reset the player stats.

**Comment by OrfeasZ** [comment]
The next map and round restart commands are both calling built-in functions, so I assumed this is normal behavior.
If someone can confirm that scores indeed reset on map change I'd be happy to implement such a feature.

**Comment by derrod** [comment]
Testing on a vanilla bf3 has shown that this is indeed intended behaviour. It seemed werid to me as no other game I know of does this, including BFBC2.
