### ISSUE TITLE
json.encode should automatically tostring objects

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#366]
json.encode currently returns nil if it fails to encode a variable, it should either throw an error, or call tostring on variables that can't be encoded.

**Comment by OrfeasZ** [comment]
When `json.encode` encounters an error, it will return `nil` along with the error message. You can read it like this: 
```lua
local jsonStr, err = json.encode(x)
```

Regardless, build `14061` introduces JSON encoding support for VEXT primitives. That means that you can `json.encode()` primitives as-is, or a table that has them as members. The following primitives are supported:
- `Vec2`
- `Vec3`
- `Vec4`
- `Quat`
- `LinearTransform`
- `QuatTransform`
- `AxisAlignedBox`
- `Guid`
