### ISSUE TITLE
EntityBusPeer entities causes a crash when accessed through vext.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#367]
Xp3_Shield, http://powback.com/u/b740aabbc9b5548dc1c8e66108e33862.png

Demonstration of crash: http://powback.com/u/c72a544948a84accece79b212ec71eba.mp4
If it never gets unloaded: http://powback.com/u/7b7a8794a735cb8df1aa57c727acd14a.mp4

The crash above happens at mod-reload, but it's generally happening regardless of "touch".
In previous versions of MapEditor, it would crash whenever I tried to move an "unspawned" object, but the :Is(type) check allows me to skip the entity if it's of type EntityBusPeer.

Interesting notes:
When spawned, the object will be a DynamicModelEntity, after it's unspawned it will become a EntityBusPeer. 

This function is supposed to loop through the entity typeinfo and return true if they are of type SpatialEntity. This is replaced with :Is(type), which works flawlessly. 

```lua
    function Util:isSpatial(ti)
        print("called")
        print(tostring(ti))
        print("name: " .. ti.name)
        if(ti == nil) then
            print("TypeInfo is nil. This shouldn't happen.")
            return false
        end
        if(ti.name == "SpatialEntity") then
            return true
        elseif ti.name == "Entity" or ti.name == "EntityBusPeer" then
            print("entity bus peer")
            return false
        elseif(ti.super == nil) then
            return false
        else
            return self:isSpatial(ti.super)
        end
    end
```
Running the unspawned DynamicModelEntity through this function results in a crash before "called" is ever printed.

If we remove the "EntityBusPeer" check however, "called" will be printed, and the process will be stuck in an infinite loop as expected.

```lua
   function Util:isSpatial(ti)
        print("called")
        print(tostring(ti))
        print("name: " .. ti.name)
        if(ti == nil) then
            print("TypeInfo is nil. This shouldn't happen.")
            return false
        end
        if(ti.name == "SpatialEntity") then
            return true
        elseif ti.name == "Entity" then
            print("entity bus peer")
            return false
        elseif(ti.super == nil) then
            return false
        else
            return self:isSpatial(ti.super)
        end
    end
```

I found this interesting since the game will crash before the first print, which I haven't experienced before.

It's probably possible to clear the reference since we're able to check it's type using :Is without crashing, but I figured it would be nice to have this issue documented anyway.

Reproduction:
Latest MapEditor, 
XP3_Shield ConquestLarge0 2
Spawn Props/BuildingProps/CardboardBox_01/CardboardBox_01_banger
Move camera away until entity despawns
Reload extension.

Alternatively you can modify https://github.com/Powback/MapEditor/blob/History_Implementation/ext/Client/ClientEntityManager.lua#L84 and do whatever to the entity there.

**Comment by Powback** [comment]
The issue is "solved" by checking the type inheritance by using :Is("whatever"). 

I'll rename the issue to something more fitting. 

Feel free to remove this issue from the 1.0 milestone.

**Comment by OrfeasZ** [comment]
This was fixed in one of the previous builds.
