### ISSUE TITLE
[Bug] Some instances can't be caught on partitionLoaded

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#369]
Some instances can't be caught with a guid check, for example in this test mod OnGroundStateData (18B95C2B-5D12-4D1F-BA8C-0266A5240C04) is never found while InAirStateData (584D7B54-FBFE-4755-8AD4-89065EEB45C3) is. This was working fine in older vu versions some time ago.

[test.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2543358/test.zip)

**Comment by 3ti65** [comment]
should probably be 1.0

**Comment by Powback** [comment]
Fool, this is your code

```
		if instance.instanceGuid == m_CharacterPhysicsData_Guid then
			print("found m_CharacterPhysicsData_Guid")
		end
```

Notice how you're looking for the CharacterPhysicsData instead of OnGroundStateData

Correcting it to
```

		if instance.instanceGuid == m_OnGroundStateData_Guid then
			print("found m_OnGroundStateData_Guid")
		end
```
yields the correct response.

~invalid

**Comment by FoolHen** [comment]
Yeah my bad. I had this happen with other instances and I don't think I made typos on all :P. If I find an actual case I'll update this issue.
