### ISSUE TITLE
serverInfo mapname format incorrect

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#37]
Currently `serverInfo` returns this:
`OK Test Server #003 0 68 ConquestLarge0 Levels/MP_001/MP_001 0 1 2 0 0 400 AcceptingPlayers true false false 0 0 IP:Port  false EU  NL false`
The mapname has to be just `MP_001` instead of `Levels/MP_001/MP_001` (like on the onLevelLoaded event).

**Comment by OrfeasZ** [comment]
This was already fixed in build 7074, it just hasn't been pushed live yet.
