### ISSUE TITLE
[REQ] Make max players per squad editable

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#370]
Max player count per squad is hardcoded to 6 right now:

https://cdn.discordapp.com/attachments/337652669797629962/509018725412896778/unknown.png

We need this to be editable so we can fit more people in a squad. (At least 8)

**Comment by OrfeasZ** [comment]
Build `14105` adds a new rcon variable `vu.SquadSize <size>` (defaults to 4) that can be used to customize the squad size. Keep in mind that changing this mid-round will not have any effect until the next round starts.
