### ISSUE TITLE
[REQ] Prevent player from automatically joining squads when joining US team

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#371]
When a player joins the US team, he automatically joins squad 1, even when forcesquad is set to false in the server settings.

Steps to reproduce:

1. Join a server with RM
2. Be on RU side -> switch teams
3. See that you're in squad 1
4. Switch back to RU -> you're not in a squad

**Comment by OrfeasZ** [comment]
Build `14101` adds a new hook `SquadId Player:FindBestSquad(Player player)` that can be used to override the default squad selection behavior. Returning `SquadId.SquadNone` will prevent the player from being placed in a squad.

**Comment by FoolHen** [comment]
The callback is never fired. Please reopen.

**Comment by OrfeasZ** [comment]
As discussed, this is client-side behavior that's bound to how the UI system works. I'm not sure if there's something I can do to make this configurable.

**Comment by FlashHit** [comment]
So `Player:FindBestSquad` isn't working right?

I tried it like this when joining a server but it doesn't get called:
`Hooks:Install('Player:FindBestSquad', 1, function(hook, player)`
	`print("hello findbestsquad")`
        `return SquadId.SquadNone`
`end)`


atm in vu:
1. Join server -> US team & Alpha squad
2. swap to RU -> no squad
3. swap back to US -> Alpha squad
4. leave squad
5. swap to RU -> no squad
6. swap back to US -> no squad

Btw on console you were able to choose if you want to join a squad or not.
![ps3](https://user-images.githubusercontent.com/56718716/92308869-281d3f80-efa1-11ea-95a1-f1c96fb703d2.jpg)

**Comment by OrfeasZ** [comment]
This is client-side behavior which for some reason forces your player to join a squad if you're in Team1. Not sure if there's anything I can do about it.

**Comment by FlashHit** [comment]
while it does nothing wouldn't it be better to remove the hook from the docs? Wasn't sure what I did wrong till I found this.

**Comment by FlashHit** [comment]
There is something called: `loadPlayer_joinSquad` which is probably exactly what we need to change, to prevent the player from automatically joining a squad. 

If you leave a squad this var will change to false. If you then leave the server and join any server (doesn’t have to be the same) then it won't put you in a squad.

So we need something like `ClientUtils:AutoJoinSquad(bool)` to change that var.

**Comment by 3ti65** [comment]
@OrfeasZ will take another look

**Comment by FlashHit** [comment]
Implemented in `19412`.
