### ISSUE TITLE
[REQ] Make BF3 Battle Royal Mod

### ISSUE THREAD

**Issue by angelroom** [VeniceUnleashed/VeniceUnleashed#372]
We Want BF3 Battle Royal Mod Plz

**Comment by OrfeasZ** [comment]
This tracker is for tracking issues related to VU and the functionality it offers, not to request mods. If you want a BR mod you can make one yourself once VU is released.

**Comment by angelroom** [comment]
im sorry

**Comment by fxtressia** [comment]
Some update tho.

https://youtu.be/O1yw5zJxUKE
