### ISSUE TITLE
[Bug] Player.guid return nothing

### ISSUE THREAD

**Issue by judemvm** [VeniceUnleashed/VeniceUnleashed#373]
Player (Server Class)
Properties: guid - return nothing

**Comment by OrfeasZ** [comment]
Build `14144` should fix this issue. It also changes the return type of the `guid` field from `string` to `Guid` and updates the `PlayerManager:GetPlayerByGUID(guid)` function to accept a `Guid` instead of a `string`.

Give it a try and let me know if it works.

**Comment by judemvm** [comment]
It works!
Thanks for fixing it
