### ISSUE TITLE
RigidBody:AddForce

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#374]
As we're moving more towards scripted entities, #339 has been great help. Unfortunately setting velocity is widely considered a bad move, as it will override any initial velocity and direction.

I propose that we implement the AddFoce method to RigidBody entities.

```
AddForce(Vec3 force, ForceType force)
AddForce(Vec3 force, ForceType force, Vec3 Position ?)
```

**Comment by OrfeasZ** [comment]
Build `14150` adds the following methods to `PhysicsEntityBase`:
- `void ApplyForce(float dt, Vec3 force)`
- `void ApplyForce(float dt, Vec3 force, Vec3 position)`
- `void ApplyTorque(float dt, Vec3 torque)`

Keep in mind that these won't work for all entity types (eg. `CharacterPhysicsEntity`).
