### ISSUE TITLE
"Select Soldier" box too small

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#382]
The "select soldier" button only covers the icon, it should cover the entire card.

**Comment by 3ti65** [comment]
I think thats per design. But double click should have the same functionality as the button in the middle. And also make that button a big bigger.

**Comment by OrfeasZ** [comment]
The plan is to completely remove the concept of the soldier eventually, since it doesn't offer anything when we're not tracking stats. In the meantime I'll make the entire card clickable.

**Comment by OrfeasZ** [comment]
Starting with build `14364` the entire soldier box is clickable.
