### ISSUE TITLE
Different casing on identifier variables

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#385]
```
InstanceID
TeamId
AssetId
ProjectId
SquadId
TrackEventID
TrackPropertyID
ViewPointID
```

VEXT should use the same identifier casing as Frostbite.
Occurences:
`Id: 94`
`ID: 18`

Conclusion: 
Please rename all identifier variables ending with ID to Id, excluding GUID and SID.

**Comment by 3ti65** [comment]
yeah man wtf xD

**Comment by OrfeasZ** [comment]
Most of the examples you provided are from Frostbite classes using inconsistent casing. I'm not sure if I want to change that.

**Comment by Powback** [comment]
@OrfeasZ Yeah that's right, it was just to demonstrate what I mean. I don't expect FB classes to change, but I'd like VEXT to be consistent with the usage.

**Comment by OrfeasZ** [comment]
Build `14854` changes the casing in the following fields:

Client `Player`:
- `teamID` -> `teamId`
- `squadID` -> `squadId`

Server `Player`:
- `onlineID` -> `onlineId`
- `teamID` -> `teamId`
- `squadID` -> `squadId`

`Entity`:
- `uniqueID` -> `uniqueId`
- `instanceID` -> `instanceId`

`WeaponFiring`:
- `instanceID` -> `instanceId`

Client `PlayerManager`:
- `GetPlayerByID` -> `GetPlayerById`

Server `PlayerManager`:
- `GetPlayerByID` -> `GetPlayerById`
- `GetPlayerByOnlineID` -> `GetPlayerByOnlineId`

`SQL`:
- `LastInsertID` -> `LastInsertId`
