### ISSUE TITLE
game keep crash when launch ! 

### ISSUE THREAD

**Issue by tarikz-h** [VeniceUnleashed/VeniceUnleashed#39]
game keep crash when launch !! "battlefield 3 not responding"
i cant play at all 
but i can play normaly in battlelog
how can i fix it ?! :|

**Comment by OrfeasZ** [comment]
What kind of crashes are you getting?
Are you receiving some kind of error message or is just the game halting with the "x has stopped working" massage?.
Also, make sure you have the Visual C++ 2012 Redistributable package installed on your computer.
You can find it via google.

**Comment by tarikz-h** [comment]
http://im63.gulfup.com/lsQ588.png
this error i get it means  "battlefield 3 not responding" 
and i have the Visual C++ 2012 Redistributable package installed

**Comment by OrfeasZ** [comment]
I'll be introducing crash reporting capabilities in a future build.
Until then I'm afraid there's not much I can do to help you.

**Comment by OrfeasZ** [comment]
@6arek212 The latest build (7106) includes crash reporting.
Update and launch your client, let it crash, and the send the produced report using the reporting dialog that will be presented to you.

**Comment by tarikz-h** [comment]
i updated my client but i dont see the send produced report

**Comment by tarikz-h** [comment]
help ! I still can't play the game !!

**Comment by OrfeasZ** [comment]
There appears to be an issue with our crash reporting code where not all threads are being 'watched' for exceptions.
The upcoming update should fix that.

**Comment by tarikz-h** [comment]
when is the next update will be ?!

**Comment by OrfeasZ** [comment]
When it's done.

**Comment by tarikz-h** [comment]
when launch the game it makes a note folder named " WebUI_debug " 
in this folder : 
The key "target-densitydpi" is not supported.
    at / (line 4)

Warning: No route matches path "". Make sure you have <Route path=""> somewhere in your routes
    at /app/bundle.js (line 6)

after it crash the folder disappear 
is this normal ?!

**Comment by OrfeasZ** [comment]
Yes, that's completely normal.

**Comment by tarikz-h** [comment]
here's the new update and still crashing !!?!

**Comment by lybxlpsv** [comment]
happened too on my Intel HD Graphics 4000 at random. mostly happened when you change from windowed to fullscreen or fullscreen to windowed before bf3 finished loading menus (or probably this is different issue(?) or because of me playing at very low resolution 800x450(?))
