### ISSUE TITLE
[Req] Allow access to first person camera

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#393]
We need a way to modify its transform. Spawning a new camera object doesn't do the job as it's third person.

**Comment by Powback** [comment]
Alternatively, this can *probably* be accomplished if we can get access to GameEntity.components
I'm not sure how that *actually* works in-engine though.

**Comment by FoolHen** [comment]
For reference, @kiwidoggie added ``Client:UpdateClientGameViewTransform (hook, linearTransform)`` hook but it seems like it doesn't do the job. Also he added ``Player.cameraTransform`` which is currently broken (returns stuff like ``(0.000000, 75563100792564893992720827154432.000000, 1143331116149901674953048064.000000) (17591643360660901855232.000000, 0.000000, 0.000000) (0.000000, 0.000000, 0.000000) (0.000000, 0.000000, 0.000000)``.

**Comment by kiwidoggie** [comment]
This has been fixed in build 15962 (pending deployment)

**Comment by FlashHit** [comment]
Yea the `Client:UpdateClientGameViewTransform (hook, linearTransform)` hook is broken I guess.

**Comment by FlashHit** [comment]
Already possible to access first person camera.
