### ISSUE TITLE
[REQ] Arguments to specify BF3 install directory 

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#396]
It seems like the BF3 install directory under WINE isn't detected properly, causing VU launch to fail.
To bypass this you can install VU into the BF3 install directory.

A launch-argument overriding the BF3 install directory would solve this issue.

**Comment by OrfeasZ** [comment]
Build `14487` allows you to explicitly specify the location of your BF3 installation using the `-gamepath` command line argument.

Example: `vu.com -gamepath C:\Games\Battlefield 3`
