### ISSUE TITLE
[Crash][14390] Client disconnect and server crash at grenade kill

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#398]
[clientdisconnect_server_crash_14390.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2770496/clientdisconnect_server_crash_14390.zip)

**Comment by OrfeasZ** [comment]
This seems like a case of using a `Player` instance for a player that doesn't exist anymore. The crash specifically is while accessing `player.name`, but that might not be accurate because of optimizations.
