### ISSUE TITLE
Game crashes when resizing window (v14441)

### ISSUE THREAD

**Issue by Frankity** [VeniceUnleashed/VeniceUnleashed#399]
Attached files, those come from resizing the window.

[dumps.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2776210/dumps.zip)

**Comment by Powback** [comment]
I have been unable to replicate this issue, and I resize the window quite a lot while the WebUI is under heavy stress.

**Comment by OrfeasZ** [comment]
I've been unable to replicate this too. @Frankity does this still happen for you with latest?

**Comment by Frankity** [comment]
Fixed in build 14741, confirmed.
