### ISSUE TITLE
[Crash][14445] Unknown server crash

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#402]
Dont know what its related to, would be nice to get a hint

Dump:

[Unknown server crash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2776758/Unknown.server.crash.zip)

**Comment by OrfeasZ** [comment]
Looks like trying to access the `.name` field of a bad player object during Engine:Update.
