### ISSUE TITLE
[Req] Enhance the SoldierEntity with Getters / Setters for unlocks

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#414]
Right now it's impossible to know what unlocks a soldier is equipped with. That goes from scope attachments to bodyparts etc. This is crucial information for realitymod, especially for weapon attachments.

My suggestion is to enhance both SoldierEntities on Client and Server, to feature an array of equipped unlocks, or at least the names of them.

Since unlocks can be set on the run, it would be nice to have a setter as well, server only so its consistant with the weapon ammo stuff. This would allow for very cool mods, for example changing the weapon attachments on the run, changing soldier looks on the run etc.

**Comment by OrfeasZ** [comment]
You can already modify weapons and such on the fly using the `soldier:ApplyCustomization(CustomizeSoldierData data)` function. I'm trying to see if there's a good way to add support for querying what the current customizations are.

**Comment by OrfeasZ** [comment]
Build `15528` introduces support for fetching unlocks and modification data for soldier weapons, on both the server and the client. More specifically, the following changes have been made:

Server `SoldierEntity` type has two new methods:
- `WeaponModifier GetCurrentWeaponModifier()`
- `WeaponModifier GetWeaponModifierByIndex(int index)`

Client `SoldierWeapon` type has one new property:
- `WeaponModifier weaponModifier`

The shared `WeaponModifier` type has been been extended and the following fields and methods have been added:
- `WeaponMiscModifierSettings weaponMiscModifierSettings`
- `WeaponFiringDataModifier weaponFiringDataModifier`
- `WeaponFiringEffectsModifier weaponFiringEffectsModifier`
- `WeaponSoundModifier weaponSoundModifier`
- `WeaponShotModifier weaponShotModifier`
- `WeaponProjectileModifier weaponProjectileModifier`
- `WeaponAimingSimulationModifier weaponAimingSimulationModifier`
- `WeaponAnimationConfigurationModifier weaponAnimationConfigurationModifier`
- `WeaponAnimTypeModifier weaponAnimTypeModifier`
- `WeaponMagazineModifier weaponMagazineModifier`
- `WeaponZoomModifier weaponZoomModifier`
- `int GetUnlockCount()`
- `UnlockAssetBase GetUnlockAtIndex(int index)`

All of the `WeaponModifier` properties are settable, but it's uncertain if changing them will have any in-game effects. Keep in mind that they might also be `nil`.
