### ISSUE TITLE
[Bug] doesnt reconnect after timeout, stuck in 'reconnecting' loop

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#421]

**Comment by Powback** [comment]
Elaborate please.

**Comment by 3ti65** [comment]
1. Login to VU, disconnect internet.
2. It will try to reconnect to Zeus a couple of times automatically, but fail
3. Replug the internet, press reconnect.
4. Be stuck in the 'reconnecting' view, restart fixes it.

**Comment by 3ti65** [comment]
its actually stuck at "LOGGING IN"

![image](https://user-images.githubusercontent.com/12377272/54721935-a5fa4a80-4b63-11e9-8355-da9004d68ab1.png)

**Comment by OrfeasZ** [comment]
Fixed in build `14818`.
