### ISSUE TITLE
GunSway:UpdateRecoil called for each player

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#423]
Every time a player shoots, the GunSway:UpdateRecoil event is called. This makes the event useless.

Worst case scenario: http://powback.com/u/35455b74dc4a7f5ded0fc94aa3a32b75.mp4
testmod: http://powback.com/u/12cb149bf34ee0706d15e7d8e915b8a5.7z

Maybe there should be a player filter?

**Comment by OrfeasZ** [comment]
This is intended behavior. I'll see if I can cook up a mod that does what you want.

**Comment by OrfeasZ** [comment]
Build `14768` updates the `GunSway:Update` and `GunSway:UpdateRecoil` to include another argument:

- `GunSway:Update(GunSway gunSway, Entity soldierWeapon, float dt)`
- `GunSway:UpdateRecoil(GunSway gunSway, Entity soldierWeapon, float dt)`

You should now be able to achieve what you want with this mod:

```lua
Events:Subscribe('GunSway:UpdateRecoil', function(gunSway, soldierWeapon, dt)
    -- Only update if we have a weapon and we're firing.
    if soldierWeapon == nil or not gunSway.isFiring then
        return
    end

    -- Get the aim assist handler.
    local weapon = SoldierWeapon(soldierWeapon)
    local simulation = weapon.aimingSimulation
    local assist = simulation.aimAssist

    -- Get the gun sway recoil deviation.
    local deviation = gunSway.currentRecoilDeviation

    -- Update the soldier's aim and reset the recoil.
    assist.pitch = assist.pitch - deviation.pitch
    assist.yaw = assist.yaw - deviation.yaw
    
    deviation.pitch = 0
    deviation.yaw = 0
end)
```

**Comment by FoolHen** [comment]
Seems like now this event is only called for the local player, so we can't modify other players' weapons on each client as you recommended.

**Comment by FoolHen** [comment]
Also, ``gunSway.isFiring`` sometimes still returns true after stopping firing (not just once, but every event call and even after switching weapons and switching back).

**Comment by FoolHen** [comment]
Correction: when there is another player connected, GunSway:UpdateRecoil is called for both local player's weapon and for the other client's, but for the latter the ``soldierWeapon`` argument is nil.
https://i.imgur.com/olTgNJr.png
