### ISSUE TITLE
[Crash] Random client crashes 

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#424]
Omar kept crashing silently and with error messages in the playtest today. Seemed to be isolated to him. He got two dumps out of it:

[Dumps.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/3031473/Dumps.zip)

Rest was silent. Version 14672

**Comment by OrfeasZ** [comment]
The best guess I can make about these crashes is that something in some ASUS On-Screen Display software is likely causing breakage (`C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\SS2OSD.dll`).

I would try turning it off (or uninstalling it) and seeing if that fixes the issue.

**Comment by 3ti65** [comment]
Think this has been resolved by turning that software off.
