### ISSUE TITLE
Non-referenced datacontainer entries in an array are returned as an invalid DataContainer

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#425]
Like this one: https://github.com/Powback/Venice-EBX/blob/071473993867cd2297dc662517c61edaff51e8fe/Levels/SP_Paris/SP_Paris.txt#L711

```
print(field.typeInfo.elementType.name) //DataContainer
print(instance[FirstToLower(field.name)]:get(i) == nil) //false
print(instance[FirstToLower(field.name)]:get(i)) // DataContainer (): 0x00000000
print(instance[FirstToLower(field.name)].instanceGuid) //nil
```

**Comment by Powback** [comment]
Actually, this may also be me just entering instances that aren't been fully loaded yet. so their array isn't loaded completely or something?

**Comment by OrfeasZ** [comment]
This should be fixed in build `14711`. These will now properly return `nil`.

**Comment by OrfeasZ** [comment]
Re-opening this because after some further investigation it looks like these should not be `nil` and are probably instead late-loaded or late-resolved.

**Comment by OrfeasZ** [comment]
This has been properly fixed in build `14741`. There are some cases where arrays **can** contain `nil` references, such as in `HavokAsset` instances, which will now be handled appropriately, along with cases where lazy-loaded instances are in an array, such as in `LevelReportingAsset` instances.
