### ISSUE TITLE
[Bug] Mouse focus not working correctly in WebUI

### ISSUE THREAD

**Issue by paulhobbel** [VeniceUnleashed/VeniceUnleashed#426]
It seems like there are some mouse focus issues on the WebUI, where the WebUI is unaware of the current mouse position or something.
I am yet to figure out when focus stops working, however I made a simple test mod to test it.
[focustest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/3051534/focustest.zip)

I also included a scrollable container because it looks like issue #319 is related to this bug.

**Comment by Powback** [comment]
I can confirm that this is an issue that I've been experiencing in MapEditor. Seems to happen randomly.

**Comment by paulhobbel** [comment]
Apparently you can trigger this bug by opening the debugger. Without the debugger it still get's triggered randomly

**Comment by OrfeasZ** [comment]
@paulhobbel I've been unable to reproduce this issue. When the dev tools are on this is normal behavior if you have the screencasting feature enabled (as it simulates a touch devices which has no hover events, and it also changing how scrolling works a bit). You can disable it by pressing the screencast button: 

![](https://i.nofate.me/PtELphWXjWEs.png)

Other than that it doesn't seem to happen randomly at all for me. During normal usage it all works as it should. Regardless, I've increased the scroll speed a bit in build `14744` and changed a couple of things to improve stability, though I don't think they will do much (if anything at all). 

Another thing to keep in mind is that the game can at any point take mouse control away from the player. A good idea is to keep calling `WebUI.Call('EnableKeyboard')` and / or `WebUI.Call('EnableMouse')` every half a second or so and then when you want to return control back to the game calling `WebUI.Call('ResetKeyboard')` and / or `WebUI.Call('ResetMouse')`. The `ResetX` calls are currently only available on the JS (WebUI) side but they will soon be added to VEXT too (see #429).

**Comment by OrfeasZ** [comment]
I completely disabled the screencasting feature in build `14744`. This should avoid further confusion.

**Comment by Powback** [comment]
Happens consistently in mapeditor

**Comment by paulhobbel** [comment]
It happens without having devtools open

**Comment by FoolHen** [comment]
Easy to repro on maped: Join a server and try to select any object on the hierarchy right after joining. If you click on the name or icon you won't be able to select it, as they are eating/blocking the click event. If you otherwise click on the blank part of the row it will select without an issue. After some seconds (10 or so) it will start working normally.

CEF update might fix this so, I'll test again when it's implemented.

**Comment by FlashHit** [comment]
@FoolHen is this fixed?

**Comment by FoolHen** [comment]
I think it got fixed, I haven't noticed it for some time
