### ISSUE TITLE
[Bug] Crash when rightclicking with chrome debug open

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#427]
Happens ingame and in the main menu.
[dump](https://github.com/EmulatorNexus/VeniceUnleashed/files/3056024/ba2c8cc8-823b-4d92-81e5-505fbb768b6e.zip)

**Comment by FoolHen** [comment]
Additionally, if you double click with the debugger open the webui zooms in, not gamebreaking but really annoying as you cant zoom out doubleclicking again and you have to restart the client.

**Comment by OrfeasZ** [comment]
This only happens when screencasting is enabled. Build `14744` removes screencasting from the devtools. See #426 for more details.
