### ISSUE TITLE
[Crash][RM] Spawning in on XP1_001 crashes

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#438]
Repro:

1. Latest RM dev branch
2. Latest VU
3. Map: XP1_001 ConquestAssaultLarge0 2
4. Spawn in

**Comment by 3ti65** [comment]
Doesnt crash in latest RM anymore, at least for Powback, gonna verify.

**Comment by kiwidoggie** [comment]
Using latest dev branch, loads in fine. Closing issue.
