### ISSUE TITLE
WebUI drag and drop and text selection doesn't work

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#439]

**Comment by paulhobbel** [comment]
Drag and drop is actually working fine, not sure about text selection though

**Comment by OrfeasZ** [comment]
It doesn't seem to work in all cases. You can try it by going to the leaflet.js homepage and trying to move the map.

**Comment by paulhobbel** [comment]
Could it be a focus issue?

**Comment by OrfeasZ** [comment]
This has been fixed in build `14893`.

**Comment by OrfeasZ** [comment]
And no, it wasn't a focus issue 😅

**Comment by paulhobbel** [comment]
What was the issue?

**Comment by OrfeasZ** [comment]
Something in the way mouse events were handled internally.
