### ISSUE TITLE
Cloning a SoldierWeaponUnlockAsset breaks original instance

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#440]
Might be because its ``weapon`` field is lazyloaded. If you clone it and then spawn a soldier with this instance (not the clone) you dont have any weapons. 

[Test mod](https://github.com/EmulatorNexus/VeniceUnleashed/files/3169145/clonetest.zip). If you comment line 54 it works just fine, as it doesnt clone the nade ``SoldierWeaponUnlockAsset``.

Might be related to #434 
Edited, it doesnt crash but spawns you without weapons.

**Comment by FoolHen** [comment]
Aso, the testmod is a modified version of spawn-soldier mod that spawns you with a nade. Type ``spawn`` to spawn.

**Comment by Powback** [comment]
So cloned instances don't keep their lazy-loaded references?

**Comment by FoolHen** [comment]
Fixed with latest dev build 💃
