### ISSUE TITLE
[Bug] Incorrect mouse button when disabling and reenabling mouse.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#442]
In mapeditor pressing righclick disables the mouse, and releasing it enables it back. ``mousemove`` event will still think that right click is pressed (``event.which == 3``) after releasing it until you alt tab.
You can use mapeditor's Hillary_Step branch as a testmod.

**Comment by OrfeasZ** [comment]
This should be fixed in build `14947`.

**Comment by FoolHen** [comment]
This is happening again. Also happens with ``event.buttons`` which is now the preferred way to get mouse key (``.which`` got deprecated).

**Comment by Powback** [comment]
[mousebuttonbug.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4540108/mousebuttonbug.zip)

**Comment by OrfeasZ** [comment]
This appears to be a bug with windows / directinput. Build `16668` makes it so mouseup events are fired for any buttons that were being pressed when the mouse input was disabled. Unfortunately that's the best I can provide for now.
