### ISSUE TITLE
[Crash][RM] Client crashes when selecting the medic bag on shield

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#444]
Run RM in ``XP3_Shield ConquestLarge0 2``

[Dump](https://github.com/EmulatorNexus/VeniceUnleashed/files/3373850/c4618356-81b1-4d3a-b9d8-0e2e16ce4e05.zip)

**Comment by OrfeasZ** [comment]
This happens for me when selecting the paddles, not the bag. Regardless, the crash seems to be because of a bad pointer to audio data in the weapon's data. More specifically, it looks like `FiringFunctionData.sound` points to garbage.

**Comment by FoolHen** [comment]
So making the defib's FiringFunctionData writable instead of cloning+replacing fixes the crash even though we weren't touching ``FiringFunctionData.sound`` or any other sound related to the defib. Cloning and replacing it had been working for a long time before this started to happen, and we haven't touched the defib recently so it might have happened because of a new VU update. Might be the new cloning implementation, but I think this started happening before the new cloning was implemented.
