### ISSUE TITLE
Silent crash when registering a damage callback on an entity

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#445]
``MP_Subway ConquestLarge0 2``

Mods: 
[BlueprintManager.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/3383142/BlueprintManager.zip)
[BoxGame.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/3383143/BoxGame.zip)

Join the server, client silently crashes when the level is loaded.

**Comment by FoolHen** [comment]
This happens because of the callback function, if you set the function inside RegisterCollisionCallback (``RegisterCollisionCallback(function() print("hi") end)``) it works just fine. Am I not setting the callback function correctly?

**Comment by Powback** [comment]
I believe you're not registering the callback correctly. 
I believe it's supposed to be
```
entity:RegisterDamageCallback(self.functionName)
```

Notice the `self.` you're missing.

**Comment by OrfeasZ** [comment]
@Powback the point of this issue is to investigate the silent crash, not bad usage.

**Comment by Powback** [comment]
@OrfeasZ I see, still @Raikem was wondering if he's using the function properly.

**Comment by OrfeasZ** [comment]
These follow the same callback registration pattern as all other callback registrations. If you want to use an object bound function you need to specify that object first and then the function. So in the example you gave it would have to be something like:

```lua
entity:RegisterDamageCallback(self, self.functionName)
```

**Comment by FoolHen** [comment]
The crash was because of me registering the callback incorrectly, if I register it properly it works just fine. Close the issue if you want, although the game shouldn't crash because of that I guess.

**Comment by FlashHit** [comment]
The silent crash seems to be fixed. It throws an error instead of a silent crash. **BUT the error doesn't show where it is in the code**:
```
[2021-08-04 02:44:50+02:00] [error] [VeniceEXT] [boxgame] Error: attempt to call a nil value
stack traceback:
[2021-08-04 02:44:50+02:00] [error] [VeniceEXT] [boxgame] Error: attempt to call a nil value
stack traceback:
[2021-08-04 02:44:50+02:00] [error] [VeniceEXT] [boxgame] Error: attempt to call a nil value
stack traceback:
```

For that I made a simpler repro mod:
[ReproRegisterCallbacksWrongCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6927822/ReproRegisterCallbacksWrongCrash.zip)

```lua
Hooks:Install('EntityFactory:Create', 1, function(p_HookCtx, p_EntityData, p_Transform)
	local s_Entity = p_HookCtx:Call()

	if s_Entity == nil then
		return
	end

	s_Entity:RegisterDestroyCallback(crashMe)
end)
```

**Comment by FlashHit** [comment]
Will open a new issue for that, since the actual reported issue got fixed already
