### ISSUE TITLE
Chat resetting when player dies

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#45]
**This issue is also in vanilla BF3**. If you die while writing then the chat will be reset, everything you were writing will be lost. Video: http://youtu.be/bPEHmiZ5RYA

**Comment by Interforce** [comment]
Chat will also flush when you get revived. Really annoying.

**Comment by OrfeasZ** [comment]
This has been implemented in the Advanced Chat mod.
Read [this](http://forums.veniceunleashed.net/viewtopic.php?t=7646) for more information.
