### ISSUE TITLE
NetEvent causes a server crash.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#451]
Sending a netevent to a client with a parameter of a table with custom classes works just fine, but adding a second argument causes a server crash.

Repro:
- [MapEditor.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/3417625/MapEditor.zip)
- XP4_Rubble ConquestAssaultLarge0 2
- Join server, it will crash when the client loads in
- Netevent call on ``Server/EditorServer.lua``, line 57
- [Dump](https://github.com/EmulatorNexus/VeniceUnleashed/files/3417628/e734f3e3-176f-4475-9f52-3b47193fd79c.zip)

**Comment by OrfeasZ** [comment]
This was fixed in one of the previous builds.
