### ISSUE TITLE
[Silent crash] Possible operator crash

### ISSUE THREAD

**Issue by txt231** [VeniceUnleashed/VeniceUnleashed#454]
Theres a silent crash when doing some math, if not its netevents(unlikely).

Instructions:
1. spawn as soldier
2. press v key on keyboard

[NoClip.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/3571587/NoClip.zip)

**Comment by Powback** [comment]
The line in question is this: ```local s_Velocity = s_CameraTransform.forward*p_FBMove + s_CameraTransform.left*p_LRMove```

Related to the Vec3 multiplication operator?

**Comment by kiwidoggie** [comment]
Closing due to finished https://github.com/EmulatorNexus/VeniceUnleashed/issues/457

**Comment by OrfeasZ** [comment]
Please don't close silent crash issues.

**Comment by FlashHit** [comment]
It's not crashing anymore.
So there is no way to reproduce this silent crash.
