### ISSUE TITLE
[Bug] WebUI.Call not working when using window.location.href

### ISSUE THREAD

**Issue by paulhobbel** [VeniceUnleashed/VeniceUnleashed#456]
I am trying to dynamically load a webui, by using
```js
window.location.href = "http://some.ui";
```
This works just fine, however from this point it's no longer possible to use WebUI.Call
The function is still there but none of the functions are being called and dispatched events are not being received in Lua.

**Comment by Powback** [comment]
Could this be solved by just copypasting the event dispatchers or whatever into the page you're trying to load?

**Comment by OrfeasZ** [comment]
Fixed in build `15472`.
