### ISSUE TITLE
Vector Operators

### ISSUE THREAD

**Issue by kiwidoggie** [VeniceUnleashed/VeniceUnleashed#457]
Add additional vector operators

**Comment by kiwidoggie** [comment]
Will need to complete the work for Vec3, Vec4, Quat

**Comment by OrfeasZ** [comment]
Release notes for build `15647`:

- Fixed an issue where `LinearTransform` by `LinearTransform` multiplication wouldn't yield the correct result
- Fixed an issue with distance calculation between two `Vec3`

- Added support for the following operations against a `LinearTransform`:
+ `Vec3 operator*(Vec3 other)`
+ `Vec3 operator*(Vec4 other)`
+ `LinearTransform operator*(float other)`

- Added support for the following operations against a `Vec2`:
+ `Vec2 operator*(float other)`
+ `Vec2 operator/(float other)`
+ `bool operator<(Vec2 other)`

- Added the following new properties and methods to `Vec2`:
+ `float magnitude`
+ `float Distance(Vec2 other)`

- Added the following new static members to `Vec2`:
+ `Vec2 Vec2.down`
+ `Vec2 Vec2.left`
+ `Vec2 Vec2.negativeInfinity`
+ `Vec2 Vec2.one`
+ `Vec2 Vec2.positiveInfinity`
+ `Vec2 Vec2.right`
+ `Vec2 Vec2.up`
+ `Vec2 Vec2.zero`

- Added support for the following operations against a `Vec3`:
+ `Vec3 operator*(float other)`
+ `Vec3 operator/(float other)`
+ `bool operator<(Vec3 other)`

- Added the following new properties to `Vec3`:
+ `float magnitude`

- Added support for the following operations against a `Vec4`:
+ `Vec4 operator*(float other)`
+ `Vec4 operator/(float other)`
+ `bool operator<(Vec4 other)`

- Added the following new properties and methods to `Vec4`:
+ `float magnitude`
+ `float Distance(Vec4 other)`

- Added the following new static members to `Vec4`:
+ `Vec4 Vec4.negativeInfinity`
+ `Vec4 Vec4.one`
+ `Vec4 Vec4.positiveInfinity`
+ `Vec4 Vec4.zero`
