### ISSUE TITLE
Client SoldierWeapon.primaryAmmo only works for local player

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#459]
Same happens with ``.secondaryAmmo``, for players that aren't the local player these fields return 0.

**Comment by FlashHit** [comment]
I think the client just doesn't know about other players ammo, aimingSimulation etc.
Anyways it should be adjusted in the docs then.

**Comment by 3ti65** [comment]
we don't think this is possible, just update the docs and thats that
