### ISSUE TITLE
hanging flag-indicator during taking a flag

### ISSUE THREAD

**Issue by Interforce** [VeniceUnleashed/VeniceUnleashed#46]
As i already reported yesterday via gamechat, here is the bugreport on git:
Sometimes (doesn't really matter what gamemode as long as it features flags) the flag indicator which gets filled up/down randomly hangs even if the flag is still beeing taken.

Happens in about 1/5 games i would say.
Video: http://a.pomf.se/iufwqt.webm

**Comment by kiwidoggie** [comment]
This issue occurs in Vanilla BF3 as well.

**Comment by OrfeasZ** [comment]
Does this occur for all players capturing the given flag?

**Comment by Interforce** [comment]
I don't know, it will stay the whole match like this though (for all flags).

**Comment by 3ti65** [comment]
probably could close this because its a vanilla issue and who the fuck cares.
