### ISSUE TITLE
Console:Register registers outside of the mod scope

### ISSUE THREAD

**Issue by Timse93** [VeniceUnleashed/VeniceUnleashed#461]
Using the console-demo mod, it registers the hello command both as console-demo.hello and hello.
The hello command doesn't execute anything though.

**Comment by kiwidoggie** [comment]
Fixed in 15751, users will have to prefix the mod themselves if they need it.

**Comment by OrfeasZ** [comment]
This looks like vanilla engine behavior as it also seems to happen with built-in commands (eg. `RenderDevice.Dx11Enable`). Not sure if it's worth fixing or not.
