### ISSUE TITLE
Crash when spawning entities.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#462]
Spawning entities crash since a recent update. 
[Repro mod](https://github.com/EmulatorNexus/VeniceUnleashed/files/3960389/spawnentitytest.zip), type ``spawn`` in chat while alive to spawn entity at your position. ``MP_Subway ConquestLarge0 2``

**Comment by OrfeasZ** [comment]
This is because of an invalid assignment (`params.transform = linearTransform`). I've enabled additional safety checks in newer builds to make it so an error is thrown when such invalid operations are performed.
