### ISSUE TITLE
[Req] Implement weapon changing event.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#465]
Currently we are using a game message that is triggered the moment a weapon is changed, but getting the weapon won't give you the new one until the weapon swapping time has finished. This means we have to do a timer to check again after a bit in order to get the correct weapon. We need an event that passes the newly selected weapon or slot if its possible, so we can update the UI without delay.

**Comment by paulhobbel** [comment]
Implemented in `19963` as event `Player:ChangingWeapon`
