### ISSUE TITLE
[BUG] Vehicle:Exit event not firing for certain seats

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#467]
Vehicle:Exit event does not fire for certain seats in some vehicles.
Tested on Firestorm CQL and Kharg CQL.

Observed on following vehicles / seats
Growler ITV - Seat 3
VDV Buggy - Seat 3
UH-1Y Venom - Seat 4&5
KA-60 Kasatka - Seat 4&5
AH-6J Little Bird - Seat 2&3
Z-11W - Seat 2&3
RHIB Boat - Seat 3&4

Demo mod, prints enter/exit to server console 
[VehicleEnterExit.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4459241/VehicleEnterExit.zip)

**Comment by OrfeasZ** [comment]
Fixed in build `16824`.
