### ISSUE TITLE
[REQ] Source of damage in Vehicle:Damage

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#468]
The Vehicle:Damage Event only passes the damaged vehicle and the amount of damage as parameter.
Would it be possible to get the source of damage too? Similar to the Soldier:Damage hook?

**Comment by OrfeasZ** [comment]
The third parameter in the `Vehicle:Damage` event is a `DamageGiverInfo` type which should have the information you need.
