### ISSUE TITLE
[BUG] Player:Killed returns invalid data in weapon parameter

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#469]
When getting killed due to collision with terrain, the weapon-parameter sometimes contains garbage data.

Tested on #16410 Firestorm CQL
Example Mod: [PlayerKilled.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4465646/PlayerKilled.zip)

Video: https://i.xulunix.de/i/djwnCDct.mp4
Example output in console: `[2020-04-12 01:49:16+02:00] [info] [VeniceEXT] [playerkilled] XuluniX killed XuluniX | Weapon: ï°à█ïâ Roadkill: no Headshot: noRevive:no`

https://i.xulunix.de/i/KFiahogk.png

**Comment by OrfeasZ** [comment]
Fixed in build `16495`.
