### ISSUE TITLE
[BUG] Killing a player in Engine:Update crashes the server

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#471]
When applying damage to a Soldier in the Engine:Update event handler and the player dies, the server crashes.

Reproduction:
1. Use Testmod [EngineUpdateCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4467032/EngineUpdateCrash.zip)
2. Spawn
3. Type "!s" in chat
-> Player has lost 50% of its health
4. Type "!s" again
-> Server crashes when the player dies

Tested on #16410 Firestorm CQL

Using soldier:Kill() crashes as well

**Comment by OrfeasZ** [comment]
Fixed in build `16480`.
