### ISSUE TITLE
Add previousSquadId to Player:SquadChange event

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#474]
Please add the previousSquadId to the Player:SquadChange event. This will make the handling of that sort of logic way easier. As well as the previousTeamId to Player:TeamChange event for consistency (since there can be more than 2 teams technically).

**Comment by FlashHit** [comment]
On the server this can be achieved by using the event `Player:SetSquad`. While the parameter `squad` gives the new squadId, the `player.squadId` gives you the previous squadId.

Maybe you could expose the same event on the client to solve this issue/request.

**Comment by FlashHit** [comment]
Implemented in `19412`.
