### ISSUE TITLE
The Player:SetSquadLeader event does not occur when calling player:SetSquadLeader(...)

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#475]
This event:

docs.veniceunleashed.net/vext/ref/client/event/playersetsquadleader/

occurs when you become a squadleader. But if we manually assign someone as squadleader by using:

https://docs.veniceunleashed.net/vext/ref/server/class/player/#setsquadleader

that event does not occur sadly. :( 👎

**Comment by kiwidoggie** [comment]
fixed in Build 16640
