### ISSUE TITLE
WebUI EventListener mousemove.movementX/Y always returns 0

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#478]
[mousebuttonbug.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4548455/mousebuttonbug.zip)

```javascript
document.addEventListener('mousemove', (e) => {
    console.log(e.movementX) // Always 0
    console.log(e.movementY) // Always 0
});

```

**Comment by OrfeasZ** [comment]
This seems like a CEF issue: https://bitbucket.org/chromiumembedded/cef/issues/2734/movementx-always-0-in-osr

I'll mark it wontfix for now and if it becomes a problem I might revisit in the future.
