### ISSUE TITLE
[Req] VU Launch Argument to automatically login to VU account

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#479]
Possible Argument: "-credentials"
Example:
vu.exe -credentials -userName "test1" -password "bla"

use case:

using multiple clients to test something, so you dont need to reenter the account credentials manually all the time.

**Comment by FlashHit** [comment]
Fixed in build `19963`. Go to [changelog](https://docs.veniceunleashed.net/general/changelog/#19963) for more information.
