### ISSUE TITLE
[Docs] physicsEntity.velocity is wrong

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#480]
https://docs.veniceunleashed.net/vext/ref/client/type/physicsentity/#velocity

velocity is vec3 not float

**Comment by OrfeasZ** [comment]
Open issues related to docs in the appropriate repository: https://github.com/EmulatorNexus/VU-Docs/issues

**Comment by 3ti65** [comment]
Done: https://github.com/EmulatorNexus/VU-Docs/issues/6
