### ISSUE TITLE
[Crash] Server crashes after firing entity callback

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#481]
> Crash ID: 5ed34e4d-e6c1-4bf2-b0cc-f8eb68264c4f
> Build Number: 16772
> Release Branch: dev

Mods:
1. https://cdn.discordapp.com/attachments/171476437193326594/712389218860531812/EntityRegisterDestroyCallback.zip
2. https://github.com/BF3RM/BlueprintManager/tree/entity_destruction_tracking

ModList.txt:

> EntityRegisterDestroyCallback
> BlueprintManager

MapList.txt:

> XP1_001 ConquestAssaultLarge0 2

Steps to reproduce:

- spawn with c4
- type 'spawn' in chat
- destroy the tank that spawns on top of you
- server crash
- it does print '>>>>> OnEntityDestroyed received!' on the server, meaning the callback works

**Comment by OrfeasZ** [comment]
Fixed in build `16802`.
