### ISSUE TITLE
[REQ] add SendMessage(message: string, toPlayer:Player)

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#483]
<h1>SendMessage(message: string, toPlayer:Player)</h1>
Use case: For an InGameAdmin mod..<br>
If an admin writes: "!kick Flash_Hit"<br>
He should get a message: "Flash_Hit got kicked." <br>
Atm I can only write to his squad or team or to everyone. Or I would have to use RCon.<br>
<br>
SendYellMessage could be also useful.

**Comment by OrfeasZ** [comment]
Build `16803` adds support for sending messages to specific players and also yelling at players. See https://docs.veniceunleashed.net/vext/ref/server/library/chatmanager/
