### ISSUE TITLE
Server crashes when sending an RCON command

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#486]
If multiple mods register RCON commands, the server crashes shortly after executing one of them.

**Comment by FlashHit** [comment]
if i use modList.ReloadExtensions the server crashes too. Am using only one mod and that mod registers one rcon command

**Comment by OrfeasZ** [comment]
That sounds like a different issue. Create a minimal reproduction mod and post it in a new issue.

**Comment by FlashHit** [comment]
done

**Comment by OrfeasZ** [comment]
Fixed in build `16824`.
