### ISSUE TITLE
[Bug] server crashes if you reload a mod that uses RCON:RegisterCommand

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#488]
Reproduce:

1. activate mod [rconbug.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4718433/rconbug.zip)
2. open procon console
3. type "modList.ReloadExtensions"
-> Server crashes

**Comment by OrfeasZ** [comment]
Fixed in build `16824`.

**Comment by FlashHit** [comment]
not fixed, pls reopen

**Comment by OrfeasZ** [comment]
I am unable to reproduce this issue. Are you getting a crash report?

**Comment by FlashHit** [comment]
Yes I get a crash report.

Crash ID: 94f8dbbc-4dcd-4ca5-ad50-b4a9cf81d8be
Build Number: 16964
Release Branch: prod

**Comment by OrfeasZ** [comment]
I'm pushing a new build (16965) that should fix this issue (should be live within the next couple of hours). Let me know if you still crash with it.

**Comment by FlashHit** [comment]
New build fixed the issue!
