### ISSUE TITLE
[Bug] Player:ManDownRevived doesn't get triggered

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#489]
Simple Testmod: 
[manDownRevivedEvent.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4747995/manDownRevivedEvent.zip)

**Comment by FlashHit** [comment]
Or is this event for the coop revive?

**Comment by FlashHit** [comment]
Player:InstantSuicide also doesn't get triggered. I tried forcekill, menu suicide, admin.kill none of that works.

Player:Left gets triggered when the round ends. I think it should only get triggered if you really leave the server.

**Comment by FoolHen** [comment]
ManDownRevive is coop revive yeah

**Comment by FlashHit** [comment]
Good to know
Then I suggest to mention it in the docs

**Comment by FlashHit** [comment]
What about Player:InstantSuicide and Player:Left?
Look what I wrote above

**Comment by OrfeasZ** [comment]
Open different issues

**Comment by FlashHit** [comment]
Alright

**Comment by FoolHen** [comment]
Sorry I was wrong, mandown is for MP and interactivemandown is for coop. Can confirm that the event is never called.

**Comment by FlashHit** [comment]
I tested it in coop before and it worked
