### ISSUE TITLE
Roundtime not implemented

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#49]
`serverInfo` will always return 0 for uptime and roundtime.

**Comment by kiwidoggie** [comment]
Fixed in build 7113.

**Comment by derrod** [comment]
Roundtime still not implemented in Build 7963.

**Comment by kiwidoggie** [comment]
RoundTime implemented, but class returns 0 always. Looked into it, we will have to figure out how to re-implement it, as the structure containing RoundTime is not being updated by the client.

**Comment by derrod** [comment]
Changed title to be accurate.

**Comment by kiwidoggie** [comment]
Fixed in build 8397.
