### ISSUE TITLE
Exit Server that runs Metro = client crash

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#490]
https://streamable.com/funl46

**Comment by OrfeasZ** [comment]
Are you running any mods?

**Comment by FlashHit** [comment]
No mods

**Comment by FlashHit** [comment]
Metro seems to have a problem to load maps. If you restart or runNextLevel in Metro the client crashes immediatly. If you end the round and the scoreboards loads the client will crash as soon as the countdown end and the next map should load.
But you can run another map and metro can be the next map. Like switching from bazaar to metro is no problem but switch from metro to anything = silent client crash.

Didn't open a new issue for that because i think it is the same case.

**Comment by OrfeasZ** [comment]
Fixed in build `17139`.
