### ISSUE TITLE
[Bug] Changing Team and getting in a full squad (5/4)

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#491]
https://streamable.com/ih7plu

1. Run a server with the [bots ](https://github.com/OrfeasZ/VEXT-Basics/tree/master/bots) mod 
2. Change squad size: "vu.SquadSize 4" (for me it is already in the StartUp.txt)
3. Place 4 bots in enemy Team Alpha Squad (Team2 Squad1)
4. Create an Alpha Squad in your Team (Team1 Squad1)
5. Switch to the enemy team
-> You get switch from Team1 Squad1 to Team2 Squad1 no matter if the squad is full or not.

If you want to move someone to a full squad with admin.movePlayer it will say "SetSquadFailed". So it is only possible this way.

In vanilla rcon prints always 3 events: (maybe this is not relevant idk)
[02:48:16] player.onTeamChange voteban_flash 2 1
[02:48:16] OK
[02:48:16] player.onSquadChange voteban_flash 2 0
[02:48:16] OK
[02:48:16] player.onSquadChange voteban_flash 2 1
[02:48:16] OK

While it is in VU just 1 event:
[02:53:09] player.onTeamChange voteban_flash 2 1
[02:53:09] OK

Note: If you are in Bravo squad and change the team you will change to the enemy bravo squad.

Console Bot Lines to copy & paste:
bots.spawn Bot1 Team2 Squad1 70 70 70
bots.spawn Bot2 Team2 Squad1 70 70 70
bots.spawn Bot3 Team2 Squad1 70 70 70
bots.spawn Bot4 Team2 Squad1 70 70 70

**Comment by OrfeasZ** [comment]
Fixed in build `16824`.
