### ISSUE TITLE
Player:Left get triggered on Level Load

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#493]
Player:Left get triggered when the round ends. I think it should only get triggered if you really leave the server.

**Comment by FlashHit** [comment]
https://streamable.com/peazg9

Test mod: [PlayerLeft.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/4807087/PlayerLeft.zip)

The mod will print "Player Left?" when the event gets triggered.

Commands for chat: 
- "restart"
- "nextround"
- "endround" (round needs to be started for this one)

So basically the Player:Left event gets triggered when the map/ level is (re)loading.

**Comment by OrfeasZ** [comment]
Fixed in build `16824`.
