### ISSUE TITLE
[Bug] Drag events don't work in WebUI

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#495]
The following events don't work:
```
drag
dragend
dragover
dragenter
dragleave
dragexit
drop
```
Only event that seems to work is ``dragstart``

[Repro mod](https://github.com/EmulatorNexus/VeniceUnleashed/files/4988746/dragtest.zip)

**Comment by OrfeasZ** [comment]
Implemented in build `17139`.
