### ISSUE TITLE
[RM] Smoke grenade sometimes causes crashes or timeouts while loading.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#496]
Repro: RM ``feature/smoke_greande`` branch, map doesn't matter, ``XP3_Shield ConquestLarge0 2`` for example.

**Comment by 3ti65** [comment]
i like how you also fucked up the name here

**Comment by OrfeasZ** [comment]
Fixed in build `16824`.

**Comment by FoolHen** [comment]
I'm getting this crash while loading. 
```
Crash ID: 29806a16-22e5-4259-9c3b-0696d72d2372
Build Number: 16841
Release Branch: dev
```

Also forgot to mention, you need [bundlemounter](https://github.com/BF3RM/BundleMounter) as well.
