### ISSUE TITLE
[Req] Add event for player leaving combat area boundaries

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#497]
We will need a client event that gets triggered when a player leaves the designated playable area. Low prio since we can most likely achieve the same effect with just looking out for the proper screen to pop up in the UI:PushScreen hook.

**Comment by FlashHit** [comment]
Suggestion for the event name: **Player:ZoneTrespass(player)**
For server too pls.

**Comment by paulhobbel** [comment]
Implemented in `19963`

There are two events:
- [CombatArea:PlayerDeserting](https://docs.veniceunleashed.net/vext/ref/server/event/combatarea_playerdeserting)
- [CombatArea:PlayerReturning](https://docs.veniceunleashed.net/vext/ref/server/event/combatarea_playerreturning)
