### ISSUE TITLE
[Silent crash] Erasing weapons

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#499]
https://streamable.com/8b32vm

This was like the 6th map loading. Sometimes the client crashes pretty fast and sometimes it takes a while. So sometimes i press the 'Run next round' button in procon 20 times till the client crashes but the client crashes always.

In my UnlockList / Loadout Manager mod I had these crashes alot while developing and I figured out that it has something to do with the erasing so I made this test mod:

[silentcrashtest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5098653/silentcrashtest.zip)

Basically the mod erases the whole loadout for each class in each team.

```lua
Events:Subscribe('Partition:Loaded', function(partition)
	for _,instance in pairs(partition.instances) do
		if instance:Is("VeniceSoldierCustomizationAsset") then
			instance = VeniceSoldierCustomizationAsset(instance)
			weaponTable = CustomizationTable(instance.weaponTable)
			for i,unlockPart in pairs(weaponTable.unlockParts) do
				unlockPart = CustomizationUnlockParts(unlockPart)
				for index = #unlockPart.selectableUnlocks, 1, -1 do
					unlockPart:MakeWritable()
					unlockPart.selectableUnlocks:erase(index)
				end
			end
		end
	end
end)
```

**Comment by OrfeasZ** [comment]
I think the knife is required and for everything else, if you don't want to have any unlocks, you need to at least have `Weapons/Common/NoSpecialization`.

**Comment by FlashHit** [comment]
Hmm the problem seems to be somewhere else, I just did some tests. You said it's because the knife is required, so I just removed the F2000 and didn't touch the other weapons and still got the client crash.
Then I thought maybe it crashes without erasing weapons and it did.
Then I had to find out if its the MakeWritable() but even without that it crashes.
I removed line by line and end up with this code: 
```lua
Events:Subscribe('Partition:Loaded', function(partition)
	for _,instance in pairs(partition.instances) do
		if instance:Is("VeniceSoldierCustomizationAsset") then
			instance = VeniceSoldierCustomizationAsset(instance)
			weaponTable = CustomizationTable(instance.weaponTable)
		end
	end
end)
```
If I comment out the weaponTable I don't get client crashes.

Here a video: https://streamable.com/qbec6r
I did this a few times it took up to 4 minutes but it crashes always.

**Comment by Powback** [comment]
@FlashHit Does it crash if you don't run mods and do the same? Also, shouldn't you be declaring the variable as local?

```
Events:Subscribe('Partition:Loaded', function(partition)
	for _,instance in pairs(partition.instances) do
		if instance:Is("VeniceSoldierCustomizationAsset") then
			instance = VeniceSoldierCustomizationAsset(instance)
			local weaponTable = CustomizationTable(instance.weaponTable)
		end
	end
end)
```

**Comment by OrfeasZ** [comment]
Looking at it again your issue is almost definitely what @Powback mentioned, which is the `weaponTable` (and `unlockPart` in your previous example) not being local. You're basically declaring those as global variables but these instances get unloaded when the level unloads, so when the Lua VM garbage collects and tries to clean these up they don't exist anymore, causing a crash. I'll be explaining the intricacies of this in the [DataContainer lifetime](https://docs.veniceunleashed.net/vext/guides/lifetimes/) guide (still pending being written).

**Comment by FlashHit** [comment]
Oh I never used local in my mods...
I will try this later to confirm it.
But it should be it since I don’t get any crashes if I comment out the weaponTable

**Comment by OrfeasZ** [comment]
You should because other than the DataContainer lifetime issues you're also poluting the global scope which could cause other issues down the line.

**Comment by FlashHit** [comment]
Ok, just did some tests and with `local` I dont get any crashes.
Ye, I will adjust my other mods then.
