### ISSUE TITLE
[Req] Update modList.Add and modList.Remove

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#502]
While these commands do nothing atm you could let them edit the modlist.txt for the next server restart. 
I am not talking about adding/ removing mods on the fly as you confirmed this won’t happen, but adding/ removing the txt file with these commands should be possible **so you can handle the modlist just via rcon.**

**Comment by OrfeasZ** [comment]
`modList.*` RCON commands have been revamped in build `17139`. See [https://docs.veniceunleashed.net/hosting/commands/](https://docs.veniceunleashed.net/hosting/commands/) for more info.

**Comment by FlashHit** [comment]
Love you

**Comment by cat24max** [comment]
These new commands are still a little inconsistent in terms of casing

modList.Available
OK adminmute ADS Advanced-Chat AdvancedRCON

modList.ListRunning
OK advanced-chat ads adminmute


ListRunning seems to ignore casing?

**Comment by FlashHit** [comment]
also it doesn't do the line break in the file.

and is on purpose that the vu rcon commands all start with a capital letter after dot?

**Comment by OrfeasZ** [comment]
@cat24max This is not intentional, please create a separate issue for it and I'll fix it.

@FlashHit It does add line breaks but they're probably not Windows ones (`\n` instead of `\r\n`), which means that Notepad or whatever will see everything as a single line. I can improve that.
