### ISSUE TITLE
[Bug] InputManager:SetMouseSensitivity not working

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#504]
https://streamable.com/qsh41o

Testmod: [MouseSensitivity.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5179680/MouseSensitivity.zip) 

```lua
Console:Register('get', 'Get current sensitivity', function()
	print(InputManager:GetMouseSensitivity())
end)

Console:Register('set', 'Set new sensitivity', function(args)
	x = tonumber(args[1])
	if tonumber(args[1]) and x >= 0 and x <= 3.01 then
		InputManager:SetMouseSensitivity(x)
		print('New sensitivity: ' .. round(InputManager:GetMouseSensitivity(), 6))
	else 
		print('Error: Value must be between 0 and 3.01')
	end
end)

function round(num, numDecimalPlaces)
	local mult = 10^(numDecimalPlaces or 0)
	return math.floor(num * mult + 0.5) / mult
end
```

**Comment by OrfeasZ** [comment]
Fixed in build `17139`. This also makes it so sensitivity values are between `0.0 and 1.0`.

**Comment by FlashHit** [comment]
What do you mean with values between `0.0 and 1.0`? Ingame it is `0.0 and 1.5` like in https://github.com/Powback/Venice-EBX/blob/071473993867cd2297dc662517c61edaff51e8fe/profile/OptionMouseSensitivity.txt
And I think InputManager:SetMouseSensitivity(x) has no limit.

**Comment by OrfeasZ** [comment]
I may be wrong. See what GetMouseSensitivity returns when setting to max how settings.

**Comment by FlashHit** [comment]
when I set it ingame to max GetMouseSensitivity return 1.5. 
Might be wrong but I think before this update it returned 3.01 that's why I limited it in my script above.

Whatever it is correct with 0.0 and 1.5 now and set and get also works, so thx!
