### ISSUE TITLE
[Client Silent Crash] accessing instances that are lazyloaded

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#505]
```lua
Events:Subscribe('Partition:Loaded', function(partition)
        for _,instance in pairs(partition.instances) do
            if instance:Is("VeniceSoldierCustomizationAsset") then
                instance = VeniceSoldierCustomizationAsset(instance)
                local visualTable = CustomizationTable(instance.visualTable) 
                print(UnlockAssetBase(CustomizationUnlockParts(visualTable.unlockParts[1]).selectableUnlocks[1]).debugUnlockId)
            end      
        end
    end)
```
It should print ```U_CAMO_DEFAULT``` but instead I get silent client crashes...

I also ran it in Shared and saw that the server prints 5 empty lines and then 3 times  ```U_CAMO_DEFAULT``` as supposed. So I tried just accessing the last kit but even then the client crashed. 
Btw this doesn't happen with specializationTable or weaponTable. Only with visualTable.

**Comment by FlashHit** [comment]
The [`U_CAMO_DEFAULT`](https://github.com/EmulatorNexus/Venice-EBX/blob/b80b49f6be7010b968eca36654e70819402fa259/UI/Art/Persistence/Camo/U_CAMO_DEFAULT.txt) gets loaded after 5 kits (at least on bazaar, might be different on other maps) so I need to wait till it gets loaded till I can access it in the visualTable. Anyways it should throw an error with nil or sth instead of a client crash. But ye that's the reason for the client crashes.

**Comment by FlashHit** [comment]
Changed the code a bit to find out at what point it starts crashing:
```lua
Events:Subscribe('Partition:Loaded', function(partition)
	for _,instance in pairs(partition.instances) do
		if instance:Is("VeniceSoldierCustomizationAsset") then
			instance = VeniceSoldierCustomizationAsset(instance)
			if instance.visualTable == nil then
				print("Error: 1")
				return
			end
			local visualTable = CustomizationTable(instance.visualTable)
			if visualTable.unlockParts == nil or visualTable.unlockParts[1] == nil then
				print("Error: 2")
				return
			end
			local unlockPart = CustomizationUnlockParts(visualTable.unlockParts[1])
			if unlockPart.selectableUnlocks == nil then
				print("Error: 3")
				return
			end
			-- Doing unlockPart.selectableUnlocks[1] makes me crash
			if unlockPart.selectableUnlocks[1] == nil then
				print("Error: 4")
				return
			end
			--[[
			local selectableUnlock = UnlockAssetBase(unlockPart.selectableUnlocks[1])
			if selectableUnlock == nil or selectableUnlock.debugUnlockId == nil then
				print("Error: 5")
				return
			end
			print(selectableUnlock.debugUnlockId)
			]]
		end
	end
end)
```

Here the repro mod:
[visualTable.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6479878/visualTable.zip)


So again, server works, but client crashes.

**Comment by FlashHit** [comment]
found another example 
```lua
Events:Subscribe('Partition:Loaded', function(p_Partition)
	for _, l_Instance in pairs(p_Partition.instances) do
		if l_Instance.instanceGuid == Guid("A5FA0A5B-EFA2-4C5B-B18A-C4435F19694F") then
			print("found")
			l_Instance = WaveSwitcherNodeData(l_Instance)
			print(l_Instance.waves[1].isLazyLoaded)
		end
	end
end)
```
So the problem has to do with instances that are lazy loaded.

**Comment by FlashHit** [comment]
Probably only for arrays.
So this might be also a duplicate of #598, not sure.

**Comment by FlashHit** [comment]
Running the visualTable mod.
With debugger attached I only get this:
```
Unhandled exception at 0x779AFC2D (ntdll.dll) in vu.exe: 0xC0000374: Ein Heap wurde beschädigt (parameters: 0x779EB960).
```
but it doesn't crash then.

**Comment by OrfeasZ** [comment]
Fixed in `17977`.
