### ISSUE TITLE
admin.listPlayers: something wrong with the order

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#506]
```
[15:08:40] admin.listPlayers all
[15:08:40] OK 12 name guid teamId squadId kills deaths score rank ping spectator playerGuid ip 1 voteban_flash ebfsbbesbfbseesbsebbssfbebef 1 1 0 0 0 true 0 0 ebfsbbesbfbseesbsebbssfbebef XXX.XXX.XXX.XX


name = voteban_flash 
guid = ebfsbbesbfbseesbsebbssfbebef 
teamId = 1
squadId = 1
kills = 0
deaths = 0
score = 0
rank = true  -------------------------------- this
ping = 0
spectator = 0 ------------------------------- and this
playerGuid = ebfsbbesbfbseesbsebbssfbebef 
ip = XXX.XXX.XXX.XX
```

correct me if I'm wrong but shouldn't rank be 0 and spectator either true or false?
even if it's just the order then spectator should be false and not true in this case.

**Comment by cat24max** [comment]
name       guid                                                       teamId squadId kills deaths score rank ping spectator
cat24max bae992d18b4f4a17b631214dc85fddeb 0         0           0      0         0       true 19    0 

playerGuid                                             ip
db808847ad4c45cb98e2ead1ce854fa5 79.206.216.154


Edit: Wow thx Github for totally fucking up the formatting

**Comment by FlashHit** [comment]
vanilla is doing
```
[17:19:59] admin.listPlayers all
[17:19:59] OK 8 name guid teamId squadId kills deaths score rank 1 voteban_flash EA_ebfsbbesbfbseesbsebbssfbebef 1 1 0 0 0 -1
```
So `ping spectator playerGuid ip` is VU only I guess.

**Comment by kiwidoggie** [comment]
This was a combination of RCON clients being stupid and not following the RCON protocol, and VU having a bug with spectator return value. Both have been fixed in development build `17585`
