### ISSUE TITLE
modList - Inconsistent casing

### ISSUE THREAD

**Issue by cat24max** [VeniceUnleashed/VeniceUnleashed#508]
These new commands are still a little inconsistent in terms of casing

**modList.Available**
OK adminmute ADS _Advanced-Chat_ AdvancedRCON

**modList.ListRunning** <-- this is the problem
OK _advanced-chat_ ads adminmute

**modList.List**
OK advanced-chat _Advanced-Chat_ AdvancedRCON advancedrcon ADS adminmute

**Comment by FlashHit** [comment]
```
[01:05:48] modlist.ListRunning
[01:05:48] OK advanced-chat bflag bflag-commands simple-spectator advancedrcon betteringameadmin bflag-countdown
```

**Comment by FlashHit** [comment]
modList.Add / Remove is also case sensitive. Could be improved as well imo.

**Comment by kiwidoggie** [comment]
Issue stems from the name being used for file pathing (case sensitive on Linux) which gets "normalized" after being loaded (to lower) need to split the display name and path to make casing consistent. Not a super hard fix just gotta be careful to not break Linux support in the process
