### ISSUE TITLE
Laggy movements in spectator mode

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#51]
Lowering the **Network Smoothing Factor** (Options -> Gameplay) will make players movement _"laggy"_ while spectating. The issue is especially evident with fast moving targets, such as jets. I would suggest forcing the **NSF** to be higher while spectating so the experience is smoother (I don't think a more precise vision is needed when spectating).

**Comment by OrfeasZ** [comment]
A smoothing factor will be enforced sometime in the near future, since the choppyness is caused because of the slow network tickrate (something we can't easily change).

**Comment by somebody873425** [comment]
I hope with "enforcing it" you mean only in spectator mode.
Playing without NSF gets rid of some lag and makes for a more precise player position.

**Comment by OrfeasZ** [comment]
The smoothing factor will only be enforced in spectator mode.
Joining as a player you will still be able to configure it via your options menu.

**Comment by OrfeasZ** [comment]
With the introduction of High Frequency modes we decided it's not necessary to enforce a smoothing factor while spectating. We rather leave that choice up to the spectators themselves.
