### ISSUE TITLE
[Req] ClientUtils:GetPing()

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#510]
With my custom scoreboard I don’t have access to the pings of the players as the Player for Client doesn’t provide a ping. I think if it would be possible it would be already included, right? but maybe you can add a ping for the local player instead. Sth like: ClientUtils:GetPing() so I can at least include this somewhere on the screen.

**Comment by FlashHit** [comment]
So if it's possible I would prefere to request the player.ping property. The vanilla scoreboard has it and so I want my custom scoreboard to provide this information too.

**Comment by kiwidoggie** [comment]
Closing due to being implemented in #520

**Comment by FlashHit** [comment]
Can you reopen this?

**Comment by Powback** [comment]
@FlashHit Why? Does it not work?

**Comment by FlashHit** [comment]
> @FlashHit Why? Does it not work?

It didn’t got implemented. We got `player.ping` for the client but it doesn’t work.
That’s why it would be nice to get at least a method for the localplayer ping.

**Comment by kiwidoggie** [comment]
Reopen the other issue, this one is not being reopened.
