### ISSUE TITLE
[Bug] RCON crash when sending wrong command args

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#512]
the server crashes if I write "squad.leader voteban_flash 1 1" which is wrong.
Correct is: "squad.leader 1 1 voteban_flash"
I think it should return an error like "InvalidArguments" instead of a server crash.

Edit: same happens with "squad.private true 1 1" 
Correct is: "squad.private 1 1 true"

**Comment by kiwidoggie** [comment]
This particular crash has been fixed (pending PR). Pending if we should go through all of the RCON endpoints and update them.

**Comment by kiwidoggie** [comment]
Fixed in build 17342
