### ISSUE TITLE
[Req] VU Server Launch argument -maxPlayers

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#513]
In RCON we already have `admin.effectiveMaxPlayers` but atm it is useless. Instead of returning `OK []` it should be read only and return `128` if the server didn't use the launch argument `-maxPlayers`.

If I give other people access to my server via Rcon/ procon layer I don't want them to be able to just change the playersize from `10` to `128` as my server might be not capable for that amount of players. So with that launch argument I could set `-maxPlayers` to `10` and `admin.effectiveMaxPlayers` would return that and they wouldn't be able to set `admin.maxPlayers` to anything higher then `10`.

**Comment by cat24max** [comment]
Vanilla bf3 actually seems to have that?
"InvalidMaxPlayerCount: vars.maxPlayers 50"
When trying to set a 48p server to 50.

**Comment by paulhobbel** [comment]
Implemented in `19963`
