### ISSUE TITLE
[Bug] WebUI select option dropdowns are invisible

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#514]
https://streamable.com/982ej1

Testmod:
[dropdownselect.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5263302/dropdownselect.zip)

**Comment by OrfeasZ** [comment]
This is intended behavior. If you want a dropdown you'll have to implement it yourself or use a javascript library that does.
