### ISSUE TITLE
[Req] KillCounterEntity for the Client

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#515]
https://prnt.sc/um57s4 
For Conquest I used the TicketCounterEntity, for Rush I use now the LifeCounterEntity and for TDM (and also SQDM) I would have to use the KillCounterEntity if I am not wrong.

The [KillCounterEntityData](https://docs.veniceunleashed.net/vext/ref/fb/killcounterentitydata/) has a property `maxKillCount = 100`
So I guess the entity would give me the actual killCount so I can use it for my scoreboard.

**Comment by kiwidoggie** [comment]
Update, this has been code completed just pending testing. Will close once tested and pushed to development branch.

**Comment by kiwidoggie** [comment]
Pushed in v1.0.3 of VeniceEXT Build 17342
