### ISSUE TITLE
vu.ServerBanner Invalid URL

### ISSUE THREAD

**Issue by cat24max** [VeniceUnleashed/VeniceUnleashed#518]
Removing a server banner is not currently possible

vu.ServerBanner ""

will result in Invalid URL

**Comment by kiwidoggie** [comment]
I cannot currently reproduce this issue. I had a server banner set, changed it to vu.ServerBanner "" in the Startup.txt and it shows the default map image. What do you need to do to reproduce this issue?

**Comment by cat24max** [comment]
RCON

**Comment by kiwidoggie** [comment]
Fixed in build 17183 (not deployed yet)
