### ISSUE TITLE
Unable to connect to server 

### ISSUE THREAD

**Issue by miloshthemedic** [VeniceUnleashed/VeniceUnleashed#52]
I just hopped on to see what everything is about when Venice stayed for 5-7mins loading the server and trying to connect to it (Multiple times) with nothing happening

**Comment by OrfeasZ** [comment]
Make sure your firewall isn't blocking outgoing UDP traffic.
The test servers use the following ports:
7948, 7958, 25200, 25300

**Comment by miloshthemedic** [comment]
working perfectly now thank you :D
