### ISSUE TITLE
[Bug?] moving player to new squad makes squad private

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#521]
If I move a player to a squad that’s not existing/ empty it will create it and make it private. So if I use this to create a new squad I need to use rcon to make it public again. I think it should be public by default because if you create a new squad from the menu it is also public by default.

**Comment by FlashHit** [comment]
Repro Mod: [ReproPrivateSquad.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6927560/ReproPrivateSquad.zip)
- Write `!newSquad` in the chat.

-> The squad will be private: ([X] PRIVACY)
![Screenshot_186](https://user-images.githubusercontent.com/56718716/128099026-d2e959e1-3096-4873-afa5-99ed0a9a3672.jpg)

```lua
Events:Subscribe('Player:Chat', function(p_Player, p_RecipientMask, p_Message)
	if p_Player == nil then
		return
	end

	if p_Message == "!newSquad" then
		p_Player.squadId = p_Player.squadId + 1
	end
end)
```

**Comment by paulhobbel** [comment]
Implemented in `19963`
