### ISSUE TITLE
[Req] click on server for server information

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#522]
Atm there is no way to get information about the server settings before joining. In battlelog each server has an own page with all information but in VU you don’t see this information anywhere.
![1ECDDE62-F30E-4572-B606-F90F11EA80A7](https://user-images.githubusercontent.com/56718716/94982762-9a038d00-053d-11eb-819a-f75b8d0d4558.jpeg)

I think it would be nice to get this information too.

Adding information about mods would be also useful. Listing all running mods + their mod.json descriptions to get an idea what each mod is doing.

**Comment by OrfeasZ** [comment]
Not interested in doing something like this. For mod discovery you should use the existing [tag system](https://docs.veniceunleashed.net/modding/your-first-mod/#tags).
