### ISSUE TITLE
[Bug] "  s_Instance.categories:add(cat)  " crashing the server

### ISSUE THREAD

**Issue by JoseFigueiras** [VeniceUnleashed/VeniceUnleashed#525]
From the SP/COOP patch mod. 

Crash ID: f4df0033-33a9-49dd-b7cf-22a276b9b753
Build Number: 17159
Release Branch: prod

[e788f441-7dc4-482b-a55e-c434d79bd5cc.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5321702/e788f441-7dc4-482b-a55e-c434d79bd5cc.zip)

[PatchSPCOOP.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5321704/PatchSPCOOP.zip)

**Comment by kiwidoggie** [comment]
This is reproducable by creating a new LevelDescriptionInclusionCategory and assigning it to the level data. If you create a new `local s_LevelDescriptionInclusionCategory = LevelDescriptionInclusionCategory ()` and assign it. The game crashes when it goes to GC that object. If you create an instance of it on startup, and then assign the created instance in LevelData it immediately crashes.

**Comment by FlashHit** [comment]
Weird things that I figured out:
Doing it in `Level:LoadingInfo` -> no crash but game doesn't go beyond `Sending spawn messages`.
Not really related to these events.
Repro for that: [ReproLevelDescriptionInclusionCategoryNoCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6927450/ReproLevelDescriptionInclusionCategoryNoCrash.zip)

It is basically this:
```lua
local s_LevelDescriptionInclusionCategory = LevelDescriptionInclusionCategory()
s_LevelDescriptionInclusionCategory.category = "GameMode"
s_LevelDescriptionInclusionCategory.mode:add("TeamDeathMatchC0")

local s_LevelDescriptionAsset = LevelDescriptionAsset()
s_LevelDescriptionAsset.categories:add(s_LevelDescriptionInclusionCategory)
```

In `Extension:Loaded` it was not allowed for whatever reason, but whenever you do that: the server will stop at `Sending spawn messages`

And now really weird with crash. I tried doing that on every partition. It didn't crash. Then I did it again while the other `LevelDescriptionAssets` got loaded and it crashed (randomly). Sometimes it crashes, sometimes it doesn't.

Repro: 
[ReproLevelDescriptionInclusionCategoryCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6927523/ReproLevelDescriptionInclusionCategoryCrash.zip)

**Comment by FlashHit** [comment]
```
Crash ID: 8ec79300-2f29-4e19-a80d-c4782a7d2b0a
Build Number: 17671
Release Branch: dev
```
Here another crash repro mod:
[ReproLevelDescriptionInclusionCategoryCrash2.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6927606/ReproLevelDescriptionInclusionCategoryCrash2.zip)
- Spawn
- Reload map/ run another map
-> Server crashes
