### ISSUE TITLE
[REQ] UTF-8 Support for Chat messages

### ISSUE THREAD

**Issue by IamDontNoob** [VeniceUnleashed/VeniceUnleashed#527]
Hello, in Vanilla BF3-BF4 we have UTF-8 (Russian messages) send support (i mean send, not receive).  VU not supported?
Also would by nice if you guys add UTF-8 support for receive messages from game chat. (In vanilla receiving UTF-8 not supported) Users from Russia, China and some other countries would be grateful. =)

**Comment by SeaniaTwix** [comment]
it can be fixed on WebUI side by javascript. 

```js
const decoder = new TextDecoder();

function translate(text) {
  const arr = Array.from(text).map(char => char.charCodeAt(0) ^ 0xFF00);
  return decoder.decode(Uint8Array.from(arr));
}
```

here is how to use:

```js
const receivedBrokenString = '￪ﾰﾀ'; // mean '가'
console.log(translate(receivedBrokenString)); // print: '가'
```

this problem looks like vu server does not support properly 'variable-length' of utf-8
all unicode characters split up into single byte and converted to 2 bytes each them.

**Comment by paulhobbel** [comment]
Implemented in `19963`, no more need to manually encode now
