### ISSUE TITLE
[Bug][Linux] MapList.txt not readable or writable

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#528]
Servers running under Linux don't load or write MapList.txt.
ModList.txt and Startup.txt are working as expected.
Tested with using the same ServerInstancePath on Windows and Linux, MapList.txt is only used on Windows.
Modifying the maplist via RCON results in an error: 
`[21:33:55]   Client: request  S: 87     [0-maplist.list]
[21:33:55]   Client: response S: 87     [0-OK] [1-1] [2-3] [3-MP_012] [4-ConquestLarge0] [5-2] (RE: [0-maplist.list])
[21:34:00]   Client: request  S: 88     [0-mapList.save]
[21:34:00]   Client: response S: 88     [0-AccessError] (RE: [0-mapList.save])`
Tested on Build 17182 under 5.0.2 on Ubuntu 18.04 and Debian 10.6

**Comment by Ax0r** [comment]
Hi,
can you try what's written on this pr ? 
https://github.com/EmulatorNexus/VU-Docs/pull/22/files
As stated by NoFate, replace the serverInstancePath by the windows path that you can get with : 
 `winepath -w <instance directory path>`

**Comment by Xulunix** [comment]
Can confirm, reading and writing to MapList.txt works with the winepath workaround
