### ISSUE TITLE
[Req] ClientSpottingTargetComponent instance properties

### ISSUE THREAD

**Issue by rierei** [VeniceUnleashed/VeniceUnleashed#530]
Manipulating the spotting state, on this component instance, requires the folowing properties:

```c
int m_spotType; //0x18 should be 1 to spot
ClientPlayer *m_spotterPlayer; // 0x1C
ClientPlayer *m_playerThatOrders; // 0x20
float m_lastOrderTime; // 0x24
```

Reference: https://github.com/Hattiwatti/BF3MinimapGenerator/blob/master/FB%20SDK/ClientSpottingTargetComponent.h

**Comment by kiwidoggie** [comment]
Do you have an example mod where you would find/get/use this entity?

**Comment by rierei** [comment]
This is a piece of code i've found on 'dark forums', that changes the behavior of BF3, i can send you the source if needed:

```c#
fb::ClientGameContext* g_pGameContext = fb::ClientGameContext::Singleton();
fb::ClientPlayerManager* pPlayerManager = g_pGameContext->m_clientPlayerManager;
eastl::vector<fb::ClientPlayer*> pVecCP = pPlayerManager->m_players;

int size = pVecCP.size();
for (int i = 0; i < size; i++)
{
    fb::ClientPlayer* pClientPlayer = pVecCP.at(i);
    fb::ClientSoldierEntity* pSoldier = pClientPlayer->getSoldierEnt();

    pClientPlayer->m_isAllowedToSpawnOn = true;

    fb::ClientSpottingTargetComponent* pCSTC = pSoldier->getComponent<fb::ClientSpottingTargetComponent>("ClientSpottingTargetComponent");
    if (POINTERCHK(pCSTC))
        pCSTC->m_spotType = fb::SpotType_Active;
}
```

This looks very plausible since SpotType enum, SoldierEntity and PlayerManager are already available on VeniceEXT. The usage on VU would be like this:

```lua
local players = PlayerManager:GetPlayers()
for _, player in pairs(players) do
    local soldier = SoldierEntity(player.soldier)
    soldier:MakeWritable()
    
    spottingTargetComponent = ClientSpottingTargetComponent(soldier.spottingTargetComponent)
    spottingTargetComponent.spotType = SpotType.SpotType_Active
end
```
This would work like a UAV mod that makes all players spotted.

**Comment by OrfeasZ** [comment]
Components are not currently supported in VEXT. Support for them will be added at some point in the future.

**Comment by FlashHit** [comment]
Fixed in build `19963`. Go to [changelog](https://docs.veniceunleashed.net/general/changelog/#19963) for more information.
