### ISSUE TITLE
[Req] execute modList.* commands from VEXT

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#531]
At the moment `modList.*` commands are not allowed to be executed from VEXT, but I would like to display which mods are running on the server and also let chosen admins add and remove mods.
So I need every `modList.*` command except `modList.Debug` and `modList.ReloadExtensions`.

so that's: 
* `modList.ListRunning`
* `modList.List`
* `modList.Available`
* `modList.Add`
* `modList.Remove`
* `modList.Clear`

**Comment by kiwidoggie** [comment]
`modList.Add`, `modList.Remove`, `modList.Clear` will never be made available (how are you supposed to keep executing a mod that gets removed from underneath you/causes crashes). I will investigate adding the List/Available as those should not change mod module state.

**Comment by kiwidoggie** [comment]
In 17184 (not deployed yet) `modList.ListRunning`, `modList.List`, `modList.available` have all been explicitly whitelisted for use with VEXT RCON. Others are still denied. Will revisit adding the rest of them once proper safety measures have been added to VEXT and RCON.
