### ISSUE TITLE
[Req] GetSpectatorCount() for client

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#532]
Something like `SpectatorManager:GetSpectatorCount()` or `PlayerManager:GetSpectatorCount()`

**Comment by kiwidoggie** [comment]
The PR for this has been completed, will close when accepted (and a build number is assigned)

`PlayerManager:GetSpectatorCount()` has been implemented for both the ClientPlayerManager and ServerPlayerManager

**Comment by kiwidoggie** [comment]
Pushed in build 17345
