### ISSUE TITLE
[Bug] Empty typeInfo.name on some VEXT types

### ISSUE THREAD

**Issue by rierei** [VeniceUnleashed/VeniceUnleashed#533]
The types **AxisAlignedBox**, **LinearTransform**, **Vec2**, **Vec3** and **Vec4** have an empty string for the typeInfo.name. VEXT documentation says that those types have typeInfo as static member. This happens in any server state, tested between the extension load and level destroy.

```lua
print(DataContainer.typeInfo.name)
> 'DataContainer'
print(Entity.typeInfo.name)
> 'Entity'
print(AxisAlignedBox.typeInfo.name)
> ''
print(LinearTransform.typeInfo.name)
> ''
print(Vec2.typeInfo.name)
> ''
print(Vec3.typeInfo.name)
> ''
print(Vec4.typeInfo.name)
> ''
```

Types that inherit from DataContainer and Entity work as expected.

**Comment by rierei** [comment]
Typeinfo is the only way to obtain the name from a VEXT type, because lua type() gives no useful information.

```
print(Vec4())
> userdata
```

**Comment by kiwidoggie** [comment]
Experimental patch for this has been pushed to the development build 17641. Still need larger testing to ensure everything is correct.

**Comment by rierei** [comment]
Some improvements on build 17641, Vec's now have a type name but no changes on **AxisAlignedBox**, also trying to access **LinearTransform.typeInfo.name** causes the game to crash.

```lua
print(AxisAlignedBox.typeInfo.name)
> ''
print(Vec2.typeInfo.name)
> 'Vec2'
print(Vec3.typeInfo.name)
> 'Vec3'
print(Vec4.typeInfo.name)
> 'Vec4'
```

**Comment by kiwidoggie** [comment]
Fixed in `17659` on development branch
