### ISSUE TITLE
[Bug] VEXT LinearTransform differs from EBX

### ISSUE THREAD

**Issue by rierei** [VeniceUnleashed/VeniceUnleashed#534]
The VEXT LinearTransform has a attribute named **left**, while in the EBX that same field is named as **right**. VEXT documentation:

Name | Type
-- | --
left | Vec3
up | Vec3
forward | Vec3
trans | Vec3

EBX files:
```
Transform::LinearTransform
    right::Vec3
    up::Vec3
    forward::Vec3
    trans::Vec3
```

**Comment by OrfeasZ** [comment]
That's by design.
