### ISSUE TITLE
[Bug] SpectatorManager ThirdPerson spectating not working

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#536]
Just played around with the SpectatorManager and it seems that `SpectatorManager:SetCameraMode(2)` and `SpectatorManager:SpectatePlayer(PlayerManager:GetPlayerByName("voteban_flash"), false)` are not working. It will say that it is ThirdPerson but it is the same as `SpectatorManager:SetCameraMode(0)`.

[testSpectator.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5411270/testSpectator.zip)

Repro: 
1. Spawn
2. Type in console: `testSpectator.SetSpectating true`
3. Type in console: `testSpectator.SetCameraMode 2` or  `testSpectator.SpectatePlayer <soldierName> false`

**Comment by OrfeasZ** [comment]
See https://github.com/EmulatorNexus/VEXT-Samples/tree/master/ingame-spec.

**Comment by OrfeasZ** [comment]
Keep in mind this mod is work in progress and doesn't have third person support yet.
