### ISSUE TITLE
[Crash] fb:// image crash after rejoining RM server

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#539]
@kiwidoggie looked into this crash and found out its related to fb:// images. 
```
[09:55] kiwidog: it's crashing on the texture loading code somewhere
[09:56] kiwidog: says canceling request 4 times
[09:56] kiwidog: fb://
```
So I tried disabling all uses of those images and it fixed the crash.
To repro you need a RM server on ``features/round-reset`` branch. You need to join with 2 clients, and with the second one you have to leave and then rejoin the server. Doesn't always crash, so you might have to rejoin more than once. Probably easier to tell me to set up the server and I'll join with my client, so you don't need to join with 2.
[Crash dump](https://github.com/EmulatorNexus/VeniceUnleashed/files/5469178/4ee17284-fdac-49f1-a2b3-e4e03f85cabc.zip)

**Comment by FoolHen** [comment]
Crash ID: d06bd09a-2445-44c9-b3dc-9fe5dbcde7a1
Build Number: 17264
Release Branch: dev

Crash ID: 3abfd88b-9f99-41ee-ae0b-855766e66dc9
Build Number: 17264
Release Branch: dev

Crash ID: 291a6980-b562-4624-b3d5-135861ee51f3
Build Number: 17264
Release Branch: dev

**Comment by OrfeasZ** [comment]
This should be fixed in `17301` which is being pushed to the dev branch right now. Please validate and let me know.
