### ISSUE TITLE
Lagging progress-circle while capturing points

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#54]
While capturing points in Conquest, sometimes the progress-indicator is lagging.
I couldn't replicate this on the next map. A player in the other team had the same issue.
Video: https://nocloud.xulunix.de/public.php?service=files&t=ffd409c85a52714cb9b26aa6d72cf906

**Comment by derrod** [comment]
This is a duplicate of #46
