### ISSUE TITLE
[Crash] Silent crash when standing nearby exploding static truck

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#542]
1. Reality Mod development branch
2. cd [...]Realitymod/webui
3. yarn
4. yarn build
5. Maplist -> XP3_Shield ConquestLarge0 2
6. Spawn in RU main, there's 2 of these white trucks
7. Stand close and put a mag into them
8. Silent crash

Video:

https://imgur.com/a/42d9DqT

**Comment by 3ti65** [comment]
Seems to also happen when the truck is out of visible range and killed by area attack. (Maybe something else that kills the server though, but only seems to happen when those trucks are around)

How to reproduce:

1. Realitymod/feature/area_strike branch
2. cd [...]Realitymod/webui
3. yarn
4. yarn build
5. Maplist -> XP3_Shield ConquestLarge0 2
6. Become Squadleader
7. Spawn in RU main
8. Map -> Right Click -> Context Menu -> Set Area Attack (aim at the different villages, you can set multiples in debug mode)
9. Silent crash

**Comment by FoolHen** [comment]
You can repro it on development branch now as well. Consistent crash, just aim the strike at buildings.

Crash ID: dafda0a4-dbd7-4b2a-bcaf-1ac7b56f10c6
Build Number: 17316
Release Branch: dev

**Comment by OrfeasZ** [comment]
This has been hotpatched in build `17335`. I'm still not sure as to what's causing it but you should no longer crash or experience mass crashes.
