### ISSUE TITLE
[Bug] Partition:Loaded client crash

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#543]
This code makes me crash:
```lua
Events:Subscribe('Partition:Loaded', function(partition)
    for _,instance in pairs(partition.instances) do
    end
end)
```
Repro Mod: [reproInstanceCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5575590/reproInstanceCrash.zip)

Just join a server and restart a map. -> Client will crash
```
Crash ID: 13b09af1-8771-4a33-a907-73e76a6d035a
Build Number: 17307
Release Branch: dev
```
[817a98bd-c179-4ba7-9ec7-6915c3b270b2.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5575599/817a98bd-c179-4ba7-9ec7-6915c3b270b2.zip)

**Comment by OrfeasZ** [comment]
This is fixed in build `17316`.
