### ISSUE TITLE
[Crash] VU loading / entity crash

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#544]
Crash ID: 94d20554-a047-402d-b0e8-42434cacd52f
Build Number: 17307
Release Branch: prod
joining server

Crash ID: b9794826-acb4-4c01-8d06-76cb3cb6f4fd
Build Number: 17307
Release Branch: prod
Loading Oman

Crash ID: 604cf01e-d6d0-44fa-ba99-dddc6bcadb30
Build Number: 17307
Release Branch: prod
loading in

Crash ID: b20cb7d0-e9e6-447d-a68a-bbda4006a96f
Build Number: 17307
Release Branch: prod
Joining server

Crashdumps from 20/11/2020 & 21/11/2020

So after camera fix, we located it to the humvee changes, which often crash silently. That never used to happen before either, just like the camera crash. Loading crashes happening at least as early as 8th of October according to Janssent.

**Comment by J4nssent** [comment]
Crash ID: 27b50424-be11-43f2-aad6-86bc84713728 from 8/10
Crash ID: a4e3dc74-be74-4c0a-87b6-8a7fed203705 from 25/10

**Comment by paulhobbel** [comment]
Crash ID: 76268368-ae27-47f6-a9a6-b6d411b2a9e1
Build Number: 17307
Release Branch: dev

**Comment by OrfeasZ** [comment]
Is there a way to easily reproduce this?

**Comment by FoolHen** [comment]
@OrfeasZ yeah, run RM with ``feature/vehicle_spawner`` branch. You will crash sometimes when joining.  ``XP1_002 ConquestLarge0 2`` for example.

**Comment by paulhobbel** [comment]
When enabling both humvees, the chance you'll crash is even bigger
