### ISSUE TITLE
[Req] enhance ControllableEntity

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#547]
https://docs.veniceunleashed.net/vext/ref/client/type/controllableentity/

Currently the ControllableEntity doesnt expose (according to the documentation) these fields:

```
class ControllableEntity
{
    public:
        BYTE pad_000[0x4];             // 0x00
        DWORD m_material;              // 0x04 MaterialContainerPair*
        INT m_teamId;                  // 0x08
        INT m_defaultTeamId;           // 0x0C
};
```

We need at least the teamId for Reality Mod and i guess it will also come in handy for a lot of mods.

**Comment by 3ti65** [comment]
would generally be nice, to have more control over vehicles, similar to players / soldiers.

VehicleManager / VehicleEntity etc

**Comment by kiwidoggie** [comment]
Implemented properties `TeamId ControllableEntity.defaultTeamId` and `TeamId ControllableEntity.teamId` for both Client and Server controllable entities. Pending testing before deployment.

**Comment by kiwidoggie** [comment]
Deployed in build 17336
