### ISSUE TITLE
[Req] CameraEntity

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#549]
To change the camera transform of the capture points, I need the ClientCameraEntity.
![Screenshot_39](https://user-images.githubusercontent.com/56718716/100529324-ae36d400-31e6-11eb-8045-1da45e0b7ee2.jpg)
I thought I could use `entity:PropertyChanged('Transform', LinearTranfrom(etc.))` but this wasn't working for me.

**Comment by OrfeasZ** [comment]
If you look at the docs you'll see that `CameraEntityData` inherits from `CameraEntityBaseData` which inherits from `SpatialEntityData`. This means that you can cast a `ClientCameraEntity` to a `SpatialEntity` and modify its [transform](https://docs.veniceunleashed.net/vext/ref/fb/spatialentitydata/#transform) property. Also, I believe that for camera entities specifically, you can modify the `transform` property in the entity data itself and that will replicate to the entity.

**Comment by FlashHit** [comment]
Oh alright thanks, I will use SpatialEntity then.

**Comment by FlashHit** [comment]
https://image.prntscr.com/image/SEUmLurKSi_3DkqEENOv0A.jpeg
https://image.prntscr.com/image/h9Pfl_kZTRu0xyL3ob1ZJg.jpeg
```lua
ResourceManager:RegisterInstanceLoadHandler(Guid('C98941E6-B300-4D5F-BC2E-ECA03DBF855D'), Guid('C4F7368E-4783-C08E-CBB9-66521D0AD158'), function(instance)
	if SharedUtils:GetLevelName() == "Levels/MP_001/MP_001" and SharedUtils:GetCurrentGameMode() == "ConquestSmall0" then
		instance = InterfaceDescriptorData(instance)
		instance:MakeWritable()
		instance.fields[3].value = 'LinearTransform ((0.98216074705124, 0.048190776258707, 0.18176361918449),(-0.0067436555400491, 0.97500890493393, -0.22206361591816),(-0.18792253732681, 0.21687638759613, 0.95794034004211),(4.077354431152, -0.392906188965, 22.938781738281))'
		instance.fields[4].value = 'LinearTransform ((-0.94940805435181, 0.048190597444773, 0.31032577157021),(0.10450667142868, 0.98031860589981, 0.16749280691147),(-0.29614654183388, 0.19145013391972, -0.93575859069824),(4.23112487793, 0.000360595703, -17.490152359009))'
	end
end)
```
This did it for me.
