### ISSUE TITLE
VEXT engine version shows wrong 

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#550]
![Screenshot_40](https://user-images.githubusercontent.com/56718716/100529583-30c09300-31e9-11eb-86e1-2e8197568c68.jpg)

Shouldn't this be `1.0.2` instead of `1.0.1`?

https://docs.veniceunleashed.net/vext/changelog/#1_0_2

**Comment by OrfeasZ** [comment]
Fixed in build `17335`.
