### ISSUE TITLE
[Req] Add a Player:getScorepoints event/hook

### ISSUE THREAD

**Issue by Maxinger15** [VeniceUnleashed/VeniceUnleashed#554]
I request do add a Player:getScorepoints event or hook which notifies when a player got new points.

This is my suggestion for that: 
function(player: playerObject, points : number, type: enum, isHeadshot : boolean, isRevenge : boolean, isComeback: boolean, extraPoints: number,playerInVehicle boolean)

Description:
- player: the player who got the points
- points: new Points the player got, fixed value for action like 250 for capture, 100 for a kill
- type: something like FLAG_CAPTURED, FLAG_DEFENDED, PLAYER_KILLED
- isHeadshot: true if the player got extra points for headshot
- isRevenge: true if the player got extra points for a revenge kill
- isComeback: true if the player got extra points for a revenge kill
- extraPoints: amount of the points the player got for headshot, comeback (points + extraPoints are the total amount)
- playerInVehicle: true if the player was in a vehicle when he got the points

Place:
- Server script

UseCase:
I need that for my killstreak mod to make it possible to adjust the killstreakpoints the player get for a action.  Unfortunately it is not possible to rework the source of the points exactly from the player.score property. This thing could be a useCase for some custom gamemodes too. It could be added as a hook that returns the scorepoints the player get if to make that easily modifieable or as a event to just get a detailed notification.

**Comment by FlashHit** [comment]
https://docs.veniceunleashed.net/vext/ref/fb/scoringdata/
https://docs.veniceunleashed.net/vext/ref/fb/statevent/
well that would contain a bunch of events

**Comment by Maxinger15** [comment]
Yeah that is true but I think that is neccessary because the score game mechanic currently hasn't a "API" (player.score is no API for me because its just a value without any additional information and it is not possible to recalculate what action happed when the score increments). The only thing I know is this [workaround](https://github.com/EmulatorNexus/Venice-EBX/blob/b80b49f6be7010b968eca36654e70819402fa259/Persistence/Scoring/Scoring.txt). But its just modify the internal values which changes the whole score system without any further interaction possibilities at the runtime or as in my case it is not possible to build a second standalone score system which is independent from the original one.

**Comment by CanT94** [comment]
I would also love to have that API. It could be useful for many custom gamemodes.

**Comment by FlashHit** [comment]
Implemented in `19412`.
`Player:Score` and `ScoringSystem:StatEvent` events are now available on the server.
