### ISSUE TITLE
RCON bugs vars.3pCam and vars.3dSpotting 

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#559]
according to Timm from XL Games the vars.3pCam and vars.3dSpotting are working reversed in the startup.txt, like: true = false, false = true. Doing it in the console works fine then.
This appears since one of the last updates.

**Comment by FlashHit** [comment]
Seems to also happen for vars.friendlyfire. Idk about the other ones

**Comment by kiwidoggie** [comment]
This has been fixed in experimental, will close when pushed to dev with a build number.

**Comment by kiwidoggie** [comment]
Fixed in dev build `17546`
