### ISSUE TITLE
console breaks open chat window.

### ISSUE THREAD

**Issue by summetje** [VeniceUnleashed/VeniceUnleashed#56]
When you open and close the console menu while you have a chat window open, then that chat window won't work anymore.
You can't type or control your character anymore until you close the broken chat window by pressing Esc.

**Comment by OrfeasZ** [comment]
That's also present in the retail version.

**Comment by OrfeasZ** [comment]
This has been implemented in the Advanced Chat mod.
Read [this](http://forums.veniceunleashed.net/viewtopic.php?t=7646) for more information.
