### ISSUE TITLE
[Req] Server browser sort by player count proportion instead of magnitude

### ISSUE THREAD

**Issue by SassythSasqutch** [VeniceUnleashed/VeniceUnleashed#560]
It would be useful if, when sorting by player in the server browser, the sort was done by proportion of players to player slots, e.g. 32/32 = 1 sorts higher than 64/128 = 0.5.

This would mean that it's more an indication of how full/empty a server is, rather than just the number of people in it, which seems like what people care about more.

**Comment by OrfeasZ** [comment]
People generally expect servers to be sorted by the number of players, not by their player to slots ratio.
