### ISSUE TITLE
[CRASH] 21/12/2020 17:07 GMT - Crashu During Promod Gameplay - Noshahr Canals

### ISSUE THREAD

**Issue by RaynorCZE** [VeniceUnleashed/VeniceUnleashed#561]
Adding crash Dump and .Checkpoint file into this thread, if any additional info required, feel free to contact me.

[21122020-1707-Noshahr-ProMod.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5725562/21122020-1707-Noshahr-ProMod.zip)

**Comment by OrfeasZ** [comment]
You refer to the [promod repo](https://github.com/kaloczikvn/kPM) and the issues there. See if anyone is experiencing the same issue as you and if not open a new one explaining what you were doing right before the crash so the mod developers can more easily identify the issue.
