### ISSUE TITLE
Indicate ip

### ISSUE THREAD

**Issue by Tiagox42** [VeniceUnleashed/VeniceUnleashed#562]
Sorry for bad English

I have a problem starting a server, my ports don't work because my internet has a dynamic ip or something, I already contacted the internet service and I was told I need a fixed ip to work, with minecraft servers this can be circumvented with no-ip a service that allows you to have a hostname in case they have a program where they take my ip and transform it into a correct ip, but I need to indicate the ip that no-ip provides me to start the server from, by default I believe that the VU takes the default ip of the machine to start the server, so in this case I need an option where I can choose this ip.

To try to understand in the minecraft wiki the option has the following description "**The player should set this if they want the server to bind to a particular IP. It is strongly recommended that the player leaves server-ip blank.**"

**Comment by kiwidoggie** [comment]
I do not believe having a dynamic IP would matter (as I host development server on a machine in my house) more than having all of your required ports needed opened. If your ISP is blocking certain ports (the ones VU needs, Game, and MHarmony) then you can try to change them to ones that are not blocked.
