### ISSUE TITLE
Add option to assign team/player to GameEntityData to prevent friendly fire

### ISSUE THREAD

**Issue by Maxinger15** [VeniceUnleashed/VeniceUnleashed#563]
I experimented to assign a team to a tv-rocket and the mortar shells to prevent players of the assigned team to be killed from that entity what didn't work. For the tv-rocket I used ControllableEntityData.defaultTeam.

For me it would me intuitive to assign it when I spawn the entity. 
Maybe give the Entity:Init method two additional parameters like teamId : TeamId  and player : Player.
Another option would be to implement this in the EntityCreationParams.
The player parameter should then assign the missile/rocket/projectile to the player so he get points on kills.

**Comment by FlashHit** [comment]
I think you can try setting the `ControllableEntity.teamId` to a new `TeamId` instead of the `ControllableEntityData`.
You have to be on the latest dev branch for that.

**Comment by FlashHit** [comment]
I guess I can close this one.
