### ISSUE TITLE
Corrupted or empty "PROF_SAVE_body" file causes the "Out of Memory" error

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#565]
Having a corrupted or empty settings file "PROF_SAVE_body" in your Battlefield 3/settings folder causes VU to crash with the "Out of Memory" error at startup.
The file probably got corrupted as i terminated VU due to a freeze.
Deleting the file solves the problem

**Comment by jmgraeffe** [comment]
Same problem, just so you know it's most likely not some weird hardware-specific thing.

**Comment by jmgraeffe** [comment]
Could it be that there is some dirty writing to the file due to opening multiple VU Clients at the same time? I use two instances of it for development reasons.

**Comment by OrfeasZ** [comment]
That's very likely.

**Comment by jmgraeffe** [comment]
Maybe it would be good if there were different directories for different accounts, with own profiles. But don't know what's in there exactly.

**Comment by kiwidoggie** [comment]
![image](https://user-images.githubusercontent.com/9152262/104095365-3929d600-524b-11eb-86e7-17e2cddacf36.png)

This image will appear if your profile is corrupted. Currently on experimental, will close the issue when it's pushed with a final build number

**Comment by kiwidoggie** [comment]
Closing as fixing this causes crashes elsewhere. Best solution is to just delete the files and let them regenerate.
