### ISSUE TITLE
invalid soldier names?

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#567]
People can create soldier names that are containing spaces only.
I don't think allowing spaces at all was a good idea but only spaces? I don't think this is intended.

**Comment by OrfeasZ** [comment]
This is a known issue and will be fixed in an upcoming backend update.

**Comment by kaloczikvn** [comment]
Created a soldier with the name `<h1>Hello</h1>`. Modders should escape player names if they use it in the UI, but it would be better to escape names before creating a soldier I think.
