### ISSUE TITLE
Sound Issue when closing VU forcefully 

### ISSUE THREAD

**Issue by timbachi** [VeniceUnleashed/VeniceUnleashed#570]
VU causes a weird sound Problem when forcefully closing the program (alt f4 or task manager) which doesnt stop till i restart my computer. 
Im on WIN10 build 18363, Asus Xonar DGX sound card

**Comment by OrfeasZ** [comment]
You could try deleting your BF3 profile settings from `My Documents/Battlefield 3/settings` (though keep in mind that this will reset all your setttings).

**Comment by kiwidoggie** [comment]
@Timtanium Has this issue been resolved for you with the provided fix?

**Comment by timbachi** [comment]
No, sadly not. I deleted my settings but the issue stil occurs.

**Comment by timbachi** [comment]
Okay guys, I found the issue. It seems like my audio driver is bugged. It works when I turn off GX-Mode in the xonar control center. It seems like the problem is not VU's fault.
