### ISSUE TITLE
Cant acces escape menu when watching kill cam

### ISSUE THREAD

**Issue by RAMBOR47** [VeniceUnleashed/VeniceUnleashed#571]
When killed (by player or admin) I cant acces the menu that normally appears when pressing escape

**Comment by FlashHit** [comment]
this is the default BF3 behavior. 
Maybe someone can make a mod that allows it.

**Comment by RAMBOR47** [comment]
Yeah but it also forces you out while you are changing settings or something. I think this should be changed

**Comment by FlashHit** [comment]
that's what mods are for :nerd_face:

**Comment by kiwidoggie** [comment]
This is an issue for: https://github.com/Powback/BF3-Bugtracker

The behavior is working as intended in VU.

**Comment by RAMBOR47** [comment]
Thanks for your clarification, I will put it in the BF3 bugs soon
