### ISSUE TITLE
Spawning on squadmates not blocked

### ISSUE THREAD

**Issue by cat24max** [VeniceUnleashed/VeniceUnleashed#576]
I was told this also happens in TDM, but my experience is coming from Rush:

When the Defenders loose a base, squadmates should not be able to spawn on teammates that are in the new attacker base. They should only be able to spawn on a teammate that is in the defender base or close too it.

This is a massive issue in regards to balance, because this limitation is intended to slow spawnrape.

Steps to reproduce:
1. You need two players, load up Damavand Peak Rush and both join Defenders.
2. Player 1 should move in the direction of attacker spawn.
3. Player 2 should not be able to spawn once Player 1 gets too far away from the base.
4. Player 2 is able to spawn.

**Comment by FlashHit** [comment]
Repro in TDM is even faster I guess.

https://user-images.githubusercontent.com/56718716/153759636-a0610c78-cf99-4ebf-b6e8-de82940dbe96.mp4

**Comment by kiwidoggie** [comment]
Think https://github.com/EmulatorNexus/VeniceUnleashed/issues/559 is related, will ask you to re-test when the new build is out.

**Comment by cat24max** [comment]
@kiwidoggie I don't think this is solved

**Comment by FlashHit** [comment]
I kinda think that it's the `AutoTeamEntity` which has a `DisableAllowedToSpawnOn` event. This doesn't get triggered on Conquest but it does in TDM. The problem is that it does nothing. The `AutoTeamEntityData` has also some properties like `.rotateTeamOnNewRound = true` which did nothing when I set it to `false`.
Might be wrong and this is not relevant, but just in case that this could be related, here is my script:
```lua
Events:Subscribe('Level:Loaded', function()
	local s_AutoTeamEntityIterator = EntityManager:GetIterator("ServerAutoTeamEntity")
	local s_AutoTeamEntity = s_AutoTeamEntityIterator:Next()
	
	while s_AutoTeamEntity do
		s_AutoTeamEntity = Entity(s_AutoTeamEntity)
		s_AutoTeamEntity:RegisterEventCallback(function(ent, entityEvent)	
			print('AutoTeamEntity: Received entity event of type ' .. entityEvent.type .. ' and id: ' .. tostring(entityEvent.eventId) .. " from entity " ..  tostring(ent.data.instanceGuid))
		end)
		s_AutoTeamEntity = s_AutoTeamEntityIterator:Next()
	end
end)
```

**Comment by FlashHit** [comment]
https://github.com/Hattiwatti/BF3MinimapGenerator/blob/master/FB%20SDK/ClientPlayer.h#L77
Or maybe sth is wrong with the (client) player.isAllowedToSpawnOn which isn’t exposed in VU.

**Comment by kiwidoggie** [comment]
The class you posted is irrelevant (as server allows the spawn, not client). 

This should work instead: https://docs.veniceunleashed.net/vext/ref/server/type/player/#isallowedtospawn

**Comment by kiwidoggie** [comment]
Also, cannot repro. Ensure that you didn't have deserting enabled.

I did these repro steps.

Damavand Peak, Rush

Myself dead on defenders in spawn menu,
Spawn Squadmate (Defender) in attacker controlled area,
Attempt to spawn
Server rejects spawn.
