### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by auschwinx** [VeniceUnleashed/VeniceUnleashed#577]
Crash ID: 4acfe6ef-e8da-4c8e-a4bb-62c8849c9591
Build Number: 17384
Release Branch: prod

**Comment by auschwinx** [comment]
Crash ID: 00e0700d-9c79-4323-a5d9-46fb07aabba8
Build Number: 17384
Release Branch: prod

**Comment by kiwidoggie** [comment]
Disable Discord Overlay and let me know if that fixes your issue.

**Comment by OrfeasZ** [comment]
This crash was caused by SteelSeries software and VU works after disabling it.
