### ISSUE TITLE
Squads not getting assigned properly in Squad Deathmatch

### ISSUE THREAD

**Issue by lywit** [VeniceUnleashed/VeniceUnleashed#578]
Whenever someone switches teams in Squad Deathmatch, there are 2 squads that work correctly. But there's also 2 squads that, when switching to them will assign you into their team but won't put you into the squad. You'll be considered as "Not in a squad" and won't be able to spawn on your teammates.

**Comment by OrfeasZ** [comment]
This should be fixed in build `17539`.

**Comment by Joe91** [comment]
On the current -dev build this is not working anymore and exactly how @lywit describes it.
Build-number = 17573
Vext-Engine = 1.1.2

@OrfeasZ can you reponen this issue?
Thanks in advance!
