### ISSUE TITLE
VeniceEXT HTTPS Request fails on Linux (Certificate validation error)

### ISSUE THREAD

**Issue by tkoschka** [VeniceUnleashed/VeniceUnleashed#579]
Hello, 

following line of code does not work on my linux hosted servers.
`res = Net:GetHTTP("https://gitlab.com/n4gi0s/vu-mapvote/-/raw/master/mod.json");`

The error I'm getting:
` [VeniceEXT] HTTP Request failed with error ‘Certificate validation error: Failed to verify certificate chain: CA not trusted’.`

Afaik wine should use the certificates installed on the linux machine just fine, I don't know why it doesn't do it in this case. Just another quirk of hosting vu on linux, that should maybe investigated later.

**Comment by tkoschka** [comment]
Additional Information:
System: Ubuntu 20.04 64bit
Running latest wine.

Here is the mod where I encountered the problem: https://gitlab.com/n4gi0s/vu-mapvote
The author tried to fix this by deactivating cert verification like this:
 ```
    options = HttpOptions({['verifyCertificate']=false}); --ignore cert for wine users
    res = Net:GetHTTP("https://gitlab.com/n4gi0s/vu-mapvote/-/raw/master/mod.json", options);
```
This did not help, this is why I suspect a problem with VeniceEXT / the lua interface when running wine.

**Comment by OrfeasZ** [comment]
This should be fixed in build `17485`. VU comes with a pre-bundled set of CA certificates that it uses for validation (which was probably outdated). You can override the one it uses by passing the `-cacert` parameter with a path to a custom CA bundle.
