### ISSUE TITLE
"APPCRASH" at launch "nvwgf2um.dll"

### ISSUE THREAD

**Issue by yemreck** [VeniceUnleashed/VeniceUnleashed#58]
i could play on my dirty windows 8 installation. i formatted my pc and installed windows 7. I tried to start venice unleashed game came. around 3-5 i could access console but after crashed and gave me "APPCRASH" and "nvwgf2um.dll". I got windows 10 preview for recovery etc.. I tried to play on windows 10 preview it crashed again but didnt give anything only "program stopped working" message
Edit: its a nvidia d3d dll and i got latest version of driver.

**Comment by ghost** [comment]
@keepdying 
This is probably a driver problem:
https://forums.geforce.com/default/topic/528454/geforce-drivers/dx10-11-games-crashing-nvwgf2um-dll/

**Comment by OrfeasZ** [comment]
This is probably a duplicate of #82 so I'll assume it's fixed and I'll close it.
