### ISSUE TITLE
[Req] Taking screenshots against questionable players

### ISSUE THREAD

**Issue by rierei** [VeniceUnleashed/VeniceUnleashed#581]
Game server bans can be easily bypassed by creating other account with the same origin license, making the only effective way to ban a player through a VU account ban, which requires staff intervention. Give server owners option to trigger client screenshots that are automatically uploaded to the game server and VU backend. That provides a solid evidence about questionable players, making easier to VU staff check player behavior.

**Comment by OrfeasZ** [comment]
Server owners can ban people by their account guid (that's the default behavior of the guid-based banning methods) which prevents the player from joining, regardless of whether they create a new account or not.

Allowing capture of a user's screen and server admins to arbitrarily inspect those screenshots would be a severe violation of privacy and not something that will be added ever.
