### ISSUE TITLE
GetCameraTransform() can cause silent crashes in specific hw/driver configurations

### ISSUE THREAD

**Issue by kapraran** [VeniceUnleashed/VeniceUnleashed#583]
[This commit](https://github.com/kapraran/vu-compass/commit/e0a6f4240b0c23f14fc8e42374d105fd3a0e202c) on `vu-compass` mod, has caused silent crashes for some players **right after they spawn**. I added a falsy value check for the result of `ClientUtils:GetCameraTransform()` but it didn't help. 

I cant reproduce it on my hardware, but @gevi may be able to help you with that.

Here is a sample version which can cause crashes. Check `client/__init__.lua : lines 76-87`.
[vu-compass-exp2.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5789742/vu-compass-exp2.zip)

**Comment by kapraran** [comment]
So, we did some extra testing with @gevi and it seems that `GetCameraTransform` works as expected for him too. We did many tests and it starts printing the expected values immediately after he spawns (i had `GetYPRFromULF` commented out).

When i tried to print the result of  GetYPRFromULF, gevi crashed and in my case it is printing these
```
(-0.000000, -0.000000, -1.000000) (0.083552, 0.996503, -0.000000) (0.996503, -0.083552, -0.000000) (46.313782, 14.655130, -1.258547) <--- this is the input LT
(4.712389, 3.225242, -nan(ind)) <-- the result of `GetYPRFromULF`
```

It didn't cause any crashes for me, and i only use the .x value for my mod, but this `-nan(ind)` may be the reason for his crashes?

You also may need to update the title of the issue.

**Comment by kiwidoggie** [comment]
Are you checking to see if the transform is nil before using?

Edit: After checking I've created this issue https://github.com/EmulatorNexus/VU-Docs/issues/48

The ability to return nil was not described properly and this is a documentation issue.

**Comment by kapraran** [comment]
I did one test with that too but it didn't changed anything. Also, it never returned nil even on gevi's machine. It's always a valid LinearTransform, like the one in the example. 

When i pass those LTs to `GetYPRFromULF`, i get these `(number, number, -nan(ind))` on my machine and on gevi's machine it crashes.

**Comment by FlashHit** [comment]
Did this got fixed?

Copied the transform above:
```lua
local s_Transform = LinearTransform(Vec3(-0.000000, -0.000000, -1.000000), Vec3(0.083552, 0.996503, -0.000000), Vec3(0.996503, -0.083552, -0.000000), Vec3(46.313782, 14.655130, -1.258547))
print(MathUtils:GetYPRFromULF(s_Transform.up, s_Transform.left, s_Transform.forward))
```
Returned:
```
(4.712389, 3.225242, 3.141593)
```

So for me `roll` is not returning `-nan(ind)`

Here as a repro mod:
[ReproGetYPRFromULF.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6931990/ReproGetYPRFromULF.zip)

Can you check this @kapraran?

**Comment by kapraran** [comment]
I get this as the response, so its probably fixed.
Although, I wasn't the one that was crashing, so not 100% sure.

```
(4.712389, 3.225242, 3.141593)
```

**Comment by FlashHit** [comment]
Btw even in prod (17487) it works fine.

**Comment by FlashHit** [comment]
```lua
LinearTransform(Vec3(-0.433542, -0.000000, -0.901134), Vec3(0.536520, 0.803441, -0.258124), Vec3(0.724008, -0.595384, -0.348325), Vec3(-396.957245, 190.302765, -1131.557373))
returns -> (5.160808, 3.779336, -nan(ind))
```
the [RotationHelper](https://github.com/BF3RM/MapEditor/blob/development/ext/Shared/Util/RotationHelper.lua#L13) returns: `{ 1 = 5.160808, 2 = 3.779336, 3 = 3.141592 }`

**Comment by FlashHit** [comment]
Same as #692
