### ISSUE TITLE
ChatManager:SendMessage weird character issue

### ISSUE THREAD

**Issue by kaloczikvn** [VeniceUnleashed/VeniceUnleashed#584]
Client calls `ChatManager:SendMessage("öüóőúéáű")`, server recives weird characters on the `Player:Chat` event. `UI:CreateChatMessage` hooks message parameter prints out wrong characters too.

https://prnt.sc/wjvym4

Example mod:
[ChatBug.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5791654/ChatBug.zip)

**Comment by kaloczikvn** [comment]
Might be a duplicate of https://github.com/EmulatorNexus/VeniceUnleashed/issues/527

**Comment by kiwidoggie** [comment]
I believe that these are similar issues, but will link the issues together and close this one.
