### ISSUE TITLE
[Request] Find entity by instanceId

### ISSUE THREAD

**Issue by MerelyMezz** [VeniceUnleashed/VeniceUnleashed#587]
`Entity EntityManager:GetEntityWithId(int instanceId)`

Fetches entity with specified instanceId in constant time, without needing to iterate through a whole list of entities.

**Comment by Mezzokoko** [comment]
While trying to implement this myself in lua, I've actually come upon the fact that uniqueId appears to always be 0, so having that work first would be cool too.

**Comment by FlashHit** [comment]
I think there is no other solution then looping, not sure.
But even then it would be still a good method to easily get an entity without saving a reference, even when it will still iterate all entities.

So it would be nice if you could implement this in VU, if there is no better method.

```lua
function GetEntityByInstanceId(instanceId)
	local s_Entity = nil

	EntityManager:TraverseAllEntities(function(p_Entity)
		if p_Entity.instanceId == instanceId then
			s_Entity = p_Entity
			return false
		end
	end)

	return s_Entity
end
```

**Comment by OrfeasZ** [comment]
There is currently no way to do this that wouldn't be sketchy and cause performance or security issues, as `instanceId` is basically similar to memory address to that entity.
