### ISSUE TITLE
[Bug] WebUI process crashed

### ISSUE THREAD

**Issue by paulhobbel** [VeniceUnleashed/VeniceUnleashed#590]
In a recent playtest we had at RealityMod one of our testers had the unfortunate bug where his WebUI got stuck. After some investigation it seemed like the CEF process crashed, also the WebUI inspection tool was not responding anymore.

Footage where the frozen UI can be seen: https://youtu.be/zBxr4XEI5ag
As seen even css hover attributes are not working aymore, hence why we checked out whether the process itself was maybe crashed.

Also the inspector of the mod itself is not accessable as seen here, this is while ingame on RealityMod after the UI froze:
![unknown](https://user-images.githubusercontent.com/20015650/105641865-84b4c480-5e86-11eb-8ea7-486822aa7d8f.png)

**Comment by paulhobbel** [comment]
Can confirm the same exact thing happens on MapEditor. We have some people that can reproduce it for you incase you need more details

**Comment by 3ti65** [comment]
pc specs for someone that has the issue the most:

----------------------------

Operating System: Windows 10 professional
19041.746
Build 2004
installed on 7/3/2020

----------------------------

CPU: Intel® Core i7-8086K, 4.0 GHz (5,0 GHz Turbo Boost) (Delid Liquid Metal)
Graphics Card: GIGABYTE AORUS GeForce GTX 1080 Ti Xtreme Edition 11G
Motherboard: ASUSTeK COMPUTER INC. ROG MAXIMUS X HERO
Storage: 2x M.2 Samsung 512 GB, 970 PRO SSD (Raid0)
Storage: 1x M.2 Samsung 1 TB, 980 PRO SSD
Storage: 3x 4TB Seagate 7200 RPM
RAM: G.Skill 16 GB DDR4-3200 Kit
PSU: Thermaltake Toughpower iRGB Plus Platinum 1050W
Cooler: Thermaltake Floe Riing RGB 360 Premium
Monitor: 2x Phillips BDM3275UP with IPS-AHVA panel
Mouse: Logitech G502 Backup Mouse: Logitech M570
Keyboard: Logitech G19 Backup Keyboard: Mac keyboard (the old "good: one)
Headset: Logitech G933 Backup Headset: Logitech Premium notebook headset
Mousepad: 1994 Looney Tunes Taz-Mania mousepad (Quality shit man)

----------------------------

internet xs4all zakelijk 200 mbps with 2ms delay to main node Arnhem. Full fiber connection to the box with cat7e cable to PC

**Comment by 3ti65** [comment]
@paulhobbel add repro mod to this issue

**Comment by paulhobbel** [comment]
I can't reproduce on my own pc :(

**Comment by paulhobbel** [comment]
Related to #720, the WebUI process crashes because the game runs out of memory

**Comment by paulhobbel** [comment]
We're in the process of upgrading CEF which potentially fixes this issue. Using #871 as reference

**Comment by FlashHit** [comment]
Potentially fixed in build `19963`. Go to [changelog](https://docs.veniceunleashed.net/general/changelog/#19963) for more information.
