### ISSUE TITLE
[BUG] Nametags hooks (+ REQ)

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#591]
The following hooks doesn't work. Unless there is some secret trick.
```
UI:DrawEnemyNametag
UI:DrawFriendlyNametag
UI:DrawSquadNametag
UI:NametagsShouldUpdate
```
It would be nice to have a **parameter for the tint**. There are color properties in [here](https://github.com/EmulatorNexus/Venice-EBX/blob/master/UI/UIComponents/UINametagComp.txt#L54) but they don't work. This would be nice for a FFA mod where all teammates have the same color as the enemies so we are not limited to the 16 TeamId's. A BattleRoyal mod would also need this probably.

These work, but I have no idea where the difference is.
```
UI:UpdateNametagIcons
UI:DrawNametags
UI:DrawMoreNametags
```

**Comment by kiwidoggie** [comment]
This was fixed in build 17490.
