### ISSUE TITLE
[Bug] VisualEnvironmentEntityData visibility

### ISSUE THREAD

**Issue by GreatApo** [VeniceUnleashed/VeniceUnleashed#597]
I create a ```VisualEnvironmentEntityData``` with a visibility value which can be changed after creation but the in game entity visibility is not updated (destroy and recreate entity obviously works).

```lua
-- Entity is created
local mydata= VisualEnvironmentEntityData()
mydata.visibility = 1.0
mydata.priority = 999999
preset = EntityManager:CreateEntity(mydata, LinearTransform())

if preset ~= nil then
	preset:Init(Realm.Realm_Client, true)
end

------------- other part of the code ----------------

-- Change visibility
local states = VisualEnvironmentManager:GetStates()
for _, state in pairs(states) do
	if state.priority == 999999 then
		state.visibility = 0.5 -- value changes but in game environment is not updated
	end
end

**Comment by OrfeasZ** [comment]
You need to call `VisualEnvironmentManager:SetDirty(true)` after any changes to the VE state.

**Comment by GreatApo** [comment]
@OrfeasZ thank you for your answer, it works :)
 As far as performance is concerned, does ```VisualEnvironmentManager:SetDirty(true)``` recreates all the elements?

**Comment by OrfeasZ** [comment]
I don't think so. I would recommend against doing it every frame just in case.
