### ISSUE TITLE
Black Screen Flickering on certain occasions

### ISSUE THREAD

**Issue by MizuDG** [VeniceUnleashed/VeniceUnleashed#60]
At first, it seemed like an issue that happened only while my TV was on as a second monitor, but since recently, I rolled back an Nvidia Driver and it's happening without the TV being on. It occurs when:

I open or close the map (M)
Change the map size (N)
Get killed (which I don't see how it's connected)
and I'm currently trying to find out more.

https://www.youtube.com/watch?v=PJfaF_XNZdM&feature=youtu.be (Recorded with phone)

https://www.youtube.com/watch?v=Tle-LATGBHM&feature=youtu.be (Recorded with Shadowplay without TV on)

**Comment by Xulunix** [comment]
can confirm this, happens in vanilla too

**Comment by MizuDG** [comment]
Doesn't happen in vanilla for me.

**Comment by ghost** [comment]
Install the latest driver. Are you using the same monitor and settings when playing vanilla BF3 and Venice Unleashed?

**Comment by OrfeasZ** [comment]
@MizuDG If you keep pressing N or M down do you get a consistent black screen?

**Comment by MizuDG** [comment]
No

**Comment by MizuDG** [comment]
Note: When I see the black screen, the FPS counter from Shadowplay disappears.

**Comment by OrfeasZ** [comment]
@MizuDG Take a look at https://forums.geforce.com/default/topic/516972/bf3-screen-goes-black-when-i-die-bf3-bug/
