### ISSUE TITLE
[Soldier creation] Name already taken, Usability (Could not create soldier. Please try again later)

### ISSUE THREAD

**Issue by Bizarrus** [VeniceUnleashed/VeniceUnleashed#600]
If you're creating a soldier on VU where the name is already taken, the error message `Could not create soldier. Please try again later.` appears.

It has happened several times in a short time that users ask for it because they can't create a Soldier.

The whole thing is just a misunderstanding at VU itself: The error message that the desired name is already assigned must be adjusted.

**Comment by OrfeasZ** [comment]
This is fixed in build `17532`.
