### ISSUE TITLE
Cannot sync Origin acc to VU

### ISSUE THREAD

**Issue by joaovictor-martins** [VeniceUnleashed/VeniceUnleashed#604]
No success trying to sync my origin account to VU. I have tried launching the game from Steam and Origin, Running Both Steam and Origin on admin mode, restarting my computer, re-logging from origin. Closing all programs and restarting them with no success. I still get a message saying an error occurred while communicating with Origin.

**Comment by OrfeasZ** [comment]
With Origin open and VU at the linking screen, after pressing "Retry" can you open your console with the `~` key and show me what you see there?

**Comment by kiwidoggie** [comment]
@joaovictor-martins Were you able to attempt the steps above/do you still have the same issue?
