### ISSUE TITLE
[Client] Your game ran out of memory

### ISSUE THREAD

**Issue by Subdarub** [VeniceUnleashed/VeniceUnleashed#607]
After about 30-45 mins of play the game will crash with an out of memory error.
Does anyone know the root cause of this, or is this something that hasn't been talked about yet?

The error also tells me that this may be caused by a mod.
The server i am playing on is this one:

![image](https://user-images.githubusercontent.com/35487480/107267567-5d91f180-6a47-11eb-9b8a-de6004ca05d6.png)

Specs:

Windows 10 2004
RTX 2060 6GB Vram (Driver Version: 460.79)
32 GB of RAM
i9 9900k

**Comment by OrfeasZ** [comment]
This is a known issue with the pink server. Afaik the admins are currently investigating it.

**Comment by Subdarub** [comment]
> This is a known issue with the pink server. Afaik the admins are currently investigating it.

Cheers for letting me know, i guess i can close the issue then.
