### ISSUE TITLE
[Crash] Crash possibly related to NetEvents

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#609]
This crash is usually silent, but my brother has an error dump when it happens to him. Seems to be triggered by completely different actions in the mod, for example when using a field dress or spawning. All seem to have NetEvent calls in common, so NetEvents being the cause is a informed guess.

```
Crash ID: 676d1197-7b84-41b5-bd75-2db25f4d66f8
Build Number: 17384
Release Branch: prod

using the bandages
```

This one might be the same crash:
```
Respawning

Crash ID: aa30ef6f-83a2-44bb-b80f-380586d9eb1a
Build Number: 17384
Release Branch: prod
```

This one is kinda old, but same issue. @OrfeasZ you already checked it (https://discord.com/channels/@me/578663798450421762/785249511508672522) and said you had to look more into it. There are 2 more crashes from the same day from him, but we dont have their crash id, they might be on the dumps server.
```
Crash ID: 69a03e7f-095f-4fec-9854-a68ebbe14b00
Build Number: 17169
Release Branch: prod

I was trying to use the bandages.
I think it was when pressing control, t, and LF click at the same time.
I had this crash 3 times in the play.
```

**Comment by kiwidoggie** [comment]
[Playground.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6018794/Playground.zip)

NetEvents Stress Test, unable to reproduce. Maybe there's more too it (or mod doesn't stress enough?)

**Comment by kiwidoggie** [comment]
Is this still applicable or some of the things been fixed already?

**Comment by FlashHit** [comment]
@kiwidoggie I think this is fixed.
