### ISSUE TITLE
I dont have permission but I can play EA BF3

### ISSUE THREAD

**Issue by blackhawkfalled** [VeniceUnleashed/VeniceUnleashed#61]
I used to play _**. Because the EA BF3 is too hard for me in Asia zone.
Yesterday, I changed the folder of the *_\* from "Battlefield 3" into "Battlefield 3 cracked"/

Then redownload one from origin.
"It is freshed downloaded and installed directly from Origin"
Play EA Bf3 at once to make sure it works.
Next download the veniceunleashed.msi

After the Installation, it still warns me 
"Failure"
"Failed to start the Battlefield 3 process,
Do you have the required permissions?"
Help!

**Comment by blackhawkfalled** [comment]
BTW, I have the BETA KEY.

**Comment by Xulunix** [comment]
don't know what **\* messes up
try to use the Repair function in origin

**Comment by blackhawkfalled** [comment]
reapired, but still have the same problem

**Comment by OrfeasZ** [comment]
Make sure that the HKEY_LOCAL_MACHINE\Software\EA Games\Battlefield 3\Install Dir key in your registry points to the correct BF3 installation folder and that the folder contains an unmodified bf3.exe.
After you verify that, if you're still getting the same error, try running vu.exe as an administrator.

Also, please refrain from discussing illegal third-party projects.

**Comment by blackhawkfalled** [comment]
Im sorry to mention that ..
Can you tell me the detail about the registry points?
becuase I dont have the Battlefield 3 folder under the EA games..

**Comment by OrfeasZ** [comment]
@blackhawkfalled Take a look at issue #28

**Comment by blackhawkfalled** [comment]
![image](https://cloud.githubusercontent.com/assets/10581573/5792705/2e7fd13a-9f61-11e4-8998-6852fa3d822b.png)
should it be like this?

**Comment by OrfeasZ** [comment]
@blackhawkfalled
The **GDFBinary** and **Install Dir** keys should point to wherever your vanilla BF3 copy is installed.
So if your installation folder is anything different than **D:\Games\FPS\Battlefield 3** you need to change it.

**Comment by blackhawkfalled** [comment]
thx . It works after I set vu.exe with administrator . Thx for your help and sorry for my noob..
