### ISSUE TITLE
[Req] Community Server browser and chat overlay, and eventually accessible chat & specialised server browser

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#610]
WIP
Edit: Final

### **motion**, marketing & code
 Title
### the meta methods behind the code of assembly in a so cross-platform scenario VU.

Introductory & concluding statements on the reference provided: This manuscript is not and nowhere a formatted scripting fix its. its easily the philosophical message between conflicting parties of 1 body or a case and that badly connected to a marketing incourse of action on the by definition marketing averse modding world.

As a perspective anfor individual action in an open platform sandbox subplatforming is its mayor issue because it is lacking a target group its accessibility is its mayor issue. to improve multiple letters of brief communications are required to be written to represntatives of each vu server as a platform entity alternatively development of vu can make this redundant. Explanantions will follow in a second.

 less so a script tho some practical concepts are assembled and contextually referenced.

Be aware this is an open study meaning is yet a big draft. Like an ad run down ad as well as a developer script and inherently unstructured towards the end. Logically summarizing it again and again is not done.

Edited: May 19th
The open platform VU has a marketing responsibility.
concept
### Procuring Server developments & Modding interests by concentrating marketing efforts with platform expanding self-organizing forms of marketing -connecting offer with demand and more.

**Action Abstract**
Community action to events
Community Server browser and chat overlay
and eventually accessible chat & specialised server browser
**Abstract plan**
0. open discussion and communication perhaps guidelines for new server hosters from what is raids to what is an  event -"themed", spatialised, specialised categories,  leadin to openess cross server/platformg to  self advertising 

Here i ask admins to brand and share information about their "brand" so they can target players to their server

0.1 events for raiding and promotion, 

0.2 or vu push notification update for live event info ads on servers

4. ads on browser pinnwall or live feed

1. an overlay for raiding from server

2. a serverbrowser independant from the overlay

Assembling players with dynamic concepts would imply
A. ) Could excite mayor innovation & player dynamics so far limited to 1 censored chat 
by the conflicting interest options of 1 monopolising agent admin.

I think its legit to think this fixes balancing once and for all, disambiguition server autobalancing, 

over plenty servers on huge player servers and small servers with predictable server side + server type specific rank filters for in round joining players in the future.
B. )Realising old promises. 
Allows tight tactical edge evolved and _skill dynamic naturally developed to player flow over many servers full maps._
C. )Could attract & assemble / host (no friendsystem required) new and old bf3 player groups.

benefits
3 More diverse playerbase
3 Less skill oriented squads
3 More girls, more hype
4 More adult
3 More servers
3 More community will invite more guilds
3 more gilds invite teams
4 will invite more mods, more quality
4 more diverse maps accepted by all
5 More success for you.
5 More easy competition
5 Price money on tournaments by viewer donations for vivid teamplay

**organizing specific content servers enables self procuring communities to more inviting environments for esport**

serves all players while maintaining all the freedoms at low cost providing organized room for alternative styles, teams and or skill.

Introduction:
 Easy self structuring servers create diverse less solo skill more player type based environments with  fictionally lower skill rating naturally.  Finding the range in battlefield autobalancing for skill and impact based on players seems impossible,  While that is too complex, the problems could be solved like casual players think by giving them room to play. At the end trends and accessibility should do, what filters did in the past. 
 Replayable bf community and esport with all the content
In the perfect case a round should end, when leading players leave the server and call it a surrender. And new players should know the game to expect should accept to spectate, until the new round. This could be easy on conquest if the serverbrowser said how high ticket difference or afk rate on the loosing side. Points shouldnt matter. 

Servers can evaluate a simple trend; only recording the links opened and i.e. number of refreshs and recommend close servers that may be viable - those not empty ones. for instance players who were good went to- players who werent good went to. Once the server sends the trend the serverbrowser learns super categories that commends the players faster.

 At the same time the player gets to express, play, develop and learn his style even with his squad on a wider base of servers with varying yet better balanced server skill level.  teamplay. The control comes from the player type who stays on the server.Naturally more skilled players might look for competition and there is the room for All. 

the mechanism also goes into overpopulated unbalanced servers by allowing inactive players or ineffective players an easy exit into a possible room- that is organised in realtime with his teammates in the same situation. This cascades into a nice server balance  right away. Once the server balancing catches up.
 
If a very good player is in the server he will be autobalanced because there are pro players few good and the normal ones, but he will feel bored very fast because the players are playing indifferent to him his style. 

At the end of the round the server can be reduced in size again because the game is better and the server full again (maybe)

The players learn that they can affect their playerbase naturally and will remember that last server and not the bad game  before. The new servers will be active in memory from then on. populated by players of onelevel type. Then they can learn  goother ways play creatively, their style, strategically ... because there is no right way.

### Abstract
 Overlay a serverbrowser while on server or add chat to the classic server browser -  a feature for 1proposing a certain server to raid  and 2voting to raid that server. 
 

 
 To get a community back we need new rules for an accessible range of servers 

 

### Meta
  improve bf3 accessability with different serverbrowsers and chats optimised for planned, small "events", more used active servers & familiar player styles
 
 Beta Phase Serverbrowser overlay
 
 Phase 1 Balancing the Method

 Phase 2 Allowing serverbrowserside Recommendations
 
 Phase 3 Trends for all players
 
 Phase 4  for tournaments or recommended servers
 
 
 Stage 1 complete: Balancing all the servers without new autobalancing 

 

 
###  Serverbrowser overlay

 version 1
If on the server a serverbrowser can be used for a percentage of players to change their game together by reassessing and voting for a new event together on another server.

### Balancing the method

Empty server protection only voting for servers at the end of the round for less than i.e. 30%* if currentplayers < 50 ;
 *counting the players at the start of the maybe 2nd last round. 
 
 or for smaller servers 40% of the players if more than 30 current players for 2 rounds

Prioritizing alternative players through a more negative deltakd and low kills.(integer) with vote 1 and 2 priority check in. 

A Priority for bored players by who votes first with positive KD for a new server and who votes leave.

B Prioritizing both players at the end of the round: by allowing the open votes at the end of the round for positive deltakd. That might motivate leaving players to take a look at certain different minded or easier servers.

Perhaps players with very negative kd(ratio) larger than i.e. 6 or afk time should change server smoother during the round. again disabling the to leave request at 20% of starting round player count value.

### Serverbrowserside recommendations
recommending character development for diversified player base
If the serverbrowser has read functions for the setting mode, and if there are enough active servers and movements of group of competitive players with kd larger to 0 can be measured if it is set to prioritize groups of alternative players.

With the new serverbrowser groups of like minded players are passively proposed playig with eachother. which possibly helps the existing serverside autobalancing and presents solutions to leaving midround as well.

There the serverbrowser is enabled to recommend the info from the serverbrowser overlay to recommend servers in the future based on the past choices, as well as combinations.

by the relative movements mapped to community creation categories
A competitive servers
B less competitive servers
B.1 B.2 B.3 least competitive server
by the movements by bored and alternative players to alternative, social servers
C fun alternative servers, for procuring memes, making rolebased, creative learning gametypes, diverse gameplay, strategic styles
D fun character server alternative followed with E
D fun tactical squad teams oriented player servers
D 1, D2, D3 by success very tactical server followed with H
by the movement by bored and alternative players to bored henceforth tactical players easy going slow creative 
E fun realistic commander servers
F realistic competitive servers
F,1 F,2 F3, very realistic server by sucess
by the server name, filter or time and success on previous stages
G dynamic roles tactical to realistic servers
H role set guilds 
I character role based guild wars
J teams

These types of known player bases can then be added to the "favorites" of the player in the server menu.

more detailed

intelligent serverbrowser overlay chat and categories and servers create 
phase 1) competitive, various filters: for top 10 average players high kills per minute or low squad coordination: all play assault or many revives for top 3 players, no assists, no parallel opjectives, high kills per minute = kill farming, high summed kills per round over all players, and high number of assault squads, high vehicle streaks, most played server for short visiting bf3 players
phase 2) hence phase 1 + 2, players leave when: round 
phase 3) inherited trend recognised categories from 1, 2 and creative concept tactical based complexity divisions and ranks
phase 4)  on all category type 3 rank server: serverbrowser overlay chat for organising events specifically on type 3 category 
on category 3 type 4 team building events
phase 5 )competitive intelligent events on phase 4 servers
phase 5 )intelligent weekly planned competitive open events from authorisation for lvl2 server browser chat on all servers by new skill coeficiant, only used here
phase 6 )event promotion by last played in intelligent server browser and world wide

### Trends for players

More skill and impact based autobalancing of players for all is not necessary, however the problems can be considered like casual players by giving them mechanisms against them, like being warned of their concentration when they look for a server from the server browser together. In my idea character orientation centering allows _bf community esport over all the content_

Voting trends beyond limits and exceptions
the server recommends most visited close servers with the info on the type to the server browser overlay and the server browser.
They recommend it to the server changing player.

### Recommendations for tournaments or recommended servers
the server browser knows where the players went for competitive servers and skill or tactical or realism

The last game impact integer
The server browser can find competitive players by  recommending him or another player other servers or based on the impact by competitiveness & skill directly a close server out of the categories.

Outlier players can stay, others get a recommendation for a server of their competitiveness and in the future the exceptional might play on another server.

Impact ideas: not based on sharing global procon details and the like. instead, sharing specialised procon 

Who is playing highly skilled, competitive, who is playing for fun ?
for the server browser where the average players went for competitive servers by last game impact integer
adding a skill and impact based autobalancing support for normal players who want to go ahead with bf esport

it follows
non afk time per min +(assists per min)*10  + kills per min*10- +(objectives)/10

adding a gametype specific skill ranking over all classes for the server browser: where the average players went by skill, .
fun teamplay measured in squad 

it follows
if squad liftetime ((sum squad squadspawn lifetime average - revives *100- afk time squad *5 if larger than 19 seconds per 5minutes )over squads)by squads
( squad average squadspawn avg lifetime - revives*100 - afk time squad_2 *5 ) )^-1
afk time squad avg > 19 / 300seconds

Request Community update: Request smart Server browser overlay, Request Server browser chat + vote system, Request in Server VU Browser overlay , Request recommendation plink, Request Server Browser Filter Categories

**Comment by kiwidoggie** [comment]
This would be a request for: https://github.com/BF3RM

You can find their website: https://bf3reality.com/

**Comment by Dontavolta** [comment]
@kiwidoggie oi didnt mean to brand it. 

fixed title, script title Community Server browser update and overlay
