### ISSUE TITLE
Infinite Loading Screen lead to Stopped Working issue

### ISSUE THREAD

**Issue by Erdano9900** [VeniceUnleashed/VeniceUnleashed#612]
Just Downloaded VU and never worked on my PC because of this issue below:

Crash ID: c077f090-9db9-4db2-9e91-e3aa2d425654
Build Number: 17487
Release Branch: prod

nb:
i'm using Win7 Pro with KB2670838 update package PATCH
8GB of RAM
AMD Radeon HD8500M with Intel HD4000 integrated
![VU crash report](https://user-images.githubusercontent.com/79781545/109409856-b01c5900-79c8-11eb-86e5-05098598a8f1.png)

**Comment by kiwidoggie** [comment]
Can you give this patch a try and see if it resolves your issue: https://docs.veniceunleashed.net/troubleshooting/#i-get-a-black-screen--loading-screen-when-launching-vu

**Comment by kiwidoggie** [comment]
In the AMD control panel, have you added VU to it? That way you can tell VU to force use the Discrete GPU? (I'm currently NVIDIA, so I can't walk you through it, but others have reported adding VU to the AMD control panel telling it to use the discrete GPU worked for them)

**Comment by Erdano9900** [comment]
my windows are already with that patch, and still not working

**Comment by kiwidoggie** [comment]
Have you tried the AMD/NVIDIA Control panel option yet?

**Comment by FlashHit** [comment]
No info. Will close it.
