### ISSUE TITLE
[Bug] WeaponState missing some entries

### ISSUE THREAD

**Issue by StuartSulaski** [VeniceUnleashed/VeniceUnleashed#613]
According to the vext documentation WeaponState should have 17 states.
2 of those are missing and are equal nil when used:
WeaponState .Reload
WeaponState .WeaponStateSizeInBits (this one might be intentional)

**Comment by kiwidoggie** [comment]
`WeaponState.WeaponStateSizeInBits` is intentionally hidden, `Reload` was missing and has been corrected (pending push, will close when completed)

**Comment by kiwidoggie** [comment]
Fixed in dev build `17547` VeniceEXT version `1.1.2`
