### ISSUE TITLE
[Req] Allow more then 16 teams

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#619]
For the BR mod it would be nice to give each player his own team and atm we are limited to 16 teamIDs.

Here a simple mod that adds more teams to the gamemode conquest large (from 2 to 17). Loading this mod will cause in a server crash.
[MoreTeamIDs.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6193334/MoreTeamIDs.zip)

**Comment by kiwidoggie** [comment]
![image](https://user-images.githubusercontent.com/9152262/112435164-9dfcb480-8d01-11eb-9ba7-52e9afb4d521.png)

Does not crash for me?

**Comment by FlashHit** [comment]
![Screenshot_94](https://user-images.githubusercontent.com/56718716/112500284-87e60700-8d88-11eb-9b02-aa18496228d5.jpg)
It should look like this (with 16 teams). Try again with conquest large.

**Comment by kiwidoggie** [comment]
This has been fixed in dev branch `17585`
