### ISSUE TITLE
Suggestion: Parse IPs to client/rcon without having PB enabled

### ISSUE THREAD

**Issue by MAGICCC** [VeniceUnleashed/VeniceUnleashed#62]
It would be nice that the servers can parse the IPs from connected users so we - the serveradmins - can use certain plugins to ban IP(ranges). Had the idea, because I tried to enable the default B3 banlist plugin, which can be found on the official B3 site/github:
http://forum.bigbrotherbot.net/plugins-by-courgette/banlist-plugin/
https://github.com/thomasleveil/b3-plugin-banlist

That suggestion applies Rome and VU

**Comment by OrfeasZ** [comment]
Starting with build `16280`, VU will send `punkBuster.onMessage` events via RCON when a player joins in the following format:

`PunkBuster Server: slot  guid(-) ip:42069 OK   1 3.0 0 (W) "name"`

For example:
`PunkBuster Server: 1  bf0fa66b799f4a2d84da81bb1bac2ab2(-) 127.0.0.1:42069 OK   1 3.0 0 (W) "NoFaTe"`

Triggering the `pv_sv_plist` command via the `punkBuster.pb_sv_command` RCON command will send similar events for all currently connected players.

The player's IP address has also been added to a new `ip` column in the `admin.listPlayers` RCON command.
