### ISSUE TITLE
[Req] Allow bots to aim

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#622]
We need a function to let bots zoom.
Using `Player.input:SetLevel(EntryInputActionEnum.EIAZoom, 1.0)` doesn't work.
Or if you set in a LAV and choose the second slot it will be bugged.

Doesn't work on the client either

**Comment by FlashHit** [comment]
Figured out that we need AimingSimulation for server as well to let bots aim. (If that's available for the server.)
So I adjusted the title.

**Comment by OrfeasZ** [comment]
AimingSimulation is not available on the server.

**Comment by FlashHit** [comment]
@OrfeasZ is there anything to let us make the bot aim?

**Comment by OrfeasZ** [comment]
I'm not sure. Would have to look into it.

**Comment by FlashHit** [comment]
`ServerWeapon:setZoomLevel(int)` something like this maybe?
or `EntryInput.zoomLevel int` / `EntryInputState.zoomLevel int`?

**Comment by FlashHit** [comment]
Implemented in `19042`
