### ISSUE TITLE
[Req] Built-in Websocket library for VeniceEXT

### ISSUE THREAD

**Issue by fxtressia** [VeniceUnleashed/VeniceUnleashed#625]
Pretty straight forward. I think it's great if VeniceEXT added a built-in Websocket library.

I mean It's possible to implement websocket with the available built-in libraries but noone including me have enough resources to create it. [RFC 6455](https://tools.ietf.org/html/rfc6455) is hard to understand.

Also, you can't use WebUI in server-side.

**Comment by Bizarrus** [comment]
You can use WebSockets on the WebUI, but not on server side, right. If you like to communicate with the UI, use the NetEvents/Events Library, it is the same interactive communication between two endpoints.

**Comment by fxtressia** [comment]
I need it server-side.

**Comment by Bizarrus** [comment]
I've tried to implement `WebSockets` now, but it's not possible:

The [NetSocket](https://docs.veniceunleashed.net/vext/ref/shared/type/netsocket/) has no server methods. It's only designed for a connection and working as an client.

**Comment by fxtressia** [comment]
> The [NetSocket](https://docs.veniceunleashed.net/vext/ref/shared/type/netsocket/) has no server methods. It's only designed for a connection and working as an client.

Just what I need. I can just run a backend server separately. However though I think that's the raw TCP client.   Might try to port third-party websocket libraries.

**Comment by Bizarrus** [comment]
you cant try porting some thinks, when you have no methods/functionality to create a socket-server.
