### ISSUE TITLE
[Bug] `ServerDoublePlayerEvent.eventId` is nil

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#626]
Repro:
1. Add [`PatchSPCOOP.zip`](https://github.com/EmulatorNexus/VeniceUnleashed/files/6253874/PatchSPCOOP.zip) and [`ServerDoublePlayerEventBug.zip`](https://github.com/EmulatorNexus/VeniceUnleashed/files/6253873/ServerDoublePlayerEventBug.zip) to ModList.txt
2. MapList.txt top entry: `COOP_010 TeamDeathMatchc0 1`
3. Start / join the server
4. Open the clientconsole and write `serverdoubleplayereventbug.register` 
5. Shoot at the bot till he goes into the interactive mandown state
6. Start the revive interaction for a few seconds
7. Check server console prints
-> the eventId is always nil while it should be `-559281700 (Activate)` or `1928776733 (Deactivate)`

**Comment by FlashHit** [comment]
Same on the client with `ClientDoublePlayerEvent`

```lua
Events:Subscribe('Level:Loaded', function()
    local s_UIGraphEntityIterator = EntityManager:GetIterator("ClientUIGraphEntity")
    local s_UIGraphEntity = s_UIGraphEntityIterator:Next()

    while s_UIGraphEntity do
	if s_UIGraphEntity.data ~= nil and (s_UIGraphEntity.data.instanceGuid == Guid("3FD5F757-7523-4D9B-81A1-FBC1F3C6492B")
	or s_UIGraphEntity.data.instanceGuid == Guid("02611C3B-7513-4238-899B-8CEF62A611BB")) then
	    s_UIGraphEntity = Entity(s_UIGraphEntity)
	    print("Register Kill screen")
	    s_UIGraphEntity:RegisterEventCallback(function(p_Entity, p_EntityEvent)
	        print(p_EntityEvent.type)
	        print(p_EntityEvent.eventId)
	    end)
        end
        s_UIGraphEntity = s_UIGraphEntityIterator:Next()
    end
end)
```

**Comment by FlashHit** [comment]
Here a simpler way to repro it:
[ClientPlayerEventRepro.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6428921/ClientPlayerEventRepro.zip)
1. Spawn
2. Kill yourself with nade
3. Check the console

**Comment by kiwidoggie** [comment]
This *should* be fixed, pending push to development for testing.

**Comment by kiwidoggie** [comment]
Pushed in development `17585`
