### ISSUE TITLE
[Bug] NetEvents don't work for spectators

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#635]
If you join a server as spectator you can't send or receive NetEvents.
Repro mod: [NetEventsTest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6406945/NetEventsTest.zip)
This mod sends NetEvents every 5 seconds with a print as confirmation. From server to client and from client to server.

**Comment by OrfeasZ** [comment]
Does this happen on only the dev branch or on prod too?

**Comment by FlashHit** [comment]
Just checked. Happens only on dev.

**Comment by OrfeasZ** [comment]
This should be fixed in `17657` alongside a bunch of other issues where spectators weren't accounted for. Please validate if you can and close.

**Comment by FlashHit** [comment]
Checked, works fine.
