### ISSUE TITLE
[Crash/Bug] Adding more TeamEntityDatas

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#640]
We can now register up to 127 teams but to use it properly we need to add a TeamEntityData for each team. And this makes me crash. Adding more then 99 TeamEntityDatas makes the server crash. Adding more then 22 TeamEntityDatas makes the client crash.

Server crash report when adding more then 99 TeamEntityDatas:
```
Crash ID: 18eb3954-1efc-4409-95cf-2d8d3f2e0a5f
Build Number: 17589
Release Branch: dev
```

**Comment by kiwidoggie** [comment]
This crashes in spawning components on the server it appears like. It's crashing due to something Frostbite doesn't like, will investigate later.

**Comment by FlashHit** [comment]
Repro: [MoreTeamIDs.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6931854/MoreTeamIDs.2.zip)

Just start the server and it will crash.
If you lower the `s_NumberOfTeams` to something like 50 the server won't crash, but the client will.

**Comment by kiwidoggie** [comment]
A proper fix has been pushed to experimental.

**Comment by kiwidoggie** [comment]
Pushed to development build 17851. Will need through testing to ensure there are no side-effects.
