### ISSUE TITLE
i want to run two instances of the vehicle restrictor mod in parallel

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#643]
Do i have to change anything else than the name of the second mod?

**Comment by FoolHen** [comment]
@Dontavolta ask the author of the mod instead, dont think running a duplicated mod makes sense

**Comment by ghost** [comment]
https://github.com/XuluniX/VehicleRestrictor/issues/1

He said he doesnt know.

**Comment by FlashHit** [comment]
You can change the folder name, and then add the new folder name to the modList. Then you have 2 instances but not sure if it’s the best way to handle it.
However the name in the mod.json is not important.

**Comment by Xulunix** [comment]
As VehicleRestrictor doesn't support having different punishment options for different vehicles, 
having two instances is currently only the way to, for example block some completely and limit usage time on others

**Comment by ghost** [comment]
Nice, thank you. Issue can be closed
