### ISSUE TITLE
[Bug] Entity param in entity destroyed callback is incorrect

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#646]
I'm registering an entity destroy callback with ``RegisterDestroyCallback()``. When the callback is triggered, the entity in the parameter is not correct. Meaning that doing ``print(p_Entity)`` prints ``    (0)``, instead of ``WhateverEntity (8392)``, and casting it doesn't help. Accessing ``.entityId`` always returns 0.

**Comment by kiwidoggie** [comment]
Is there a repro mod for this?

**Comment by FoolHen** [comment]
I haven't been able to create one because of #657

**Comment by OrfeasZ** [comment]
Fixed in latest dev.
