### ISSUE TITLE
[Crash] Crash when firing an entity event/issues with entity destroyed callback

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#647]
We are having a crash on RM, where we fire a "Stop" event on an effect entity after a timeout. Sometimes this leads to a crash, with vexttrace leading to the exact line where the event is fired. I suspected that it happens when the entity was destroyed by the game, so I experimented a bit with RegisterDestroyCallback(). While doing so I found out issue #646 , but also that if you destroy the entity (with ``entity:Destroy()``) the callback is triggered after some delay. This might be why the crash happens, the Stop event is fired after the entity is destroyed but before the callback is called, but this is just expeculation.

Here are some crash infos:
```
Crash ID: 598c5866-887c-4c7f-b230-8e37128e176f
Build Number: 17623
Release Branch: dev

Crash ID: 598c5866-887c-4c7f-b230-8e37128e176f
Build Number: 17623
Release Branch: dev

Crash ID: 65834481-d809-4e50-88dc-bcf977fd7cc7
Build Number: 17589
Release Branch: dev

Crash ID: d840b72d-3990-4113-87e9-e5c05b2510a0
Build Number: 17563
Release Branch: dev

```

**Comment by OrfeasZ** [comment]
Please test this again with latest dev.

**Comment by FoolHen** [comment]
I just tested and found the same issue: the destroyed callback is triggered after some delay
```
[2021-07-15 01:16:17+02:00] [info] [VeniceEXT] [realitymod] DESTROY
[2021-07-15 01:16:29+02:00] [info] [VeniceEXT] [realitymod] Entity: EffectEntity (3996485872:0)
```
First line is printed before doing entity:Destroy(), and second in the destroy callback. The effect is indeed stopped right when it's destroyed but the destroyed callback takes 12 seconds to fire.

I suspect that this is the cause of the crash in RM: the smoke effect entity is destroyed by the engine and before the destroy callback is called the custom timer we have fires the ``Stop`` event. The entity reference hasn't been cleared (as that is done in the destroy callback) and is corrupted, leading to a crash when firing the event on it.

**Comment by OrfeasZ** [comment]
This should be fine since after calling Destroy on an entity (or the engine does) any calls to that entity won't work anymore since one of my recent updates. I'm going to close this issue now but feel free to re-open if you get any more crashes.
