### ISSUE TITLE
jet balancing f35 vs su flanker

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#649]
is it possible to equal their physics and remove hovering on f35. dog fighters ar talking to move to bf4 bc the most played map oman doesnt support balanced jets.

**Comment by FlashHit** [comment]
That's a job for a mod not for VU itself.

**Comment by ghost** [comment]
i see, where can i ask for mods, or is that preposterous? where do i find the methods available if i want to high level develop a mod for this?

**Comment by FlashHit** [comment]
In the forum @ community.veniceunleashed.net

**Comment by ghost** [comment]
Thank you. G

**Comment by fxtressia** [comment]
Should this issue be closed?
