### ISSUE TITLE
[Req] Client ControllableEntity OverrideTeamId function

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#651]
Same as #642 but for the [`ControllableEntity.teamId`](https://docs.veniceunleashed.net/vext/ref/client/type/controllableentity/).

**Comment by OrfeasZ** [comment]
Implemented in `17630`. Two new client `Player` methods: `OverrideTeamId(teamId: TeamId)` and `OverrideSquadId(squadId: SquadId)`

**Comment by FlashHit** [comment]
This is already available, but the soldier teamId didn't get overwritten. 
Anyways I am sure kiwidog said he added that aswell now.

**Comment by OrfeasZ** [comment]
OverrideTeam/SquadId have been removed and instead `teamId` and `squadId` properties have been made writable. The `teamId` property on the server and client ControllableEntities has also been made writable.
