### ISSUE TITLE
[Feature] Server raycasts

### ISSUE THREAD

**Issue by Firjens** [VeniceUnleashed/VeniceUnleashed#652]
I've created this because an issue was created on the fun-bots project page and we are unable to resolve this issue due to limitation(s) or bug(s) in Venice Unleashed. For more information related to this issue see: https://github.com/Joe91/fun-bots/issues/102

### Requested feature
Allowing for server raycasts to be used to lessen the load on clients (the same way clients currently do raycasting).

**Notes:**
https://discord.com/channels/125257766649593856/451188288628326410/821131633385144361

**Comment by FlashHit** [comment]
This got implemented in build 17777

**Comment by Firjens** [comment]
Fixed.
