### ISSUE TITLE
[Feature] Ability to set squad perks

### ISSUE THREAD

**Issue by Firjens** [VeniceUnleashed/VeniceUnleashed#653]
I've created this because an issue was created on the fun-bots project page and we are unable to resolve this issue due to limitation(s) or bug(s) in Venice Unleashed. For more information related to this issue see: https://github.com/Joe91/fun-bots/issues/101

### Requested feature
Allow the ability to set squad perks for bots.

**Comment by FlashHit** [comment]
Duplicate of #620
