### ISSUE TITLE
[BUG] zip-versioin of VU does not support ResourceManager:RegisterInstanceLoadHandler

### ISSUE THREAD

**Issue by Joe91** [VeniceUnleashed/VeniceUnleashed#655]
the zip-version of VU does not support ResourceManager:RegisterInstanceLoadHandler.
If the same thing is done with the 'Partition:Loaded' it works.
With the installed version both solutions work just fine.

**Comment by OrfeasZ** [comment]
The files in the zipped version are actually exactly the same as the one the installer installs so what you're describing isn't possible and most likely an issue with your usage.

**Comment by Joe91** [comment]
It might be something related to rights.
If I run the same server once with the zip and once with the installed Version, Bots on the zipped Version do not deal damage.
It is easy to reproduce.
