### ISSUE TITLE
Zipped Version of VU cannot Register Load-Handler

### ISSUE THREAD

**Issue by Joe91** [VeniceUnleashed/VeniceUnleashed#656]
In the Zipped version the "ResourceManager:RegisterInstanceLoadHandler"  do not work:
Installed Version:
![grafik](https://user-images.githubusercontent.com/6923271/125335252-a1698980-e34c-11eb-900f-f8b02a6af793.png)

Zipped Version:
![grafik](https://user-images.githubusercontent.com/6923271/125335406-cfe76480-e34c-11eb-84cf-f39d5d12510c.png)

Used mod for this:
[BugTestVuZip.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6803495/BugTestVuZip.zip)

**Comment by Joe91** [comment]
This is really valid! No need to close it again ;-)

**Comment by OrfeasZ** [comment]
Where have you extracted the zip in relation to the game?

**Comment by Joe91** [comment]
Zip: C:/temp/vu
Bf3: default (C:/programm_files(x86)/ origin ...) Or something like that

**Comment by Joe91** [comment]
A fun-bots-user reported this and it took me a very long time to find out whats wrong with his setup.
Running it as Admin does not change anything...

**Comment by Joe91** [comment]
was fixed in the past. At least it works atm :-)
