### ISSUE TITLE
[Dev] RegisterDestroyCallback is never called

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#657]
Last dev updates broke ``RegisterDestroyCallback()``. Now it's never triggered (at least in my tests), even when manually deleting the entity with ``entity:Destroy()``.

I've created a simple repro mod. Spawn with M320 with smoke grenade and fire a round, the callback will not trigger after the effect disappears. You can type ``d`` in chat to delete the last smoke effect entity. If you do so after the smoke disappears you will crash, as the entity has been deleted and the mod is firing a stop event on it, but the destroy callback was never called to clear the entity reference.

Crash info, in case it's helpful:
```
Crash ID: 2ab13110-c273-4f13-8f21-1df66ea2715e
Build Number: 17641
Release Branch: dev
```

[Test mod, map is irrelevant](https://github.com/EmulatorNexus/VeniceUnleashed/files/6808146/destroycb.zip)

**Comment by OrfeasZ** [comment]
Fixed in `17649`.

**Comment by FoolHen** [comment]
This is indeed fixed, thanks
