### ISSUE TITLE
[Dev] Mapeditor client crash when loading karkand on dev branch

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#659]
Repro:
Mapeditor development branch in ``XP1_001 ConquestAssaultLarge0 2``. Compile UI running ``yarn`` and ``yarn build``.

Crash info:
```
Crash ID: d6bcafe1-1a68-4c2f-9436-b46641fbb83b
Build Number: 17641
Release Branch: dev
```
```
Crash ID: 9e84d453-52ac-4cba-b562-038cba607c22
Build Number: 17641
Release Branch: dev
```

**Comment by FlashHit** [comment]
I can confirm, happens too on that map, but for me it was silent. (Also seems to be an webui issue)

**Comment by FlashHit** [comment]
Seems to be fixed. I only get a blank error now.

![grafik](https://user-images.githubusercontent.com/56718716/151642414-7179a442-62b0-4a88-ba76-8debc23b4f78.png)

**Comment by FlashHit** [comment]
@FoolHen can I close this?

**Comment by FoolHen** [comment]
We should probably find out what the cause of the error is, but as it's not crashing anymore i guess it can be closed
