### ISSUE TITLE
Selecting a player in spectator mode crashes the client

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#66]
This was observed on Build 7962 on server #001.
Free camera works.

**Comment by Powback** [comment]
Confirmed crash on server #3 & #1. Free camera worked slightly on server #1, not in server #3. Both resulted in a crash.

**Comment by OrfeasZ** [comment]
This has been confirmed as an issue in build 8116.
Working on resolving it.

**Comment by OrfeasZ** [comment]
This has been resolved in build 8154.
