### ISSUE TITLE
RegisterInstanceLoadHandlerOnce issue

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#662]
Not sure how to describe the issue in the title correctly, so feel free to adjust that.

as discussed in #661 

Just start the server then you see both prints. Then load another map and you will only see the print from `Partition:Loaded`.

here the repro mod:
[RegisterInstanceLoadHandlerOnceIssue.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6819591/RegisterInstanceLoadHandlerOnceIssue.zip)
this is the code from the mod:
```lua
class 'TEST'

function TEST:__init()
	ResourceManager:RegisterInstanceLoadHandlerOnce(Guid('993445AF-2476-11E0-834E-C984E80F7234'), Guid('5FE2571D-D0AD-CF75-3CB6-43A43AFC0E8B'), self, self.OnInstanceLoaded)
	Events:Subscribe('Partition:Loaded', self, self.OnPartitionLoaded)
end

function TEST:OnInstanceLoaded(p_Instance)
	-- I want that this gets called again the next time this instance gets loaded
	print("OnRegisterInstanceLoadHandlerOnce")
	ResourceManager:RegisterInstanceLoadHandlerOnce(Guid('993445AF-2476-11E0-834E-C984E80F7234'), Guid('5FE2571D-D0AD-CF75-3CB6-43A43AFC0E8B'), self, self.OnInstanceLoaded)
end

function TEST:OnPartitionLoaded(p_Partition)
	if p_Partition.guid == Guid("993445AF-2476-11E0-834E-C984E80F7234") then
		print("OnPartitionLoaded")
	end
end

if g_TEST == nil then
	g_TEST = TEST()
end
```

**Comment by OrfeasZ** [comment]
This behavior can be achieved by calling `RegisterInstanceLoadHandler` (not the `Once` version), and it's probably better to do it like that anyway. In any case, the example above should work so I'll take a look.

**Comment by OrfeasZ** [comment]
I've pushed a fix for this in `17658`. Please try it out and let me know.

**Comment by FlashHit** [comment]
Works fine, thank you.
