### ISSUE TITLE
Servercrash

### ISSUE THREAD

**Issue by EC2-V100** [VeniceUnleashed/VeniceUnleashed#668]
Server has crashed.

Crash ID: 4b52413e-fbcb-477d-a2df-e9a850a00ae0
Build Number: 17487
Release Branch: prod

Running stable mods fun-bots and mapvote

**Comment by EC2-V100** [comment]
Crash ID: 4a23775b-447c-4d41-851a-0681361f488c
Build Number: 17487
Release Branch: prod

**Comment by EC2-V100** [comment]
Crash ID: 43e4565e-879f-44fd-87f0-035a50edbacd
Build Number: 17487
Release Branch: prod

**Comment by kiwidoggie** [comment]
This bug has already been fixed on development branch :)

Also next time just the crash id's are needed, crash dumps could contain sensitive information, so I've removed them from this issue.
