### ISSUE TITLE
[Req] Extended Component support

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#669]
So I checked [this](https://github.com/Hattiwatti/BF3MinimapGenerator/tree/master/FB%20SDK) to get an overview in how VU could add support for components.

#### Properties:
- [x] updateInterval (no clue)
- [ ] collection: ComponentCollection
#### Methods:
- [x] GetComponent(name: string)
______________________________________
#### Properties:
- [ ] owner: GameEntity
- [x] playerCount: int (probably the amount of players that are affected by this component collection)
- [x] totalCount: int
- [x] offsetCount: int (no clue)
#### Methods:
- [ ] GetComponentInfo(index: int)
______________________________________
#### Properties:
- [ ] component: Component
- [ ] entry: Component (not sure if this can be nil too. Example entry could be SoldierBodyComponent. So we have an owner GameEntity: SoldierEntity which has a ComponentCollection. In there is the SoldierBodyComponent. And if you look at its [data](https://github.com/EmulatorNexus/Venice-EBX/blob/master/Characters/Soldiers/MpSoldier.txt#L5221) you see that it has also components in it. So I guess this would be the entry for all the components in there.)
- [ ] flags (no clue)
______________________________________
#### Properties:
- [ ] collection: ComponentCollection
______________________________________
Make sure to check the links, they might help, not sure tho.

### Summarized:
- [x] extend GameEntity
- [ ] implement ComponentCollection
- [ ] implement ComponentInfo
- [ ] implement Component

**Comment by kiwidoggie** [comment]
`updateInterval` has been exposed in `18070`

**Comment by FlashHit** [comment]
@OrfeasZ wouldn't it still make sense to implement these as well?

**Comment by OrfeasZ** [comment]
They are being implemented so I'm closing this for now since base Component support is here.

**Comment by FlashHit** [comment]
Idk renaming the title would make more sense, if we would want the ComponentCollection stuff in the future 🤷‍♂️
