### ISSUE TITLE
Game crashes/doesn't start if missing settings file

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#67]
If you launch BF3 using the Venice Unleashed shortcut it won't launch (stuck on loading screen") or just crash to desktop (the usual "application stopped working").

**Comment by Powback** [comment]
Confirmed. Don't know about the settings file though. Stuck at 10-12 % CPU usage while the memory stays the same.

**Comment by OrfeasZ** [comment]
This is a known issue which we're currently working on.

**Comment by OrfeasZ** [comment]
Latest build (7986) should have fixed this.
Can someone confirm? @powback @Dendari92

**Comment by Dendari92** [comment]
No more issues here.

**Comment by Powback** [comment]
No more issues here either, nice new background!
