### ISSUE TITLE
[Bug] RagdollComponent Get-/ SetLocalTransform 

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#672]
https://docs.veniceunleashed.net/vext/ref/client/type/ragdollcomponent/

For some reason there is Get-/ SetLocalTransform twice. Not sure if there are really two methods with the same name or if it is just a docs issue.

**Comment by kiwidoggie** [comment]
Funny enough, this was a copy-paste error, it was just added duplicate times in the source. Create an issue for VU-Docs just removing the duplicate Get/SetLocalTransform them in the yaml. This will be in the next dev build of vu.
