### ISSUE TITLE
[Bug] Crash - `PhysicsEntityBase:GetPart(i)` wrong index

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#674]
If you do `PhysicsEntityBase:GetPart(i)` and `i` is not a valid index the game will crash.

Crash Report: 
```
Crash ID: 26c7e2e5-c44e-46b4-8755-64db6c92fede
Build Number: 17669
Release Branch: dev
```

It's basically this: 
```lua
local s_PhysicsEntityBase = p_Player.controlledControllable.physicsEntityBase
local s_Entity = s_PhysicsEntityBase:GetPart(s_PhysicsEntityBase.partCount)
```
This is not crashing:
```lua
local s_Entity = s_PhysicsEntityBase:GetPart(s_PhysicsEntityBase.partCount - 1)
```

Repro: 
[ReproGetPartCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6911355/ReproGetPartCrash.zip)
- Join a vehicle
- Write `!test` in the chat

Note: With a soldier it works as supposed, but in vehicles it doesn't.

I did it in `MP_001 ConquestSmall0 1` but I guess that doesn't matter.

**Comment by kiwidoggie** [comment]
Fixed in build 17671
