### ISSUE TITLE
[Bug] Client crash since update

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#675]
Repro: 
- Start the vu client
- Quit the vu client

Client:
```
Crash ID: 212c65f7-4682-49a2-b8f3-535dde059199
Build Number: 17671
Release Branch: dev
```
Since the latest update I get this crash whenever I quit the game, without even joining a server or whatever.
Sry there is no other information then that.

**Comment by kiwidoggie** [comment]
This is a crash happening in nvwgf2um.dll (NVIDIA drivers), try updating and see if that fixes your issue

**Comment by FlashHit** [comment]
Windows said no to the nvidia update.

**Comment by kiwidoggie** [comment]
Check using NVIDIA's website, what version are you on?

**Comment by FlashHit** [comment]
Yea I tried with the website.
My driver version: 441.41
The problem with the update is that I cant do the SHA-2 windows updates ^^

**Comment by FlashHit** [comment]
I updated to 442 and it stopped showing that message, doubt that there was sth important in that update, my nvidia was probably bugged idk.
