### ISSUE TITLE
NetEvents - Allow a callback using return

### ISSUE THREAD

**Issue by Firjens** [VeniceUnleashed/VeniceUnleashed#683]
Issue related to a question at https://discord.com/channels/125257766649593856/721729037092782080/880880418251997234

When the client or server sends a NetEvent, allow the target to return a value.

- A timeout should be configurable in the NetEvent. (eg. if no response is received within 5 seconds, return nil and maybe an error?)

**Example server:**
```lua
NetEvents:Subscribe('MyServerNetEvent', function(data)
  print('Got NetEvent from server with data:')
 return "pancakes"
end)
```
**Example client:**
```lua
print(NetEvents:Send('MyClientNetEvent', 'hello server!')) -- prints "pancakes"
```

**Comment by FoolHen** [comment]
Why not just send a netevent back?

**Comment by OrfeasZ** [comment]
NetEvents are what the name implies: events. They perform one-way communication and as such they cannot return data to the other side. If you want to do that you can emulate the behavior by sending another event back with some sort of identifier in both events to be able to cross-corelate them.
