### ISSUE TITLE
Client Error: Attempted to access a destroyed player object

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#688]
`soldier:GetPlayerInEntry(0)` -> this returns an error on the client.
```
[2021-09-08 01:01:56+02:00] [error] [VeniceEXT] [testplayersoldier] Error: [string "__init__.lua"]:15: Attempted to access a destroyed player object.
stack traceback:
        [C]: in metamethod 'index'
        [string "__init__.lua"]:15: in function <[string "__init__.lua"]:1>
```
Repro:
[testplayersoldier.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/7124736/testplayersoldier.zip)

1. Spawn and kill yourself with a grenade
2. if it didn't work do `modList.ReloadExtensions` and repeat

Either it returns this error (destroyed player) or it returns nil, but it never returns the player. On the server it works fine.

**Comment by OrfeasZ** [comment]
This should be fixed in `17684`.

**Comment by FlashHit** [comment]
I can confirm that the error doesn't appear anymore, but it still never returns a player for the `ControllableEntity:GetPlayerInEntry(0)` on the client, while it works fine on the server.

**Comment by FlashHit** [comment]
Please let me know if I should create another issue for this.
