### ISSUE TITLE
I can not log in after the last update

### ISSUE THREAD

**Issue by kremos** [VeniceUnleashed/VeniceUnleashed#69]
I enter the data from the forum, I have played and I have the key
![default](https://cloud.githubusercontent.com/assets/11767892/6961902/09389b08-d938-11e4-9d18-849cf3eaf1eb.jpg)

**Comment by OrfeasZ** [comment]
What's your forum username?

**Comment by kremos** [comment]
kremos

**Comment by OrfeasZ** [comment]
You beta key has been manually de-activated by a staff member.
Due to policy, we cannot disclose the exact reason during the Closed Beta.
