### ISSUE TITLE
[Bug] Changing `ServerSettings.serverName`

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#691]
Changing `ServerSettings.serverName` will affect the return value of `vars.serverName` which is perfect.
But the server name in the VU server browser won't update. Exception: Only if you do it on the first startup it will work.
However if you update the server name with rcon it will work properly.

**Comment by OrfeasZ** [comment]
The right way to change the server name is through the aforementioned RCON command. Manually changing `SystemSettings` DataContainers for changes like these can have weird side-effects and it's not recommended.
