### ISSUE TITLE
Crash in MathUtils:GetYPRFromULF

### ISSUE THREAD

**Issue by maojunhui666** [VeniceUnleashed/VeniceUnleashed#692]
Crash ID: 6a5acc1c-0f05-46cd-ad37-b35a720d4a21
Build Number: 17487
Release Branch: prod

**Comment by FlashHit** [comment]
Update it to throw the same results as: https://github.com/BF3RM/RotationHelper

**Comment by OrfeasZ** [comment]
`GetTransformFromYPR` and `MathUtils:GetYPRFromULF` have been re-implemented based on the RM RotationHelper in build `18802`.
