### ISSUE TITLE
[Bug] Hard WebGL crash when creating/removing textures

### ISSUE THREAD

**Issue by paulhobbel** [VeniceUnleashed/VeniceUnleashed#694]
As discussed CEF seems to have an issue with either creating/removing textures or there's an issue with the fetching of images.

Test:
Cycle through three different images and load them in a texture, show them, hide them, unload texture, etc.

Expected behavior:
CEF should cycle through the images normally and cache the images itself

Actual behavior:
CEF cycles through the images for ca. 5 minutes and will eventually either just crash or first throw an WebGL error followed by a DirectX error or frozen UI (CEF process of mod crashes)
It also seems to re-download the images each and every request, caching not working?

**Comment by kiwidoggie** [comment]
This should have been fixed here https://docs.veniceunleashed.net/general/changelog/#17768
