### ISSUE TITLE
Feature: Add InfluxDB support

### ISSUE THREAD

**Issue by Firjens** [VeniceUnleashed/VeniceUnleashed#696]
Add support for InfluxDB.

Use case:
I want to create statistics for the amount of users that play on each map and gamemode, store various performance data and more and visualize it using Grafana.

**Comment by OrfeasZ** [comment]
This is a bit beyond the scope as well. Here's a couple of recommended approaches:

1. You can write data to [Influx over HTTP](https://archive.docs.influxdata.com/influxdb/v1.2/guides/writing_data/). You can use the existing VEXT HTTP methods to send your data to your Influx server.
2. Run Telegraf alongside your server, configure it with a [Socket Listener Input](https://www.influxdata.com/blog/telegraf-socket-listener-input-plugin/) (and any other input plugins are relevant) and your InfluxDB instance as the output and send your metrics to it over UDP using the existing VEXT UDP socket interfaces.
