### ISSUE TITLE
Menu flickering in SLI configurations

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#7]
While running 2x GTX780 in SLI, I'm getting constant flickering.
http://i.gyazo.com/f3ffa10f90c79f5aa2e9fcfcde4189fd.gif
This happens 100 times faster than what's showed in this gif. It's also depending on the window resolution. I can at one point make the menu stand completely still, instead of it realigning itself. 

Both the menu and the background are moving. 

Lowering the refresh-rate from 120hz to 60hz makes the flickering go slightly slower, but the issue still persists. 

I should also notice that I am unable to log in. I haven't received a beta-key, but I would assume that I should get some kind of message informing me about that. No message when I type the wrong password either.

There is no issue when I'm at the loading screen right after I start vu.exe. The issue starts once the loading if complete.

Edit:
The issue disappears once I disable SLI.

**Comment by Xulunix** [comment]
Confirmed on other PC
SLI -> flickering like mentioned above or blackscreen flickering etc.
disabeling SLI fixes it.

2 x GTX 560

**Comment by OrfeasZ** [comment]
We are currently investigating this issue.

**Comment by OrfeasZ** [comment]
@powback Can you check if you're still experiencing UI resizing issues with the latest update?

**Comment by Powback** [comment]
@OrfeasZ The resizing issue is fixed, I am still, however, experiencing flickering. 
http://i.gyazo.com/b6d55c64282e9acc23aa1f396678dd5e.mp4
This happens every two frames or so.

The flickering lasts until I resize the window, but then the background keeps flickering between frame 1 and whatever frame that's next. Somewhat shown here,
http://i.gyazo.com/6d988801c7c255fe60c539f0eaf74edb.mp4

edit:
I do, however get a notification if I enter the wrong password, which I didn't get last time I tried. But it keeps toggling between the two frames. Shown here:
http://i.gyazo.com/1ac11810285b01afd4244b4a4147a5ae.mp4

Edit again:
If I now resize the window, that particular frame becomes the one that's toggled. Here I selected password after having username selected:
http://i.gyazo.com/97df639eb6cf7b7b43a422f3db02845a.mp4

Different error, same story:
http://i.gyazo.com/c9afd1bcd9f908c96e62229019e7d11a.mp4

**Comment by OrfeasZ** [comment]
From what it seems this appears to be an issue related to how frames are being pre-rendered (or alternatively rendered) when running in SLI mode.

We will be looking into optimizing our rendering pipeline to account for that, but until then you'll have to settle with not using SLI.

**Comment by Xulunix** [comment]
https://nocloud.xulunix.de/public.php?service=files&t=462da8efee5d72972069e54867c1373b
https://nocloud.xulunix.de/public.php?service=files&t=63fddca0eedd28c6ccecda96d6e7f076

2x GTX 560 (Win 8.1)

Just to keep it complete, NoFaTe already knows the videos

**Comment by OrfeasZ** [comment]
This issue has been resolved in build 8620.
If anyone who's been having this issue can also verify that'd be great.
@XuluniX @powback
