### ISSUE TITLE
"webui.exe has stopped working" after closing VU

### ISSUE THREAD

**Issue by lrabe** [VeniceUnleashed/VeniceUnleashed#70]
When closing the game after having joined a server (and only then) I get the "webui.exe has stopped working" popup.

Behaviour can be reproduced by joining server 001 (with night mod enabled), leaving and _instantly_ quitting VU (i.e. before the blue background has completely faded in)

Behaviour could **not** be reproduced when waiting a few seconds before quitting VU.

Full dump of webui.exe after crashing: http://a.pomf.se/uxekez.7z

VU build: 7987
OS: Windows 8.1 x64

**Comment by OrfeasZ** [comment]
@lrabe 
Does this still occur in the latest build?

**Comment by lrabe** [comment]
@OrfeasZ 
Yep.
