### ISSUE TITLE
Bug: Server not in server browser

### ISSUE THREAD

**Issue by Firjens** [VeniceUnleashed/VeniceUnleashed#700]
When running a server using -env dev the server is not visible in the server branch, and when trying to connect it bugs,

![image](https://user-images.githubusercontent.com/57008952/133463823-1fb65831-d851-437a-8d87-93054b4c43df.png)

Fun-bots community and dev server.

**Comment by FlashHit** [comment]
You need to run the client as well with `-env dev`
