### ISSUE TITLE
[Bug] Error with no traceback

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#703]
[ReproNoTraceback.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/7236597/ReproNoTraceback.zip)

Just start the server and check the console.

Code:
```lua
class "SomeClass"

function SomeClass:__init()
	Events:Subscribe('Level:LoadingInfo', self, self.OnLevelLoadingInfo)
end

return SomeClass()
```

Output:
```
[2021-09-27 15:17:08+02:00] [error] [VeniceEXT] [repronotraceback] Error: attempt to call a nil value
stack traceback:
```

**Comment by kiwidoggie** [comment]
Not a bug, error is clear. Your `self.OnLevelLoadingInfo` does not exist, so it's trying to call into a nil value.

**Comment by FlashHit** [comment]
Build `17851` will now print:
`[error] 'Level:LoadingInfo' callback does not exist, check event registration parameters.`
instead of printing errors with no traceback. So the event subscription will fail and throw this error.
