### ISSUE TITLE
[Crash] Serversided Async-Raycast crashes on specific entity types

### ISSUE THREAD

**Issue by Joe91** [VeniceUnleashed/VeniceUnleashed#708]
As soon as an async-raycast hits anything the server crashes the server.

Testmod:
[BugTestVuRaycast.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/7360494/BugTestVuRaycast.zip)
:
Just set two positions (Chatcommands: "!pos1" and "!pos2")
It does not matter if its the Engine-Update or the Update-Manager Event...

**Comment by FlashHit** [comment]
```lua
local function _DoRaycast()
    local s_RayCastHit = RaycastManager:CollisionRaycast(Vec3(0,0,0), Vec3(999,999,999), 1, 0, RayCastFlags.IsAsyncRaycast)
    print("Hits: " .. #s_RayCastHit)
end

---@param p_DeltaTime number
---@param p_UpdatePass UpdatePass|integer
Events:Subscribe('UpdateManager:Update', function(p_DeltaTime, p_UpdatePass)
    _DoRaycast()
end)
```

hmm.. doesn't crash for me

**Comment by Joe91** [comment]
Okay. Will retry this. Maybe it was fixed  some day.

**Comment by 3ti65** [comment]
use updatepass presim

**Comment by FlashHit** [comment]
@Joe91 any update on this?

**Comment by FlashHit** [comment]
```
Crash ID: c390cf11-24ab-46cf-8658-b1e666b0179f
Build Number: 18848
Release Branch: dev
```

Found a repro:
[BugTestVuRaycast.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8836421/BugTestVuRaycast.zip)

- Map has to be `XP1_002 ConquestLarge0 1`
- Start server 
->Crash

Note: It only crashes when hitting a `GroupPhysicsEntity`. Well I didn't test all different entity types, but at this one it crashes when it's async. And on some others it didn't crash.

Code:
```lua
-- XP1_002 ConquestLarge0 1
local pos1 = Vec3(192.320511, 33.607101, -130.182938)
local pos2 = Vec3(192.413132, 33.818378, -133.146606)

local function OnUpdateManagerUpdate(p_DeltaTime, p_UpdatePass)
	if p_UpdatePass ~= UpdatePass.UpdatePass_PreSim then
		return
	end

	local s_Result = RaycastManager:CollisionRaycast(pos1, pos2, 10, 0, RayCastFlags.IsAsyncRaycast)
end

Events:Subscribe('UpdateManager:Update', OnUpdateManagerUpdate)
```

**Comment by FlashHit** [comment]
Seems to happen with `DynamicPhysicsEntities` as well. So probably all type of `PhysicsEntity`.

**Comment by FlashHit** [comment]
Fixed in build `19968`. Go to [changelog](https://docs.veniceunleashed.net/general/changelog/#19968) for more information.
