### ISSUE TITLE
Crash in Main Menu when connecting to the Backend

### ISSUE THREAD

**Issue by FreshyYT** [VeniceUnleashed/VeniceUnleashed#71]
When I launch bf3 everything seems to be fine, but then that guy in the background comes out and says "WOW" and it just crashes.

**Comment by tarikz-h** [comment]
i have the same problem

**Comment by OrfeasZ** [comment]
This appears to be an issue with our networking library which only happens in some configurations.
We're working on resolving it as soon as possible.

I will post any updates in this issue.

**Comment by OrfeasZ** [comment]
This has been fixed in build 8054.

**Comment by 6arek212** [comment]
its not fixed

**Comment by Frankity** [comment]
i agree, i'm getting the same issue

2015-04-11 10:48 GMT-05:00 6arek212 notifications@github.com:
