### ISSUE TITLE
[Req] Http redirect / alternative mirrors for ui.vuic

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#711]
As previously discussed, some people have super slow UI downloads. This can be mitigated by providing an alternative mirror for the file through RCON.

**Comment by FlashHit** [comment]
First implementation in build `18043`.

**Comment by 3ti65** [comment]
first implementation doesnt work properly, needs to be fixed

**Comment by FlashHit** [comment]
if the mod folder is missing in `%localappdata%\VeniceUnleashed\mods\<mod folder>` the client won't download the ui.

**Comment by FlashHit** [comment]
Should be fixed in `18474`
