### ISSUE TITLE
[BUG] Silent client crash at the end of the level load related to enlighten. 

### ISSUE THREAD

**Issue by keku645** [VeniceUnleashed/VeniceUnleashed#712]
This is a bug related to the mod [vu-spterrains](https://github.com/SassythSasqutch/vu-spterrains) from *SassythSasqutch*, apparently unless you force disable **DynamicEnlightenEntityData** from the SP map you're working on, you'll get a silent client crash as soon as the level finishes to load, all coop maps seem to not be affected by this.

With visual studio attached you get this:
![image](https://user-images.githubusercontent.com/36018654/138683608-c92b4294-5fa7-496a-a870-41c58d07de69.png)
![image](https://user-images.githubusercontent.com/36018654/138721389-dec9acbb-5a29-4ac9-bd64-332306dad4da.png)

There's a way to make Enlighten appear but that would mean to also lose the ability to place assets on maped because then you get a server crash related to havok.

Here is when I re-import the bundles from such level so I can use maped but doing so we lose Enlighten:
[https://github.com/keku645/vu-all-gamemodes-in-all-maps/blob/main/ext/Shared/MpPresets/Villa/MpDataLoad_Ziba.lua#L73](url)

And here is where I disable **DynamicEnlightenEntityData** so I can get in the level without a crash:
[https://github.com/keku645/vu-all-gamemodes-in-all-maps/blob/main/ext/Shared/SpMapModifications/SpVilla.lua#L144](url)

To load the level simply type:  _SP_Villa Domination0 1_ and should be good to go.

You can download my fork here: [https://github.com/keku645/vu-all-gamemodes-in-all-maps](url)

**Comment by keku645** [comment]
the problem was related to ``bundles[1]`` at the end of the list of the desired bundles you wanted to load.
Getting rid of it fixed it.

**Comment by SassythSasqutch** [comment]
To elaborate for anyone else experiencing this in future: it seems like you cannot load the main level bundle (e.g. levels/sp_tank/sp_tank) twice. This is the mistake that was being made. For example, for the level sp_tank,

```lua
if #bundles == 1 and bundles[1] == 'Levels/SP_Tank/SP_Tank' then

    bundles = {
        'whatever/bundle',
        'levels/sp_tank/sp_tank',
        bundles[1]
    }

    hook:Pass(bundles, compartment)

end
```

This is bad, because the 'levels/sp_tank/sp_tank' bundle is being added twice, and this seems to fuck with Enlighten. What `bundles` should be is

`
    bundles = {
        'whatever/bundle',
        'levels/sp_tank/sp_tank'
    }`
