### ISSUE TITLE
ServersidedRaycasts: latency-Raycasts

### ISSUE THREAD

**Issue by Joe91** [VeniceUnleashed/VeniceUnleashed#714]
Same behaviour of the latency-Raycasts as the Async-Raycasts.
As soon as they hit anything, the server just crashes.

The vext-trace shows to the Raycast-Call itself.
Reprod-Mod:
[BugTestVuRaycast.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/7427670/BugTestVuRaycast.zip)
:
Same usage as before. Just set two positions with "!pos1" and "!pos2" in the chat

**Comment by kiwidoggie** [comment]
Update: Even when restricting to PreSim there's an issue with Excluded entities for where the start is pointing to garbage data. Seems to work for server spawns, but not in VEXT. Will continue to investigate, once this is resolved, it should fix other raycasts using the same functionality.

**Comment by FlashHit** [comment]
These might require a callback, which would work like this: 
- https://github.com/EmulatorNexus/VeniceUnleashed/issues/862

**Comment by FlashHit** [comment]
This was fixed in build `18848`.
