### ISSUE TITLE
Client-CollisionRaycast and DetailedRaycast crash the Client if Async

### ISSUE THREAD

**Issue by Joe91** [VeniceUnleashed/VeniceUnleashed#715]
Same behaviour as on the Server-Side.
As soon as the RaycastFlag is set to Async-Raycast it crashes the Client.
At least the maxHitCountVar works here...

If you need a reprod-mod for that as well, just let me know.

**Comment by FlashHit** [comment]
```
Crash ID: 96078b39-207d-4b4c-873f-aa4f494eb505
Build Number: 18808
Release Branch: dev
```

**Comment by FlashHit** [comment]
Fixed in build `19968`. Go to [changelog](https://docs.veniceunleashed.net/general/changelog/#19968) for more information.
