### ISSUE TITLE
[Bug] Memory leak in WebUI:ExecuteJS

### ISSUE THREAD

**Issue by paulhobbel** [VeniceUnleashed/VeniceUnleashed#720]
Objects created by WebUI:ExecuteJS do not seem to properly clean up after usage.

I made a simple mod where you can test this, see the vid for results as well: https://streamable.com/wdeyxq
The mods calls the WebUI:ExecuteJS function with a payload. There's also the same test made in JS itself. If you use a tool like process hacker you will see that in the JS test the memory will increase just slightly and drop back down when stopping the test.

![image](https://user-images.githubusercontent.com/20015650/139965079-e383b9a9-322a-4ff7-9c3b-46a9b884ad4e.png)

[uistress.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/7464574/uistress.zip)

**Comment by FoolHen** [comment]
This was fixed and tested, can be closed.
