### ISSUE TITLE
[Bug] OnPlayerConnected - Attempted to access a destroyed player object

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#728]
https://cdn.discordapp.com/attachments/578663798450421762/916062439181795368/unknown.png

Ignore the voip warnings, they are irrelevant. This results in all sorts of issues in RM, needs to be fixed before release. Happens since the PlayerManager changes.

**Comment by FlashHit** [comment]
I think this got fixed in `17892`.

**Comment by 3ti65** [comment]
i think this is fixed too, didnt get any of these in the last playtest.
