### ISSUE TITLE
[Bug] `vu.SetTeamTicketCount` command doesn't work in TDM (`KillCounterEntity`)

### ISSUE THREAD

**Issue by beamthelaser** [VeniceUnleashed/VeniceUnleashed#729]
Using the vu.SetTeamTicketCount command through ProCon on Grand Bazaar while the mode is Team Deathmatch does nothing.
Mods used:
fun-bots-2.3.0-RC1
killfeed-2.0
no-preround
vu-compass-1.2.1
vu-loading
vu-maploader
vu-mapvote
vu-welcome-screen
and 2 of my own mods that only touch weapon and bullet statistics.

**Comment by FlashHit** [comment]
Can confirm it.
Doing: `vu.SetTeamTicketCount 1 50` works for Rush & Conquest but not for TDM.
With the [TicketManager](https://docs.veniceunleashed.net/vext/ref/server/library/ticketmanager/#setticketcount) it works.
So I assume that the RCON command only changes the `LifeCounterEntity (for Rush)` & `TicketCounterEntity (for Conquest)` but not the `KillCounterEntity` which is used in TDM.

**Comment by kiwidoggie** [comment]
Pushed to experimental, pending build number.

**Comment by kiwidoggie** [comment]
Fixed in build `18070`
