### ISSUE TITLE
Round with minimum player count restarts when spectator leaves.

### ISSUE THREAD

**Issue by derrod** [VeniceUnleashed/VeniceUnleashed#73]
If you have the minimum player count set to 2 and two players join the round will start as intended. However if one spectator joins and leaves again the "too few players" message will appear and the round will be restarted only to be started again when the >= 2 players condition is still met in the pre-round.

Apparently the check if enough players are present counts spectators as players and might not be affected by vars.RoundStartPlayerCount as intended.

**Comment by Powback** [comment]
I can confirm this.

**Comment by OrfeasZ** [comment]
This has been resolved in build 8337.
