### ISSUE TITLE
[BUG] Not being able to type password if a server has performance issues.

### ISSUE THREAD

**Issue by keku645** [VeniceUnleashed/VeniceUnleashed#734]
https://user-images.githubusercontent.com/36018654/146695352-fc41d6d0-4aa6-4a9e-88ab-001b024b2681.mp4

You can't get into the server after the warning message because you can't type the password due it not appearing.

**Comment by FlashHit** [comment]
@keku645 can you check if this is still happening?

**Comment by FlashHit** [comment]
PR:
- https://github.com/EmulatorNexus/Fusion-UI/pull/28

**Comment by FlashHit** [comment]
Was fixed in 20056.
