### ISSUE TITLE
[Bug] #member.instanceScale sometimes returns something around 4191029016

### ISSUE THREAD

**Issue by kapraran** [VeniceUnleashed/VeniceUnleashed#735]
We found this issue while trying to fix nohavok mod. It appears a lot of times in pretty much every map.

For example in this file https://raw.githubusercontent.com/EmulatorNexus/Venice-EBX/master/Levels/XP3_Valley/XP3_Valley.txt
line 14035, the size of the `instanceScale` array returns this crazy number instead of 0, which is the correct value according to ebx.

Also, accessing this `instanceScale` array returns crazy values too instead of throwing some error.
(i guess this makes some sense since vext thinks those are valid indexes and just returns the random values at those memory addresses)

TODO post repo 😄

**Comment by 3ti65** [comment]
relevant for nohavok

**Comment by FlashHit** [comment]
```lua
---@param p_Partition DatabasePartition
Events:Subscribe('Partition:Loaded', function(p_Partition)
	for _, l_Instance in pairs(p_Partition.instances) do
		if l_Instance:Is("StaticModelGroupEntityData") then
			l_Instance = StaticModelGroupEntityData(l_Instance)
			for l_Index, l_MemberData in ipairs(l_Instance.memberDatas) do
				print(#l_MemberData.instanceScale)
				if #l_MemberData.instanceScale > 99999 then
					print(l_Index)
					error("FOUND STH")
				end
			end
		end
	end
end)
```
Wasn't able to reproduce this. Might have been fixed in the past.
