### ISSUE TITLE
[Req] Add microseconds version of `GetTime`

### ISSUE THREAD

**Issue by kapraran** [VeniceUnleashed/VeniceUnleashed#736]
^^ title

Currently, we have the `GetTime` (seconds) and `GetTimeMs` (milliseconds).
https://docs.veniceunleashed.net/vext/ref/shared/library/sharedutils/

I started building a "profiler" mod and milliseconds aren't enough since i get a lot of zeros.

**Comment by OrfeasZ** [comment]
Added in `18244` / VEXT `1.6.0`, though don't expect it to be very accurate.
