### ISSUE TITLE
[Req] `SharedUtils:GetBuildId()`

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#738]
Would be nice to get the VU build somehow. Atm it is only possible on the server via RCON.
`SharedUtils:GetBuildId()` -> returns int `18016`

Example use case:

```lua
if SharedUtils:GetBuildId() >= 17358 then
    ServerUtils:SetCustomMapName("MyCustomMap")
end
```
well obviously this will never work with old builds.

**Comment by OrfeasZ** [comment]
You should not be gating features behind a build id check. You can define a dependency to a specific vext version in your mod.json file for this.
