### ISSUE TITLE
[Bug] `vu.DrawMemoryStats` bugged

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#741]
![grafik](https://user-images.githubusercontent.com/56718716/149636847-7e50a325-6b3c-49b6-9627-7beda1136b0c.png)

**Comment by OrfeasZ** [comment]
Fixed in build `18804`.

**Comment by FlashHit** [comment]
![image](https://user-images.githubusercontent.com/56718716/170213186-416a10d0-252b-466c-ac7e-b442e7d4b315.png)
