### ISSUE TITLE
[Bug] `Player:UpdateInput` stopped working

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#742]
Doesn't get triggered at all anymore, running the latest dev build (18060).
If you spawn you should get a bunch of prints the whole time.
[PlayerUpdateInput.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/7884681/PlayerUpdateInput.zip)
Talking about the server event.

**Comment by kiwidoggie** [comment]
Fix pushed to experimental

**Comment by kiwidoggie** [comment]
Reverted fix, nothing was wrong.

**Comment by kiwidoggie** [comment]
The docs are out of date this was changed to be `Player:UpdateInteract` to better reflect what it is doing. Please create a PR or an issue fixing the docs. Same arguments.

**Comment by FlashHit** [comment]
https://github.com/EmulatorNexus/VU-Docs/pull/108
