### ISSUE TITLE
[Req] Make `PhysicsEntity.velocity` writable

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#747]
Soldiers get bugged when they die while running. They make footstep sounds when they shouldn't and the velocity of the entity is not 0. So I want to modify this, because I think that this is the best way to fix the bug. Might be enough to fix it on the client but if possible provide it on client and server as well.

**Comment by FlashHit** [comment]
[FixFootsteps.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8083941/FixFootsteps.zip)

**Comment by kiwidoggie** [comment]
Fixed in build `18070` Vext `1.5.0`
