### ISSUE TITLE
Crash on scavenger mod

### ISSUE THREAD

**Issue by ErJy31** [VeniceUnleashed/VeniceUnleashed#750]
Hello,

As soon as I want to launch any map in scavenger mod on my personnal server, VU crashes. I don't don't know why.

Hereunder the details :

Crash ID: 998acbab-cc07-4e97-9af7-9e65d164afe5
Build Number: 17487
Release Branch: prod

I'm using the following mods : fun-bots-2.4.0, BetterBF3VisualMod + VEManager, vu-compass-1.2.1, vu-mapvote, VU-More-Gore

Thanks in advance for your support !

**Comment by OrfeasZ** [comment]
This seems to crash while trying render a skinned mesh / model. It's hard to tell why from the report, but it's probably one of the mods that's causing this. Maybe trying to spawn a model that you're missing (eg. because lacking the DLC?).

**Comment by ErJy31** [comment]
I'm Premium user since almost the release of the game. Therefore I don't think that it's caused by lacking of any DLC...
My game just crashed again. I was in conquest large on Caspian Border... I didn't understant.

**Comment by OrfeasZ** [comment]
I'd suggest reaching out to the author of the mod in that case.

**Comment by ErJy31** [comment]
I think I found the problem. Seems that BetterBF3VisualMod + VEManager make VU crash. I removed them, and my game didn't crash again. I didn't test on scavenger yet.
