### ISSUE TITLE
[Bug] Research multiple cases of extremely long server connection times

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#753]
Multiple people have consistently extremely high connection times when trying to load into the server. This only started happening very recently. Related to VU memory allocation changes? Or bigger map pictures / loading screen pictures of RM? Could also be a similar issue to the extremely long loading times of the UI itself, however not sure, because this happens before the UI is even downloaded, in the 'Connecting' screen.

People that can always repro: CrysoK, tria 

People that can sometimes repro: The Mamafeinn, FoolHen, Leper Messiah

relevant forum posts:

https://forum.bf3reality.com/threads/playtest-09-01-2022.71/post-702
https://forum.bf3reality.com/threads/playtest-30-01-2022.74/post-710

**Comment by FoolHen** [comment]
It's generally way slower than it was before, some recent update (some months ago) increased the time.

**Comment by FlashHit** [comment]
The reason for this is because the player is downloading the mods (the lua files). So the problem that needs to get fixed is the actual slow download speed in VU. The CrysoK guy has like 1mb per minute.

**Comment by 3ti65** [comment]
The issue is both the mod download and the UI download being slower for people further away from the server where the mod / UI is hosted. it will go down to below 50kb/s at times. We circumvented this by hosting big savefiles etc. on the s3 and loading them with the http vext lib on loading. This works, but it should still be improved on VU side, because every bigger mod will have to compensate for this.
