### ISSUE TITLE
[Bug] `Player:SetSquadLeader` doesn't fire when leaving squad

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#756]
I think it would trigger if I leave ingame via the button but not when I change the `player.squadId` (not 100% sure tho).
Also only tested it with bots
See [#746](https://github.com/EmulatorNexus/VeniceUnleashed/issues/746#issuecomment-1036357390) for more information
There is also a reproduction mod.

**Comment by OrfeasZ** [comment]
Same as #759, may be fixed. Give it a try.

**Comment by FlashHit** [comment]
Still the same.
This is a server only issue btw. On client it works fine.
