### ISSUE TITLE
[Req] Implement `ServerAutoTeamEntity` events

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#757]
Seems like the events don't do its job rn.

Incoming events:
```
PlayerEnter = -182176866
EnableAllowedToSpawnOn = -1967223203
DisableAllowedToSpawnOn = 959444424
```

This would fix #576 as well

**Comment by FlashHit** [comment]
This mod registers an event callback to the ServerAutoTeamEntity and prints all incoming events: [ServerAutoTeamEntityEvents.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8056223/ServerAutoTeamEntityEvents.zip)

**Comment by kiwidoggie** [comment]
SeverAutoTeamEntity::event functionality is the default Game entity handler, appears code may be stripped by dice? Will need to manually handle and update on frostbite event the player structures

**Comment by kiwidoggie** [comment]
Implementation has been fixed, missing code was re-added by hand. On experimental pending build number.

**Comment by kiwidoggie** [comment]
Fixed in `18070`
