### ISSUE TITLE
[Crash] Out of memory / memory leak / memory issues

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#764]
RM still has some issue with memory leaks, even after some of the memory leaks having been fixed.

The following symptoms are still persisting:

1. Out of memory error message after crash. "most likely caused by a mod"
2. UI will crash / black screen / flicker
3. WebGL out of memory error in console
4. Silent crash during round

Observations:

1. Huge memory differences to begin with, when joining a fresh server for different clients: https://github.com/BF3RM/RealityMod/issues/493 Up to 1GB of difference in memory usage after just joining. More research is being done currently with the RM team / QA.
2. Usually happens after 10-30 minutes into the game in latest RM / VU.

Fixing this is highest priority for Reality Mod.

**Comment by FlashHit** [comment]
Potentially fixed in build `19963`. Go to [changelog](https://docs.veniceunleashed.net/general/changelog/#19963) for more information.
