### ISSUE TITLE
[Bug] Destroyed instance

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#770]
Just start a server with the mod and you will get the errors.
[ReproLensDestroyedInstance.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8221133/ReproLensDestroyedInstance.zip)

```
[2022-03-10 08:17:01+01:00] [info] [VeniceEXT] [reprolensdestroyedinstance] After:
[2022-03-10 08:17:01+01:00] [info] [VeniceEXT] [reprolensdestroyedinstance] nil
[2022-03-10 08:17:01+01:00] [error] [VeniceEXT] Error: [string "shared/__init__.lua"]:31: sol: no matching function call takes this number of arguments and the specified types
stack traceback:
        [C]: in global 'LensFlareEntityData'
        [string "shared/__init__.lua"]:31: in function <[string "shared/__init__.lua"]:17>
[2022-03-10 08:17:01+01:00] [info] [VeniceEXT] [reprolensdestroyedinstance] DataContainer (LensFlareEntityData): 0xF4E7C4D0
[2022-03-10 08:17:01+01:00] [error] [VeniceEXT] [reprolensdestroyedinstance] Error: [string "shared/__init__.lua"]:47: cannot cast a nil or destroyed instance to 'LensFlareEntityData'
stack traceback:
        [C]: in global 'LensFlareEntityData'
        [string "shared/__init__.lua"]:47: in function <[string "shared/__init__.lua"]:42>
```

```lua
function RemoveVanillaScopeGlint:OnScopeGlintBlueprintLoaded(p_SpatialPrefabBlueprint)
	p_SpatialPrefabBlueprint = SpatialPrefabBlueprint(p_SpatialPrefabBlueprint)
	p_SpatialPrefabBlueprint:MakeWritable()

	-- If I access the object it will be available later, but otherwise not
	--print("Before:")
	--print(p_SpatialPrefabBlueprint.objects[1])

	-- clearing eventConnections will destroy the LensFlareEntityData for some reason
	p_SpatialPrefabBlueprint.eventConnections:clear()

	print("After:")
	print(p_SpatialPrefabBlueprint.objects[1])

	local s_LensFlareEntityData = LensFlareEntityData(p_SpatialPrefabBlueprint.objects[1])
	s_LensFlareEntityData:MakeWritable()

	s_LensFlareEntityData.isEventConnectionTarget = Realm.Realm_None
	s_LensFlareEntityData.visible = false
	-- this is doing it
	s_LensFlareEntityData.elements:clear()
	print("done")
end
```

If I do the print that is commented out, the errors disappear. But otherwise the object will be destroyed.

**Comment by OrfeasZ** [comment]
My previous assumption seems to be correct. Looking loaded data of this instance, it does indeed look that the `LensFlareEntityData` instance has an internal reference count of `2` when it should have `3`. When both references from the `eventConnections` are removed, it ends up getting destroyed. Currently trying to see if this is standard engine behavior (ie. arrays of instances dont modify reference count) or if it's some sort of bug we introduced.

![](https://i.nofate.me/qAqA22SkuOaZPgH.png)

**Comment by OrfeasZ** [comment]
Something very fucky is going on here. It looks like the engine doesn't set reference counts correctly. Mostly everything ends up with a default reference count of `2` but then some instances like [9BDCD16D-7178-44E5-98B1-8E3CA492FE67](https://github.com/EmulatorNexus/Venice-EBX/blob/1b48533a42f9fce794b52b72e9e8bd33541e6b35/Persistence/StatCategories/KitCategories.txt#L61) end up with `9`. This looks like an engine bug, but I need to investigate further.

**Comment by OrfeasZ** [comment]
Am pushing an experimental fix for this in `18489`. Give it a try and let me know.

**Comment by Dumpy250** [comment]
After being in the server for 6 minutes no crash.

Client: 
![image](https://user-images.githubusercontent.com/83517134/166614416-fe0aff30-0884-44bc-9e46-6210fd4c67a0.png)

Server: 
![image](https://user-images.githubusercontent.com/83517134/166614442-806eb836-94b7-450a-b8aa-a6edce1f492a.png)

Seems to be fixed now?

**Comment by FlashHit** [comment]
Yep, seems to be fixed.
