### ISSUE TITLE
[Bug] `Entity:RegisterDestroyCallback` for components

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#777]
Repro:
[OmanRepro.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8465896/OmanRepro.zip)
- load `XP1_002 ConquestLarge0 1`
- join with client -> Crash

The issue is that `RegisterDestroyCallback` doesn't work for ClientPartComponents (which get treated as entities) anymore.

In build 17623:
```
[2022-04-11 18:02:40+01:00] [info] [VeniceEXT] [omanrepro] Entity: ClientPartComponent (0)
[2022-04-11 18:02:40+01:00] [info] [VeniceEXT] [omanrepro] Destroying ClientPartComponent
```

but since 17629 it doesn't do the second print anymore.

```
Crash ID: 3a35f4b3-8ea7-44e0-9056-816be781e86a
Build Number: 18476
Release Branch: dev

---------------------------
vu
---------------------------
[string "client.lua"]:49: <unknown>

---------------------------
omanrepro
---------------------------
[string "__init__.lua"]:29: <unknown>

---------------------------
fastload
---------------------------
[string "__init__.lua"]:32: <unknown>
```

**Comment by Dumpy250** [comment]
No server crash after about 10minutes. 
![image](https://user-images.githubusercontent.com/83517134/166604475-e960e2ed-5664-49e0-ac98-fc75da82f372.png)

No client crash:
![image](https://user-images.githubusercontent.com/83517134/166614922-0c7ceae4-2480-456a-9447-9564ab6c8c20.png)

**Comment by FlashHit** [comment]
Fixed in 18675.
