### ISSUE TITLE
[bug] gamemode scavenger crashes VU with bots

### ISSUE THREAD

**Issue by Joe91** [VeniceUnleashed/VeniceUnleashed#781]
when playing scavenger with bots, VU crashes directly

how to reproduce:
Just use a normal version of fun-bots and start a scavenger map:
`XP4_FD Scavenger0 2`
a fun-bots-version is attached. Just add this to the Modlist and start the map above.

[fun-bots.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8613763/fun-bots.zip)

As soon as you spawn or after a few bots have spawned the game crashes (most of the times the Client, but not always).
It usually only takes 4 or 5 seconds.
The trace leads to different functions of fun-bots, but always the same line of VU: 

```
---------------------------
vu
---------------------------
[string "client.lua"]:49: <unknown>

---------------------------
fun-bots
---------------------------
?:-1: CheckForBotBotAttack
```

and the next one shows this:

```
---------------------------
vu
---------------------------
[string "client.lua"]:49: <unknown>

---------------------------
fun-bots
---------------------------
?:-1: OnUpdateManagerUpdate
```

and anouther one this:

```
---------------------------
vu
---------------------------
[string "client.lua"]:49: <unknown>

---------------------------
fun-bots
---------------------------
?:-1: OnUIDrawHud
```

It happens with the dev and prod version of VU. As far as I know it worked with the old prod-version.

Crash Details:

```
Crash ID: b885e2dc-351f-4612-a961-0f013d39a96d
Build Number: 18675
Release Branch: dev
```

I was not able to narrow it down further.
If there is anything more I can do to help with this issue, just let me know.

Thanks a lot in advance!
Joe

**Comment by OrfeasZ** [comment]
Does this also happen in prod?

**Comment by Joe91** [comment]
Yeah:

```
---------------------------
vu
---------------------------
[string "client.lua"]:49: <unknown>

---------------------------
fun-bots_crash_scav
---------------------------
?:-1: CheckForBotBotAttack
```

```
Crash ID: e165de1f-7d0c-4e29-b01f-48e0bd86d5af
Build Number: 18476
Release Branch: prod
```

I think it worked before the big update, but I really didn't play this gamemode at all for quite a while... So could also happend a while ago in the past in either VU or fun-bots... But without a usable trace I can't identify if there is a fun-bots issue...

**Comment by Joe91** [comment]
If you can provide me an older version of VU I can try to find out when it stopped working if that would help you...

**Comment by Joe91** [comment]
Some old version also crash.

V18330:
```
---------------------------
vu
---------------------------
[string "client.lua"]:241: <unknown>

---------------------------
fun-bots_crash_scav
---------------------------
?:-1: OnUpdateManagerUpdate
```

```
Crash ID: 1391f094-a96c-40f3-8ca3-11b10d94bd88
Build Number: 18330
Release Branch: dev
```

V18029:
```
---------------------------
vu
---------------------------
[string "client.lua"]:49: <unknown>

---------------------------
fun-bots_crash_scav
---------------------------
?:-1: OnUpdateManagerUpdate
```
```
Crash ID: 9ff4a22e-776a-44fe-8c9a-eda136cc5d1e
Build Number: 18029
Release Branch: dev
```

It really seems to be like that for a very long time. 
I also tried an old verion of fun-bots (a year ago) with the latest prod-version but it still crashes in the same way.

**Comment by OrfeasZ** [comment]
Seems to be crashing in mesh rendering code in all cases, but can't tell much more correctly. Maybe that gives you a hint.

**Comment by Joe91** [comment]
That is a good hint.
Seems to be related to some weapons, gadgets and/or attachments I think... When I make the bots only use the knife it works. Also the pistols seem to be okay. But everything else just crashes...

**Comment by Joe91** [comment]
Problem caused by usage of wrong weapons. Thanks for the help!!

**Comment by FlashHit** [comment]
@Joe91 do you know what exactly caused the crash? Because maybe it could still be improved in vu to throw an error instead of crashing.
