### ISSUE TITLE
[Bug] Error with no traceback

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#785]
The silent crash seems to be fixed. It throws an error instead of a silent crash. **BUT the error doesn't show where it is in the code**:
```
[2021-08-04 02:44:50+02:00] [error] [VeniceEXT] [boxgame] Error: attempt to call a nil value
stack traceback:
[2021-08-04 02:44:50+02:00] [error] [VeniceEXT] [boxgame] Error: attempt to call a nil value
stack traceback:
[2021-08-04 02:44:50+02:00] [error] [VeniceEXT] [boxgame] Error: attempt to call a nil value
stack traceback:
```

For that I made a simpler repro mod:
[ReproRegisterCallbacksWrongCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6927822/ReproRegisterCallbacksWrongCrash.zip)

```lua
Hooks:Install('EntityFactory:Create', 1, function(p_HookCtx, p_EntityData, p_Transform)
	local s_Entity = p_HookCtx:Call()

	if s_Entity == nil then
		return
	end

	s_Entity:RegisterDestroyCallback(crashMe)
end)
```

https://github.com/EmulatorNexus/VeniceUnleashed/issues/445#issuecomment-892270245

**Comment by FlashHit** [comment]
Similar errors happened when I had some corruption.

**Comment by OrfeasZ** [comment]
This was an issue with `nil` passing as a correct value for functions for some reason. I've added checks that will make this throw a hard error in build `18788` for most places that accept callbacks and will patch up the remaining few in a subsequent build.
