### ISSUE TITLE
[Bug] RegisterLoadHandlerOnce doesn't work anymore for LazyLoaded instances on Dev branch

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#787]
`function M320:ModifyFiringFunctionData(p_FiringFunctionData)
	local s_FireLogicData = p_FiringFunctionData.fireLogic

	if s_FireLogicData ~= nil then
		s_FireLogicData.alwaysAutoReload = false
		s_FireLogicData.reloadTime = RM_WEAPON_CONFIG.M320_HE.RELOAD_TIME
		s_FireLogicData.reloadTimeBulletsLeft = RM_WEAPON_CONFIG.M320_HE.RELOAD_TIME_BULLETS_LEFT
		m_Logger:Write("Changed M320 FireLogicData")
	end

	local s_AmmoConfigData = p_FiringFunctionData.ammo

	if s_AmmoConfigData ~= nil then
		s_AmmoConfigData.numberOfMagazines = RM_WEAPON_CONFIG.M320_HE.MAX_NUMBER_OF_MAGAZINES
		m_Logger:Write("Changed M320 AmmoConfigData")
	end

	local s_ShotConfigData = p_FiringFunctionData.shot

	if s_ShotConfigData ~= nil then
		if s_ShotConfigData.projectileData.isLazyLoaded then
			s_ShotConfigData.projectileData:RegisterLoadHandlerOnce(self, self.ModifyProjectileData)
		else
			self:ModifyProjectileData(s_ShotConfigData.projectileData)
		end

		m_Logger:Write("Changed M320 ShotConfigData")
	end
end

function M320:ModifyProjectileData(p_Instance)
	if p_Instance ~= nil then
		local s_ProjectileData = DCExt:MakeWritable(p_Instance)
		s_ProjectileData.trailEffect = nil
	end
end`

the ModifyProjectileData is not called anymore on Dev branch, still works on Prod. Josephus will add a repro tomorrow.

**Comment by joecons97** [comment]
See attached repro mod:
[GLTrailRepro.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8708496/GLTrailRepro.zip)

To repro:
Run mod on dev server/client

**Comment by OrfeasZ** [comment]
I can't repro this. On dev branch this calls `ModifyProjectileData` because `s_ShotConfigData.projectileData.isLazyLoaded` is `false` on both client and server? What map / mode are you running this in?

**Comment by FoolHen** [comment]
> I can't repro this. On dev branch this calls `ModifyProjectileData` because `s_ShotConfigData.projectileData.isLazyLoaded` is `false` on both client and server? What map / mode are you running this in?

`XP1_001 ConquestAssaultLarge0 2 # Strike at Karkand` acoding to Joe

**Comment by FlashHit** [comment]
Here another one:
[ReproRegisterLoadHandler.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/8769581/ReproRegisterLoadHandler.zip)

**Comment by OrfeasZ** [comment]
Fixed in `18837`.
