### ISSUE TITLE
server crashes = connection to the server timed out

### ISSUE THREAD

**Issue by shuparupa** [VeniceUnleashed/VeniceUnleashed#788]
Crashes the active server window & message in the client: Disconnected. The connection to the server timed out [close]
VU Build 18476, fun-bots-2.6.0-dev1
First about how to reproduce, and then why. So:

Turn off for the convenience of bots (\fun-bots\ext\Shared - Config.lua InitNumberOfBots = 0)
Come in for example on Firestorm CQ, and taking helicopter or tank to destroy the vehicles at your base (everything is not necessary).
Try adding a bot through the menu (even one). Profit.

[string "Vehicles.lua"]:43: GetVehicleByEntity

were also:
[string "Bot.lua"]:2463: _EnterVehicleEntity

All mods except Fun-Bots were disconnected.
Values vars.teamKillххх or the absence of these parameters in Startup are of no consequence.

What's the for?
While flying over on some maps (me more often Oman), i caused damage to the vehicles at the seized points (enemy attacks and our far), received such a problem.

**Comment by FlashHit** [comment]
This seems more like an issue for https://github.com/Joe91/fun-bots/issues

@Joe91 you might wanna take a look into this
