### ISSUE TITLE
Timing issues on HighFreq-Servers

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#79]
High Frequency mode causes some issues with time-related events.
- Tickets in domination gamemode drain way too fast.
- You get killed within ~3 seconds if you are outside of the battlezone

**Comment by kiwidoggie** [comment]
Confirmed bugs in build 8312.

**Comment by derrod** [comment]
I've also noticed that using the mouse wheel to scroll through weapons skips over every 2nd weapon i.e. you go directly from your SMG to your RPG if you are engineer.

**Comment by OrfeasZ** [comment]
These issues have been resolved in build 8332.

**Comment by Xulunix** [comment]
tickets still drain too fast
