### ISSUE TITLE
[Crash] Client disconnect when trying to load in Oman, Kiasar, Parl (and maybe Shield)

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#791]
Top Priority for RM, we currently can't play (almost) half of our maps. 80% of people crash when loading into one of the mentioned maps. I think most people only crash after some people are already on the server. Most likely not related to the OnPartitionLoaded crash that we also have.

Modlist:

BlueprintManager
CustomLevelLoader
RealityMod
VEManager

Maplist:

XP1_002 ConquestLarge0 1
XP5_003 ConquestLarge0 2
XP4_Parl ConquestLarge0 1

VU Version: 18752

Steps to reproduce:

1. Load server, check that all mods have been loaded.
2. Try to load in with client.
3. -> Silent crash when loading in.
4. If you don't crash, try switching map -> https://github.com/EmulatorNexus/VeniceUnleashed/issues/790

Disclaimer: Not all clients crash on loading, also doesn't seem to happen always, "just" in like 80% of cases.

**Comment by 3ti65** [comment]
Repro is not reliable enough i think. Will try to get a better one.

**Comment by OrfeasZ** [comment]
- `XP1_002` and `XP4_Parl` don't seem to crash server or client.
- `XP5_003` seems to crash my server when trying to spawn `Levels/XP3_Valley/objects/Prefabs/StoreRoom_01_Prefab_Lit_XP5`.
- Switching in-between `XP1_002` and `XP4_Parl` yielded one crash inside `Client:UpdateInput` and one in `Input:PreUpdate` after about 20 tries. Not entirely sure why,

**Comment by FoolHen** [comment]
This might be related to custom levels, @OrfeasZ are you running customlevelloader in `realitymod-dev` branch? It's easier to update RM and its deps via vumm, let us know if you need help setting it up, will save you some time.

**Comment by OrfeasZ** [comment]
Yes, 3ti gave me a copy of the exact version causing this issue.

**Comment by 3ti65** [comment]
We could with a 100% certainty replicate this on the Dedi:

1. VU 18808
2. Only Reality Mod latest Dev branch, compile UI (the version you have will work too)
3. Kiasar -> XP5_003 ConquestLarge0 1
4. Connect to the server
5. After loading, you don't even have to spawn
6. Disconnect from server
7. Reconnect
8. -> During loading you get disconnected

Additional findings:

Doesn't matter how long the server is up, the first player to join will trigger the server becoming inaccessible. You'll still be able to join within like 30 seconds of the first player, after that it's rien ne va plus. It doesn't matter whether you disconnect or restart your client.

Repro'd 100% on:

- Dedi
- 3ti's local
- Jack's local
- Bree's local

**Comment by 3ti65** [comment]
this is related to something we made for Fob Blueprints. happens on Prod too. not related to Entity stuff update.

**Comment by FlashHit** [comment]
Was related to wrong use of RegistryContainer
