### ISSUE TITLE
`Component.componentData` is redundant

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#795]
https://docs.veniceunleashed.net/vext/ref/shared/type/component/#componentdata

`Component.componentData` is the same as `Component.data`
I don't think it makes sense to have 2 properties that do the same thing.
So I would say it should get removed. Right?

**Comment by OrfeasZ** [comment]
Is it the same 100% of the time, for all different component types?

**Comment by FlashHit** [comment]
I only checked the SoldierEntity.bus.components. They were all equal. I can check again later if there is anywhere a component where it is not equal.

**Comment by FlashHit** [comment]
Okay checked it now. It is 100% equal in all cases.

I ran this code in shared to verify it:
```lua
---@param p_HookCtx HookContext
---@param p_EntityData DataContainer
---@param p_Transform LinearTransform
---@return Component|Entity|nil
Hooks:Install('EntityFactory:Create', 1, function(p_HookCtx, p_EntityData, p_Transform)
    ---@type Component
    local s_Component = p_HookCtx:Call()

    if s_Component ~= nil and s_Component:Is("Component") then
        if s_Component.data ~= s_Component.componentData then
            print(s_Component)
            print(s_Component.data)
            print(s_Component.componentData)
        end
    end
end)

```

**Comment by FlashHit** [comment]
> breaking change
