### ISSUE TITLE
[Feature-Request] Property Events

### ISSUE THREAD

**Issue by IllustrisJack** [VeniceUnleashed/VeniceUnleashed#798]
Would be neat to have component property changed events.

e.g. needed for my custom RM recoil system:

Possibility of grabbing: https://github.com/EmulatorNexus/Venice-EBX/blob/1b48533a42f9fce794b52b72e9e8bd33541e6b35/Characters/Soldiers/MpSoldier.txt#L2898

**Comment by OrfeasZ** [comment]
Build `18848` (vext `1.8.1`) adds a `RegisterPropertyChangedCallback` method to `EntityBusPeer`. Callback is in the form of `function(peer: Entity | Component, propertyName: int)`.

**Comment by FlashHit** [comment]
awesome!

**Comment by IllustrisJack** [comment]
dayyuum that was fast <3 thx a lot we´ll test it!
