### ISSUE TITLE
[Req] way to identify deployed bipod

### ISSUE THREAD

**Issue by IllustrisJack** [VeniceUnleashed/VeniceUnleashed#803]
Since the property event approach didn´t seem to work (for new RM recoil system). Would it be possible to expose the SupportedShooting property altogether to VEXT? So we can maybe call it from Soldier.isSupportedShooting as a boolean.
(generally i don´t know what you have access to in the back and if this is even possible)

![grafik](https://user-images.githubusercontent.com/76592751/171156967-3831331a-a73d-452c-b155-832ca851fdc0.png)

Talking about this component: https://github.com/EmulatorNexus/Venice-EBX/blob/1b48533a42f9fce794b52b72e9e8bd33541e6b35/Characters/Soldiers/MpSoldier.txt#L7307

Talking about this property: https://github.com/EmulatorNexus/Venice-EBX/blob/1b48533a42f9fce794b52b72e9e8bd33541e6b35/Characters/Soldiers/MpSoldier.txt#L2898

**Comment by FlashHit** [comment]
Well I believe that is a property for the component. So we would need support for that component and can’t just have it for the SoldierEntity.
i would change the request to be more general: provide a way to identify deployed bipods. Maybe there is something in SoldierWeapon for bipod and taclight/laser pointer.

Another solution that would fit for RM is: GunSway.modifierData returning the GunSwayModifierData or nil. Then we would just have to check the partition name of it to see if the bipod is currently deployed.

**Comment by FlashHit** [comment]
we need `GunSway.getUnlockData` with the `GetUnlockData` class exposed.

**Comment by FlashHit** [comment]
Implemented in `19072`.
