### ISSUE TITLE
[Crash] RealityMod server crash repro

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#805]
```
Ausnahme ausgelöst bei 0xF9880008 in vu.exe: 0xC0000005: Zugriffsverletzung beim Ausführen an Position 0xF9880008.

Crash ID: 372ef970-a8d5-459a-83bd-ca62201b5d5c
Build Number: 18848
Release Branch: dev

---------------------------
vu
---------------------------
:0: <unknown>

---------------------------
realitymod
---------------------------
[string "Player/SoldierDamageModifier.lua"]:135: _GetVanillaDamageMultipliers
```

Repro:
- Run this mod with the given MapList and it will crash pretty soon.
- Sometimes it crashes immediately but if it doesn't just give it a couple minutes.

https://github.com/BF3RM/RealityMod/tree/crash/reproForCrash

MapList:
```
XP4_Parl ConquestLarge0 1
XP1_002 ConquestLarge0 1
XP3_Shield ConquestLarge0 1
XP5_003 ConquestLarge0 1
XP1_001 ConquestAssaultLarge0 1
XP3_Valley ConquestLarge0 1
XP5_001 ConquestLarge0 1
XP5_004 ConquestLarge0 1
```
Or here as a file:
[MapList.txt](https://github.com/EmulatorNexus/VeniceUnleashed/files/8818873/MapList.txt)

**Comment by Dumpy250** [comment]
Crash ID: 2c58e590-0b8b-4001-ab17-a23ae176cb59
Build Number: 18848
Release Branch: dev
Attached debugger to Server: Exception thrown at 0xF9860008 in vu.exe: 0xC0000005: Access violation executing location 0xF9860008.
https://cdn.discordapp.com/attachments/566299084143591439/981779066401222707/744cdda3-0161-4347-95cc-d837b1775192.dmp

**Comment by FlashHit** [comment]
Btw this crashes on prod branch `18474` as well.

**Comment by FlashHit** [comment]
Will be fixed with:
- https://github.com/EmulatorNexus/VeniceUnleashed/issues/879

**Comment by FlashHit** [comment]
Duplicate of #879
