### ISSUE TITLE
chars limit 

### ISSUE THREAD

**Issue by seifelbakry101** [VeniceUnleashed/VeniceUnleashed#809]
hey there,
I was trying recently to add a clan tag to my soldier's name but there was a limit for the chars which is 16. I suggest you add another option so the players can add their clan tag without the need to add it in the player name or make the player name a bit larger for the chars limit. thanks for understanding!

**Comment by OrfeasZ** [comment]
The 16 character limit is enforced by the game engine and cannot be easily changed.

**Comment by seifelbakry101** [comment]
could you add an option so the players can add their clan tag without putting it in their name then?
