### ISSUE TITLE
WebUI causes a crash on older GPUs

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#82]
On older GPUs, where DirectX11 is not fully supported (and the game is running in DirectX10.1 mode), the WebUI rendering code causes the client to crash on startup.

Might be related to #39

**Comment by OrfeasZ** [comment]
Build 8350 was just published with several changes that could help in resolving this issue.
I'll keep this open until someone verifies it has been fixed.

**Comment by ghost** [comment]
UI now shows up (was plain white before) but I can't click on anything :(
The background animation also works.

**Comment by OrfeasZ** [comment]
@win32re What you're mentioning is related to issue #11.

**Comment by ghost** [comment]
Sorry, my bad!

I guess you can close this issue now or wait for others to confirm the fix.

**Comment by Curious-Nikhil** [comment]
@OrfeasZ  Nope, It just goes till the loading screen and crashes.(It's updated.)

**Comment by Curious-Nikhil** [comment]
Oh..! Thnx !! It works.. now.! :D Thnx for looking into it !

**Comment by Curious-Nikhil** [comment]
Oh.. come on ! not again! it crashed again..! :(

**Comment by Curious-Nikhil** [comment]
And it works now..am i lucky or is my PC playing with me..?
But i am not able to enter Full Screen in there..
