### ISSUE TITLE
[Crash] Crash when calling `RCON:GetServerGuid()` in the `OnLoadResources` event

### ISSUE THREAD

**Issue by paulhobbel** [VeniceUnleashed/VeniceUnleashed#820]
There seems to be a silent crash when trying to receive the server GUID using RCON. 1/10 times it will return nil, all the other times the server will just silently crash.

[CrashTest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/9114835/CrashTest.zip)

**Comment by kiwidoggie** [comment]
Fixed in 19008
