### ISSUE TITLE
Random Freeze

### ISSUE THREAD

**Issue by kiwidoggie** [VeniceUnleashed/VeniceUnleashed#821]
A handful of players when playtesting RealityMod would have a random freeze where the process CPU usage would drop to 0-1% and stop responding. A restart of the VU client would fix this. Holding this issue open for a little bit while I try and reproduce the issue locally.

Will update if more users are reporting the same issue.

**Comment by thom855j** [comment]
I have experienced that the VU-server, on a heavy load with more that 64 players, would suddenly freeze the server and require a forced shutdown to stop. Maybe the same happens for clients?

**Comment by OrfeasZ** [comment]
I'm thinking this happens for people on fullscreen, where the game crashes with the "Out of memory" error so it freezes itself until you dismiss.

**Comment by paulhobbel** [comment]
Could also be related to an issue in CEF, one of the patches I applied is known to fix freezes that are causes by recent changes in NVDIA drivers. Will be fixed in #871

**Comment by FlashHit** [comment]
Potentially fixed in build `19963`. Go to [changelog](https://docs.veniceunleashed.net/general/changelog/#19963) for more information.
