### ISSUE TITLE
VU Crash

### ISSUE THREAD

**Issue by Befence-w** [VeniceUnleashed/VeniceUnleashed#825]
When i launch VU launcher the window of game appears and then crashes.
Crash ID: b2b407cc-a3f9-4ba5-b01f-45c65b592fcc
Build Number: 18848
Release Branch: prod
![image](https://user-images.githubusercontent.com/58823527/179681706-5078c030-44d1-4426-acef-da58e97687af.png)

**Comment by MaxKruse** [comment]
same

Crash ID: 09936316-259f-4dea-a1b6-c63b87661d91
Build Number: 18848
Release Branch: prod

**Comment by OrfeasZ** [comment]
@Befence-w are you playing on a mobile GPU? 

@MaxKruse this crash is not readable unfortunately. Can you send another one once you crash again?

**Comment by MaxKruse** [comment]
sure thing

Crash ID: bb2d3ec0-b9c1-4f0f-aafc-d5db8ee1941e
Build Number: 18848
Release Branch: prod


a little more info on my end:

R5 5600x
RX 6700XT with 22.5.1 drivers
win10 latest updates

BF3 itself runs normally

**Comment by Befence-w** [comment]
@OrfeasZ Yes. I just launched VU and problem fixed himself somehow. LOL. Maybe problem was because of low resolution (I use 800x600),

**Comment by OrfeasZ** [comment]
@MaxKruse don't upload crash dumps directly here, since they can contain personal information. I have identified the issue and I'm tracking it separately here #826.

@Befence-w Not sure. I'll close this issue for now. If you experience more crashes just reply here.
