### ISSUE TITLE
VU client always stop working after black screen since i installed build 18896.

### ISSUE THREAD

**Issue by fiberboard** [VeniceUnleashed/VeniceUnleashed#828]
Crash ID: b2d6005a-8de7-48a7-ae2e-8e712b149c96
Build Number: 18896
Release Branch: prod

**Comment by FlashHit** [comment]
We are on it

**Comment by FlashHit** [comment]
Got fixed. Please retry with latest version @fiberboard

**Comment by fiberboard** [comment]
> Got fixed. Please retry with latest version @fiberboard

it works.
