### ISSUE TITLE
Vaulting over objects can kill you in High Frequency Mode

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#83]
Sometimes, vaulting over specific objects can kill you when playing in a High Frequency server.
The exact reason for that is still unknown, but we assume it has something to do with physics calculations.

**Comment by Dendari92** [comment]
Stairs also cause random _K.I.A._ deaths. http://youtu.be/g1t4H4N0x2w

**Comment by OrfeasZ** [comment]
We have pushed a hotfix for this issue in build 8461, which should greatly reduce the occurrences of this bug. However, this is only a temporary fix, and we'll be looking more deeply into the root cause of the issue soon.
