### ISSUE TITLE
Client console history

### ISSUE THREAD

**Issue by Julien00859** [VeniceUnleashed/VeniceUnleashed#834]
Hello there,

First of all, sorry if I'm suggesting this on the wrong channel, I'm new to VU.

We are running an unlisted server with my friends and we connect to the server via the `connect` command in the console. We would like to press the up-arrow to type the last command we ran so that it is easy to quickly join back our server. Note that we tried using a `vu://` kind of link, it does start VU client but it doesn't auto-join the server.

Regards,

**Comment by FlashHit** [comment]
That’s already a thing

**Comment by Julien00859** [comment]
Oh indeed, can the history be persisted across client startups ?

**Comment by FlashHit** [comment]
I don’t think that’s a good idea
