### ISSUE TITLE
After joining in for the first time I get an immediate crash

### ISSUE THREAD

**Issue by emilrueh** [VeniceUnleashed/VeniceUnleashed#836]
All described procedures had been followed precisely.
This is my copy to clipboard:

Crash ID: caac4619-d94d-4275-bd30-6483f94aabfe
Build Number: 19006
Release Branch: prod

**Comment by emilrueh** [comment]
After playing a round the game crashed on exiting it with:
Crash ID: 36f79ad7-275b-4f64-8fab-26bc192d8c98
Build Number: 19006
Release Branch: prod

**Comment by FlashHit** [comment]
Missing information to this issue. We already have other issues that might fix these crashes. So I am closing this one.
