### ISSUE TITLE
Chat disappears randomly while typing

### ISSUE THREAD

**Issue by jk53bg** [VeniceUnleashed/VeniceUnleashed#84]
The new in game-chat disappears randomly, even while typing. The chat-window fades out and the main menu cursor shows. Sometimes waiting a few seconds helps and is displays again.

**Comment by Curious-Nikhil** [comment]
Same here.

**Comment by OrfeasZ** [comment]
This should be fixed in the latest build. Please verify.

**Comment by jk53bg** [comment]
Seems fixed. Didn't happen to me again.
