### ISSUE TITLE
Cpu Spikes

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#86]
Im  getting huge cpu spikes almost all the time while playing it doesnt happend that often in retail bf3.

**Comment by jk53bg** [comment]
What CPU you're using? Also, did you played on a highfreq server? Because that causes a slightly increased cpu load.

**Comment by ghost** [comment]
Intel core 2 duo e8500 and yes i was playing on highfreq server.

**Comment by jk53bg** [comment]
That might be it, since its not the strongest cpu anymore.
