### ISSUE TITLE
Cursor disappears at loadout screen when used the chat once

### ISSUE THREAD

**Issue by jk53bg** [VeniceUnleashed/VeniceUnleashed#87]
The cursor disappears at the loadout screen when opening the chat and confirm with enter. Just closing it (J,K,L) does not cause this issue.

**Comment by ghost** [comment]
Yea happend to me too

**Comment by kiwidoggie** [comment]
Confirmed bug, will investigate.

**Comment by SUTempest** [comment]
Was able to make the cursor reappear on the loadout screen by hitting Esc to bring up the menu, then quitting it. The cursor returns at that point.

**Comment by OrfeasZ** [comment]
This has been resolved in build 8756.
