### ISSUE TITLE
Vehicle Sensitivity issues

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#89]
Both mouse sensitivities (soldier and vehicles) are way slower than the retail version (naturally same values), it's especially evident with the vehicles.

NOTE: doesn't seem to be a HFU issue.

**Comment by SolidAapie** [comment]
Same happened to me, on foot its fine but in vehicles its really slow. Also it didn't happen in the gunner position only from the driver position.

**Comment by klappflapp** [comment]
Can confirm this, especially in driver position.

**Comment by kiwidoggie** [comment]
I have personally had this issue myself, correcting title.

**Comment by OrfeasZ** [comment]
This is a confirmed issue which appears to occur on all turrets (both stationary, and in vehicles), and is only present when running in higher frequency modes (Fun fact: This is also present in BF4 CTE https://www.reddit.com/r/Battlefield_4_CTE/comments/39caxq/cte_prototypes_patch_54/cs26n01).

This has been resolved in build 8746.  

If you're still experiencing issues, or you think that turrets feel different in higher frequencies, please make sure to let us know.
