### ISSUE TITLE
VU has stopped working

### ISSUE THREAD

**Issue by xThunderRain22** [VeniceUnleashed/VeniceUnleashed#891]
Hello,

This night i got this error from VU:

Crash ID: 1a7fbc10-2af8-4e2e-b343-9dc0b11a03cb
Build Number: 19968
Release Branch: prod.

Could you please help me to understand what happened?

Thanks,
Mario

**Comment by xThunderRain22** [comment]
Hello,

Seems the mod "artifacts" get stuck when a round is close to the end and a map has bo be chosen

Thanks,
Mario

**Comment by FlashHit** [comment]
This might be fixed on the dev branch then. Try to switch to it by adding `-updateBranch dev` to you vu launch arguments.

**Comment by FlashHit** [comment]
Duplicate of https://github.com/VeniceUnleashed/VeniceUnleashed/issues/889
