### ISSUE TITLE
Modify AT Mine to affect teammates

### ISSUE THREAD

**Issue by Dumpy250** [VeniceUnleashed/VeniceUnleashed#894]
As a player playing Reality Mod, I expect AT Mines to damage or destroy both enemy and friendly vehicles.

**Comment by Dumpy250** [comment]
RM Issue: https://github.com/BF3RM/RealityMod/issues/1862

**Comment by FoolHen** [comment]
If a mine kills a teammate it should not give negative points to the player that put the mine, should only give positive points if it kills an enemy

**Comment by FlashHit** [comment]
Implemented in `20054`. Using `vu.TeamActivatedMines` via RCON.
