### ISSUE TITLE
[Req] Modify suppression to affect all players

### ISSUE THREAD

**Issue by Dumpy250** [VeniceUnleashed/VeniceUnleashed#895]
As a player in RM I expect to be suppressed by all explosions and bullets regardless of team for realism.

Currently friendly does not get suppressed.

**Comment by FlashHit** [comment]
Added as RCON command `vu.FriendlyFireSuppression <bool>` in `19985`.
Check https://docs.veniceunleashed.net/hosting/commands/#vufriendlyfiresuppression
