### ISSUE TITLE
Custom Gamemode Names Don´t Allow Numbers

### ISSUE THREAD

**Issue by IllustrisJack** [VeniceUnleashed/VeniceUnleashed#898]
Custom defined gamemodes, to load in MapList.txt, don´t seem to allow numbers.
e.g. like DICE: ConquestLarge0 -> CustomGameMode0 doesn´t work.

A fix to support numbers in game mode names would be nice but low prio

**Comment by FlashHit** [comment]
Just remove the number for `GameModeSettings`.
`GameModeSize.name` doesn't allow numbers. And I see why. Example: you have Conquest0 and Conquest1, but for the GameModeSettings it's both just Conquest. That is all it need to know.
Anyways I am working on it in RM so dw about it.
