### ISSUE TITLE
Impossible to join/create squad

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#90]
I was able to do that only the first try after that I couldn't get back into it, and once I left the squad I was in (only member) I couldn't create a new squad too.

http://youtu.be/Ijn5Adrm7Bw

**Comment by 3ti65** [comment]
I can confirm this bug.

**Comment by Xulunix** [comment]
It is not possible to leave the squad if you are the leader and only one player is left in the squad.
Kicking the last player in the squad is not possible too

**Comment by OrfeasZ** [comment]
This should be resolved in one of the latest builds.
