### ISSUE TITLE
Crash VU Battlefield 3

### ISSUE THREAD

**Issue by BOBOROSE28** [VeniceUnleashed/VeniceUnleashed#903]
Crash ID: a7991c26-4fce-4558-94e9-edd89390999d
Build Number: 19969
Release Branch: prod
[dumps.zip](https://github.com/VeniceUnleashed/VeniceUnleashed/files/11185550/dumps.zip)

**Comment by BigShottt** [comment]
Constantly crashing at round end when tickets hit 1.

**Comment by fredsanchez** [comment]
Server crashing on round end, randomly.
Attached dump file
[Dump.txt](https://github.com/VeniceUnleashed/VeniceUnleashed/files/11456779/Dump.txt)

**Comment by FlashHit** [comment]
Was fixed in latest fun bots update
