### ISSUE TITLE
Cant activate server

### ISSUE THREAD

**Issue by alecstuhr** [VeniceUnleashed/VeniceUnleashed#910]
When trying to activate the game as described in the [Setting up a server on Linux Docs](https://docs.veniceunleashed.net/hosting/setup-linux/) i get the following error:

```
root@fbce5c70fbad:/client# wine vu.com -gamepath /bf3 -activate -o_mail "myEmail@myEmailProvider.com" -o_pass "myPassword"
Please wait while your game is being activated. This process can take up to one minute...
Failed to activate game. The specified credentials could not be validated.
```

the same email/password combination works in the origin client
the password does only contain numbers and letters, no special characters

```
root@fbce5c70fbad:~# uname -a
Linux fbce5c70fbad 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
root@fbce5c70fbad:~# wine --version
wine-5.0.3 (Debian 5.0.3-3)
```

**Comment by FlashHit** [comment]
Should be fixed in `Build 20041 (25/08/2023)`.
Check this for more info: https://docs.veniceunleashed.net/general/changelog/#20041
