### ISSUE TITLE
Client can't login

### ISSUE THREAD

**Issue by Elereman** [VeniceUnleashed/VeniceUnleashed#911]
I'm trying to active VU, but getting the following error

`vu -activate -o_mail "myEmail" -o_pass "myPassword"`
`Please wait while your game is being activated. This process can take up to one minute...`
`Failed to activate game. The specified credentials could not be validated.`

I've tried to login for 30 times during 3 days with no luck.

**Comment by FlashHit** [comment]
Should be fixed in `Build 20041 (25/08/2023)`.
Check this for more info: https://docs.veniceunleashed.net/general/changelog/#20041
