### ISSUE TITLE
Can not join any servers

### ISSUE THREAD

**Issue by Gumby8888** [VeniceUnleashed/VeniceUnleashed#92]
Build #8352 
Can not join any servers as client or spec, it tries but then brings me back to the main screen.
If I select spectator, it tries to connect as well but then returns to the main scree, but then I also loose my mouse, and have to alt-tab and kill the program. 
MY specs:
    Motherboard: Asrock Z77 Extreme 6 Bios 2.80

```
Processor: Intel 3770K @ 3.5 GHz no OC yet.

Memory: 16Gb G.skill RipjawsX DDR3 F3=12800CL9Q-16GBXL 9.9.9.24

Hard Drive: 2x OCZ Vertex 4 128GB (FW 1.5)

Hard Drive: OCZ Vertex 4 256GB (FW 1.5)

Hard Drive: OCZ Arc 100 240GB

Hard Drive: 1 1TB Velociraptor storage

DVD Burner: LITE-ON - SATA Model iHAS124-04

Video Card: 2 EVGA NVIDIA GeForce GTX 670 FTW not in SLI

Monitor: ASUS VG236 3D 1920x1080 @ 120Hz

Monitor2: Viewsonic VX922 60Hz

Sound Card: Speakers Realtek High Definition Audio

Speakers/Headphones: G51 / Logitech G930 Gaming Headphones

Keyboard: G510, G13

Mouse: G502
```

   Operating System: Windows 8.1 64 bit

**Comment by Gumby8888** [comment]
Same issue with #Build 8389 
https://youtu.be/0hdF15D9S7U

**Comment by OrfeasZ** [comment]
Try opening UDP ports 25200, 25300, 7948, and 7958 on your firewall and try again.

**Comment by kiwidoggie** [comment]
Here's a few things you can try first, Add Battlefield 3 (bf3.exe) to your Windows Firewall exception list, try to make sure that there are no firewall's blocking ports 25200, 25300, 7948, and 7958.

**Comment by Gumby8888** [comment]
nope no luck doing this on my end opened ports and even disabled firewalls still a no go here

**Comment by kiwidoggie** [comment]
We will take a closer look upon introduction of error messages very soon.
