### ISSUE TITLE
DiscardVirtualMemory could not be located

### ISSUE THREAD

**Issue by toba-zz** [VeniceUnleashed/VeniceUnleashed#925]
build 20079 download dev branch update and throw error
DiscardVirtualMemory could not be located

![vu_dev_update](https://github.com/user-attachments/assets/8ad3d86f-0943-43e2-b577-4c7a8ab48270)

OS win7

**Comment by OrfeasZ** [comment]
VU only supports Windows 10 or newer.

________________________________
From: toba-zz ***@***.***>
Sent: Thursday, August 8, 2024 12:35:13 PM
To: VeniceUnleashed/VeniceUnleashed ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VeniceUnleashed/VeniceUnleashed] DiscardVirtualMemory could not be located (Issue #925)


build 20079 download dev branch update and throw error
DiscardVirtualMemory could not be located

vu_dev_update.png (view on web)<https://github.com/user-attachments/assets/8ad3d86f-0943-43e2-b577-4c7a8ab48270>

OS win7
