### ISSUE TITLE
Crashes due to Low Resolution

### ISSUE THREAD

**Issue by Curious-Nikhil** [VeniceUnleashed/VeniceUnleashed#93]
VE launches in Box mode, then you go join a server and then while in game, go full screen with a res of 640*480, then it works fine with some minor scaling issues.Now if you restart the game, then it will crash as it will go into full screen with 640 res.So one has to try repeatedly - ALT + Enter to come back to box mode.
So basically it crashes on low resolution on restarting.
I guess i got that correct. :D

**Comment by OrfeasZ** [comment]
We currently don't support resolutions lower than 720p, and probably never will.
