### ISSUE TITLE
Instant death after reviving

### ISSUE THREAD

**Issue by Romern** [VeniceUnleashed/VeniceUnleashed#94]
After one gets revived, he sometimes instantly dies and has to be revived again.

**Comment by Siilwyn** [comment]
Can confirm this, it seems to happen randomly.

**Comment by SkippTekk** [comment]
this happened to me about 3 times in a row. i almost raged quit xD

**Comment by Xulunix** [comment]
You have about 1 sec time to accept the revive.
If you'd not standing up within 1 sec, you die again as the time is not 
correct.

**Comment by SkippTekk** [comment]
does it not take about 2 seconds to stand up? bump it to maybe 3 seconds to bring the rage down :p

**Comment by klappflapp** [comment]
Afaik in vanilla BF3 one could crawl around quite a long time after being revived, without standing up (i.e. accepting the revive).

**Comment by OrfeasZ** [comment]
This happens because of some physics simulation issues in High Frequency mode and is related to #83.
We are currently looking into a fix.

**Comment by OrfeasZ** [comment]
We have pushed a hotfix for this issue in build 8461, which should greatly reduce the occurrences of this bug. However, this is only a temporary fix, and we'll be looking more deeply into the root cause of the issue soon.
